SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 設定情報データ変更 ※hyouji_jun900以降はカスタマイズ領域
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- （期別）部門
ALTER TABLE KI_BUMON RENAME TO KI_BUMON_OLD;
CREATE TABLE KI_BUMON
(
	KESN SMALLINT NOT NULL,
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	OYA_SYUUKEI_BUMON_CD VARCHAR(8) NOT NULL,
	PRIMARY KEY (KESN, FUTAN_BUMON_CD, OYA_SYUUKEI_BUMON_CD)
) WITHOUT OIDS;
COMMENT ON TABLE KI_BUMON IS '（期別）部門';
COMMENT ON COLUMN KI_BUMON.KESN IS '内部決算期';
COMMENT ON COLUMN KI_BUMON.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN KI_BUMON.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON COLUMN KI_BUMON.OYA_SYUUKEI_BUMON_CD IS '親集計部門コード';

INSERT 
INTO KI_BUMON
SELECT
	KESN,
	FUTAN_BUMON_CD,
	FUTAN_BUMON_NAME,
	OYA_SYUUKEI_BUMON_CD
FROM
  KI_BUMON_OLD;
DROP table KI_BUMON_OLD;

-- （期別）部署入出力仕訳
CREATE TABLE KI_BUSHO_SHIWAKE
(
	KESN SMALLINT NOT NULL,
	DKEI SMALLINT NOT NULL,
	DSEQ INT NOT NULL,
	SSEQ INT NOT NULL,
	DYMD DATE NOT NULL,
	DCNO VARCHAR(8) NOT NULL,
	VALU DECIMAL(15) NOT NULL,
	RKMK VARCHAR(15) NOT NULL,
	REDA VARCHAR(12) NOT NULL,
	RBMN VARCHAR(8) NOT NULL,
	SKMK VARCHAR(15) NOT NULL,
	SEDA VARCHAR(12) NOT NULL,
	SBMN VARCHAR(8) NOT NULL,
	PRIMARY KEY (KESN, DKEI, DSEQ, SSEQ)
) WITHOUT OIDS;
COMMENT ON TABLE KI_BUSHO_SHIWAKE IS '（期別）部署入出力仕訳';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.KESN IS '内部決算期';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.DKEI IS '経過月';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.DSEQ IS '伝票SEQ';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.SSEQ IS '仕訳SEQ';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.DYMD IS '（オープン２１）伝票日付';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.DCNO IS '（オープン２１）伝票番号';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.VALU IS '（オープン２１）金額';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.RKMK IS '（オープン２１）借方　科目内部コード';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.REDA IS '（オープン２１）借方　枝番コード';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.RBMN IS '（オープン２１）借方　部門コード';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.SKMK IS '（オープン２１）貸方　科目内部コード';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.SEDA IS '（オープン２１）貸方　枝番コード';
COMMENT ON COLUMN KI_BUSHO_SHIWAKE.SBMN IS '（オープン２１）貸方　部門コード';

-- マスター管理版数・マスター管理一覧
\copy MASTER_KANRI_HANSUU          FROM '.\files\csv\master_kanri_hansuu_patch.csv'          WITH CSV header ENCODING 'SHIFT-JIS';
\copy MASTER_KANRI_ICHIRAN          FROM '.\files\csv\master_kanri_ichiran_patch.csv'          WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター取込一覧・詳細（SIAS）
DELETE FROM MASTER_TORIKOMI_ICHIRAN_SIAS;
\copy MASTER_TORIKOMI_ICHIRAN_SIAS FROM '.\files\csv\master_torikomi_ichiran_sias.csv'       WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM MASTER_TORIKOMI_SHOUSAI_SIAS;
\copy MASTER_TORIKOMI_SHOUSAI_SIAS FROM '.\files\csv\master_torikomi_shousai_sias.csv'       WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター取込一覧・詳細（DE3）
DELETE FROM MASTER_TORIKOMI_ICHIRAN_DE3;
\copy MASTER_TORIKOMI_ICHIRAN_DE3 FROM '.\files\csv\master_torikomi_ichiran_de3.csv'       WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM MASTER_TORIKOMI_SHOUSAI_DE3;
\copy MASTER_TORIKOMI_SHOUSAI_DE3 FROM '.\files\csv\master_torikomi_shousai_de3.csv'       WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM master_torikomi_term_ichiran_de3;
\copy master_torikomi_term_ichiran_de3 FROM '.\files\csv\master_torikomi_term_ichiran_de3.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM master_torikomi_term_shousai_de3;
\copy master_torikomi_term_shousai_de3 FROM '.\files\csv\master_torikomi_term_shousai_de3.csv' WITH CSV header ENCODING 'SHIFT-JIS';


-- 所属部門割当
ALTER TABLE SHOZOKU_BUMON_WARIATE RENAME TO SHOZOKU_BUMON_WARIATE_OLD;
CREATE TABLE SHOZOKU_BUMON_WARIATE
(
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_ROLE_ID VARCHAR(5) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	DAIHYOU_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (BUMON_CD, BUMON_ROLE_ID, USER_ID, YUUKOU_KIGEN_FROM)
) WITHOUT OIDS;
COMMENT ON TABLE SHOZOKU_BUMON_WARIATE IS '所属部門割り当て';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.BUMON_CD IS '部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.BUMON_ROLE_ID IS '部門ロールID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.DAIHYOU_FUTAN_BUMON_CD IS '代表負担部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO SHOZOKU_BUMON_WARIATE
SELECT 
	BUMON_CD,
	BUMON_ROLE_ID,
	USER_ID,
	DAIHYOU_FUTAN_BUMON_CD,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	HYOUJI_JUN,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM SHOZOKU_BUMON_WARIATE_OLD;

DROP TABLE SHOZOKU_BUMON_WARIATE_OLD;

commit;