SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 所属部門割り当てテーブルのカラム追加
ALTER TABLE shozoku_bumon_wariate RENAME TO shozoku_bumon_wariate_old;
CREATE TABLE SHOZOKU_BUMON_WARIATE
(
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_ROLE_ID VARCHAR(5) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	DAIHYOU_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (BUMON_CD, BUMON_ROLE_ID, USER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE SHOZOKU_BUMON_WARIATE IS '所属部門割り当て';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.BUMON_CD IS '部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.BUMON_ROLE_ID IS '部門ロールID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.DAIHYOU_FUTAN_BUMON_CD IS '代表負担部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON_WARIATE.KOUSHIN_TIME IS '更新日時';

INSERT INTO shozoku_bumon_wariate
SELECT
	BUMON_CD,
	BUMON_ROLE_ID,
	USER_ID,
	COALESCE((SELECT shain.daihyou_futan_bumon_cd FROM shain LEFT OUTER JOIN user_info ON shain.shain_no = user_info.shain_no WHERE user_info.user_id = main.user_id LIMIT 1), ''),
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY BUMON_CD ASC),
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM shozoku_bumon_wariate_old AS main;
DROP TABLE shozoku_bumon_wariate_old;

-- 伝票テーブルの代表負担部門カラム追加
ALTER TABLE DENPYOU RENAME TO DENPYOU_OLD;

CREATE TABLE DENPYOU
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	DENPYOU_JOUTAI VARCHAR(2) NOT NULL,
	SANSHOU_DENPYOU_ID VARCHAR(19) NOT NULL,
	DAIHYOU_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	SERIAL_NO BIGINT NOT NULL,
	CHUUSHUTSU_ZUMI_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE DENPYOU IS '伝票';
COMMENT ON COLUMN DENPYOU.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN DENPYOU.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU.DENPYOU_JOUTAI IS '伝票状態';
COMMENT ON COLUMN DENPYOU.SANSHOU_DENPYOU_ID IS '参照伝票ID';
COMMENT ON COLUMN DENPYOU.DAIHYOU_FUTAN_BUMON_CD IS '代表負担部門コード';
COMMENT ON COLUMN DENPYOU.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN DENPYOU.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN DENPYOU.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN DENPYOU.SERIAL_NO IS 'シリアル番号';
COMMENT ON COLUMN DENPYOU.CHUUSHUTSU_ZUMI_FLG IS '抽出済フラグ';

INSERT 
  INTO DENPYOU
      (DENPYOU_ID
      ,DENPYOU_KBN
      ,DENPYOU_JOUTAI
      ,SANSHOU_DENPYOU_ID
      ,DAIHYOU_FUTAN_BUMON_CD
      ,TOUROKU_USER_ID
      ,TOUROKU_TIME
      ,KOUSHIN_USER_ID
      ,KOUSHIN_TIME
      ,SERIAL_NO
      ,CHUUSHUTSU_ZUMI_FLG)
SELECT DENPYOU_OLD.DENPYOU_ID 
      ,DENPYOU_OLD.DENPYOU_KBN 
      ,DENPYOU_OLD.DENPYOU_JOUTAI 
      ,DENPYOU_OLD.SANSHOU_DENPYOU_ID 
      ,CASE WHEN SHOZOKU_BUMON_WARIATE.DAIHYOU_FUTAN_BUMON_CD IS NULL THEN '' 
            ELSE SHOZOKU_BUMON_WARIATE.DAIHYOU_FUTAN_BUMON_CD
       END  
      ,DENPYOU_OLD.TOUROKU_USER_ID 
      ,DENPYOU_OLD.TOUROKU_TIME 
      ,DENPYOU_OLD.KOUSHIN_USER_ID 
      ,DENPYOU_OLD.KOUSHIN_TIME 
      ,DENPYOU_OLD.SERIAL_NO 
      ,DENPYOU_OLD.CHUUSHUTSU_ZUMI_FLG 
  FROM DENPYOU_OLD
  LEFT OUTER JOIN (SELECT DENPYOU_ID
                         ,BUMON_CD
	                     ,USER_ID
                     FROM SHOUNIN_ROUTE
                    WHERE EDANO = 1
                  ) SHOUNIN_ROUTE
    ON DENPYOU_OLD.DENPYOU_ID = SHOUNIN_ROUTE.DENPYOU_ID
  LEFT OUTER JOIN SHOZOKU_BUMON_WARIATE
    ON SHOUNIN_ROUTE.BUMON_CD = SHOZOKU_BUMON_WARIATE.BUMON_CD
   AND SHOUNIN_ROUTE.USER_ID  = SHOZOKU_BUMON_WARIATE.USER_ID;

DROP TABLE DENPYOU_OLD;

-- 伝票種別一覧テーブルに 申請時帳票出力フラグ を追加
ALTER TABLE DENPYOU_SHUBETSU_ICHIRAN RENAME TO DENPYOU_SHUBETSU_ICHIRAN_OLD;

CREATE TABLE DENPYOU_SHUBETSU_ICHIRAN
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT DEFAULT 0 NOT NULL,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	NAIYOU VARCHAR(160) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	KANREN_SENTAKU_FLG VARCHAR(1) NOT NULL,
	KANREN_HYOUJI_FLG VARCHAR(1) NOT NULL,
	DENPYOU_PRINT_FLG VARCHAR(1) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_SHUBETSU_ICHIRAN IS '伝票種別一覧';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.NAIYOU IS '内容（伝票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_SENTAKU_FLG IS '関連伝票選択フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_HYOUJI_FLG IS '関連伝票入力欄表示フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_FLG IS '申請時帳票出力フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_TIME IS '更新日時';

INSERT INTO DENPYOU_SHUBETSU_ICHIRAN(
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	DENPYOU_PRINT_FLG,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	'0',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM DENPYOU_SHUBETSU_ICHIRAN_OLD;

DROP TABLE DENPYOU_SHUBETSU_ICHIRAN_OLD;

-- 設定情報データ変更
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

UPDATE setting_info SET setting_val = 
CASE WHEN (SELECT setting_val FROM setting_info WHERE setting_name = 'shiwake_kbn' ) = '1' THEN '' 
     ELSE '1' 
END 
WHERE setting_name = 'kakutei_umu';

-- 仕訳パターンマスターのカラム追加（摘要入力フラグ・摘要）
ALTER TABLE SHIWAKE_PATTERN_MASTER RENAME TO SHIWAKE_PATTERN_MASTER_OLD;

CREATE TABLE SHIWAKE_PATTERN_MASTER
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	DELETE_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	BUNRUI1 VARCHAR(20) NOT NULL,
	BUNRUI2 VARCHAR(20) NOT NULL,
	BUNRUI3 VARCHAR(20) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_FLG VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(20),
	DEFAULT_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KAKE_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	SHAIN_CD_RENKEI_FLG VARCHAR(1) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_PROJECT_CD VARCHAR NOT NULL,
	KARI_KAZEI_KBN VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD1 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD1 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN1 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD2 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD2 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN2 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD3 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD3 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN3 VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, SHIWAKE_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE SHIWAKE_PATTERN_MASTER IS '仕訳パターンマスター';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DELETE_FLG IS '削除フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI1 IS '分類1';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI2 IS '分類2';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI3 IS '分類3';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TEKIYOU_FLG IS '摘要フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TEKIYOU IS '摘要';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DEFAULT_HYOUJI_FLG IS 'デフォルト表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSAIHI_HYOUJI_FLG IS '交際費表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KAKE_FLG IS '掛けフラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHAIN_CD_RENKEI_FLG IS '社員コード連携フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_FUTAN_BUMON_CD IS '借方負担部門コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_CD IS '借方科目コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_TORIHIKISAKI_CD IS '借方取引先コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_PROJECT_CD IS '借方プロジェクトコード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAZEI_KBN IS '借方課税区分（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD1 IS '貸方負担部門コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD1 IS '貸方科目コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD1 IS '貸方科目枝番コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD1 IS '貸方取引先コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN1 IS '貸方課税区分１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD2 IS '貸方負担部門コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD2 IS '貸方取引先コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD2 IS '貸方科目コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD2 IS '貸方科目枝番コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN2 IS '貸方課税区分２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD3 IS '貸方負担部門コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD3 IS '貸方取引先コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD3 IS '貸方科目コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD3 IS '貸方科目枝番コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN3 IS '貸方課税区分３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO SHIWAKE_PATTERN_MASTER( 
  DENPYOU_KBN
  , SHIWAKE_EDANO
  , DELETE_FLG
  , YUUKOU_KIGEN_FROM
  , YUUKOU_KIGEN_TO
  , BUNRUI1
  , BUNRUI2
  , BUNRUI3
  , TORIHIKI_NAME
  , TEKIYOU_FLG
  , TEKIYOU
  , DEFAULT_HYOUJI_FLG
  , KOUSAIHI_HYOUJI_FLG
  , KAKE_FLG
  , HYOUJI_JUN
  , SHAIN_CD_RENKEI_FLG
  , KARI_FUTAN_BUMON_CD
  , KARI_KAMOKU_CD
  , KARI_KAMOKU_EDABAN_CD
  , KARI_TORIHIKISAKI_CD
  , KARI_PROJECT_CD
  , KARI_KAZEI_KBN
  , KASHI_FUTAN_BUMON_CD1
  , KASHI_KAMOKU_CD1
  , KASHI_KAMOKU_EDABAN_CD1
  , KASHI_TORIHIKISAKI_CD1
  , KASHI_KAZEI_KBN1
  , KASHI_FUTAN_BUMON_CD2
  , KASHI_TORIHIKISAKI_CD2
  , KASHI_KAMOKU_CD2
  , KASHI_KAMOKU_EDABAN_CD2
  , KASHI_KAZEI_KBN2
  , KASHI_FUTAN_BUMON_CD3
  , KASHI_TORIHIKISAKI_CD3
  , KASHI_KAMOKU_CD3
  , KASHI_KAMOKU_EDABAN_CD3
  , KASHI_KAZEI_KBN3
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME
) 
SELECT
  DENPYOU_KBN
  , SHIWAKE_EDANO
  , DELETE_FLG
  , YUUKOU_KIGEN_FROM
  , YUUKOU_KIGEN_TO
  , BUNRUI1
  , BUNRUI2
  , BUNRUI3
  , TORIHIKI_NAME
  , '0'
  , ''
  , DEFAULT_HYOUJI_FLG
  , KOUSAIHI_HYOUJI_FLG
  , KAKE_FLG
  , HYOUJI_JUN
  , SHAIN_CD_RENKEI_FLG
  , KARI_FUTAN_BUMON_CD
  , KARI_KAMOKU_CD
  , KARI_KAMOKU_EDABAN_CD
  , KARI_TORIHIKISAKI_CD
  , KARI_PROJECT_CD
  , KARI_KAZEI_KBN
  , KASHI_FUTAN_BUMON_CD1
  , KASHI_KAMOKU_CD1
  , KASHI_KAMOKU_EDABAN_CD1
  , KASHI_TORIHIKISAKI_CD1
  , KASHI_KAZEI_KBN1
  , KASHI_FUTAN_BUMON_CD2
  , KASHI_TORIHIKISAKI_CD2
  , KASHI_KAMOKU_CD2
  , KASHI_KAMOKU_EDABAN_CD2
  , KASHI_KAZEI_KBN2
  , KASHI_FUTAN_BUMON_CD3
  , KASHI_TORIHIKISAKI_CD3
  , KASHI_KAMOKU_CD3
  , KASHI_KAMOKU_EDABAN_CD3
  , KASHI_KAZEI_KBN3
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME 
FROM
  SHIWAKE_PATTERN_MASTER_OLD;

DROP TABLE SHIWAKE_PATTERN_MASTER_OLD;

-- 旅費精算明細テーブルの日数をINTからNUMERICに変更
ALTER TABLE RYOHISEISAN_MEISAI ALTER COLUMN NISSUU TYPE NUMERIC;

-- 業務ロール割り当てテーブルのカラム追加
ALTER TABLE gyoumu_role_wariate RENAME TO gyoumu_role_wariate_old;
CREATE TABLE GYOUMU_ROLE_WARIATE
(
	USER_ID VARCHAR(30) NOT NULL,
	GYOUMU_ROLE_ID VARCHAR(5) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	SHORI_BUMON_CD VARCHAR(8) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (USER_ID, GYOUMU_ROLE_ID)
) WITHOUT OIDS;
COMMENT ON TABLE GYOUMU_ROLE_WARIATE IS '業務ロール割り当て';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.SHORI_BUMON_CD IS '処理部門コード';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN GYOUMU_ROLE_WARIATE.KOUSHIN_TIME IS '更新日時';

INSERT INTO gyoumu_role_wariate
SELECT
    USER_ID
  , GYOUMU_ROLE_ID
  , YUUKOU_KIGEN_FROM
  , YUUKOU_KIGEN_TO
  , '0000'
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME
FROM gyoumu_role_wariate_old AS main;
DROP TABLE gyoumu_role_wariate_old;

commit;
