SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;


-- 伝票種別一覧
ALTER TABLE DENPYOU_SHUBETSU_ICHIRAN RENAME TO DENPYOU_SHUBETSU_ICHIRAN_OLD;
CREATE TABLE DENPYOU_SHUBETSU_ICHIRAN
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT DEFAULT 0 NOT NULL,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	HYOUJI_JUN INT NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	NAIYOU VARCHAR(160) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	KANREN_SENTAKU_FLG VARCHAR(1) NOT NULL,
	KANREN_HYOUJI_FLG VARCHAR(1) NOT NULL,
	DENPYOU_PRINT_FLG VARCHAR(1) NOT NULL,
	KIANBANGOU_UNYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YOSAN_SHIKKOU_TAISHOU VARCHAR(1) DEFAULT 'X' NOT NULL,
	ROUTE_HANTEI_KINGAKU VARCHAR(1) DEFAULT '0' NOT NULL,
	ROUTE_TORIHIKI_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	SHOUNIN_JYOUKYOU_PRINT_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	SHINSEI_SHORI_KENGEN_NAME VARCHAR(6) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_SHUBETSU_ICHIRAN IS '伝票種別一覧';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_SHUBETSU IS '伝票種別（帳票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（帳票・仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.NAIYOU IS '内容（伝票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_SENTAKU_FLG IS '関連伝票選択フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_HYOUJI_FLG IS '関連伝票入力欄表示フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_FLG IS '申請時帳票出力フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KIANBANGOU_UNYOU_FLG IS '起案番号運用フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU IS '予算執行対象';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.ROUTE_HANTEI_KINGAKU IS 'ルート判定金額';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.ROUTE_TORIHIKI_FLG IS 'ルート取引毎設定フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.SHOUNIN_JYOUKYOU_PRINT_FLG IS '承認状況欄印刷フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.SHINSEI_SHORI_KENGEN_NAME IS '申請処理権限名';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO DENPYOU_SHUBETSU_ICHIRAN(
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU,
	DENPYOU_PRINT_SHUBETSU,
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	DENPYOU_PRINT_FLG,
	KIANBANGOU_UNYOU_FLG,
	YOSAN_SHIKKOU_TAISHOU,
	ROUTE_HANTEI_KINGAKU,
	ROUTE_TORIHIKI_FLG,
	SHOUNIN_JYOUKYOU_PRINT_FLG,
	SHINSEI_SHORI_KENGEN_NAME,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU,
	DENPYOU_PRINT_SHUBETSU,
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	DENPYOU_PRINT_FLG,
	KIANBANGOU_UNYOU_FLG,
	YOSAN_SHIKKOU_TAISHOU,
	ROUTE_HANTEI_KINGAKU,
	ROUTE_TORIHIKI_FLG,
	SHOUNIN_JYOUKYOU_PRINT_FLG,
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM DENPYOU_SHUBETSU_ICHIRAN_OLD;
DROP TABLE DENPYOU_SHUBETSU_ICHIRAN_OLD;


-- 承認ルート子
ALTER TABLE SAISHUU_SYOUNIN_ROUTE_KO RENAME TO SAISHUU_SYOUNIN_ROUTE_KO_OLD;
CREATE TABLE SAISHUU_SYOUNIN_ROUTE_KO
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	EDANO INT NOT NULL,
	EDAEDANO INT NOT NULL,
	GYOUMU_ROLE_ID VARCHAR(5) NOT NULL,
	SAISHUU_SHOUNIN_SHORI_KENGEN_NAME VARCHAR(6) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30),
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, EDANO, EDAEDANO)
) WITHOUT OIDS;
COMMENT ON TABLE SAISHUU_SYOUNIN_ROUTE_KO IS '最終承認ルート子';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.EDANO IS '枝番号';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.EDAEDANO IS '枝枝番号';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.SAISHUU_SHOUNIN_SHORI_KENGEN_NAME IS '最終承認処理権限名';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SAISHUU_SYOUNIN_ROUTE_KO.KOUSHIN_TIME IS '更新日時';
INSERT INTO SAISHUU_SYOUNIN_ROUTE_KO(
	DENPYOU_KBN,
	EDANO,
	EDAEDANO,
	GYOUMU_ROLE_ID,
	SAISHUU_SHOUNIN_SHORI_KENGEN_NAME,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_KBN,
	EDANO,
	EDAEDANO,
	GYOUMU_ROLE_ID,
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM SAISHUU_SYOUNIN_ROUTE_KO_OLD;
DROP TABLE SAISHUU_SYOUNIN_ROUTE_KO_OLD;


-- 画面権限制御の追加
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';


-- 内部コード ※オプション用レコードはパッチ前になければ削除
CREATE TABLE naibu_cd_setting_tmp AS SELECT * FROM naibu_cd_setting;
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM naibu_cd_setting WHERE naibu_cd='A003' AND (SELECT COUNT(*) FROM naibu_cd_setting_tmp WHERE naibu_cd='A003')=0;
DROP TABLE naibu_cd_setting_tmp;


-- 設定情報データ変更 ※hyouji_jun900以降はカスタマイズ領域
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);

UPDATE setting_info SET setting_val = 
CASE (SELECT setting_val FROM setting_info_tmp WHERE setting_name = 'ouin_num')
 WHEN 'Z' THEN 'X'
 ELSE (SELECT setting_val FROM setting_info_tmp WHERE setting_name = 'ouin_num') END 
WHERE setting_name = 'ouin_format';

UPDATE setting_info SET setting_val = 
CASE (SELECT setting_val FROM setting_info_tmp WHERE setting_name = 'ouin_num')
 WHEN 'W' THEN '1'
 WHEN 'X' THEN '2'
 WHEN 'Z' THEN '2'
 ELSE '0' END 
WHERE setting_name = 'ouin_naiyou';

UPDATE setting_info
 SET setting_val =
  CASE (SELECT setting_val FROM setting_info_tmp WHERE setting_name = 'ouin_num')
   WHEN 'W' THEN '1'
   WHEN 'Z' THEN '1'
   ELSE '0' END
 WHERE setting_name = 'inei';

DROP TABLE setting_info_tmp;


-- 機能制御(IC)追加
\copy kinou_seigyo FROM '.\files\csv\kinou_seigyo_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';


-- 仮払なし伝票の摘要に全角スペース（仮払申請）
UPDATE karibarai k SET tekiyou = '　' 
WHERE k.karibarai_on = '0' 
AND NOT EXISTS(SELECT * FROM yosan_kiankingaku_check WHERE denpyou_id = k.denpyou_id) --実施起案は除外。実施起案で申請中なら必ず予算起案金額チェックにレコードがある。
AND EXISTS(SELECT * FROM denpyou WHERE denpyou_id = k.denpyou_id AND denpyou_joutai = '20');

-- 仮払なし伝票の摘要に目的（旅費仮払申請）
UPDATE ryohi_karibarai k SET tekiyou = CASE mokuteki WHEN '' THEN '　' ELSE mokuteki END 
WHERE k.karibarai_on = '0' 
AND NOT EXISTS(SELECT * FROM yosan_kiankingaku_check WHERE denpyou_id = k.denpyou_id) --実施起案は除外。
AND EXISTS(SELECT * FROM denpyou WHERE denpyou_id = k.denpyou_id AND denpyou_joutai = '20');

-- 仮払なし伝票の摘要に目的（海外旅費仮払申請）
UPDATE kaigai_ryohi_karibarai k SET tekiyou = CASE mokuteki WHEN '' THEN '　' ELSE mokuteki END 
WHERE k.karibarai_on = '0' 
AND NOT EXISTS(SELECT * FROM yosan_kiankingaku_check WHERE denpyou_id = k.denpyou_id) --実施起案は除外。
AND EXISTS(SELECT * FROM denpyou WHERE denpyou_id = k.denpyou_id AND denpyou_joutai = '20');


-- ICカード
CREATE TABLE EKI_MASTER
(
	REGION_CD VARCHAR(3) NOT NULL,
	LINE_CD VARCHAR(3) NOT NULL,
	EKI_CD VARCHAR(3) NOT NULL,
	LINE_NAME VARCHAR NOT NULL,
	EKI_NAME VARCHAR NOT NULL
) WITHOUT OIDS;
CREATE INDEX EKI_MASTER_NAT ON EKI_MASTER (REGION_CD, LINE_CD, EKI_CD);
COMMENT ON TABLE EKI_MASTER IS '駅マスター';
COMMENT ON COLUMN EKI_MASTER.REGION_CD IS '地域コード';
COMMENT ON COLUMN EKI_MASTER.LINE_CD IS '路線コード';
COMMENT ON COLUMN EKI_MASTER.EKI_CD IS '駅コード';
COMMENT ON COLUMN EKI_MASTER.LINE_NAME IS '路線名';
COMMENT ON COLUMN EKI_MASTER.EKI_NAME IS '駅名';
\copy eki_master FROM '.\files\csv\eki_master.csv' WITH CSV header ENCODING 'SHIFT-JIS';

CREATE TABLE IC_CARD
(
	IC_CARD_NO VARCHAR(16) NOT NULL,
	TOKEN VARCHAR NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	PRIMARY KEY (IC_CARD_NO)
) WITHOUT OIDS;
COMMENT ON TABLE IC_CARD IS 'ICカード';
COMMENT ON COLUMN IC_CARD.IC_CARD_NO IS 'ICカード番号';
COMMENT ON COLUMN IC_CARD.TOKEN IS 'トークン';
COMMENT ON COLUMN IC_CARD.USER_ID IS 'ユーザーID';

CREATE TABLE IC_CARD_RIREKI
(
	IC_CARD_NO VARCHAR(16) NOT NULL,
	IC_CARD_SEQUENCE_NO VARCHAR(10) NOT NULL,
	IC_CARD_RIYOUBI DATE NOT NULL,
	LINE_CD_FROM VARCHAR(3) NOT NULL,
	LINE_NAME_FROM VARCHAR NOT NULL,
	EKI_CD_FROM VARCHAR(3) NOT NULL,
	EKI_NAME_FROM VARCHAR NOT NULL,
	LINE_CD_TO VARCHAR(3) NOT NULL,
	LINE_NAME_TO VARCHAR NOT NULL,
	EKI_CD_TO VARCHAR(3) NOT NULL,
	EKI_NAME_TO VARCHAR NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	PRIMARY KEY (IC_CARD_NO, IC_CARD_SEQUENCE_NO)
) WITHOUT OIDS;
COMMENT ON TABLE IC_CARD_RIREKI IS 'ICカード利用履歴';
COMMENT ON COLUMN IC_CARD_RIREKI.IC_CARD_NO IS 'ICカード番号';
COMMENT ON COLUMN IC_CARD_RIREKI.IC_CARD_SEQUENCE_NO IS 'ICカードシーケンス番号';
COMMENT ON COLUMN IC_CARD_RIREKI.IC_CARD_RIYOUBI IS 'ICカード利用日';
COMMENT ON COLUMN IC_CARD_RIREKI.LINE_CD_FROM IS '路線コード（FROM）';
COMMENT ON COLUMN IC_CARD_RIREKI.LINE_NAME_FROM IS '路線名（FROM）';
COMMENT ON COLUMN IC_CARD_RIREKI.EKI_CD_FROM IS '駅コード（FROM）';
COMMENT ON COLUMN IC_CARD_RIREKI.EKI_NAME_FROM IS '駅名（FROM）';
COMMENT ON COLUMN IC_CARD_RIREKI.LINE_CD_TO IS '路線コード（TO）';
COMMENT ON COLUMN IC_CARD_RIREKI.LINE_NAME_TO IS '路線名（TO）';
COMMENT ON COLUMN IC_CARD_RIREKI.EKI_CD_TO IS '駅コード（TO）';
COMMENT ON COLUMN IC_CARD_RIREKI.EKI_NAME_TO IS '駅名（TO）';
COMMENT ON COLUMN IC_CARD_RIREKI.KINGAKU IS '金額';
COMMENT ON COLUMN IC_CARD_RIREKI.USER_ID IS 'ユーザーID';


CREATE TABLE HOUJIN_CARD_JOUHOU
(
	CARD_JOUHOU_ID BIGSERIAL NOT NULL,
	CARD_SHUBETSU VARCHAR(3) NOT NULL,
	TORIKOMI_DENPYOU_ID VARCHAR(19) NOT NULL,
	BUSHO_CD VARCHAR(15) NOT NULL,
	SHAIN_BANGOU VARCHAR(16) NOT NULL,
	SHIYOUSHA VARCHAR(30) NOT NULL,
	RIYOUBI DATE NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	CARD_BANGOU VARCHAR(16) NOT NULL,
	KAMEITEN VARCHAR(60) NOT NULL,
	GYOUSHU_CD VARCHAR(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (CARD_JOUHOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE HOUJIN_CARD_JOUHOU IS '法人カード使用履歴情報';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.CARD_JOUHOU_ID IS 'カード情報ID';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.CARD_SHUBETSU IS 'カード種別コード';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.TORIKOMI_DENPYOU_ID IS '取込先伝票ID';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.BUSHO_CD IS '部署コード';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.SHAIN_BANGOU IS '社員番号';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.SHIYOUSHA IS '使用者';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.RIYOUBI IS '利用日';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.KINGAKU IS '金額';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.CARD_BANGOU IS 'カード番号';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.KAMEITEN IS '加盟店';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.GYOUSHU_CD IS '業種コード';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN HOUJIN_CARD_JOUHOU.KOUSHIN_TIME IS '更新日時';

-- 交通費にICカード、紐付元カード明細を追加
ALTER TABLE KOUTSUUHISEISAN_MEISAI RENAME TO KOUTSUUHISEISAN_MEISAI_OLD;
CREATE TABLE KOUTSUUHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	IC_CARD_NO VARCHAR(16) NOT NULL,
	IC_CARD_SEQUENCE_NO VARCHAR(10) NOT NULL,
	HIMODUKE_CARD_MEISAI BIGINT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KOUTSUUHISEISAN_MEISAI IS '交通費精算明細';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KAISHA_TEHAI_FLG IS '会社手配フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.IC_CARD_NO IS 'ICカード番号';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.IC_CARD_SEQUENCE_NO IS 'ICカードシーケンス番号';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.HIMODUKE_CARD_MEISAI IS '紐付元カード明細';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KOUTSUUHISEISAN_MEISAI
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	JIDOUNYUURYOKU_FLG,
	TANKA,
	MEISAI_KINGAKU,
	'', --IC_CARD_NO,
	'', --IC_CARD_SEQUENCE_NO,
	null, --HIMODUKE_CARD_MEISAI
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KOUTSUUHISEISAN_MEISAI_OLD;
DROP TABLE KOUTSUUHISEISAN_MEISAI_OLD;

-- 国内出張旅費精算 交通費明細にICカード、紐付元カード明細を追加
ALTER TABLE RYOHISEISAN_MEISAI RENAME TO RYOHISEISAN_MEISAI_OLD;
CREATE TABLE RYOHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	KYUUJITSU_NISSUU NUMERIC,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU NUMERIC,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	IC_CARD_NO VARCHAR(16) NOT NULL,
	IC_CARD_SEQUENCE_NO VARCHAR(10) NOT NULL,
	HIMODUKE_CARD_MEISAI BIGINT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN_MEISAI IS '旅費精算明細';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KYUUJITSU_NISSUU IS '休日日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KAISHA_TEHAI_FLG IS '会社手配フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.IC_CARD_NO IS 'ICカード番号';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.IC_CARD_SEQUENCE_NO IS 'ICカードシーケンス番号';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.HIMODUKE_CARD_MEISAI IS '紐付元カード明細';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO RYOHISEISAN_MEISAI
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	KYUUJITSU_NISSUU,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	TANKA,
	MEISAI_KINGAKU,
	'', --IC_CARD_NO,
	'', --IC_CARD_SEQUENCE_NO,
	null, --HIMODUKE_CARD_MEISAI
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM RYOHISEISAN_MEISAI_OLD;
DROP TABLE RYOHISEISAN_MEISAI_OLD;

-- 海外出張旅費精算 交通費明細にICカード、紐付元カード明細を追加
ALTER TABLE KAIGAI_RYOHISEISAN_MEISAI RENAME TO KAIGAI_RYOHISEISAN_MEISAI_OLD;
CREATE TABLE KAIGAI_RYOHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KAIGAI_FLG VARCHAR(1) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	KYUUJITSU_NISSUU NUMERIC,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU NUMERIC,
	HEISHU_CD VARCHAR(4),
	RATE DECIMAL(11,5),
	GAIKA DECIMAL(19,2),
	CURRENCY_UNIT VARCHAR(20),
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	ZEI_KUBUN VARCHAR(1),
	KAZEI_FLG VARCHAR(1),
	IC_CARD_NO VARCHAR(16) NOT NULL,
	IC_CARD_SEQUENCE_NO VARCHAR(10) NOT NULL,
	HIMODUKE_CARD_MEISAI BIGINT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, KAIGAI_FLG, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KAIGAI_RYOHISEISAN_MEISAI IS '海外旅費精算明細';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KAIGAI_FLG IS '海外フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KYUUJITSU_NISSUU IS '休日日数';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KAISHA_TEHAI_FLG IS '会社手配フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.HEISHU_CD IS '幣種コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.RATE IS 'レート';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.GAIKA IS '外貨金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.CURRENCY_UNIT IS '通貨単位';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.ZEI_KUBUN IS '税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KAZEI_FLG IS '課税フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.IC_CARD_NO IS 'ICカード番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.IC_CARD_SEQUENCE_NO IS 'ICカードシーケンス番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.HIMODUKE_CARD_MEISAI IS '紐付元カード明細';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KAIGAI_RYOHISEISAN_MEISAI
SELECT
	DENPYOU_ID,
	KAIGAI_FLG,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	KYUUJITSU_NISSUU,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	HEISHU_CD,
	RATE,
	GAIKA,
	CURRENCY_UNIT,
	TANKA,
	MEISAI_KINGAKU,
	ZEI_KUBUN,
	KAZEI_FLG,
	'', --IC_CARD_NO,
	'', --IC_CARD_SEQUENCE_NO,
	null, --HIMODUKE_CARD_MEISAI
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KAIGAI_RYOHISEISAN_MEISAI_OLD;
DROP TABLE KAIGAI_RYOHISEISAN_MEISAI_OLD;

-- 経費精算明細 紐付元カード明細を追加
ALTER TABLE KEIHISEISAN_MEISAI RENAME TO KEIHISEISAN_MEISAI_OLD;
CREATE TABLE KEIHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1),
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	HIMODUKE_CARD_MEISAI BIGINT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KEIHISEISAN_MEISAI IS '経費精算明細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KAISHA_TEHAI_FLG IS '会社手配フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HIMODUKE_CARD_MEISAI IS '紐付元カード明細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KEIHISEISAN_MEISAI
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	SHIYOUBI,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	null, --HIMODUKE_CARD_MEISAI
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME 
FROM KEIHISEISAN_MEISAI_OLD;
DROP TABLE KEIHISEISAN_MEISAI_OLD;

-- 旅費精算経費明細 紐付元カード明細を追加
ALTER TABLE RYOHISEISAN_KEIHI_MEISAI RENAME TO RYOHISEISAN_KEIHI_MEISAI_OLD;
CREATE TABLE RYOHISEISAN_KEIHI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1),
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	HIMODUKE_CARD_MEISAI BIGINT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN_KEIHI_MEISAI IS '旅費精算経費明細';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KAISHA_TEHAI_FLG IS '会社手配フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.HIMODUKE_CARD_MEISAI IS '紐付元カード明細';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO RYOHISEISAN_KEIHI_MEISAI
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	SHIYOUBI,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	null, --HIMODUKE_CARD_MEISAI
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME 
FROM RYOHISEISAN_KEIHI_MEISAI_OLD;
DROP TABLE RYOHISEISAN_KEIHI_MEISAI_OLD;


-- 海外旅費精算経費明細 紐付元カード明細を追加
ALTER TABLE KAIGAI_RYOHISEISAN_KEIHI_MEISAI RENAME TO KAIGAI_RYOHISEISAN_KEIHI_MEISAI_OLD;
CREATE TABLE KAIGAI_RYOHISEISAN_KEIHI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KAIGAI_FLG VARCHAR(1) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1),
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	KAZEI_FLG VARCHAR(1) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	HEISHU_CD VARCHAR(4),
	RATE DECIMAL(11,5),
	GAIKA DECIMAL(19,2),
	CURRENCY_UNIT VARCHAR(20),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	HIMODUKE_CARD_MEISAI BIGINT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO, KAIGAI_FLG)
) WITHOUT OIDS;
COMMENT ON TABLE KAIGAI_RYOHISEISAN_KEIHI_MEISAI IS '海外旅費精算経費明細';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KAIGAI_FLG IS '海外フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KAZEI_FLG IS '課税フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KAISHA_TEHAI_FLG IS '会社手配フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.HEISHU_CD IS '幣種コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.RATE IS 'レート';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.GAIKA IS '外貨金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.CURRENCY_UNIT IS '通貨単位';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.HIMODUKE_CARD_MEISAI IS '紐付元カード明細';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KAIGAI_RYOHISEISAN_KEIHI_MEISAI
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	KAIGAI_FLG,
	SHIWAKE_EDANO,
	SHIYOUBI,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	KAZEI_FLG,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	HEISHU_CD,
	RATE,
	GAIKA,
	CURRENCY_UNIT,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	null, --HIMODUKE_CARD_MEISAI
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME 
FROM KAIGAI_RYOHISEISAN_KEIHI_MEISAI_OLD;
DROP TABLE KAIGAI_RYOHISEISAN_KEIHI_MEISAI_OLD;

commit;