SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 仮払申請
ALTER TABLE KARIBARAI RENAME TO KARIBARAI_OLD;
CREATE TABLE KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	SEISAN_YOTEIBI DATE,
	SEISAN_KANRYOUBI DATE,
	SHIHARAIBI DATE,
	KARIBARAI_ON VARCHAR(1),
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15),
	KARIBARAI_KINGAKU DECIMAL(15),
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KARIBARAI IS '仮払';
COMMENT ON COLUMN KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KARIBARAI.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN KARIBARAI.SEISAN_KANRYOUBI IS '精算完了日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KARIBARAI.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN KARIBARAI.KARIBARAI_KINGAKU IS '仮払金額';
COMMENT ON COLUMN KARIBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KARIBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KARIBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KARIBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KARIBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KARIBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KARIBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KARIBARAI
SELECT
	DENPYOU_ID,
	SEISAN_YOTEIBI,
	SEISAN_KANRYOUBI,
	SHIHARAIBI,
	'1',       ---移行データは一律「仮払あり」
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	NULL,      ---申請金額
	KINGAKU,   ---仮払金額には旧テーブルの「金額」をセット
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KARIBARAI_OLD;
DROP TABLE KARIBARAI_OLD;

-- 経費精算
ALTER TABLE KEIHISEISAN RENAME TO KEIHISEISAN_OLD;
CREATE TABLE KEIHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1),
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	DAIRIFLG VARCHAR(1) DEFAULT '0' NOT NULL,
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	HOUJIN_CARD_RIYOU_KINGAKU DECIMAL(15) NOT NULL,
	KAISHA_TEHAI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KEIHISEISAN IS '経費精算';
COMMENT ON COLUMN KEIHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN KEIHISEISAN.DAIRIFLG IS '代理フラグ';
COMMENT ON COLUMN KEIHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KEIHISEISAN.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN KEIHISEISAN.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN KEIHISEISAN.HOUJIN_CARD_RIYOU_KINGAKU IS '内法人カード利用合計';
COMMENT ON COLUMN KEIHISEISAN.KAISHA_TEHAI_KINGAKU IS '会社手配合計';
COMMENT ON COLUMN KEIHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN KEIHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KEIHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KEIHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KEIHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO KEIHISEISAN
SELECT
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	CASE KARIBARAI_DENPYOU_ID WHEN '' THEN '' ELSE '1' END,
	KARIBARAI_MISHIYOU_FLG,
	DAIRIFLG,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	HOUJIN_CARD_RIYOU_KINGAKU,
	KAISHA_TEHAI_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KEIHISEISAN_OLD;
DROP TABLE KEIHISEISAN_OLD;


-- 海外旅費精算
ALTER TABLE KAIGAI_RYOHISEISAN RENAME TO KAIGAI_RYOHISEISAN_OLD;
CREATE TABLE KAIGAI_RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	DAIRIFLG VARCHAR(1) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KAIGAI_TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	HOUJIN_CARD_RIYOU_KINGAKU DECIMAL(15) NOT NULL,
	KAISHA_TEHAI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_NUM NUMERIC(2),
	SASHIHIKI_TANKA DECIMAL(6),
	SASHIHIKI_NUM_KAIGAI NUMERIC(2),
	SASHIHIKI_TANKA_KAIGAI DECIMAL(6),
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	RYOHI_KAZEI_FLG VARCHAR(1) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	KAIGAI_SHIWAKE_EDANO INT,
	KAIGAI_TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KAIGAI_KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KAIGAI_KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KAIGAI_KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KAIGAI_KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KAIGAI_KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KAIGAI_KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KAIGAI_KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KAIGAI_KAZEI_FLG VARCHAR(1) NOT NULL,
	KAIGAI_KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KAIGAI_KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KAIGAI_KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KAIGAI_KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KAIGAI_KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KAIGAI_KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KAIGAI_KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KAIGAI_UF1_CD VARCHAR(20) NOT NULL,
	KAIGAI_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KAIGAI_UF2_CD VARCHAR(20) NOT NULL,
	KAIGAI_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KAIGAI_UF3_CD VARCHAR(20) NOT NULL,
	KAIGAI_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KAIGAI_PROJECT_CD VARCHAR(12) NOT NULL,
	KAIGAI_PROJECT_NAME VARCHAR(20) NOT NULL,
	KAIGAI_TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KAIGAI_RYOHISEISAN IS '海外旅費精算';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.DAIRIFLG IS '代理フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_TEKIYOU IS '摘要（海外）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HOUJIN_CARD_RIYOU_KINGAKU IS '内法人カード利用合計';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAISHA_TEHAI_KINGAKU IS '会社手配合計';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SASHIHIKI_NUM IS '差引回数';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SASHIHIKI_TANKA IS '差引単価';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SASHIHIKI_NUM_KAIGAI IS '差引回数（海外）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SASHIHIKI_TANKA_KAIGAI IS '差引単価（海外）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.RYOHI_KAZEI_FLG IS '旅費課税フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_SHIWAKE_EDANO IS '海外仕訳枝番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_TORIHIKI_NAME IS '海外取引名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KARI_FUTAN_BUMON_CD IS '海外借方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KARI_FUTAN_BUMON_NAME IS '海外借方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KARI_KAMOKU_CD IS '海外借方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KARI_KAMOKU_NAME IS '海外借方科目名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KARI_KAMOKU_EDABAN_CD IS '海外借方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KARI_KAMOKU_EDABAN_NAME IS '海外借方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KARI_KAZEI_KBN IS '海外借方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KAZEI_FLG IS '海外課税フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KASHI_FUTAN_BUMON_CD IS '海外貸方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KASHI_FUTAN_BUMON_NAME IS '海外貸方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KASHI_KAMOKU_CD IS '海外貸方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KASHI_KAMOKU_NAME IS '海外貸方科目名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KASHI_KAMOKU_EDABAN_CD IS '海外貸方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KASHI_KAMOKU_EDABAN_NAME IS '海外貸方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_KASHI_KAZEI_KBN IS '海外貸方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_UF1_CD IS '海外UF1コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_UF1_NAME_RYAKUSHIKI IS '海外UF1名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_UF2_CD IS '海外UF2コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_UF2_NAME_RYAKUSHIKI IS '海外UF2名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_UF3_CD IS '海外UF3コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_UF3_NAME_RYAKUSHIKI IS '海外UF3名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_PROJECT_CD IS '海外プロジェクトコード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_PROJECT_NAME IS '海外プロジェクト名';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KAIGAI_TEKIYOU_CD IS '海外摘要コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO KAIGAI_RYOHISEISAN
SELECT
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_ON,
	KARIBARAI_MISHIYOU_FLG,
	DAIRIFLG,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	KAIGAI_TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	HOUJIN_CARD_RIYOU_KINGAKU,
	KAISHA_TEHAI_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	NULL,
	NULL,
	NULL,
	NULL,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	RYOHI_KAZEI_FLG,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	KAIGAI_SHIWAKE_EDANO,
	KAIGAI_TORIHIKI_NAME,
	KAIGAI_KARI_FUTAN_BUMON_CD,
	KAIGAI_KARI_FUTAN_BUMON_NAME,
	KAIGAI_KARI_KAMOKU_CD,
	KAIGAI_KARI_KAMOKU_NAME,
	KAIGAI_KARI_KAMOKU_EDABAN_CD,
	KAIGAI_KARI_KAMOKU_EDABAN_NAME,
	KAIGAI_KARI_KAZEI_KBN,
	KAIGAI_KAZEI_FLG,
	KAIGAI_KASHI_FUTAN_BUMON_CD,
	KAIGAI_KASHI_FUTAN_BUMON_NAME,
	KAIGAI_KASHI_KAMOKU_CD,
	KAIGAI_KASHI_KAMOKU_NAME,
	KAIGAI_KASHI_KAMOKU_EDABAN_CD,
	KAIGAI_KASHI_KAMOKU_EDABAN_NAME,
	KAIGAI_KASHI_KAZEI_KBN,
	KAIGAI_UF1_CD,
	KAIGAI_UF1_NAME_RYAKUSHIKI,
	KAIGAI_UF2_CD,
	KAIGAI_UF2_NAME_RYAKUSHIKI,
	KAIGAI_UF3_CD,
	KAIGAI_UF3_NAME_RYAKUSHIKI,
	KAIGAI_PROJECT_CD,
	KAIGAI_PROJECT_NAME,
	KAIGAI_TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KAIGAI_RYOHISEISAN_OLD;
DROP TABLE KAIGAI_RYOHISEISAN_OLD;

-- 海外旅費仮払
ALTER TABLE KAIGAI_RYOHI_KARIBARAI RENAME TO KAIGAI_RYOHI_KARIBARAI_OLD;
CREATE TABLE KAIGAI_RYOHI_KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1) DEFAULT '0' NOT NULL,
	DAIRIFLG VARCHAR(1) NOT NULL,
	USER_ID VARCHAR(30),
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	KARIBARAI_KINGAKU DECIMAL(15),
	SASHIHIKI_NUM NUMERIC(2),
	SASHIHIKI_TANKA DECIMAL(6),
	SASHIHIKI_NUM_KAIGAI NUMERIC(2),
	SASHIHIKI_TANKA_KAIGAI DECIMAL(6),
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KAIGAI_RYOHI_KARIBARAI IS '海外旅費仮払';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.DAIRIFLG IS '代理フラグ';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.MOKUTEKI IS '目的';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARIBARAI_KINGAKU IS '仮払金額';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SASHIHIKI_NUM IS '差引回数';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SASHIHIKI_TANKA IS '差引単価';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SASHIHIKI_NUM_KAIGAI IS '差引回数（海外）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SASHIHIKI_TANKA_KAIGAI IS '差引単価（海外）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHI_KARIBARAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KAIGAI_RYOHI_KARIBARAI
SELECT
	DENPYOU_ID,
	KARIBARAI_ON,
	DAIRIFLG,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	KINGAKU,
	KARIBARAI_KINGAKU,
	NULL,
	NULL,
	NULL,
	NULL,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KAIGAI_RYOHI_KARIBARAI_OLD;
DROP TABLE KAIGAI_RYOHI_KARIBARAI_OLD;

-- 旅費精算
ALTER TABLE RYOHISEISAN RENAME TO RYOHISEISAN_OLD;
CREATE TABLE RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	DAIRIFLG VARCHAR(1) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	HOUJIN_CARD_RIYOU_KINGAKU DECIMAL(15) NOT NULL,
	KAISHA_TEHAI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_NUM NUMERIC(2),
	SASHIHIKI_TANKA DECIMAL(6),
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.DAIRIFLG IS '代理フラグ';
COMMENT ON COLUMN RYOHISEISAN.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN RYOHISEISAN.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN RYOHISEISAN.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.HOUJIN_CARD_RIYOU_KINGAKU IS '内法人カード利用合計';
COMMENT ON COLUMN RYOHISEISAN.KAISHA_TEHAI_KINGAKU IS '会社手配合計';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_NUM IS '差引回数';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_TANKA IS '差引単価';
COMMENT ON COLUMN RYOHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO RYOHISEISAN
SELECT
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_ON,
	KARIBARAI_MISHIYOU_FLG,
	DAIRIFLG,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	HOUJIN_CARD_RIYOU_KINGAKU,
	KAISHA_TEHAI_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	NULL,
	NULL,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM RYOHISEISAN_OLD;
DROP TABLE RYOHISEISAN_OLD;

-- 旅費仮払
ALTER TABLE RYOHI_KARIBARAI RENAME TO RYOHI_KARIBARAI_OLD;
CREATE TABLE RYOHI_KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1) DEFAULT '0' NOT NULL,
	DAIRIFLG VARCHAR(1) NOT NULL,
	USER_ID VARCHAR(30),
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	KARIBARAI_KINGAKU DECIMAL(15),
	SASHIHIKI_NUM NUMERIC(2),
	SASHIHIKI_TANKA DECIMAL(6),
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHI_KARIBARAI IS '旅費仮払';
COMMENT ON COLUMN RYOHI_KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI.DAIRIFLG IS '代理フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN RYOHI_KARIBARAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN RYOHI_KARIBARAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN RYOHI_KARIBARAI.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHI_KARIBARAI.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHI_KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARIBARAI_KINGAKU IS '仮払金額';
COMMENT ON COLUMN RYOHI_KARIBARAI.SASHIHIKI_NUM IS '差引回数';
COMMENT ON COLUMN RYOHI_KARIBARAI.SASHIHIKI_TANKA IS '差引単価';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO RYOHI_KARIBARAI
SELECT
	DENPYOU_ID,
	KARIBARAI_ON,
	DAIRIFLG,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	KINGAKU,
	KARIBARAI_KINGAKU,
	NULL,
	NULL,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM RYOHI_KARIBARAI_OLD;
DROP TABLE RYOHI_KARIBARAI_OLD;

-- 所属部門(有効期限Fromをプライマリキーに変更)
ALTER TABLE SHOZOKU_BUMON RENAME TO SHOZOKU_BUMON_OLD;
CREATE TABLE SHOZOKU_BUMON
(
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_NAME VARCHAR(20) NOT NULL,
	OYA_BUMON_CD VARCHAR(8) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	SECURITY_PATTERN VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (BUMON_CD, YUUKOU_KIGEN_FROM)
) WITHOUT OIDS;
COMMENT ON TABLE SHOZOKU_BUMON IS '所属部門';
COMMENT ON COLUMN SHOZOKU_BUMON.BUMON_CD IS '部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON.BUMON_NAME IS '部門名';
COMMENT ON COLUMN SHOZOKU_BUMON.OYA_BUMON_CD IS '親所属部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHOZOKU_BUMON.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHOZOKU_BUMON.SECURITY_PATTERN IS 'セキュリティパターン';
COMMENT ON COLUMN SHOZOKU_BUMON.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHOZOKU_BUMON.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON.KOUSHIN_TIME IS '更新日時';
INSERT INTO SHOZOKU_BUMON
SELECT
	BUMON_CD,
	BUMON_NAME,
	OYA_BUMON_CD,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	SECURITY_PATTERN,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM SHOZOKU_BUMON_OLD;
DROP TABLE SHOZOKU_BUMON_OLD;

-- 振込日ルール(曜日)テーブルの追加
ALTER TABLE FURIKOMI_BI_RULE RENAME TO FURIKOMI_BI_RULE_HI;

CREATE TABLE FURIKOMI_BI_RULE_YOUBI
(
	KIJUN_WEEKDAY SMALLINT NOT NULL,
	FURIKOMI_WEEKDAY SMALLINT NOT NULL,
	PRIMARY KEY (KIJUN_WEEKDAY)
) WITHOUT OIDS;
COMMENT ON TABLE FURIKOMI_BI_RULE_YOUBI IS '振込日ルール(曜日)';
COMMENT ON COLUMN FURIKOMI_BI_RULE_YOUBI.KIJUN_WEEKDAY IS '基準曜日';
COMMENT ON COLUMN FURIKOMI_BI_RULE_YOUBI.FURIKOMI_WEEKDAY IS '振込曜日';

-- マスター管理の振込日ルール(日付)テーブル部分を修正
update master_kanri_hansuu
set master_id = 'furikomi_bi_rule_hi'
where master_id = 'furikomi_bi_rule';

update master_kanri_ichiran
set master_id = 'furikomi_bi_rule_hi', master_name = '振込日ルール(日付)'
where master_id = 'furikomi_bi_rule';

-- マスター管理の振込日ルール(曜日)テーブル部分を追加
\copy master_kanri_hansuu FROM '.\files\csv\master_kanri_hansuu_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';
\copy master_kanri_ichiran FROM '.\files\csv\master_kanri_ichiran_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 設定情報データ変更 ※hyouji_jun900以降はカスタマイズ領域
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
UPDATE setting_info SET setting_val = '1' WHERE setting_name = 'keihi_karibarai_sentaku_seigyo';	-- 既存環境のUPDATEでは連続性を保つため、初期値を既存機能にあわせて変更
DROP TABLE setting_info_tmp;

--画面項目制御の変更
ALTER TABLE GAMEN_KOUMOKU_SEIGYO RENAME TO GAMEN_KOUMOKU_SEIGYO_TMP;
CREATE TABLE GAMEN_KOUMOKU_SEIGYO
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	KOUMOKU_ID VARCHAR NOT NULL,
	DEFAULT_KOUMOKU_NAME VARCHAR NOT NULL,
	KOUMOKU_NAME VARCHAR NOT NULL,
	HYOUJI_FLG VARCHAR(1) NOT NULL,
	HISSU_FLG VARCHAR(1) NOT NULL,
	HYOUJI_SEIGYO_FLG VARCHAR(1) NOT NULL,
	PDF_HYOUJI_FLG VARCHAR(1) NOT NULL,
	PDF_HYOUJI_SEIGYO_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, KOUMOKU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE GAMEN_KOUMOKU_SEIGYO IS '画面項目制御';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.KOUMOKU_ID IS '項目ID';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.DEFAULT_KOUMOKU_NAME IS 'デフォルト項目名';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.KOUMOKU_NAME IS '項目名';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_FLG IS '表示フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HISSU_FLG IS '必須フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_SEIGYO_FLG IS '表示制御フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.PDF_HYOUJI_FLG IS '帳票表示フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.PDF_HYOUJI_SEIGYO_FLG IS '帳票表示制御フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_JUN IS '表示順';
\copy gamen_koumoku_seigyo FROM '.\files\csv\gamen_koumoku_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE gamen_koumoku_seigyo new SET
  koumoku_name = (SELECT koumoku_name FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
  ,hyouji_flg  = (SELECT hyouji_flg   FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
  ,hissu_flg   = (SELECT hissu_flg    FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
WHERE
  (new.denpyou_kbn,new.koumoku_id) IN (SELECT denpyou_kbn,koumoku_id FROM gamen_koumoku_seigyo_tmp);
-- PDFの表示有無変更可能な項目は、UPDATE前の画面表示有無に合わせてPDF表示有無を初期化する
UPDATE gamen_koumoku_seigyo SET pdf_hyouji_flg = hyouji_flg WHERE pdf_hyouji_seigyo_flg = '1';
INSERT INTO GAMEN_KOUMOKU_SEIGYO    --- カスタマイズ伝票用
SELECT
	DENPYOU_KBN,
	KOUMOKU_ID,
	DEFAULT_KOUMOKU_NAME,
	KOUMOKU_NAME,
	HYOUJI_FLG,
	HISSU_FLG,
	HYOUJI_SEIGYO_FLG,
	'0',       --- pdf表示フラグは一律0（常にチェックOFF状態）
	'0',       --- pdf表示制御フラグは一律0（チェックボックス非表示）
	HYOUJI_JUN
FROM GAMEN_KOUMOKU_SEIGYO_TMP
WHERE denpyou_kbn NOT LIKE 'A%';
DROP TABLE gamen_koumoku_seigyo_tmp;


-- 内部コード ※オプション用レコードはパッチ前になければ削除
DROP TABLE IF EXISTS naibu_cd_setting_tmp;
CREATE TABLE naibu_cd_setting_tmp AS SELECT * FROM naibu_cd_setting;
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM naibu_cd_setting WHERE naibu_cd='A003' AND (SELECT COUNT(*) FROM naibu_cd_setting_tmp WHERE naibu_cd='A003')=0;
DROP TABLE naibu_cd_setting_tmp;

-- 機能制御データ追加(初期値はDKの値を引き継ぐ)
INSERT INTO kinou_seigyo VALUES ( 'UD' , (SELECT kinou_seigyo_kbn FROM kinou_seigyo WHERE kinou_seigyo_cd = 'DK') );

-- 画面権限制御
UPDATE gamen_kengen_seigyo SET system_kanri_riyoukanou_flg='1' WHERE gamen_id IN ('KianKingakuCheck','YosanCheck');

-- 伝票テーブル定義更新
DROP TABLE DENPYOU_ICHIRAN CASCADE;
CREATE TABLE DENPYOU_ICHIRAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	NAME VARCHAR NOT NULL,
	DENPYOU_KBN VARCHAR(4),
	JISSHI_KIAN_BANGOU VARCHAR(15) NOT NULL,
	SHISHUTSU_KIAN_BANGOU VARCHAR(15) NOT NULL,
	YOSAN_SHIKKOU_TAISHOU VARCHAR NOT NULL,
	SERIAL_NO BIGINT,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	TOUROKU_TIME TIMESTAMP,
	BUMON_FULL_NAME VARCHAR NOT NULL,
	USER_FULL_NAME VARCHAR(50) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	DENPYOU_JOUTAI VARCHAR(2) NOT NULL,
	KOUSHIN_TIME TIMESTAMP,
	SHOUNINBI TIMESTAMP,
	MARUHI_FLG VARCHAR(1) NOT NULL,
	ALL_CNT BIGINT,
	CUR_CNT BIGINT,
	ZAN_CNT BIGINT,
	GEN_BUMON_FULL_NAME VARCHAR NOT NULL,
	GEN_USER_FULL_NAME VARCHAR NOT NULL,
	GEN_GYOUMU_ROLE_NAME VARCHAR NOT NULL,
	GEN_NAME VARCHAR NOT NULL,
	VERSION INT,
	KINGAKU DECIMAL(15),
	GAIKA VARCHAR NOT NULL,
	HOUJIN_KINGAKU DECIMAL(15),
	TEHAI_KINGAKU DECIMAL(15),
	TORIHIKISAKI1 VARCHAR NOT NULL,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15),
	KEIJOUBI DATE,
	SHIWAKEKEIJOUBI DATE,
	SEISAN_YOTEIBI DATE,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	KENMEI VARCHAR NOT NULL,
	NAIYOU VARCHAR NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	GEN_USER_ID VARCHAR NOT NULL,
	GEN_GYOUMU_ROLE_ID VARCHAR NOT NULL,
	KIAN_BANGOU_UNYOU_FLG VARCHAR(1) NOT NULL,
	YOSAN_SHIKKOU_TAISHOU_CD VARCHAR NOT NULL,
	KIAN_SYURYOU_FLG VARCHAR NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_NAME VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_NAME VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR NOT NULL,
	KASHI_KAMOKU_CD VARCHAR NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_NAME VARCHAR NOT NULL,
	TEKIYOU VARCHAR NOT NULL,
	HOUJIN_CARD_USE VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_USE VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_EXIST VARCHAR NOT NULL,
	MISEISAN_KARIBARAI_EXIST VARCHAR(1) NOT NULL,
	MISEISAN_UKAGAI_EXIST VARCHAR(1) NOT NULL,
	SHIWAKE_STATUS VARCHAR NOT NULL,
	FB_STATUS VARCHAR NOT NULL,
	JISSHI_NENDO VARCHAR(4) NOT NULL,
	SHISHUTSU_NENDO VARCHAR(4) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	KIAN_BANGOU_INPUT VARCHAR(1) NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_ICHIRAN IS '伝票一覧';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.NAME IS 'ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_ICHIRAN.JISSHI_KIAN_BANGOU IS '実施起案番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHISHUTSU_KIAN_BANGOU IS '支出起案番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU IS '予算執行対象';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SERIAL_NO IS 'シリアル番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_ICHIRAN.BUMON_FULL_NAME IS '部門フル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_FULL_NAME IS 'ユーザーフル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_JOUTAI IS '伝票状態';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHOUNINBI IS '承認日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MARUHI_FLG IS 'マル秘文書フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.ALL_CNT IS '全承認人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.CUR_CNT IS '承認済人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.ZAN_CNT IS '残り承認人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_BUMON_FULL_NAME IS '現在承認者部門フル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_USER_FULL_NAME IS '現在承認者ユーザーフル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_GYOUMU_ROLE_NAME IS '現在承認者業務ロール名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_NAME IS '現在承認者名称';
COMMENT ON COLUMN DENPYOU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KINGAKU IS '金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GAIKA IS '外貨';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUJIN_KINGAKU IS '法人カード払金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TEHAI_KINGAKU IS '会社手配金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TORIHIKISAKI1 IS '取引先1';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIWAKEKEIJOUBI IS '仕訳計上日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KENMEI IS '件名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.NAIYOU IS '内容';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_USER_ID IS '現在承認者ユーザーIDリスト';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_GYOUMU_ROLE_ID IS '現在承認者業務ロールIDリスト';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_BANGOU_UNYOU_FLG IS '起案番号運用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU_CD IS '予算執行対象コード';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_SYURYOU_FLG IS '起案終了フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_KAMOKU_CD IS '借方科目コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_KAMOKU_NAME IS '借方科目名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_TORIHIKISAKI_CD IS '借方取引先コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_TORIHIKISAKI_NAME IS '借方取引先名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_KAMOKU_CD IS '貸方科目コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_KAMOKU_NAME IS '貸方科目名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_TORIHIKISAKI_CD IS '貸方取引先コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_TORIHIKISAKI_NAME IS '貸方取引先名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TEKIYOU IS '摘要(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUJIN_CARD_USE IS '法人カード使用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KAISHA_TEHAI_USE IS '会社手配使用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.RYOUSHUUSHO_EXIST IS '領収書フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MISEISAN_KARIBARAI_EXIST IS '未精算仮払伝票フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MISEISAN_UKAGAI_EXIST IS '未精算伺い伝票フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIWAKE_STATUS IS '仕訳データ作成ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.FB_STATUS IS 'FBデータ作成ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.JISSHI_NENDO IS '実施年度';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHISHUTSU_NENDO IS '支出年度';
COMMENT ON COLUMN DENPYOU_ICHIRAN.BUMON_CD IS '部門コード';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_BANGOU_INPUT IS '起案番号採番フラグ';

-- 定期区間の文字数制限外す(Ver 17.10.27.13と同じもの)
ALTER TABLE teiki_jouhou					ALTER COLUMN web_teiki_kukan	TYPE VARCHAR;
ALTER TABLE tsuukinteiki					ALTER COLUMN jyousha_kukan		TYPE VARCHAR;
ALTER TABLE kaigai_ryohiseisan_meisai		ALTER COLUMN bikou				TYPE VARCHAR;
ALTER TABLE kaigai_ryohi_karibarai_meisai	ALTER COLUMN bikou				TYPE VARCHAR;
ALTER TABLE koutsuuhiseisan_meisai			ALTER COLUMN bikou				TYPE VARCHAR;
ALTER TABLE ryohiseisan_meisai				ALTER COLUMN bikou				TYPE VARCHAR;
ALTER TABLE ryohi_karibarai_meisai			ALTER COLUMN bikou				TYPE VARCHAR;


commit;