SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;


-- 定期情報に定期区間シリアライズデータを追加
ALTER TABLE TEIKI_JOUHOU RENAME TO TEIKI_JOUHOU_TMP;
CREATE TABLE TEIKI_JOUHOU
(
    USER_ID VARCHAR(30) NOT NULL,
    SHIYOU_KAISHIBI DATE NOT NULL,
    SHIYOU_SHUURYOUBI DATE NOT NULL,
    INTRA_EKI_NAME VARCHAR(200),
    INTRA_ROSEN VARCHAR(200),
    WEB_TEIKI_KUKAN VARCHAR,
    WEB_TEIKI_SERIALIZE_DATA VARCHAR NOT NULL,
    TOUROKU_USER_ID VARCHAR(30) NOT NULL,
    TOUROKU_TIME TIMESTAMP NOT NULL,
    KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
    KOUSHIN_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (USER_ID, SHIYOU_KAISHIBI, SHIYOU_SHUURYOUBI)
) WITHOUT OIDS;
COMMENT ON TABLE TEIKI_JOUHOU IS '定期券情報';
COMMENT ON COLUMN TEIKI_JOUHOU.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN TEIKI_JOUHOU.SHIYOU_KAISHIBI IS '使用開始日';
COMMENT ON COLUMN TEIKI_JOUHOU.SHIYOU_SHUURYOUBI IS '使用終了日';
COMMENT ON COLUMN TEIKI_JOUHOU.INTRA_EKI_NAME IS '定期区間駅名';
COMMENT ON COLUMN TEIKI_JOUHOU.INTRA_ROSEN IS '定期区間路線名';
COMMENT ON COLUMN TEIKI_JOUHOU.WEB_TEIKI_KUKAN IS '定期区間情報';
COMMENT ON COLUMN TEIKI_JOUHOU.WEB_TEIKI_SERIALIZE_DATA IS '定期区間シリアライズデータ';
COMMENT ON COLUMN TEIKI_JOUHOU.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN TEIKI_JOUHOU.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN TEIKI_JOUHOU.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN TEIKI_JOUHOU.KOUSHIN_TIME IS '更新日時';
INSERT INTO TEIKI_JOUHOU
SELECT
    USER_ID
    ,SHIYOU_KAISHIBI
    ,SHIYOU_SHUURYOUBI
    ,INTRA_EKI_NAME
    ,INTRA_ROSEN
    ,WEB_TEIKI_KUKAN
    ,'' -- WEB_TEIKI_SERIALIZE_DATA
    ,TOUROKU_USER_ID
    ,TOUROKU_TIME
    ,KOUSHIN_USER_ID
    ,KOUSHIN_TIME
FROM TEIKI_JOUHOU_TMP;
DROP TABLE TEIKI_JOUHOU_TMP;

-- 通勤定期に定期区間シリアライズデータを追加
ALTER TABLE TSUUKINTEIKI RENAME TO TSUUKINTEIKI_TMP;
CREATE TABLE TSUUKINTEIKI
(
    DENPYOU_ID VARCHAR(19) NOT NULL,
    SHIYOU_KIKAN_KBN VARCHAR(2) NOT NULL,
    SHIYOU_KAISHIBI DATE NOT NULL,
    SHIYOU_SHUURYOUBI DATE NOT NULL,
    JYOUSHA_KUKAN VARCHAR NOT NULL,
    TEIKI_SERIALIZE_DATA VARCHAR NOT NULL,
    SHIHARAIBI DATE,
    TEKIYOU VARCHAR(60) NOT NULL,
    ZEIRITSU DECIMAL(3) NOT NULL,
    KINGAKU DECIMAL(15) NOT NULL,
    TENYUURYOKU_FLG VARCHAR(1) NOT NULL,
    HF1_CD VARCHAR(20) NOT NULL,
    HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF2_CD VARCHAR(20) NOT NULL,
    HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF3_CD VARCHAR(20) NOT NULL,
    HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF4_CD VARCHAR(20) NOT NULL,
    HF4_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF5_CD VARCHAR(20) NOT NULL,
    HF5_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF6_CD VARCHAR(20) NOT NULL,
    HF6_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF7_CD VARCHAR(20) NOT NULL,
    HF7_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF8_CD VARCHAR(20) NOT NULL,
    HF8_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF9_CD VARCHAR(20) NOT NULL,
    HF9_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    HF10_CD VARCHAR(20) NOT NULL,
    HF10_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    SHIWAKE_EDANO INT NOT NULL,
    TORIHIKI_NAME VARCHAR(20) NOT NULL,
    KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
    KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
    TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
    TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
    KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
    KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
    KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
    KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
    KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
    KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
    KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
    KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
    KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
    KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
    KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
    UF1_CD VARCHAR(20) NOT NULL,
    UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF2_CD VARCHAR(20) NOT NULL,
    UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF3_CD VARCHAR(20) NOT NULL,
    UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF4_CD VARCHAR(20) NOT NULL,
    UF4_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF5_CD VARCHAR(20) NOT NULL,
    UF5_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF6_CD VARCHAR(20) NOT NULL,
    UF6_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF7_CD VARCHAR(20) NOT NULL,
    UF7_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF8_CD VARCHAR(20) NOT NULL,
    UF8_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF9_CD VARCHAR(20) NOT NULL,
    UF9_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    UF10_CD VARCHAR(20) NOT NULL,
    UF10_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    PROJECT_CD VARCHAR(12) NOT NULL,
    PROJECT_NAME VARCHAR(20) NOT NULL,
    SEGMENT_CD VARCHAR(8) NOT NULL,
    SEGMENT_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
    TEKIYOU_CD VARCHAR(4) NOT NULL,
    TOUROKU_USER_ID VARCHAR(30) NOT NULL,
    TOUROKU_TIME TIMESTAMP NOT NULL,
    KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
    KOUSHIN_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE TSUUKINTEIKI IS '通勤定期';
COMMENT ON COLUMN TSUUKINTEIKI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_KIKAN_KBN IS '使用期間区分';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_KAISHIBI IS '使用開始日';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_SHUURYOUBI IS '使用終了日';
COMMENT ON COLUMN TSUUKINTEIKI.JYOUSHA_KUKAN IS '乗車区間';
COMMENT ON COLUMN TSUUKINTEIKI.TEIKI_SERIALIZE_DATA IS '定期区間シリアライズデータ';
COMMENT ON COLUMN TSUUKINTEIKI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN TSUUKINTEIKI.TEKIYOU IS '摘要';
COMMENT ON COLUMN TSUUKINTEIKI.ZEIRITSU IS '税率';
COMMENT ON COLUMN TSUUKINTEIKI.KINGAKU IS '金額';
COMMENT ON COLUMN TSUUKINTEIKI.TENYUURYOKU_FLG IS '手入力フラグ';
COMMENT ON COLUMN TSUUKINTEIKI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF4_CD IS 'HF4コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF4_NAME_RYAKUSHIKI IS 'HF4名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF5_CD IS 'HF5コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF5_NAME_RYAKUSHIKI IS 'HF5名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF6_CD IS 'HF6コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF6_NAME_RYAKUSHIKI IS 'HF6名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF7_CD IS 'HF7コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF7_NAME_RYAKUSHIKI IS 'HF7名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF8_CD IS 'HF8コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF8_NAME_RYAKUSHIKI IS 'HF8名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF9_CD IS 'HF9コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF9_NAME_RYAKUSHIKI IS 'HF9名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF10_CD IS 'HF10コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF10_NAME_RYAKUSHIKI IS 'HF10名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN TSUUKINTEIKI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN TSUUKINTEIKI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN TSUUKINTEIKI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN TSUUKINTEIKI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF4_CD IS 'UF4コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF4_NAME_RYAKUSHIKI IS 'UF4名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF5_CD IS 'UF5コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF5_NAME_RYAKUSHIKI IS 'UF5名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF6_CD IS 'UF6コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF6_NAME_RYAKUSHIKI IS 'UF6名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF7_CD IS 'UF7コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF7_NAME_RYAKUSHIKI IS 'UF7名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF8_CD IS 'UF8コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF8_NAME_RYAKUSHIKI IS 'UF8名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF9_CD IS 'UF9コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF9_NAME_RYAKUSHIKI IS 'UF9名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF10_CD IS 'UF10コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF10_NAME_RYAKUSHIKI IS 'UF10名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN TSUUKINTEIKI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN TSUUKINTEIKI.SEGMENT_CD IS 'セグメントコード';
COMMENT ON COLUMN TSUUKINTEIKI.SEGMENT_NAME_RYAKUSHIKI IS 'セグメント名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN TSUUKINTEIKI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN TSUUKINTEIKI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN TSUUKINTEIKI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN TSUUKINTEIKI.KOUSHIN_TIME IS '更新日時';
INSERT INTO TSUUKINTEIKI
SELECT
    DENPYOU_ID
    ,SHIYOU_KIKAN_KBN
    ,SHIYOU_KAISHIBI
    ,SHIYOU_SHUURYOUBI
    ,JYOUSHA_KUKAN
    ,'' -- TEIKI_SERIALIZE_DATA
    ,SHIHARAIBI
    ,TEKIYOU
    ,ZEIRITSU
    ,KINGAKU
    ,TENYUURYOKU_FLG
    ,HF1_CD
    ,HF1_NAME_RYAKUSHIKI
    ,HF2_CD
    ,HF2_NAME_RYAKUSHIKI
    ,HF3_CD
    ,HF3_NAME_RYAKUSHIKI
    ,HF4_CD
    ,HF4_NAME_RYAKUSHIKI
    ,HF5_CD
    ,HF5_NAME_RYAKUSHIKI
    ,HF6_CD
    ,HF6_NAME_RYAKUSHIKI
    ,HF7_CD
    ,HF7_NAME_RYAKUSHIKI
    ,HF8_CD
    ,HF8_NAME_RYAKUSHIKI
    ,HF9_CD
    ,HF9_NAME_RYAKUSHIKI
    ,HF10_CD
    ,HF10_NAME_RYAKUSHIKI
    ,SHIWAKE_EDANO
    ,TORIHIKI_NAME
    ,KARI_FUTAN_BUMON_CD
    ,KARI_FUTAN_BUMON_NAME
    ,TORIHIKISAKI_CD
    ,TORIHIKISAKI_NAME_RYAKUSHIKI
    ,KARI_KAMOKU_CD
    ,KARI_KAMOKU_NAME
    ,KARI_KAMOKU_EDABAN_CD
    ,KARI_KAMOKU_EDABAN_NAME
    ,KARI_KAZEI_KBN
    ,KASHI_FUTAN_BUMON_CD
    ,KASHI_FUTAN_BUMON_NAME
    ,KASHI_KAMOKU_CD
    ,KASHI_KAMOKU_NAME
    ,KASHI_KAMOKU_EDABAN_CD
    ,KASHI_KAMOKU_EDABAN_NAME
    ,KASHI_KAZEI_KBN
    ,UF1_CD
    ,UF1_NAME_RYAKUSHIKI
    ,UF2_CD
    ,UF2_NAME_RYAKUSHIKI
    ,UF3_CD
    ,UF3_NAME_RYAKUSHIKI
    ,UF4_CD
    ,UF4_NAME_RYAKUSHIKI
    ,UF5_CD
    ,UF5_NAME_RYAKUSHIKI
    ,UF6_CD
    ,UF6_NAME_RYAKUSHIKI
    ,UF7_CD
    ,UF7_NAME_RYAKUSHIKI
    ,UF8_CD
    ,UF8_NAME_RYAKUSHIKI
    ,UF9_CD
    ,UF9_NAME_RYAKUSHIKI
    ,UF10_CD
    ,UF10_NAME_RYAKUSHIKI
    ,PROJECT_CD
    ,PROJECT_NAME
    ,SEGMENT_CD
    ,SEGMENT_NAME_RYAKUSHIKI
    ,TEKIYOU_CD
    ,TOUROKU_USER_ID
    ,TOUROKU_TIME
    ,KOUSHIN_USER_ID
    ,KOUSHIN_TIME
FROM TSUUKINTEIKI_TMP;
DROP TABLE TSUUKINTEIKI_TMP;


commit;