SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 交通手段マスター（テーブル作成）
CREATE TABLE KOUTSUU_SHUDAN_MASTER
(
	SORT_JUN CHAR(3) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (KOUTSUU_SHUDAN)
) WITHOUT OIDS;

COMMENT ON TABLE KOUTSUU_SHUDAN_MASTER IS '交通手段マスター';
COMMENT ON COLUMN KOUTSUU_SHUDAN_MASTER.SORT_JUN IS '並び順';
COMMENT ON COLUMN KOUTSUU_SHUDAN_MASTER.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN KOUTSUU_SHUDAN_MASTER.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';

-- 交通費精算（テーブル作成）
CREATE TABLE KOUTSUUHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE KOUTSUUHISEISAN IS '交通費精算';
COMMENT ON COLUMN KOUTSUUHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN KOUTSUUHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KOUTSUUHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN KOUTSUUHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_TIME IS '更新日時';


-- 交通費精算明細（テーブル作成）
CREATE TABLE KOUTSUUHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE KOUTSUUHISEISAN_MEISAI IS '交通費精算明細';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

-- 日当等マスター（カラム追加）
-- テーブルバックアップ
ALTER TABLE NITTOU_NADO_MASTER RENAME TO NITTOU_NADO_MASTER_OLD;

-- テーブル作成
CREATE TABLE NITTOU_NADO_MASTER
(
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	YAKUSHOKU_CD VARCHAR(10) NOT NULL,
	TANKA DECIMAL(15),
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (SHUBETSU1, SHUBETSU2, YAKUSHOKU_CD)
) WITHOUT OIDS;

COMMENT ON TABLE NITTOU_NADO_MASTER IS '日当等マスター';
COMMENT ON COLUMN NITTOU_NADO_MASTER.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN NITTOU_NADO_MASTER.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN NITTOU_NADO_MASTER.YAKUSHOKU_CD IS '役職コード';
COMMENT ON COLUMN NITTOU_NADO_MASTER.TANKA IS '単価';
COMMENT ON COLUMN NITTOU_NADO_MASTER.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';

-- データ移行
INSERT INTO NITTOU_NADO_MASTER (
	SHUBETSU1,
	SHUBETSU2,
	YAKUSHOKU_CD,
	TANKA,
	SHOUHYOU_SHORUI_HISSU_FLG
)
SELECT 
	SHUBETSU1,
	SHUBETSU2,
	YAKUSHOKU_CD,
	TANKA,
	'0'
FROM NITTOU_NADO_MASTER_OLD;
DROP TABLE NITTOU_NADO_MASTER_OLD;

-- 旅費精算明細（カラム追加）
-- テーブルバックアップ
ALTER TABLE RYOHISEISAN_MEISAI RENAME TO RYOHISEISAN_MEISAI_OLD;

-- テーブル作成
CREATE TABLE RYOHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU INT,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE RYOHISEISAN_MEISAI IS '旅費精算明細';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

-- データ移行
INSERT INTO RYOHISEISAN_MEISAI (
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	TANKA,
	MEISAI_KINGAKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	'',
	'0',
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	TANKA,
	MEISAI_KINGAKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM RYOHISEISAN_MEISAI_OLD;
DROP TABLE RYOHISEISAN_MEISAI_OLD;

-- 伝票種別一覧データ変更
CREATE TABLE denpyou_shubetsu_ichiran_tmp AS SELECT * FROM denpyou_shubetsu_ichiran;
DELETE FROM denpyou_shubetsu_ichiran_tmp;
\copy denpyou_shubetsu_ichiran_tmp FROM '.\files\csv\denpyou_shubetsu_ichiran.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE denpyou_shubetsu_ichiran SET denpyou_shubetsu = (SELECT denpyou_shubetsu FROM denpyou_shubetsu_ichiran_tmp WHERE denpyou_kbn = 'A004') WHERE denpyou_kbn = 'A004';
UPDATE denpyou_shubetsu_ichiran SET hyouji_jun = hyouji_jun + 1 WHERE hyouji_jun > (SELECT hyouji_jun FROM denpyou_shubetsu_ichiran WHERE denpyou_kbn = 'A004');
INSERT INTO denpyou_shubetsu_ichiran (select * from denpyou_shubetsu_ichiran_tmp WHERE denpyou_kbn = 'A010');
UPDATE denpyou_shubetsu_ichiran SET hyouji_jun = (SELECT hyouji_jun FROM denpyou_shubetsu_ichiran WHERE denpyou_kbn = 'A004') + 1 WHERE denpyou_kbn = 'A010';
DROP TABLE denpyou_shubetsu_ichiran_tmp;

-- 画面権限制御データ変更（差分のみインポート）
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 機能制御データ変更（差分のみインポート）
\copy kinou_seigyo FROM '.\files\csv\kinou_seigyo_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター管理版数データ変更（差分のみインポート）
\copy master_kanri_hansuu FROM '.\files\csv\master_kanri_hansuu_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター管理一覧データ変更（差分のみインポート）
\copy master_kanri_ichiran FROM '.\files\csv\master_kanri_ichiran_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 内部コード設定データ変更
CREATE TABLE naibu_cd_setting_tmp AS SELECT * FROM naibu_cd_setting;
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM naibu_cd_setting
	WHERE NOT EXISTS (SELECT naibu_cd_name FROM naibu_cd_setting_tmp WHERE naibu_cd_name = 'denpyou_kbn' AND naibu_cd = 'A003') 
	      AND naibu_cd_name = 'denpyou_kbn' AND naibu_cd = 'A003';
DELETE FROM naibu_cd_setting 
	WHERE NOT EXISTS (SELECT naibu_cd_name FROM naibu_cd_setting_tmp WHERE naibu_cd_name = 'shiwake_pattern_denpyou_kbn' AND naibu_cd = 'A003') 
	      AND naibu_cd_name = 'shiwake_pattern_denpyou_kbn' AND naibu_cd = 'A003';
DROP TABLE naibu_cd_setting_tmp;

-- 設定情報データ変更
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info;
\copy setting_info FROM '.\files\csv\setting_info.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 仕訳パターン設定データ変更
CREATE TABLE shiwake_pattern_setting_tmp AS SELECT * FROM shiwake_pattern_setting;
DELETE FROM shiwake_pattern_setting;
\copy shiwake_pattern_setting FROM '.\files\csv\shiwake_pattern_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM shiwake_pattern_setting WHERE NOT EXISTS (SELECT denpyou_kbn FROM shiwake_pattern_setting_tmp WHERE denpyou_kbn = 'A003') AND denpyou_kbn = 'A003';
DROP TABLE shiwake_pattern_setting_tmp;

commit;
