SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;


CREATE TABLE BACKUP_COMMENT
(
	FILE_NAME VARCHAR NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	COMMENT VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (FILE_NAME)
) WITHOUT OIDS;


COMMENT ON TABLE BACKUP_COMMENT IS 'バックアップコメント';
COMMENT ON COLUMN BACKUP_COMMENT.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN BACKUP_COMMENT.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN BACKUP_COMMENT.COMMENT IS 'コメント';
COMMENT ON COLUMN BACKUP_COMMENT.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN BACKUP_COMMENT.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN BACKUP_COMMENT.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN BACKUP_COMMENT.KOUSHIN_TIME IS '更新日時';
