SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 設定情報データ変更 ※hyouji_jun900以降はカスタマイズ領域
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 部門推奨ルート
ALTER TABLE BUMON_SUISHOU_ROUTE_OYA RENAME TO BUMON_SUISHOU_ROUTE_OYA_OLD;
CREATE TABLE BUMON_SUISHOU_ROUTE_OYA
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	EDANO INT NOT NULL,
	DEFAULT_FLG VARCHAR(1) NOT NULL,
	SHIWAKE_EDANO INT[],
	KINGAKU_FROM DECIMAL(15),
	KINGAKU_TO DECIMAL(15),
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, BUMON_CD, EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE BUMON_SUISHOU_ROUTE_OYA IS '部門推奨ルート親';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.BUMON_CD IS '部門コード';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.EDANO IS '枝番号';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.DEFAULT_FLG IS 'デフォルトフラグ';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.KINGAKU_FROM IS '金額開始';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.KINGAKU_TO IS '金額終了';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_OYA.KOUSHIN_TIME IS '更新日時';
INSERT INTO BUMON_SUISHOU_ROUTE_OYA(
	DENPYOU_KBN,
	BUMON_CD,
	EDANO,
	DEFAULT_FLG,
	SHIWAKE_EDANO,
	KINGAKU_FROM,
	KINGAKU_TO,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_KBN,
	BUMON_CD,
	EDANO,
	'1',
	null,
	KINGAKU_FROM,
	KINGAKU_TO,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM BUMON_SUISHOU_ROUTE_OYA_OLD;
DROP TABLE BUMON_SUISHOU_ROUTE_OYA_OLD;

-- 伝票種別一覧
ALTER TABLE DENPYOU_SHUBETSU_ICHIRAN RENAME TO DENPYOU_SHUBETSU_ICHIRAN_OLD;
CREATE TABLE DENPYOU_SHUBETSU_ICHIRAN
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT DEFAULT 0 NOT NULL,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	HYOUJI_JUN INT NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	NAIYOU VARCHAR(160) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	KANREN_SENTAKU_FLG VARCHAR(1) NOT NULL,
	KANREN_HYOUJI_FLG VARCHAR(1) NOT NULL,
	DENPYOU_PRINT_FLG VARCHAR(1) NOT NULL,
	KIANBANGOU_UNYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YOSAN_SHIKKOU_TAISHOU VARCHAR(1) DEFAULT 'X' NOT NULL,
	ROUTE_HANTEI_KINGAKU VARCHAR(1) DEFAULT '0' NOT NULL,
	ROUTE_TORIHIKI_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	SHOUNIN_JYOUKYOU_PRINT_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_SHUBETSU_ICHIRAN IS '伝票種別一覧';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_SHUBETSU IS '伝票種別（帳票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（帳票・仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.NAIYOU IS '内容（伝票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_SENTAKU_FLG IS '関連伝票選択フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_HYOUJI_FLG IS '関連伝票入力欄表示フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_FLG IS '申請時帳票出力フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KIANBANGOU_UNYOU_FLG IS '起案番号運用フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU IS '予算執行対象';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.ROUTE_HANTEI_KINGAKU IS 'ルート判定金額';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.ROUTE_TORIHIKI_FLG IS 'ルート取引毎設定フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.SHOUNIN_JYOUKYOU_PRINT_FLG IS '承認状況欄印刷フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO DENPYOU_SHUBETSU_ICHIRAN(
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU,
	DENPYOU_PRINT_SHUBETSU,
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	DENPYOU_PRINT_FLG,
	KIANBANGOU_UNYOU_FLG,
	YOSAN_SHIKKOU_TAISHOU,
	ROUTE_HANTEI_KINGAKU,
	ROUTE_TORIHIKI_FLG,
	SHOUNIN_JYOUKYOU_PRINT_FLG,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU,
	DENPYOU_PRINT_SHUBETSU,
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	DENPYOU_PRINT_FLG,
	KIANBANGOU_UNYOU_FLG,
	YOSAN_SHIKKOU_TAISHOU,
	ROUTE_HANTEI_KINGAKU,
	'0',
	SHOUNIN_JYOUKYOU_PRINT_FLG,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM DENPYOU_SHUBETSU_ICHIRAN_OLD;
DROP TABLE DENPYOU_SHUBETSU_ICHIRAN_OLD;


-- 伝票一覧情報保持テーブルの作成

CREATE TABLE DENPYOU_ICHIRAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	NAME VARCHAR NOT NULL,
	DENPYOU_KBN VARCHAR(4),
	JISSHI_KIAN_BANGOU VARCHAR(13) NOT NULL,
	SHISHUTSU_KIAN_BANGOU VARCHAR(13) NOT NULL,
	YOSAN_SHIKKOU_TAISHOU VARCHAR NOT NULL,
	SERIAL_NO BIGINT,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	TOUROKU_TIME TIMESTAMP,
	BUMON_FULL_NAME VARCHAR NOT NULL,
	USER_FULL_NAME VARCHAR(50) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	GYOUMU_ROLE_ID VARCHAR(5) NOT NULL,
	DENPYOU_JOUTAI VARCHAR(2) NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	KOUSHIN_TIME TIMESTAMP,
	SHOUNINBI TIMESTAMP,
	MARUHI_FLG VARCHAR(1) NOT NULL,
	ALL_CNT BIGINT,
	CUR_CNT BIGINT,
	ZAN_CNT BIGINT,
	GEN_BUMON_FULL_NAME VARCHAR NOT NULL,
	GEN_USER_FULL_NAME VARCHAR NOT NULL,
	GEN_GYOUMU_ROLE_NAME VARCHAR NOT NULL,
	GEN_NAME VARCHAR NOT NULL,
	VERSION INT,
	KINGAKU DECIMAL(15),
	GAIKA VARCHAR NOT NULL,
	HOUJIN_KINGAKU DECIMAL(15),
	TEHAI_KINGAKU DECIMAL(15),
	TORIHIKISAKI1 VARCHAR NOT NULL,
	TORIHIKISAKI2 VARCHAR NOT NULL,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15),
	KEIJOUBI DATE,
	SHIWAKEKEIJOUBI DATE,
	SEISAN_YOTEIBI DATE,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	KENMEI VARCHAR NOT NULL,
	NAIYOU VARCHAR NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	GEN_USER_ID VARCHAR NOT NULL,
	GEN_GYOUMU_ROLE_ID VARCHAR NOT NULL,
	KIAN_BANGOU_UNYOU_FLG VARCHAR(1) NOT NULL,
	YOSAN_SHIKKOU_TAISHOU_CD VARCHAR NOT NULL,
	KIAN_SYURYOU_FLG VARCHAR NOT NULL,
	KIAN_ARI_SHISHUTU_NASI_FLG VARCHAR NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_NAME VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_NAME VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR NOT NULL,
	KASHI_KAMOKU_CD VARCHAR NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_NAME VARCHAR NOT NULL,
	TEKIYOU VARCHAR NOT NULL,
	HOUJIN_CARD_USE VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_USE VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_EXIST VARCHAR NOT NULL,
	MISEISAN_EXIST VARCHAR(1) NOT NULL,
	SHIWAKE_STATUS VARCHAR NOT NULL,
	FB_STATUS VARCHAR NOT NULL,
	JISSHI_NENDO VARCHAR(4) NOT NULL,
	SHISHUTSU_NENDO VARCHAR(4) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	FUTAN_BUMON_CD VARCHAR NOT NULL,
	KIAN_BANGOU_INPUT VARCHAR(1) NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE DENPYOU_ICHIRAN IS '伝票一覧';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.NAME IS 'ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_ICHIRAN.JISSHI_KIAN_BANGOU IS '実施起案番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHISHUTSU_KIAN_BANGOU IS '支出起案番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU IS '予算執行対象';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SERIAL_NO IS 'シリアル番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_ICHIRAN.BUMON_FULL_NAME IS '部門フル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_FULL_NAME IS 'ユーザーフル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_JOUTAI IS '伝票状態';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHOUNINBI IS '承認日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MARUHI_FLG IS 'マル秘文書フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.ALL_CNT IS '全承認人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.CUR_CNT IS '承認済人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.ZAN_CNT IS '残り承認人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_BUMON_FULL_NAME IS '現在承認者部門フル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_USER_FULL_NAME IS '現在承認者ユーザーフル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_GYOUMU_ROLE_NAME IS '現在承認者業務ロール名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_NAME IS '現在承認者名称';
COMMENT ON COLUMN DENPYOU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KINGAKU IS '金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GAIKA IS '外貨';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUJIN_KINGAKU IS '法人カード払金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TEHAI_KINGAKU IS '会社手配金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TORIHIKISAKI1 IS '取引先1';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TORIHIKISAKI2 IS '取引先2';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIWAKEKEIJOUBI IS '仕訳計上日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KENMEI IS '件名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.NAIYOU IS '内容';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_USER_ID IS '現在承認者ユーザーIDリスト';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_GYOUMU_ROLE_ID IS '現在承認者業務ロールIDリスト';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_BANGOU_UNYOU_FLG IS '起案番号運用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU_CD IS '予算執行対象コード';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_SYURYOU_FLG IS '起案終了フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_ARI_SHISHUTU_NASI_FLG IS '起案番号あり且つ支出依頼なしフラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_KAMOKU_CD IS '借方科目コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_KAMOKU_NAME IS '借方科目名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_TORIHIKISAKI_CD IS '借方取引先コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_TORIHIKISAKI_NAME IS '借方取引先名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_KAMOKU_CD IS '貸方科目コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_KAMOKU_NAME IS '貸方科目名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_TORIHIKISAKI_CD IS '貸方取引先コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_TORIHIKISAKI_NAME IS '貸方取引先名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TEKIYOU IS '摘要(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUJIN_CARD_USE IS '法人カード使用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KAISHA_TEHAI_USE IS '会社手配使用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.RYOUSHUUSHO_EXIST IS '領収書フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MISEISAN_EXIST IS '未精算仮払伝票フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIWAKE_STATUS IS '仕訳データ作成ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.FB_STATUS IS 'FBデータ作成ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.JISSHI_NENDO IS '実施年度';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHISHUTSU_NENDO IS '支出年度';
COMMENT ON COLUMN DENPYOU_ICHIRAN.BUMON_CD IS '部門コード';
COMMENT ON COLUMN DENPYOU_ICHIRAN.FUTAN_BUMON_CD IS '負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_BANGOU_INPUT IS '起案番号採番フラグ';


commit;