SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 海外旅費精算明細
ALTER TABLE KAIGAI_RYOHISEISAN_MEISAI RENAME TO KAIGAI_RYOHISEISAN_MEISAI_OLD;
CREATE TABLE KAIGAI_RYOHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KAIGAI_FLG VARCHAR(1) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	KYUUJITSU_NISSUU NUMERIC,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU NUMERIC,
	HEISHU_CD VARCHAR(4),
	RATE DECIMAL(11,5),
	GAIKA DECIMAL(19,2),
	CURRENCY_UNIT VARCHAR(20),
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	ZEI_KUBUN VARCHAR(1),
	KAZEI_FLG VARCHAR(1),
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, KAIGAI_FLG, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KAIGAI_RYOHISEISAN_MEISAI IS '海外旅費精算明細';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KAIGAI_FLG IS '海外フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KYUUJITSU_NISSUU IS '休日日数';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KAISHA_TEHAI_FLG IS '会社手配フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.HEISHU_CD IS '幣種コード';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.RATE IS 'レート';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.GAIKA IS '外貨金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.CURRENCY_UNIT IS '通貨単位';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.ZEI_KUBUN IS '税区分';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KAZEI_FLG IS '課税フラグ';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KAIGAI_RYOHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KAIGAI_RYOHISEISAN_MEISAI(
	DENPYOU_ID,
	KAIGAI_FLG,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	KYUUJITSU_NISSUU,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	HEISHU_CD,
	RATE,
	GAIKA,
	CURRENCY_UNIT,
	TANKA,
	MEISAI_KINGAKU,
	ZEI_KUBUN,
	KAZEI_FLG,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_ID,
	KAIGAI_FLG,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	KYUUJITSU_NISSUU,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	HOUJIN_CARD_RIYOU_FLG,
	KAISHA_TEHAI_FLG,
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	HEISHU_CD,
	RATE,
	GAIKA,
	CURRENCY_UNIT,
	TANKA,
	MEISAI_KINGAKU,
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KAIGAI_RYOHISEISAN_MEISAI_OLD;
DROP TABLE KAIGAI_RYOHISEISAN_MEISAI_OLD;

commit;