SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 添付ファイル名にUTF-8のノーブレークスペース(&nbsp)がある場合通常半角スペースに変換 ※Ver 17.08.04.09の追いかけ対応
UPDATE tenpu_file SET file_name = REPLACE(file_name, CONVERT_FROM('\xc2a0', 'utf8'), CONVERT_FROM('\x20', 'utf8'));

-- 伝票一覧
ALTER TABLE DENPYOU_ICHIRAN RENAME TO DENPYOU_ICHIRAN_OLD;
CREATE TABLE DENPYOU_ICHIRAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	NAME VARCHAR NOT NULL,
	DENPYOU_KBN VARCHAR(4),
	JISSHI_KIAN_BANGOU VARCHAR(15) NOT NULL,
	SHISHUTSU_KIAN_BANGOU VARCHAR(15) NOT NULL,
	YOSAN_SHIKKOU_TAISHOU VARCHAR NOT NULL,
	SERIAL_NO BIGINT,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	TOUROKU_TIME TIMESTAMP,
	BUMON_FULL_NAME VARCHAR NOT NULL,
	USER_FULL_NAME VARCHAR(50) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	GYOUMU_ROLE_ID VARCHAR(5) NOT NULL,
	DENPYOU_JOUTAI VARCHAR(2) NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	KOUSHIN_TIME TIMESTAMP,
	SHOUNINBI TIMESTAMP,
	MARUHI_FLG VARCHAR(1) NOT NULL,
	ALL_CNT BIGINT,
	CUR_CNT BIGINT,
	ZAN_CNT BIGINT,
	GEN_BUMON_FULL_NAME VARCHAR NOT NULL,
	GEN_USER_FULL_NAME VARCHAR NOT NULL,
	GEN_GYOUMU_ROLE_NAME VARCHAR NOT NULL,
	GEN_NAME VARCHAR NOT NULL,
	VERSION INT,
	KINGAKU DECIMAL(15),
	GAIKA VARCHAR NOT NULL,
	HOUJIN_KINGAKU DECIMAL(15),
	TEHAI_KINGAKU DECIMAL(15),
	TORIHIKISAKI1 VARCHAR NOT NULL,
	TORIHIKISAKI2 VARCHAR NOT NULL,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15),
	KEIJOUBI DATE,
	SHIWAKEKEIJOUBI DATE,
	SEISAN_YOTEIBI DATE,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	KENMEI VARCHAR NOT NULL,
	NAIYOU VARCHAR NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	GEN_USER_ID VARCHAR NOT NULL,
	GEN_GYOUMU_ROLE_ID VARCHAR NOT NULL,
	KIAN_BANGOU_UNYOU_FLG VARCHAR(1) NOT NULL,
	YOSAN_SHIKKOU_TAISHOU_CD VARCHAR NOT NULL,
	KIAN_SYURYOU_FLG VARCHAR NOT NULL,
	KIAN_ARI_SHISHUTU_NASI_FLG VARCHAR NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_NAME VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_NAME VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR NOT NULL,
	KASHI_KAMOKU_CD VARCHAR NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_NAME VARCHAR NOT NULL,
	TEKIYOU VARCHAR NOT NULL,
	HOUJIN_CARD_USE VARCHAR(1) NOT NULL,
	KAISHA_TEHAI_USE VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_EXIST VARCHAR NOT NULL,
	MISEISAN_EXIST VARCHAR(1) NOT NULL,
	SHIWAKE_STATUS VARCHAR NOT NULL,
	FB_STATUS VARCHAR NOT NULL,
	JISSHI_NENDO VARCHAR(4) NOT NULL,
	SHISHUTSU_NENDO VARCHAR(4) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	FUTAN_BUMON_CD VARCHAR NOT NULL,
	KIAN_BANGOU_INPUT VARCHAR(1) NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_ICHIRAN IS '伝票一覧';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.NAME IS 'ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_ICHIRAN.JISSHI_KIAN_BANGOU IS '実施起案番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHISHUTSU_KIAN_BANGOU IS '支出起案番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU IS '予算執行対象';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SERIAL_NO IS 'シリアル番号';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_ICHIRAN.BUMON_FULL_NAME IS '部門フル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_FULL_NAME IS 'ユーザーフル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.DENPYOU_JOUTAI IS '伝票状態';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHOUNINBI IS '承認日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MARUHI_FLG IS 'マル秘文書フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.ALL_CNT IS '全承認人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.CUR_CNT IS '承認済人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.ZAN_CNT IS '残り承認人数カウント';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_BUMON_FULL_NAME IS '現在承認者部門フル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_USER_FULL_NAME IS '現在承認者ユーザーフル名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_GYOUMU_ROLE_NAME IS '現在承認者業務ロール名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_NAME IS '現在承認者名称';
COMMENT ON COLUMN DENPYOU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KINGAKU IS '金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GAIKA IS '外貨';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUJIN_KINGAKU IS '法人カード払金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TEHAI_KINGAKU IS '会社手配金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TORIHIKISAKI1 IS '取引先1';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TORIHIKISAKI2 IS '取引先2';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIWAKEKEIJOUBI IS '仕訳計上日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KENMEI IS '件名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.NAIYOU IS '内容';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN DENPYOU_ICHIRAN.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_USER_ID IS '現在承認者ユーザーIDリスト';
COMMENT ON COLUMN DENPYOU_ICHIRAN.GEN_GYOUMU_ROLE_ID IS '現在承認者業務ロールIDリスト';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_BANGOU_UNYOU_FLG IS '起案番号運用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU_CD IS '予算執行対象コード';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_SYURYOU_FLG IS '起案終了フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_ARI_SHISHUTU_NASI_FLG IS '起案番号あり且つ支出依頼なしフラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_KAMOKU_CD IS '借方科目コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_KAMOKU_NAME IS '借方科目名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_TORIHIKISAKI_CD IS '借方取引先コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KARI_TORIHIKISAKI_NAME IS '借方取引先名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_KAMOKU_CD IS '貸方科目コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_KAMOKU_NAME IS '貸方科目名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_TORIHIKISAKI_CD IS '貸方取引先コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KASHI_TORIHIKISAKI_NAME IS '貸方取引先名(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.TEKIYOU IS '摘要(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.HOUJIN_CARD_USE IS '法人カード使用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KAISHA_TEHAI_USE IS '会社手配使用フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.RYOUSHUUSHO_EXIST IS '領収書フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.MISEISAN_EXIST IS '未精算仮払伝票フラグ';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHIWAKE_STATUS IS '仕訳データ作成ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.FB_STATUS IS 'FBデータ作成ステータス';
COMMENT ON COLUMN DENPYOU_ICHIRAN.JISSHI_NENDO IS '実施年度';
COMMENT ON COLUMN DENPYOU_ICHIRAN.SHISHUTSU_NENDO IS '支出年度';
COMMENT ON COLUMN DENPYOU_ICHIRAN.BUMON_CD IS '部門コード';
COMMENT ON COLUMN DENPYOU_ICHIRAN.FUTAN_BUMON_CD IS '負担部門コード(一覧検索用)';
COMMENT ON COLUMN DENPYOU_ICHIRAN.KIAN_BANGOU_INPUT IS '起案番号採番フラグ';
INSERT INTO DENPYOU_ICHIRAN SELECT * FROM DENPYOU_ICHIRAN_OLD;
DROP TABLE DENPYOU_ICHIRAN_OLD;


-- 伝票起案紐づけ
ALTER TABLE DENPYOU_KIAN_HIMOZUKE RENAME TO DENPYOU_KIAN_HIMOZUKE_OLD;
CREATE TABLE DENPYOU_KIAN_HIMOZUKE
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	BUMON_CD VARCHAR(8),
	NENDO VARCHAR(4),
	RYAKUGOU VARCHAR(7),
	KIAN_BANGOU_FROM INT,
	KIAN_BANGOU INT,
	KIAN_SYURYO_FLG VARCHAR(1),
	KIAN_SYURYO_BI DATE,
	KIAN_DENPYOU VARCHAR(19),
	KIAN_DENPYOU_KBN VARCHAR(4),
	JISSHI_NENDO VARCHAR(4),
	JISSHI_KIAN_BANGOU VARCHAR(15),
	SHISHUTSU_NENDO VARCHAR(4),
	SHISHUTSU_KIAN_BANGOU VARCHAR(15),
	RINGI_KINGAKU DECIMAL(15),
	RINGI_KINGAKU_HIKITSUGIMOTO_DENPYOU VARCHAR(19) NOT NULL,
	RINGI_KINGAKU_CHOUKA_COMMENT VARCHAR(240) NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_KIAN_HIMOZUKE IS '伝票起案紐付';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.BUMON_CD IS '部門コード';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.NENDO IS '年度';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.RYAKUGOU IS '略号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_BANGOU_FROM IS '開始起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_BANGOU IS '起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_SYURYO_FLG IS '起案終了フラグ';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_SYURYO_BI IS '起案終了日';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_DENPYOU IS '起案伝票';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_DENPYOU_KBN IS '起案伝票区分';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.JISSHI_NENDO IS '実施年度';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.JISSHI_KIAN_BANGOU IS '実施起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.SHISHUTSU_NENDO IS '支出年度';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.SHISHUTSU_KIAN_BANGOU IS '支出起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.RINGI_KINGAKU IS '稟議金額';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.RINGI_KINGAKU_HIKITSUGIMOTO_DENPYOU IS '稟議金額引継ぎ元伝票';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.RINGI_KINGAKU_CHOUKA_COMMENT IS '稟議金額超過コメント';
INSERT INTO DENPYOU_KIAN_HIMOZUKE SELECT * FROM DENPYOU_KIAN_HIMOZUKE_OLD;
DROP TABLE DENPYOU_KIAN_HIMOZUKE_OLD;

-- 起案番号簿
ALTER TABLE KIAN_BANGOU_BO RENAME TO KIAN_BANGOU_BO_OLD;
CREATE TABLE KIAN_BANGOU_BO
(
	BUMON_CD VARCHAR(8) NOT NULL,
	NENDO VARCHAR(4) NOT NULL,
	RYAKUGOU VARCHAR(7) NOT NULL,
	KIAN_BANGOU_FROM INT DEFAULT 1 NOT NULL,
	KIAN_BANGOU_TO INT DEFAULT 999999 NOT NULL,
	KBN_NAIYOU VARCHAR NOT NULL,
	KIANBANGOU_BO_SENTAKU_HYOUJI_FLG VARCHAR(1) DEFAULT '1' NOT NULL,
	DENPYOU_KENSAKU_HYOUJI_FLG VARCHAR(1) DEFAULT '1' NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	PRIMARY KEY (BUMON_CD, NENDO, RYAKUGOU, KIAN_BANGOU_FROM)
) WITHOUT OIDS;
COMMENT ON TABLE KIAN_BANGOU_BO IS '起案番号簿';
COMMENT ON COLUMN KIAN_BANGOU_BO.BUMON_CD IS '部門コード';
COMMENT ON COLUMN KIAN_BANGOU_BO.NENDO IS '年度';
COMMENT ON COLUMN KIAN_BANGOU_BO.RYAKUGOU IS '略号';
COMMENT ON COLUMN KIAN_BANGOU_BO.KIAN_BANGOU_FROM IS '開始起案番号';
COMMENT ON COLUMN KIAN_BANGOU_BO.KIAN_BANGOU_TO IS '終了起案番号';
COMMENT ON COLUMN KIAN_BANGOU_BO.KBN_NAIYOU IS '区分内容';
COMMENT ON COLUMN KIAN_BANGOU_BO.KIANBANGOU_BO_SENTAKU_HYOUJI_FLG IS '起案番号簿選択表示フラグ';
COMMENT ON COLUMN KIAN_BANGOU_BO.DENPYOU_KENSAKU_HYOUJI_FLG IS '伝票検索表示フラグ';
COMMENT ON COLUMN KIAN_BANGOU_BO.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN KIAN_BANGOU_BO.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN KIAN_BANGOU_BO.HYOUJI_JUN IS '表示順';
INSERT INTO KIAN_BANGOU_BO SELECT * FROM KIAN_BANGOU_BO_OLD;
DROP TABLE KIAN_BANGOU_BO_OLD;

-- 起案番号採番
ALTER TABLE KIAN_BANGOU_SAIBAN RENAME TO KIAN_BANGOU_SAIBAN_OLD;
CREATE TABLE KIAN_BANGOU_SAIBAN
(
	BUMON_CD VARCHAR(8) NOT NULL,
	NENDO VARCHAR(4) NOT NULL,
	RYAKUGOU VARCHAR(7) NOT NULL,
	KIAN_BANGOU_FROM INT NOT NULL,
	KIAN_BANGOU_LAST INT NOT NULL,
	PRIMARY KEY (BUMON_CD, NENDO, RYAKUGOU, KIAN_BANGOU_FROM)
) WITHOUT OIDS;
COMMENT ON TABLE KIAN_BANGOU_SAIBAN IS '起案番号採番';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.BUMON_CD IS '部門コード';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.NENDO IS '年度';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.RYAKUGOU IS '略号';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.KIAN_BANGOU_FROM IS '開始起案番号';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.KIAN_BANGOU_LAST IS '最終起案番号';
INSERT INTO KIAN_BANGOU_SAIBAN SELECT * FROM KIAN_BANGOU_SAIBAN_OLD;
DROP TABLE KIAN_BANGOU_SAIBAN_OLD;

-- マスター管理版数（起案番号簿）
UPDATE MASTER_KANRI_HANSUU SET DELETE_FLG = '1' WHERE MASTER_ID = 'kian_bangou_bo';
INSERT INTO MASTER_KANRI_HANSUU 
(
  MASTER_ID
  , VERSION
  , DELETE_FLG
  , FILE_NAME
  , FILE_SIZE
  , CONTENT_TYPE
  , BINARY_DATA
  , TOUROKU_USER_ID 
  , TOUROKU_TIME 
  , KOUSHIN_USER_ID 
  , KOUSHIN_TIME 
) VALUES (
   'kian_bangou_bo'
 , (SELECT MAX(version) + 1 FROM master_kanri_hansuu WHERE master_id ='kian_bangou_bo')
 , '0'
 , '起案番号簿_patch.csv'
 , length(convert_to(E'部門コード,年度,略号,開始起案番号,終了起案番号,区分内容,起案番号簿選択表示フラグ,伝票検索表示フラグ,有効期限開始日,有効期限終了日,表示順\r\nbumon_cd,nendo,ryakugou,kian_bangou_from,kian_bangou_to,kbn_naiyou,kianbangou_bo_sentaku_hyouji_flg,denpyou_kensaku_hyouji_flg,yuukou_kigen_from,yuukou_kigen_to,hyouji_jun\r\nvarchar(8),varchar(4),varchar(7),int,int,varchar,varchar(1),varchar(1),date,date,int\r\n1,1,1,1,2,2,2,2,2,2,2\r\n' || ARRAY_TO_STRING(ARRAY(SELECT bumon_cd || ',' || nendo || ',' || ryakugou || ',' || kian_bangou_from || ',' || kian_bangou_to || ',' || kbn_naiyou || ',' || kianbangou_bo_sentaku_hyouji_flg || ',' || denpyou_kensaku_hyouji_flg || ',' || replace(yuukou_kigen_from::text,'-'::text,'/'::text) || ',' || replace(yuukou_kigen_to::text,'-'::text,'/'::text) || ',' || hyouji_jun FROM kian_bangou_bo), E'\r\n') || (CASE (SELECT count(*) FROM kian_bangou_bo) WHEN 0 THEN '' ELSE E'\r\n' END),'sjis') )
 , 'application/vnd.ms-excel'
 , convert_to(E'部門コード,年度,略号,開始起案番号,終了起案番号,区分内容,起案番号簿選択表示フラグ,伝票検索表示フラグ,有効期限開始日,有効期限終了日,表示順\r\nbumon_cd,nendo,ryakugou,kian_bangou_from,kian_bangou_to,kbn_naiyou,kianbangou_bo_sentaku_hyouji_flg,denpyou_kensaku_hyouji_flg,yuukou_kigen_from,yuukou_kigen_to,hyouji_jun\r\nvarchar(8),varchar(4),varchar(7),int,int,varchar,varchar(1),varchar(1),date,date,int\r\n1,1,1,1,2,2,2,2,2,2,2\r\n' || ARRAY_TO_STRING(ARRAY(SELECT bumon_cd || ',' || nendo || ',' || ryakugou || ',' || kian_bangou_from || ',' || kian_bangou_to || ',' || kbn_naiyou || ',' || kianbangou_bo_sentaku_hyouji_flg || ',' || denpyou_kensaku_hyouji_flg || ',' || replace(yuukou_kigen_from::text,'-'::text,'/'::text) || ',' || replace(yuukou_kigen_to::text,'-'::text,'/'::text) || ',' || hyouji_jun FROM kian_bangou_bo), E'\r\n') || (CASE (SELECT count(*) FROM kian_bangou_bo) WHEN 0 THEN '' ELSE E'\r\n' END),'sjis')
 , 'patch'
 , current_timestamp
 , 'patch'
 , current_timestamp
);

-- 会計マスターはマスター管理上で参照のみとする
UPDATE master_kanri_ichiran SET henkou_kahi_flg = '0' WHERE henkou_kahi_flg = '1';

-- 添付ファイル名にUTF-8のノーブレークスペース(&nbsp)がある場合通常半角スペースに変換
UPDATE tenpu_file SET file_name = REPLACE(file_name, CONVERT_FROM('\xc2a0', 'utf8'), CONVERT_FROM('\x20', 'utf8'));

commit;