package eteam.gyoumu.tsuuchi;

import java.math.BigDecimal;
import java.sql.Date;

import eteam.gyoumu.user.User;
import lombok.Getter;
import lombok.Setter;

/**
 * @author j_matsumoto
 * 伝票検索の検索用パラメーターを集約
 * 際限なく引数が増えるのにもう振り回されたくないので
 */
@Getter @Setter
public class DenpyouKensakuQueryParameter {
	/** ログインユーザ */
	public User user;
	/** 関連伝票 */
	public String kanrenDenpyou;
	/** 伝票ID */
	public String denpyouId;
	/** シリアル番号 */
	public Long serialNo;
	/** 伝票状態 */
	public String denpyouJoutai;
	/** 業務種別 */
	public String gyoumuShubetsu;
	/** 伝票種別 */
	public String denpyouShubetsu;
	/** 起案番号年度 */
	public String kianBangouNendo;
	/** 略号 */
	public String kianBangouRyakugou;
	/** 起案番号 */
	public String kianBangou;
	/** 起案番号範囲指定略号 */
	public String kianBangouRyakugouFromTo;
	/** 起案番号From */
	public String kianBangouFrom;
	/** 起案番号To */
	public String kianBangouTo;
	/** 起案番号入力 */
	public String kianBangouInput;
	/** 起案番号終了 */
	public String kianBangouEnd;
	/** 起案番号運用 */
	public String kianBangouUnyou;
	/** 起案番号あり且つ支出依頼なし */
	public String kianBangouNoShishutsuIrai;
	/** 予算執行種別 */
	public String[] yosanshikkouShubetsu;
	/** 予算執行対象月From */
	public String yosanCheckNengetsuFrom;
	/** 予算執行対象月To */
	public String yosanCheckNengetsuTo;
	/** 起票日付From */
	public Date kihyouBiFrom;
	/** 起票日付To */
	public Date kihyouBiTo;
	/** 起票者所属部門ID */
	public String kihyouShozokuBumonCd;
	/** 起票者所属部門名 */
	public String kihyouShozokuBumonName;
	/** 起票者社員番号 */
	public String kihyouShozokuUserShainNo;
	/** 起票者名 */
	public String kihyouShozokuUserName;
	/** 承認日付From */
	public Date shouninBiFrom;
	/** 承認日付To */
	public Date shouninBiTo;
	/** 承認者所属部門ID */
	public String shouninsyaShozokuBumonCd;
	/** 承認者所属部門名 */
	public String shouninsyaShozokuBumonName;
	/** 承認者社員番号 */
	public String shouninsyaShozokuUserShainNo;
	/** 承認者名 */
	public String shouninsyaShozokuUserName;
	/** 所有者所属部門コード */
	public String shoyuushaShozokuBumonCd;
	/** 所有者所属部門名 */
	public String shoyuushaShozokuBumonName;
	/** 所有者社員番号 */
	public String shoyuushaShozokuUserShainNo;
	/** 所有者名 */
	public String shoyuushaShozokuUserName;
	/** 摘要 */
	public String tekiyou;
	/** 金額From */
	public BigDecimal kingakuFrom;
	/** 金額To */
	public BigDecimal kingakuTo;
	/** 明細金額From */
	public BigDecimal meisaiKingakuFrom;
	/** 明細金額To */
	public BigDecimal meisaiKingakuTo;
	/** クエリ用税率 */
	public String queryZeiritsu;
	/** 軽減税率区分 */
	public String keigenZeiritsuKbn;
	/** 法人カード利用 */
	public String houjinCardRiyou;
	/** 会社手配利用 */
	public String kaishaTehai;
	/** マル秘文書フラグ */
	public String maruhi;
	/** 支払日From */
	public Date shiharaiBiFrom;
	/** 支払日To */
	public Date shiharaiBiTo;
	/** 支払希望日From */
	public Date shiharaiKiboubiFrom;
	/** 支払希望日To */
	public Date shiharaiKiboubiTo;
	/** 計上日From */
	public Date keijoubiFrom;
	/** 計上日To */
	public Date keijoubiTo;
	/** 仕訳計上日From */
	public Date shiwakeKeijoubiFrom;
	/** 仕訳計上日To */
	public Date shiwakeKeijoubiTo;
	/** 借方部門コード(From) */
	public String karikataBumonCdFrom;
	/** 借方部門コード(To) */
	public String karikataBumonCdTo;
	/** 貸方部門コード(From) */
	public String kashikataBumonCdFrom;
	/** 貸方部門コード(To) */
	public String kashikataBumonCdTo;
	/** 借方科目コード(From) */
	public String karikataKamokuCdFrom;
	/** 借方科目コード(To) */
	public String karikataKamokuCdTo;
	/** 貸方科目コード(From) */
	public String kashikataKamokuCdFrom;
	/** 貸方科目コード(To) */
	public String kashikataKamokuCdTo;
	/** 借方科目枝番コード(From) */
	public String karikataKamokuEdanoCdFrom;
	/** 借方科目枝番コード(To) */
	public String karikataKamokuEdanoCdTo;
	/** 貸方科目枝番コード(From) */
	public String kashikataKamokuEdanoCdFrom;
	/** 貸方科目枝番コード(To) */
	public String kashikataKamokuEdanoCdTo;
	/** 借方取引先コード(From) */
	public String karikataTorihikisakiCdFrom;
	/** 借方取引先コード(To) */
	public String karikataTorihikisakiCdTo;
	/** 貸方取引先コード(From) */
	public String kashikataTorihikisakiCdFrom;
	/** 貸方取引先コード(To) */
	public String kashikataTorihikisakiCdTo;
	/** 借方部門選択フラグ */
	public String bumonSentakuFlag;
	/** 領収書・請求書等 */
	public String ryoushuushoSeikyuushoTou;
	/** 未精算仮払 */
	public String miseisanKaribarai;
	/** 未精算伺い */
	public String miseisanUkagai;
	/** 添付ファイルフラグ */
	public String tenpuFileFlg;
	/** 添付ファイル種別 */
	public String[] tenpuFileShubetsu;
	/** e文書種別 */
	public String ebunshoShubetsu;
	/** e文書年月日From */
	public Date ebunshoNengappiFrom;
	/** e文書年月日To */
	public Date ebunshoNengappiTo;
	/** e文書年月日未入力フラグ */
	public String ebunshoNengappiMinyuuryokuFlg;
	/** e文書金額From */
	public BigDecimal ebunshoKingakuFrom;
	/** e文書金額To */
	public BigDecimal ebunshoKingakuTo;
	/** e文書金額未入力フラグ */
	public String ebunshoKingakuMinyuuryokuFlg;
	/** e文書発行者 */
	public String ebunshoHakkousha;
	/** e文書発行者未入力フラグ */
	public String ebunshoHakkoushaMinyuuryokuFlg;
	/** 仕訳抽出状態 */
	public String shiwakeStatus;
	/** FB作成状態 */
	public String fbStatus;
	/** 部門コードFrom */
	public String bumonCdFrom;
	/** 部門コードTo */
	public String bumonCdTo;
	/** ユーザー定義届書の件名 */
	public String kanitodokeKenmei;
	/** ユーザー定義届書の内容 */
	public String kanitodokeNaiyou;
	/** 取下済・否認済　表示 */
	public String torisageHininHyoujiFlg;
	/** 事業者区分 */
	public String jigyoushaKbn;
	/** 支払先名（一覧検索用） */
	public String shiharaiName;
	/** 税抜金額From */
	public BigDecimal zeinukiKingakuFrom;
	/** 税抜金額To */
	public BigDecimal zeinukiKingakuTo;
	/** 税抜明細金額From */
	public BigDecimal zeinukiMeisaiKingakuFrom;
	/** 税抜明細金額To */
	public BigDecimal zeinukiMeisaiKingakuTo;
}
