SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;


-- 伝票の承認ルート変更フラグ追加
ALTER TABLE DENPYOU ADD COLUMN SHOUNIN_ROUTE_HENKOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL;
COMMENT ON COLUMN DENPYOU.SHOUNIN_ROUTE_HENKOU_FLG IS '承認ルート変更フラグ';

-- (連絡票No.755 19.04.04) 過去バージョンからのアップデート後、申請・更新後に承認ルートがデフォルト設定に戻る現象の修正
UPDATE DENPYOU SET SHOUNIN_ROUTE_HENKOU_FLG = '1';


-- 設定情報データ変更
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 内部コード設定データ変更
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 機能制御データ変更
\copy kinou_seigyo FROM '.\files\csv\kinou_seigyo_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- ユーザー情報の変更
ALTER TABLE USER_INFO RENAME TO USER_INFO_OLD;
CREATE TABLE USER_INFO
(
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	MAIL_ADDRESS VARCHAR(50) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PASS_KOUSHIN_DATE DATE,
	PASS_FAILURE_COUNT INT DEFAULT 0 NOT NULL,
	PASS_FAILURE_TIME TIMESTAMP,
	TMP_LOCK_FLG VARCHAR(1) NOT NULL,
	TMP_LOCK_TIME TIMESTAMP,
	LOCK_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	LOCK_TIME TIMESTAMP,
	DAIRIKIHYOU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLAG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_SHIKIBETSUYOU_NUM VARCHAR(20) NOT NULL,
	SECURITY_PATTERN VARCHAR(4) NOT NULL,
	SECURITY_WFONLY_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE USER_INFO IS 'ユーザー情報';
COMMENT ON COLUMN USER_INFO.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN USER_INFO.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN USER_INFO.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN USER_INFO.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN USER_INFO.MAIL_ADDRESS IS 'メールアドレス';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN USER_INFO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN USER_INFO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN USER_INFO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN USER_INFO.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN USER_INFO.PASS_KOUSHIN_DATE IS 'パスワード変更日';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_COUNT IS 'パスワード誤り回数';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_TIME IS 'パスワード誤り時間';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_FLG IS 'アカウント一時ロックフラグ';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_TIME IS 'アカウント一時ロック時間';
COMMENT ON COLUMN USER_INFO.LOCK_FLG IS 'アカウントロックフラグ';
COMMENT ON COLUMN USER_INFO.LOCK_TIME IS 'アカウントロック時間';
COMMENT ON COLUMN USER_INFO.DAIRIKIHYOU_FLG IS '代理起票可能フラグ';
COMMENT ON COLUMN USER_INFO.HOUJIN_CARD_RIYOU_FLAG IS '法人カード利用';
COMMENT ON COLUMN USER_INFO.HOUJIN_CARD_SHIKIBETSUYOU_NUM IS '法人カード識別用番号';
COMMENT ON COLUMN USER_INFO.SECURITY_PATTERN IS 'セキュリティパターン';
COMMENT ON COLUMN USER_INFO.SECURITY_WFONLY_FLG IS 'セキュリティワークフロー限定フラグ';

INSERT 
INTO USER_INFO( 
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME,
	DAIRIKIHYOU_FLG,
	HOUJIN_CARD_RIYOU_FLAG,
	HOUJIN_CARD_SHIKIBETSUYOU_NUM,
	SECURITY_PATTERN,
	SECURITY_WFONLY_FLG
) 
SELECT
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME,
	DAIRIKIHYOU_FLG,
	'0',
	'',
	SECURITY_PATTERN,
	SECURITY_WFONLY_FLG
FROM
  USER_INFO_OLD;

DROP TABLE USER_INFO_OLD;

-- 仕訳パターンマスターの変更
ALTER TABLE SHIWAKE_PATTERN_MASTER RENAME TO SHIWAKE_PATTERN_MASTER_OLD;

CREATE TABLE SHIWAKE_PATTERN_MASTER
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	DELETE_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	BUNRUI1 VARCHAR(20) NOT NULL,
	BUNRUI2 VARCHAR(20) NOT NULL,
	BUNRUI3 VARCHAR(20) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_FLG VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(20),
	DEFAULT_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KAKE_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	SHAIN_CD_RENKEI_FLG VARCHAR(1) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_PROJECT_CD VARCHAR NOT NULL,
	KARI_KAZEI_KBN VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD1 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD1 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN1 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD2 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD2 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN2 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD3 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD3 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN3 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD4 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD4 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD4 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD4 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN4 VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, SHIWAKE_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE SHIWAKE_PATTERN_MASTER IS '仕訳パターンマスター';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DELETE_FLG IS '削除フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI1 IS '分類1';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI2 IS '分類2';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI3 IS '分類3';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TEKIYOU_FLG IS '摘要フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TEKIYOU IS '摘要';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DEFAULT_HYOUJI_FLG IS 'デフォルト表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSAIHI_HYOUJI_FLG IS '交際費表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KAKE_FLG IS '掛けフラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHAIN_CD_RENKEI_FLG IS '社員コード連携フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_FUTAN_BUMON_CD IS '借方負担部門コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_CD IS '借方科目コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_TORIHIKISAKI_CD IS '借方取引先コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_PROJECT_CD IS '借方プロジェクトコード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAZEI_KBN IS '借方課税区分（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD1 IS '貸方負担部門コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD1 IS '貸方科目コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD1 IS '貸方科目枝番コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD1 IS '貸方取引先コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN1 IS '貸方課税区分１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD2 IS '貸方負担部門コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD2 IS '貸方取引先コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD2 IS '貸方科目コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD2 IS '貸方科目枝番コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN2 IS '貸方課税区分２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD3 IS '貸方負担部門コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD3 IS '貸方取引先コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD3 IS '貸方科目コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD3 IS '貸方科目枝番コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN3 IS '貸方課税区分３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD4 IS '貸方負担部門コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD4 IS '貸方取引先コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD4 IS '貸方科目コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD4 IS '貸方科目枝番コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN4 IS '貸方課税区分４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO SHIWAKE_PATTERN_MASTER( 
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	TEKIYOU_FLG,
	TEKIYOU,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	SHAIN_CD_RENKEI_FLG,
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	KARI_PROJECT_CD,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	KASHI_KAZEI_KBN2,
	KASHI_FUTAN_BUMON_CD3,
	KASHI_TORIHIKISAKI_CD3,
	KASHI_KAMOKU_CD3,
	KASHI_KAMOKU_EDABAN_CD3,
	KASHI_KAZEI_KBN3,
	KASHI_FUTAN_BUMON_CD4,
	KASHI_TORIHIKISAKI_CD4,
	KASHI_KAMOKU_CD4,
	KASHI_KAMOKU_EDABAN_CD4,
	KASHI_KAZEI_KBN4,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
) 
SELECT
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	TEKIYOU_FLG,
	TEKIYOU,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	SHAIN_CD_RENKEI_FLG,
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	KARI_PROJECT_CD,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	KASHI_KAZEI_KBN2,
	KASHI_FUTAN_BUMON_CD3,
	KASHI_TORIHIKISAKI_CD3,
	KASHI_KAMOKU_CD3,
	KASHI_KAMOKU_EDABAN_CD3,
	KASHI_KAZEI_KBN3,
	'',
	'',
	'',
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
  SHIWAKE_PATTERN_MASTER_OLD;

DROP TABLE SHIWAKE_PATTERN_MASTER_OLD;

-- 画面項目制御の修正
CREATE TABLE gamen_koumoku_seigyo_tmp AS SELECT * FROM gamen_koumoku_seigyo;
DELETE FROM gamen_koumoku_seigyo WHERE denpyou_kbn LIKE 'A%';
\copy gamen_koumoku_seigyo FROM '.\files\csv\gamen_koumoku_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE gamen_koumoku_seigyo new SET
  koumoku_name = (SELECT koumoku_name FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
  ,hyouji_flg  = (SELECT hyouji_flg   FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
  ,hissu_flg   = (SELECT hissu_flg    FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
WHERE
  (new.denpyou_kbn,new.koumoku_id) IN (SELECT denpyou_kbn,koumoku_id FROM gamen_koumoku_seigyo_tmp);
DROP TABLE gamen_koumoku_seigyo_tmp;

-- 交通費精算の修正
ALTER TABLE KOUTSUUHISEISAN RENAME TO KOUTSUUHISEISAN_OLD;

CREATE TABLE KOUTSUUHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	HOUJIN_CARD_RIYOU_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KOUTSUUHISEISAN IS '交通費精算';
COMMENT ON COLUMN KOUTSUUHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN KOUTSUUHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN KOUTSUUHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KOUTSUUHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN KOUTSUUHISEISAN.HOUJIN_CARD_RIYOU_KINGAKU IS '内法人カード利用合計';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO KOUTSUUHISEISAN( 
	DENPYOU_ID,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	HOUJIN_CARD_RIYOU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
	)
	SELECT
	DENPYOU_ID,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	0,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
  KOUTSUUHISEISAN_OLD;

DROP TABLE KOUTSUUHISEISAN_OLD;

-- 交通費明細の修正
ALTER TABLE KOUTSUUHISEISAN_MEISAI RENAME TO KOUTSUUHISEISAN_MEISAI_OLD;

CREATE TABLE KOUTSUUHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KOUTSUUHISEISAN_MEISAI IS '交通費精算明細';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO KOUTSUUHISEISAN_MEISAI( 
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	HOUJIN_CARD_RIYOU_FLG,
	JIDOUNYUURYOKU_FLG,
	TANKA,
	MEISAI_KINGAKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
	)
	SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	'0',
	JIDOUNYUURYOKU_FLG,
	TANKA,
	MEISAI_KINGAKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
  KOUTSUUHISEISAN_MEISAI_OLD;

DROP TABLE KOUTSUUHISEISAN_MEISAI_OLD;

-- 経費立替精算の修正
ALTER TABLE KEIHISEISAN RENAME TO KEIHISEISAN_OLD;

CREATE TABLE KEIHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	DAIRIFLG VARCHAR(1) DEFAULT '0' NOT NULL,
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	HOUJIN_CARD_RIYOU_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KEIHISEISAN IS '経費精算';
COMMENT ON COLUMN KEIHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN KEIHISEISAN.DAIRIFLG IS '代理フラグ';
COMMENT ON COLUMN KEIHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KEIHISEISAN.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN KEIHISEISAN.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN KEIHISEISAN.HOUJIN_CARD_RIYOU_KINGAKU IS '内法人カード利用合計';
COMMENT ON COLUMN KEIHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN KEIHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KEIHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KEIHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KEIHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO KEIHISEISAN( 
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	DAIRIFLG,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	HOUJIN_CARD_RIYOU_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	DAIRIFLG,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	0,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
  KEIHISEISAN_OLD;

DROP TABLE KEIHISEISAN_OLD;

-- 経費精算明細の修正
ALTER TABLE KEIHISEISAN_MEISAI RENAME TO KEIHISEISAN_MEISAI_OLD;

CREATE TABLE KEIHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1),
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KEIHISEISAN_MEISAI IS '経費精算明細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO KEIHISEISAN_MEISAI( 
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	SHIYOUBI,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	HOUJIN_CARD_RIYOU_FLG,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	SHIYOUBI,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	'0',
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
  KEIHISEISAN_MEISAI_OLD;

DROP TABLE KEIHISEISAN_MEISAI_OLD;

-- 旅費精算の修正
ALTER TABLE RYOHISEISAN RENAME TO RYOHISEISAN_OLD;
CREATE TABLE RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	HOUJIN_CARD_RIYOU_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.HOUJIN_CARD_RIYOU_KINGAKU IS '内法人カード利用合計';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO RYOHISEISAN( 
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_ON,
	KARIBARAI_MISHIYOU_FLG,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	HOUJIN_CARD_RIYOU_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
) 
SELECT
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_ON,
	KARIBARAI_MISHIYOU_FLG,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_FROM_HOUR,
	SEISANKIKAN_FROM_MIN,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO_HOUR,
	SEISANKIKAN_TO_MIN,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	0,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
	RYOHISEISAN_OLD;

DROP TABLE RYOHISEISAN_OLD;

-- 旅費精算経費明細の修正
ALTER TABLE RYOHISEISAN_KEIHI_MEISAI RENAME TO RYOHISEISAN_KEIHI_MEISAI_OLD;
CREATE TABLE RYOHISEISAN_KEIHI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1),
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN_KEIHI_MEISAI IS '旅費精算経費明細';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO RYOHISEISAN_KEIHI_MEISAI( 
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	SHIYOUBI,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	HOUJIN_CARD_RIYOU_FLG,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
) 
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	SHIYOUBI,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	'0',
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
	RYOHISEISAN_KEIHI_MEISAI_OLD;

DROP TABLE RYOHISEISAN_KEIHI_MEISAI_OLD;

-- 旅費精算明細の修正
ALTER TABLE RYOHISEISAN_MEISAI RENAME TO RYOHISEISAN_MEISAI_OLD;
CREATE TABLE RYOHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	KYUUJITSU_NISSUU NUMERIC,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU NUMERIC,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN_MEISAI IS '旅費精算明細';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KYUUJITSU_NISSUU IS '休日日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.HOUJIN_CARD_RIYOU_FLG IS '法人カード利用フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO RYOHISEISAN_MEISAI( 
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	KYUUJITSU_NISSUU,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	HOUJIN_CARD_RIYOU_FLG,
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	TANKA,
	MEISAI_KINGAKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
) 
SELECT
	DENPYOU_ID,
	DENPYOU_EDANO,
	KIKAN_FROM,
	KIKAN_TO,
	KYUUJITSU_NISSUU,
	SHUBETSU_CD,
	SHUBETSU1,
	SHUBETSU2,
	KOUTSUU_SHUDAN,
	SHOUHYOU_SHORUI_HISSU_FLG,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG,
	NAIYOU,
	BIKOU,
	OUFUKU_FLG,
	'0',
	JIDOUNYUURYOKU_FLG,
	NISSUU,
	TANKA,
	MEISAI_KINGAKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM
	RYOHISEISAN_MEISAI_OLD;

DROP TABLE RYOHISEISAN_MEISAI_OLD;

-- 画面権限制御の追加
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';


-- CSV作成用一時テーブルの追加
CREATE TABLE TEMP_CSVMAKE
(
	ROW_NUM INT NOT NULL,
	DATA_ROWBINARY BYTEA,
	PRIMARY KEY (ROW_NUM)
) WITHOUT OIDS;
COMMENT ON TABLE TEMP_CSVMAKE IS 'CSV作成用一時テーブル';
COMMENT ON COLUMN TEMP_CSVMAKE.ROW_NUM IS '行番号';
COMMENT ON COLUMN TEMP_CSVMAKE.DATA_ROWBINARY IS '行バイナリデータ';

-- user_info.user_sei、user_info.user_meiのトリム
UPDATE user_info SET user_sei = TRANSLATE(user_sei, ' 　', ''), user_mei = TRANSLATE(user_mei, ' 　', '');

-- shiwake_pattern_setting 入れ替え
CREATE TABLE shiwake_pattern_setting_tmp AS SELECT * FROM shiwake_pattern_setting WHERE 1 = 2;
\copy shiwake_pattern_setting_tmp FROM '.\files\csv\shiwake_pattern_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM shiwake_pattern_setting_tmp WHERE denpyou_kbn='A003' AND (SELECT COUNT(*) FROM shiwake_pattern_setting WHERE denpyou_kbn='A003') = 0;
DELETE FROM shiwake_pattern_setting;
INSERT INTO shiwake_pattern_setting SELECT * FROM shiwake_pattern_setting_tmp;
DROP TABLE shiwake_pattern_setting_tmp;


commit;