SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 設定情報データ変更 ※hyouji_jun900以降はカスタマイズ領域
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 画面権限制御の更新
DELETE from gamen_kengen_seigyo;
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 内部コード ※オプション用レコードはパッチ前になければ削除
CREATE TABLE naibu_cd_setting_tmp AS SELECT * FROM naibu_cd_setting;
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM naibu_cd_setting WHERE naibu_cd='A003' AND (SELECT COUNT(*) FROM naibu_cd_setting_tmp WHERE naibu_cd='A003')=0;
DROP TABLE naibu_cd_setting_tmp;

-- 仕訳パターン設定にUFを追加
\copy shiwake_pattern_setting FROM '.\files\csv\shiwake_pattern_setting_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
-- 仕訳パターン変数設定にUFを追加
\copy shiwake_pattern_var_setting FROM '.\files\csv\shiwake_pattern_var_setting_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 仕訳パターンマスターにUFを追加
ALTER TABLE SHIWAKE_PATTERN_MASTER RENAME TO SHIWAKE_PATTERN_MASTER_OLD;
CREATE TABLE SHIWAKE_PATTERN_MASTER
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	DELETE_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	BUNRUI1 VARCHAR(20) NOT NULL,
	BUNRUI2 VARCHAR(20) NOT NULL,
	BUNRUI3 VARCHAR(20) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_FLG VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(20),
	DEFAULT_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KAKE_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	SHAIN_CD_RENKEI_FLG VARCHAR(1) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_PROJECT_CD VARCHAR NOT NULL,
	KARI_UF1_CD VARCHAR(20) NOT NULL,
	KARI_UF2_CD VARCHAR(20) NOT NULL,
	KARI_UF3_CD VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD1 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD1 VARCHAR NOT NULL,
	KASHI_UF1_CD1 VARCHAR(20) NOT NULL,
	KASHI_UF2_CD1 VARCHAR(20) NOT NULL,
	KASHI_UF3_CD1 VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN1 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD2 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD2 VARCHAR NOT NULL,
	KASHI_UF1_CD2 VARCHAR(20) NOT NULL,
	KASHI_UF2_CD2 VARCHAR(20) NOT NULL,
	KASHI_UF3_CD2 VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN2 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD3 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD3 VARCHAR NOT NULL,
	KASHI_UF1_CD3 VARCHAR(20) NOT NULL,
	KASHI_UF2_CD3 VARCHAR(20) NOT NULL,
	KASHI_UF3_CD3 VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN3 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD4 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD4 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD4 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD4 VARCHAR NOT NULL,
	KASHI_UF1_CD4 VARCHAR(20) NOT NULL,
	KASHI_UF2_CD4 VARCHAR(20) NOT NULL,
	KASHI_UF3_CD4 VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN4 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD5 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD5 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD5 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD5 VARCHAR NOT NULL,
	KASHI_UF1_CD5 VARCHAR(20) NOT NULL,
	KASHI_UF2_CD5 VARCHAR(20) NOT NULL,
	KASHI_UF3_CD5 VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN5 VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, SHIWAKE_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE SHIWAKE_PATTERN_MASTER IS '仕訳パターンマスター';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DELETE_FLG IS '削除フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI1 IS '分類1';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI2 IS '分類2';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI3 IS '分類3';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TEKIYOU_FLG IS '摘要フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TEKIYOU IS '摘要';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DEFAULT_HYOUJI_FLG IS 'デフォルト表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSAIHI_HYOUJI_FLG IS '交際費表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KAKE_FLG IS '掛けフラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHAIN_CD_RENKEI_FLG IS '社員コード連携フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_FUTAN_BUMON_CD IS '借方負担部門コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_CD IS '借方科目コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_TORIHIKISAKI_CD IS '借方取引先コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_PROJECT_CD IS '借方プロジェクトコード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_UF1_CD IS '借方UF1コード';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_UF2_CD IS '借方UF2コード';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_UF3_CD IS '借方UF3コード';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAZEI_KBN IS '借方課税区分（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD1 IS '貸方負担部門コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD1 IS '貸方科目コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD1 IS '貸方科目枝番コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD1 IS '貸方取引先コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF1_CD1 IS '貸方UF1コード１';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF2_CD1 IS '貸方UF2コード１';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF3_CD1 IS '貸方UF3コード１';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN1 IS '貸方課税区分１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD2 IS '貸方負担部門コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD2 IS '貸方取引先コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD2 IS '貸方科目コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD2 IS '貸方科目枝番コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF1_CD2 IS '貸方UF1コード２';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF2_CD2 IS '貸方UF2コード２';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF3_CD2 IS '貸方UF3コード２';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN2 IS '貸方課税区分２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD3 IS '貸方負担部門コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD3 IS '貸方取引先コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD3 IS '貸方科目コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD3 IS '貸方科目枝番コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF1_CD3 IS '貸方UF1コード３';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF2_CD3 IS '貸方UF2コード３';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF3_CD3 IS '貸方UF3コード３';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN3 IS '貸方課税区分３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD4 IS '貸方負担部門コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD4 IS '貸方取引先コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD4 IS '貸方科目コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD4 IS '貸方科目枝番コード４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF1_CD4 IS '貸方UF1コード４';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF2_CD4 IS '貸方UF2コード４';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF3_CD4 IS '貸方UF3コード４';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN4 IS '貸方課税区分４（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD5 IS '貸方負担部門コード５（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD5 IS '貸方取引先コード５（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD5 IS '貸方科目コード５（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD5 IS '貸方科目枝番コード５（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF1_CD5 IS '貸方UF1コード５';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF2_CD5 IS '貸方UF2コード５';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_UF3_CD5 IS '貸方UF3コード５';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN5 IS '貸方課税区分５（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_TIME IS '更新日時';

INSERT INTO  SHIWAKE_PATTERN_MASTER (
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	TEKIYOU_FLG,
	TEKIYOU,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	SHAIN_CD_RENKEI_FLG,
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	KARI_PROJECT_CD,
	KARI_UF1_CD,
	KARI_UF2_CD,
	KARI_UF3_CD,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	KASHI_UF1_CD1,
	KASHI_UF2_CD1,
	KASHI_UF3_CD1,
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	KASHI_UF1_CD2,
	KASHI_UF2_CD2,
	KASHI_UF3_CD2,
	KASHI_KAZEI_KBN2,
	KASHI_FUTAN_BUMON_CD3,
	KASHI_TORIHIKISAKI_CD3,
	KASHI_KAMOKU_CD3,
	KASHI_KAMOKU_EDABAN_CD3,
	KASHI_UF1_CD3,
	KASHI_UF2_CD3,
	KASHI_UF3_CD3,
	KASHI_KAZEI_KBN3,
	KASHI_FUTAN_BUMON_CD4,
	KASHI_TORIHIKISAKI_CD4,
	KASHI_KAMOKU_CD4,
	KASHI_KAMOKU_EDABAN_CD4,
	KASHI_UF1_CD4,
	KASHI_UF2_CD4,
	KASHI_UF3_CD4,
	KASHI_KAZEI_KBN4,
	KASHI_FUTAN_BUMON_CD5,
	KASHI_TORIHIKISAKI_CD5,
	KASHI_KAMOKU_CD5,
	KASHI_KAMOKU_EDABAN_CD5,
	KASHI_UF1_CD5,
	KASHI_UF2_CD5,
	KASHI_UF3_CD5,
	KASHI_KAZEI_KBN5,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME

)
SELECT
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	TEKIYOU_FLG,
	TEKIYOU,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	SHAIN_CD_RENKEI_FLG,
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	KARI_PROJECT_CD,
	'<UF>',
	'<UF>',
	'<UF>',
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	'',
	'',
	'',
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	'',
	'',
	'',
	KASHI_KAZEI_KBN2,
	KASHI_FUTAN_BUMON_CD3,
	KASHI_TORIHIKISAKI_CD3,
	KASHI_KAMOKU_CD3,
	KASHI_KAMOKU_EDABAN_CD3,
	'',
	'',
	'',
	KASHI_KAZEI_KBN3,
	KASHI_FUTAN_BUMON_CD4,
	KASHI_TORIHIKISAKI_CD4,
	KASHI_KAMOKU_CD4,
	KASHI_KAMOKU_EDABAN_CD4,
	'',
	'',
	'',
	KASHI_KAZEI_KBN4,
	KASHI_FUTAN_BUMON_CD5,
	KASHI_TORIHIKISAKI_CD5,
	KASHI_KAMOKU_CD5,
	KASHI_KAMOKU_EDABAN_CD5,
	'',
	'',
	'',
	KASHI_KAZEI_KBN5,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM SHIWAKE_PATTERN_MASTER_OLD;
DROP TABLE SHIWAKE_PATTERN_MASTER_OLD;

commit;