SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 設定情報データ変更 ※hyouji_jun900以降はカスタマイズ領域
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;


-- ユーザー情報(マル秘設定・解除権限の分割)
ALTER TABLE USER_INFO RENAME TO USER_INFO_OLD;
CREATE TABLE USER_INFO
(
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	MAIL_ADDRESS VARCHAR(50) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PASS_KOUSHIN_DATE DATE,
	PASS_FAILURE_COUNT INT DEFAULT 0 NOT NULL,
	PASS_FAILURE_TIME TIMESTAMP,
	TMP_LOCK_FLG VARCHAR(1) NOT NULL,
	TMP_LOCK_TIME TIMESTAMP,
	LOCK_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	LOCK_TIME TIMESTAMP,
	DAIRIKIHYOU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLAG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_SHIKIBETSUYOU_NUM VARCHAR(20) NOT NULL,
	SECURITY_PATTERN VARCHAR(4) NOT NULL,
	SECURITY_WFONLY_FLG VARCHAR(1) NOT NULL,
	SHOUNIN_ROUTE_HENKOU_LEVEL VARCHAR(1) NOT NULL,
	MARUHI_KENGEN_FLG VARCHAR(1) NOT NULL,
	MARUHI_KAIJYO_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE USER_INFO IS 'ユーザー情報';
COMMENT ON COLUMN USER_INFO.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN USER_INFO.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN USER_INFO.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN USER_INFO.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN USER_INFO.MAIL_ADDRESS IS 'メールアドレス';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN USER_INFO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN USER_INFO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN USER_INFO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN USER_INFO.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN USER_INFO.PASS_KOUSHIN_DATE IS 'パスワード変更日';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_COUNT IS 'パスワード誤り回数';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_TIME IS 'パスワード誤り時間';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_FLG IS 'アカウント一時ロックフラグ';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_TIME IS 'アカウント一時ロック時間';
COMMENT ON COLUMN USER_INFO.LOCK_FLG IS 'アカウントロックフラグ';
COMMENT ON COLUMN USER_INFO.LOCK_TIME IS 'アカウントロック時間';
COMMENT ON COLUMN USER_INFO.DAIRIKIHYOU_FLG IS '代理起票可能フラグ';
COMMENT ON COLUMN USER_INFO.HOUJIN_CARD_RIYOU_FLAG IS '法人カード利用';
COMMENT ON COLUMN USER_INFO.HOUJIN_CARD_SHIKIBETSUYOU_NUM IS '法人カード識別用番号';
COMMENT ON COLUMN USER_INFO.SECURITY_PATTERN IS 'セキュリティパターン';
COMMENT ON COLUMN USER_INFO.SECURITY_WFONLY_FLG IS 'セキュリティワークフロー限定フラグ';
COMMENT ON COLUMN USER_INFO.SHOUNIN_ROUTE_HENKOU_LEVEL IS '承認ルート変更権限レベル';
COMMENT ON COLUMN USER_INFO.MARUHI_KENGEN_FLG IS 'マル秘設定権限';
COMMENT ON COLUMN USER_INFO.MARUHI_KAIJYO_FLG IS 'マル秘解除権限';
INSERT INTO USER_INFO(
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME,
	DAIRIKIHYOU_FLG,
	HOUJIN_CARD_RIYOU_FLAG,
	HOUJIN_CARD_SHIKIBETSUYOU_NUM,
	SECURITY_PATTERN,
	SECURITY_WFONLY_FLG ,
	SHOUNIN_ROUTE_HENKOU_LEVEL,
	MARUHI_KENGEN_FLG,
	MARUHI_KAIJYO_FLG
)
SELECT
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME,
	DAIRIKIHYOU_FLG,
	HOUJIN_CARD_RIYOU_FLAG,
	HOUJIN_CARD_SHIKIBETSUYOU_NUM,
	SECURITY_PATTERN,
	SECURITY_WFONLY_FLG ,
	SHOUNIN_ROUTE_HENKOU_LEVEL,
	MARUHI_KENGEN_FLG,
	MARUHI_KENGEN_FLG
FROM USER_INFO_OLD;
DROP TABLE USER_INFO_OLD;

commit;