SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;


-- 設定情報データ変更 ※hyouji_jun900以降はカスタマイズ領域
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 内部コード ※オプション用レコードはパッチ前になければ削除
DROP TABLE IF EXISTS naibu_cd_setting_tmp;
CREATE TABLE naibu_cd_setting_tmp AS SELECT * FROM naibu_cd_setting;
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM naibu_cd_setting WHERE naibu_cd='A003' AND (SELECT COUNT(*) FROM naibu_cd_setting_tmp WHERE naibu_cd='A003')=0;
DROP TABLE naibu_cd_setting_tmp;

-- WF関連追加
ALTER TABLE denpyou ADD COLUMN MARUHI_FLG VARCHAR(1) DEFAULT '0' NOT NULL;
COMMENT ON COLUMN DENPYOU.MARUHI_FLG IS 'マル秘フラグ';

CREATE TABLE SHOUNIN_SHORI_KENGEN
(
	SHOUNIN_SHORI_KENGEN_NO BIGSERIAL NOT NULL,
	SHOUNIN_SHORI_KENGEN_NAME VARCHAR(6) NOT NULL,
	KIHON_MODEL_CD VARCHAR(1) NOT NULL,
	SHOUNIN_HISSU_FLG VARCHAR(1) NOT NULL,
	SHOUNIN_KEN_FLG VARCHAR(1) NOT NULL,
	HENKOU_FLG VARCHAR(1) NOT NULL,
	SETSUMEI VARCHAR(100) NOT NULL,
	SHOUNIN_MONGON VARCHAR(6) NOT NULL,
	HANREI_HYOUJI_CD VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (SHOUNIN_SHORI_KENGEN_NO)
) WITHOUT OIDS;
COMMENT ON TABLE SHOUNIN_SHORI_KENGEN IS '承認処理権限';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.SHOUNIN_SHORI_KENGEN_NO IS '承認処理権限番号';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.SHOUNIN_SHORI_KENGEN_NAME IS '承認処理権限名';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.KIHON_MODEL_CD IS '基本モデルコード';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.SHOUNIN_HISSU_FLG IS '承認必須フラグ';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.SHOUNIN_KEN_FLG IS '承認権フラグ';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.HENKOU_FLG IS '変更フラグ';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.SETSUMEI IS '説明';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.SHOUNIN_MONGON IS '承認文言';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.HANREI_HYOUJI_CD IS '凡例表示コード';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHOUNIN_SHORI_KENGEN.KOUSHIN_TIME IS '更新日時';
\copy shounin_shori_kengen FROM '.\files\csv\shounin_shori_kengen.csv' WITH CSV header ENCODING 'SHIFT-JIS';

ALTER TABLE shounin_route RENAME TO shounin_route_tmp;
CREATE TABLE SHOUNIN_ROUTE
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	USER_FULL_NAME VARCHAR(50) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_FULL_NAME VARCHAR NOT NULL,
	BUMON_ROLE_ID VARCHAR(5) NOT NULL,
	BUMON_ROLE_NAME VARCHAR NOT NULL,
	GYOUMU_ROLE_ID VARCHAR(5) NOT NULL,
	GYOUMU_ROLE_NAME VARCHAR NOT NULL,
	GENZAI_FLG VARCHAR(1) NOT NULL,
	SAISHU_SHOUNIN_FLG VARCHAR(1),
	JOUKYOU_EDANO INT,
	SHOUNIN_SHORI_KENGEN_NO BIGINT,
	SHOUNIN_SHORI_KENGEN_NAME VARCHAR(6) NOT NULL,
	KIHON_MODEL_CD VARCHAR(1) NOT NULL,
	SHOUNIN_HISSU_FLG VARCHAR(1) NOT NULL,
	SHOUNIN_KEN_FLG VARCHAR(1) NOT NULL,
	HENKOU_FLG VARCHAR(1) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE SHOUNIN_ROUTE IS '承認ルート';
COMMENT ON COLUMN SHOUNIN_ROUTE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SHOUNIN_ROUTE.EDANO IS '枝番号';
COMMENT ON COLUMN SHOUNIN_ROUTE.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN SHOUNIN_ROUTE.USER_FULL_NAME IS 'ユーザーフル名';
COMMENT ON COLUMN SHOUNIN_ROUTE.BUMON_CD IS '部門コード';
COMMENT ON COLUMN SHOUNIN_ROUTE.BUMON_FULL_NAME IS '部門フル名';
COMMENT ON COLUMN SHOUNIN_ROUTE.BUMON_ROLE_ID IS '部門ロールID';
COMMENT ON COLUMN SHOUNIN_ROUTE.BUMON_ROLE_NAME IS '部門ロール名';
COMMENT ON COLUMN SHOUNIN_ROUTE.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN SHOUNIN_ROUTE.GYOUMU_ROLE_NAME IS '業務ロール名';
COMMENT ON COLUMN SHOUNIN_ROUTE.GENZAI_FLG IS '現在フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE.SAISHU_SHOUNIN_FLG IS '最終承認フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE.JOUKYOU_EDANO IS '承認状況枝番';
COMMENT ON COLUMN SHOUNIN_ROUTE.SHOUNIN_SHORI_KENGEN_NO IS '承認処理権限番号';
COMMENT ON COLUMN SHOUNIN_ROUTE.SHOUNIN_SHORI_KENGEN_NAME IS '承認処理権限名';
COMMENT ON COLUMN SHOUNIN_ROUTE.KIHON_MODEL_CD IS '基本モデルコード';
COMMENT ON COLUMN SHOUNIN_ROUTE.SHOUNIN_HISSU_FLG IS '承認必須フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE.SHOUNIN_KEN_FLG IS '承認権フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE.HENKOU_FLG IS '変更フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHOUNIN_ROUTE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHOUNIN_ROUTE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHOUNIN_ROUTE.KOUSHIN_TIME IS '更新日時';
INSERT INTO shounin_route
SELECT
	DENPYOU_ID,
	EDANO,
	USER_ID,
	USER_FULL_NAME,
	BUMON_CD,
	BUMON_FULL_NAME,
	BUMON_ROLE_ID,
	BUMON_ROLE_NAME,
	GYOUMU_ROLE_ID,
	GYOUMU_ROLE_NAME,
	GENZAI_FLG,
	SAISHU_SHOUNIN_FLG,
	JOUKYOU_EDANO,
	CASE WHEN edano=1 THEN NULL ELSE 0 END,
	CASE WHEN edano=1 THEN '' ELSE '承認者' END,
	CASE WHEN edano=1 THEN '' ELSE '1' END,
	CASE WHEN edano=1 THEN '' ELSE '1' END,
	CASE WHEN edano=1 THEN '' ELSE '1' END,
	CASE WHEN edano=1 THEN '' ELSE '1' END,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM shounin_route_tmp;
DROP TABLE shounin_route_tmp;

CREATE TABLE GOUGI_PATTERN_OYA
(
	GOUGI_PATTERN_NO BIGSERIAL NOT NULL,
	GOUGI_NAME VARCHAR(20) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (GOUGI_PATTERN_NO)
) WITHOUT OIDS;
COMMENT ON TABLE GOUGI_PATTERN_OYA IS '合議パターン親';
COMMENT ON COLUMN GOUGI_PATTERN_OYA.GOUGI_PATTERN_NO IS '合議パターン番号';
COMMENT ON COLUMN GOUGI_PATTERN_OYA.GOUGI_NAME IS '合議名';
COMMENT ON COLUMN GOUGI_PATTERN_OYA.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN GOUGI_PATTERN_OYA.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN GOUGI_PATTERN_OYA.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN GOUGI_PATTERN_OYA.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN GOUGI_PATTERN_OYA.KOUSHIN_TIME IS '更新日時';

CREATE TABLE GOUGI_PATTERN_KO
(
	GOUGI_PATTERN_NO BIGINT NOT NULL,
	EDANO INT NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_ROLE_ID VARCHAR(5) NOT NULL,
	SHOUNIN_SHORI_KENGEN_NO BIGSERIAL NOT NULL,
	SHOUNIN_NINZUU_CD VARCHAR(1) NOT NULL,
	SHOUNIN_NINZUU_HIRITSU INT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (GOUGI_PATTERN_NO, EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE GOUGI_PATTERN_KO IS '合議パターン子';
COMMENT ON COLUMN GOUGI_PATTERN_KO.GOUGI_PATTERN_NO IS '合議パターン番号';
COMMENT ON COLUMN GOUGI_PATTERN_KO.EDANO IS '枝番号';
COMMENT ON COLUMN GOUGI_PATTERN_KO.BUMON_CD IS '部門コード';
COMMENT ON COLUMN GOUGI_PATTERN_KO.BUMON_ROLE_ID IS '部門ロールID';
COMMENT ON COLUMN GOUGI_PATTERN_KO.SHOUNIN_SHORI_KENGEN_NO IS '承認処理権限番号';
COMMENT ON COLUMN GOUGI_PATTERN_KO.SHOUNIN_NINZUU_CD IS '承認人数コード';
COMMENT ON COLUMN GOUGI_PATTERN_KO.SHOUNIN_NINZUU_HIRITSU IS '承認人数比率';
COMMENT ON COLUMN GOUGI_PATTERN_KO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN GOUGI_PATTERN_KO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN GOUGI_PATTERN_KO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN GOUGI_PATTERN_KO.KOUSHIN_TIME IS '更新日時';

CREATE TABLE SHOUNIN_ROUTE_GOUGI_OYA
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	EDANO INT NOT NULL,
	GOUGI_EDANO INT NOT NULL,
	GOUGI_PATTERN_NO BIGINT NOT NULL,
	GOUGI_NAME VARCHAR(20) NOT NULL,
	SYORI_CD VARCHAR(1) NOT NULL,
	PRIMARY KEY (DENPYOU_ID, EDANO, GOUGI_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE SHOUNIN_ROUTE_GOUGI_OYA IS '承認ルート合議親';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_OYA.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_OYA.EDANO IS '枝番号';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_OYA.GOUGI_EDANO IS '合議枝番号';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_OYA.GOUGI_PATTERN_NO IS '合議パターン番号';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_OYA.GOUGI_NAME IS '合議名';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_OYA.SYORI_CD IS '処理コード';

CREATE TABLE SHOUNIN_ROUTE_GOUGI_KO
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	EDANO INT NOT NULL,
	GOUGI_EDANO INT NOT NULL,
	GOUGI_EDAEDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	USER_FULL_NAME VARCHAR(50) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_FULL_NAME VARCHAR NOT NULL,
	BUMON_ROLE_ID VARCHAR(5) NOT NULL,
	BUMON_ROLE_NAME VARCHAR NOT NULL,
	GOUGI_GENZAI_FLG VARCHAR(1) NOT NULL,
	SHOUNIN_SHORI_KENGEN_NO BIGINT NOT NULL,
	SHOUNIN_SHORI_KENGEN_NAME VARCHAR(6) NOT NULL,
	KIHON_MODEL_CD VARCHAR(1) NOT NULL,
	SHOUNIN_HISSU_FLG VARCHAR(1) NOT NULL,
	SHOUNIN_KEN_FLG VARCHAR(1) NOT NULL,
	HENKOU_FLG VARCHAR(1) NOT NULL,
	SHOUNIN_NINZUU_CD VARCHAR(1) NOT NULL,
	SHOUNIN_NINZUU_HIRITSU INT,
	SYORI_CD VARCHAR(1) NOT NULL,
	GOUGINAI_GROUP INT NOT NULL,
	JOUKYOU_EDANO INT,
	PRIMARY KEY (DENPYOU_ID, EDANO, GOUGI_EDANO, GOUGI_EDAEDANO, USER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE SHOUNIN_ROUTE_GOUGI_KO IS '承認ルート合議子';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.EDANO IS '枝番号';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.GOUGI_EDANO IS '合議枝番号';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.GOUGI_EDAEDANO IS '合議枝々番号';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.USER_FULL_NAME IS 'ユーザーフル名';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.BUMON_CD IS '部門コード';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.BUMON_FULL_NAME IS '部門フル名';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.BUMON_ROLE_ID IS '部門ロールID';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.BUMON_ROLE_NAME IS '部門ロール名';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.GOUGI_GENZAI_FLG IS '合議現在フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.SHOUNIN_SHORI_KENGEN_NO IS '承認処理権限番号';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.SHOUNIN_SHORI_KENGEN_NAME IS '承認処理権限名';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.KIHON_MODEL_CD IS '基本モデルコード';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.SHOUNIN_HISSU_FLG IS '承認必須フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.SHOUNIN_KEN_FLG IS '承認権フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.HENKOU_FLG IS '変更フラグ';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.SHOUNIN_NINZUU_CD IS '承認人数コード';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.SHOUNIN_NINZUU_HIRITSU IS '承認人数比率';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.SYORI_CD IS '処理コード';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.GOUGINAI_GROUP IS '合議内グループ';
COMMENT ON COLUMN SHOUNIN_ROUTE_GOUGI_KO.JOUKYOU_EDANO IS '承認状況枝番';

-- WF関連変更
ALTER TABLE bumon_suishou_route_ko RENAME TO bumon_suishou_route_ko_tmp;
CREATE TABLE BUMON_SUISHOU_ROUTE_KO
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	EDANO INT NOT NULL,
	EDAEDANO INT NOT NULL,
	BUMON_ROLE_ID VARCHAR(5) NOT NULL,
	SHOUNIN_SHORI_KENGEN_NO BIGINT,
	GOUGI_PATTERN_NO BIGINT,
	GOUGI_EDANO INT,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, BUMON_CD, EDANO, EDAEDANO)
) WITHOUT OIDS;
COMMENT ON TABLE BUMON_SUISHOU_ROUTE_KO IS '部門推奨ルート子';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.BUMON_CD IS '部門コード';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.EDANO IS '枝番号';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.EDAEDANO IS '枝枝番号';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.BUMON_ROLE_ID IS '部門ロールID';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.SHOUNIN_SHORI_KENGEN_NO IS '承認処理権限番号';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.GOUGI_PATTERN_NO IS '合議パターン番号';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.GOUGI_EDANO IS '合議枝番';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN BUMON_SUISHOU_ROUTE_KO.KOUSHIN_TIME IS '更新日時';
INSERT INTO bumon_suishou_route_ko
SELECT
	DENPYOU_KBN,
	BUMON_CD,
	EDANO,
	EDAEDANO,
	BUMON_ROLE_ID,
	0,
	null,
	null,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM bumon_suishou_route_ko_tmp;
DROP TABLE bumon_suishou_route_ko_tmp;

-- 承認状況への追加
ALTER TABLE shounin_joukyou RENAME TO shounin_joukyou_tmp;
CREATE TABLE SHOUNIN_JOUKYOU
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	USER_FULL_NAME VARCHAR(50) NOT NULL,
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_FULL_NAME VARCHAR NOT NULL,
	BUMON_ROLE_ID VARCHAR(5) NOT NULL,
	BUMON_ROLE_NAME VARCHAR NOT NULL,
	GYOUMU_ROLE_ID VARCHAR(5) NOT NULL,
	GYOUMU_ROLE_NAME VARCHAR NOT NULL,
	JOUKYOU_CD VARCHAR(1) NOT NULL,
	JOUKYOU VARCHAR NOT NULL,
	COMMENT VARCHAR NOT NULL,
	SHOUNIN_ROUTE_EDANO INT,
	SHOUNIN_ROUTE_GOUGI_EDANO INT,
	SHOUNIN_ROUTE_GOUGI_EDAEDANO INT,
	SHOUNIN_SHORI_KENGEN_NO BIGINT,
	SHOUNIN_SHORI_KENGEN_NAME VARCHAR(6) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE SHOUNIN_JOUKYOU IS '承認状況';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.EDANO IS '枝番号';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.USER_FULL_NAME IS 'ユーザーフル名';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.BUMON_CD IS '部門コード';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.BUMON_FULL_NAME IS '部門フル名';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.BUMON_ROLE_ID IS '部門ロールID';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.BUMON_ROLE_NAME IS '部門ロール名';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.GYOUMU_ROLE_NAME IS '業務ロール名';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.JOUKYOU_CD IS '状況コード';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.JOUKYOU IS '状況';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.COMMENT IS 'コメント';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.SHOUNIN_ROUTE_EDANO IS '承認ルート枝番号';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.SHOUNIN_ROUTE_GOUGI_EDANO IS '承認ルート合議枝番号';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.SHOUNIN_ROUTE_GOUGI_EDAEDANO IS '承認ルート合議枝々番号';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.SHOUNIN_SHORI_KENGEN_NO IS '承認処理権限番号';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.SHOUNIN_SHORI_KENGEN_NAME IS '承認処理権限名';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHOUNIN_JOUKYOU.KOUSHIN_TIME IS '更新日時';
INSERT INTO shounin_joukyou
SELECT
	DENPYOU_ID,
	EDANO,
	USER_ID,
	USER_FULL_NAME,
	BUMON_CD,
	BUMON_FULL_NAME,
	BUMON_ROLE_ID,
	BUMON_ROLE_NAME,
	GYOUMU_ROLE_ID,
	GYOUMU_ROLE_NAME,
	'',   --JOUKYOU_CD,
	JOUKYOU,
	COMMENT,
	null, --SHOUNIN_ROUTE_EDANO,
	null, --SHOUNIN_ROUTE_GOUGI_EDANO,
	null, --SHOUNIN_ROUTE_GOUGI_EDAEDANO,
	null, --SHOUNIN_SHORI_KENGEN_NO,
	'',   --SHOUNIN_SHORI_KENGEN_NAME,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM shounin_joukyou_tmp;
DROP TABLE shounin_joukyou_tmp;
UPDATE shounin_joukyou s SET joukyou_cd=
	(SELECT CASE
		WHEN joukyou='申請'   THEN '1'
		WHEN joukyou='取戻し' THEN '2'
		WHEN joukyou='取下げ' THEN '3'
		WHEN joukyou='承認'   THEN '4'
		WHEN joukyou='否認'   THEN '5'
		WHEN joukyou='差戻し' THEN '6'
		ELSE ''
	END
	FROM shounin_joukyou tmp WHERE (tmp.denpyou_id,tmp.edano)=(s.denpyou_id,s.edano));

-- 画面権限制御の追加
DELETE from gamen_kengen_seigyo;
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 簡易届項目定義変更
ALTER TABLE kani_todoke_koumoku RENAME TO kani_todoke_koumoku_tmp;
CREATE TABLE KANI_TODOKE_KOUMOKU
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT NOT NULL,
	AREA_KBN VARCHAR NOT NULL,
	ITEM_NAME VARCHAR NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	BUHIN_TYPE VARCHAR NOT NULL,
	DEFAULT_VALUE1 VARCHAR NOT NULL,
	DEFAULT_VALUE2 VARCHAR NOT NULL,
	YOSAN_SHIKKOU_KOUMOKU_ID VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, VERSION, AREA_KBN, ITEM_NAME)
) WITHOUT OIDS;
COMMENT ON TABLE KANI_TODOKE_KOUMOKU IS '簡易届項目定義';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.VERSION IS 'バージョン';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.AREA_KBN IS 'エリア区分';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.ITEM_NAME IS '項目名';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.BUHIN_TYPE IS '部品タイプ';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.DEFAULT_VALUE1 IS 'デフォルト値１';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.DEFAULT_VALUE2 IS 'デフォルト値２';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.YOSAN_SHIKKOU_KOUMOKU_ID IS '予算執行項目ID';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KANI_TODOKE_KOUMOKU.KOUSHIN_TIME IS '更新日時';
INSERT INTO kani_todoke_koumoku
SELECT
	DENPYOU_KBN,
	VERSION,
	AREA_KBN,
	ITEM_NAME,
	HYOUJI_JUN,
	BUHIN_TYPE,
	DEFAULT_VALUE1,
	DEFAULT_VALUE2,
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM kani_todoke_koumoku_tmp;
DROP TABLE kani_todoke_koumoku_tmp;

-- 伝票種別一覧変更
ALTER TABLE denpyou_shubetsu_ichiran RENAME TO denpyou_shubetsu_ichiran_tmp;
CREATE TABLE DENPYOU_SHUBETSU_ICHIRAN
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT DEFAULT 0 NOT NULL,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	HYOUJI_JUN INT NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	NAIYOU VARCHAR(160) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	KANREN_SENTAKU_FLG VARCHAR(1) NOT NULL,
	KANREN_HYOUJI_FLG VARCHAR(1) NOT NULL,
	DENPYOU_PRINT_FLG VARCHAR(1) NOT NULL,
	KIANBANGOU_UNYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YOSAN_SHIKKOU_TAISHOU VARCHAR(1) DEFAULT 'X' NOT NULL,
	ROUTE_HANTEI_KINGAKU VARCHAR(1) DEFAULT '0' NOT NULL,
	SHOUNIN_JYOUKYOU_PRINT_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_SHUBETSU_ICHIRAN IS '伝票種別一覧';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_SHUBETSU IS '伝票種別（帳票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（帳票・仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.NAIYOU IS '内容（伝票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_SENTAKU_FLG IS '関連伝票選択フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_HYOUJI_FLG IS '関連伝票入力欄表示フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_FLG IS '申請時帳票出力フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KIANBANGOU_UNYOU_FLG IS '起案番号運用フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YOSAN_SHIKKOU_TAISHOU IS '予算執行対象';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.ROUTE_HANTEI_KINGAKU IS 'ルート判定金額';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.SHOUNIN_JYOUKYOU_PRINT_FLG IS '承認状況欄印刷フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO denpyou_shubetsu_ichiran
SELECT
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU,
	DENPYOU_PRINT_SHUBETSU,
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	DENPYOU_PRINT_FLG,
	'0',
	'X',
	'0',
	'0',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM denpyou_shubetsu_ichiran_tmp;
DROP TABLE denpyou_shubetsu_ichiran_tmp;

CREATE TABLE KANI_TODOKE_SUMMARY
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	RINGI_KINGAKU DECIMAL(15),
	SHISHUTSU_KINGAKU_GOUKEI DECIMAL(15),
	SHUUNYUU_KINGAKU_GOUKEI DECIMAL(15),
	KENMEI VARCHAR NOT NULL,
	NAIYOU VARCHAR NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KANI_TODOKE_SUMMARY IS '簡易届サマリ';
COMMENT ON COLUMN KANI_TODOKE_SUMMARY.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KANI_TODOKE_SUMMARY.RINGI_KINGAKU IS '稟議金額';
COMMENT ON COLUMN KANI_TODOKE_SUMMARY.SHISHUTSU_KINGAKU_GOUKEI IS '支出金額合計';
COMMENT ON COLUMN KANI_TODOKE_SUMMARY.SHUUNYUU_KINGAKU_GOUKEI IS '収入金額合計';
COMMENT ON COLUMN KANI_TODOKE_SUMMARY.KENMEI IS '件名';
COMMENT ON COLUMN KANI_TODOKE_SUMMARY.NAIYOU IS '内容';
INSERT INTO KANI_TODOKE_SUMMARY
SELECT
	denpyou_id,
	null,
	null,
	null,
	'',
	''
FROM KANI_TODOKE
GROUP BY denpyou_id;

-- 起案関係
CREATE TABLE DENPYOU_KIAN_HIMOZUKE
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	BUMON_CD VARCHAR(8),
	NENDO VARCHAR(4),
	RYAKUGOU VARCHAR(7),
	KIAN_BANGOU_FROM SMALLINT,
	KIAN_BANGOU SMALLINT,
	KIAN_SYURYO_FLG VARCHAR(1),
	KIAN_SYURYO_BI DATE,
	KIAN_DENPYOU VARCHAR(19),
	KIAN_DENPYOU_KBN VARCHAR(4),
	JISSHI_NENDO VARCHAR(4),
	JISSHI_KIAN_BANGOU VARCHAR(13),
	SHISHUTSU_NENDO VARCHAR(4),
	SHISHUTSU_KIAN_BANGOU VARCHAR(13),
	RINGI_KINGAKU DECIMAL(15),
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_KIAN_HIMOZUKE IS '伝票起案紐付';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.BUMON_CD IS '部門コード';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.NENDO IS '年度';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.RYAKUGOU IS '略号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_BANGOU_FROM IS '開始起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_BANGOU IS '起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_SYURYO_FLG IS '起案終了フラグ';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_SYURYO_BI IS '起案終了日';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_DENPYOU IS '起案伝票';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.KIAN_DENPYOU_KBN IS '起案伝票区分';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.JISSHI_NENDO IS '実施年度';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.JISSHI_KIAN_BANGOU IS '実施起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.SHISHUTSU_NENDO IS '支出年度';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.SHISHUTSU_KIAN_BANGOU IS '支出起案番号';
COMMENT ON COLUMN DENPYOU_KIAN_HIMOZUKE.RINGI_KINGAKU IS '稟議金額';
INSERT INTO denpyou_kian_himozuke
SELECT
    A.denpyou_id AS denpyou_id
  , null
  , null
  , null
  , null
  , null
  , '0'
  , null
  , null
  , null
  , null
  , null
  , null
  , null
  , null
FROM denpyou AS A
LEFT OUTER JOIN denpyou_kian_himozuke AS B ON B.denpyou_id = A.denpyou_id
WHERE B.denpyou_id IS NULL;
CREATE TABLE KIAN_BANGOU_BO
(
	BUMON_CD VARCHAR(8) NOT NULL,
	NENDO VARCHAR(4) NOT NULL,
	RYAKUGOU VARCHAR(7) NOT NULL,
	KIAN_BANGOU_FROM SMALLINT DEFAULT 1 NOT NULL,
	KIAN_BANGOU_TO SMALLINT DEFAULT 9999 NOT NULL,
	KBN_NAIYOU VARCHAR NOT NULL,
	KIANBANGOU_BO_SENTAKU_HYOUJI_FLG VARCHAR(1) DEFAULT '1' NOT NULL,
	DENPYOU_KENSAKU_HYOUJI_FLG VARCHAR(1) DEFAULT '1' NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	PRIMARY KEY (BUMON_CD, NENDO, RYAKUGOU, KIAN_BANGOU_FROM)
) WITHOUT OIDS;
COMMENT ON TABLE KIAN_BANGOU_BO IS '起案番号簿';
COMMENT ON COLUMN KIAN_BANGOU_BO.BUMON_CD IS '部門コード';
COMMENT ON COLUMN KIAN_BANGOU_BO.NENDO IS '年度';
COMMENT ON COLUMN KIAN_BANGOU_BO.RYAKUGOU IS '略号';
COMMENT ON COLUMN KIAN_BANGOU_BO.KIAN_BANGOU_FROM IS '開始起案番号';
COMMENT ON COLUMN KIAN_BANGOU_BO.KIAN_BANGOU_TO IS '終了起案番号';
COMMENT ON COLUMN KIAN_BANGOU_BO.KBN_NAIYOU IS '区分内容';
COMMENT ON COLUMN KIAN_BANGOU_BO.KIANBANGOU_BO_SENTAKU_HYOUJI_FLG IS '起案番号簿選択表示フラグ';
COMMENT ON COLUMN KIAN_BANGOU_BO.DENPYOU_KENSAKU_HYOUJI_FLG IS '伝票検索表示フラグ';
COMMENT ON COLUMN KIAN_BANGOU_BO.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN KIAN_BANGOU_BO.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN KIAN_BANGOU_BO.HYOUJI_JUN IS '表示順';
CREATE TABLE KIAN_BANGOU_SAIBAN
(
	BUMON_CD VARCHAR(8) NOT NULL,
	NENDO VARCHAR(4) NOT NULL,
	RYAKUGOU VARCHAR(7) NOT NULL,
	KIAN_BANGOU_FROM SMALLINT NOT NULL,
	KIAN_BANGOU_LAST SMALLINT NOT NULL,
	PRIMARY KEY (BUMON_CD, NENDO, RYAKUGOU, KIAN_BANGOU_FROM)
) WITHOUT OIDS;
COMMENT ON TABLE KIAN_BANGOU_SAIBAN IS '起案番号採番';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.BUMON_CD IS '部門コード';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.NENDO IS '年度';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.RYAKUGOU IS '略号';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.KIAN_BANGOU_FROM IS '開始起案番号';
COMMENT ON COLUMN KIAN_BANGOU_SAIBAN.KIAN_BANGOU_LAST IS '最終起案番号';

-- 予算・起案金額チェック関連テーブルの新規作成
CREATE TABLE YOSAN_KIANKINGAKU_CHECK
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	SYUUKEI_BUMON_CD VARCHAR(8) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	SYUUKEI_BUMON_NAME VARCHAR(20) NOT NULL,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	EDABAN_NAME VARCHAR(20) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KIJUN_KINGAKU DECIMAL(15),
	JISSEKIGAKU DECIMAL(15),
	SHINSEI_KINGAKU DECIMAL(15),
	PRIMARY KEY (DENPYOU_ID, SYUUKEI_BUMON_CD, KAMOKU_GAIBU_CD, KAMOKU_EDABAN_CD, FUTAN_BUMON_CD)
) WITHOUT OIDS;

CREATE TABLE YOSAN_KIANKINGAKU_CHECK_COMMENT
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	COMMENT VARCHAR(220) NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE YOSAN_KIANKINGAKU_CHECK IS '予算・起案金額チェック';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.SYUUKEI_BUMON_CD IS '集計部門コード';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.KAMOKU_EDABAN_CD IS '科目枝番コード';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.SYUUKEI_BUMON_NAME IS '集計部門名';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.EDABAN_NAME IS '枝番名';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.KIJUN_KINGAKU IS '基準金額';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.JISSEKIGAKU IS '実績額';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK.SHINSEI_KINGAKU IS '申請金額';
COMMENT ON TABLE YOSAN_KIANKINGAKU_CHECK_COMMENT IS '予算・起案金額チェックコメント';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK_COMMENT.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN YOSAN_KIANKINGAKU_CHECK_COMMENT.COMMENT IS 'コメント';


-- 計上日締日テーブル新規追加・請求書計上日締日ドロップ
CREATE TABLE keijoubi_shimebi
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	SHIMEBI DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, SHIMEBI)
) WITHOUT OIDS;
COMMENT ON TABLE KEIJOUBI_SHIMEBI IS '計上日締日';
COMMENT ON COLUMN KEIJOUBI_SHIMEBI.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN KEIJOUBI_SHIMEBI.SHIMEBI IS '締日';
COMMENT ON COLUMN KEIJOUBI_SHIMEBI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIJOUBI_SHIMEBI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIJOUBI_SHIMEBI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIJOUBI_SHIMEBI.KOUSHIN_TIME IS '更新日時';
INSERT INTO keijoubi_shimebi
SELECT
	'A003',
	SHIMEBI,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM seikyuusho_keijoubi_shimebi;
DROP TABLE seikyuusho_keijoubi_shimebi;


-- 所属部門
ALTER TABLE shozoku_bumon RENAME TO shozoku_bumon_tmp;
CREATE TABLE SHOZOKU_BUMON
(
	BUMON_CD VARCHAR(8) NOT NULL,
	BUMON_NAME VARCHAR(20) NOT NULL,
	OYA_BUMON_CD VARCHAR(8) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	SECURITY_PATTERN VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (BUMON_CD)
) WITHOUT OIDS;
COMMENT ON TABLE SHOZOKU_BUMON IS '所属部門';
COMMENT ON COLUMN SHOZOKU_BUMON.BUMON_CD IS '部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON.BUMON_NAME IS '部門名';
COMMENT ON COLUMN SHOZOKU_BUMON.OYA_BUMON_CD IS '親所属部門コード';
COMMENT ON COLUMN SHOZOKU_BUMON.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHOZOKU_BUMON.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHOZOKU_BUMON.SECURITY_PATTERN IS 'セキュリティパターン';
COMMENT ON COLUMN SHOZOKU_BUMON.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHOZOKU_BUMON.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHOZOKU_BUMON.KOUSHIN_TIME IS '更新日時';
INSERT INTO shozoku_bumon
SELECT
	BUMON_CD,
	BUMON_NAME,
	OYA_BUMON_CD,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM shozoku_bumon_tmp;
DROP TABLE shozoku_bumon_tmp;


-- ユーザー
ALTER TABLE USER_INFO RENAME TO USER_INFO_OLD;
CREATE TABLE USER_INFO
(
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	MAIL_ADDRESS VARCHAR(50) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PASS_KOUSHIN_DATE DATE,
	PASS_FAILURE_COUNT INT DEFAULT 0 NOT NULL,
	PASS_FAILURE_TIME TIMESTAMP,
	TMP_LOCK_FLG VARCHAR(1) NOT NULL,
	TMP_LOCK_TIME TIMESTAMP,
	LOCK_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	LOCK_TIME TIMESTAMP,
	DAIRIKIHYOU_FLG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_RIYOU_FLAG VARCHAR(1) NOT NULL,
	HOUJIN_CARD_SHIKIBETSUYOU_NUM VARCHAR(20) NOT NULL,
	SECURITY_PATTERN VARCHAR(4) NOT NULL,
	SECURITY_WFONLY_FLG VARCHAR(1) NOT NULL,
	SHOUNIN_ROUTE_HENKOU_LEVEL VARCHAR(1) NOT NULL,
	MARUHI_KENGEN_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE USER_INFO IS 'ユーザー情報';
COMMENT ON COLUMN USER_INFO.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN USER_INFO.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN USER_INFO.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN USER_INFO.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN USER_INFO.MAIL_ADDRESS IS 'メールアドレス';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN USER_INFO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN USER_INFO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN USER_INFO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN USER_INFO.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN USER_INFO.PASS_KOUSHIN_DATE IS 'パスワード変更日';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_COUNT IS 'パスワード誤り回数';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_TIME IS 'パスワード誤り時間';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_FLG IS 'アカウント一時ロックフラグ';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_TIME IS 'アカウント一時ロック時間';
COMMENT ON COLUMN USER_INFO.LOCK_FLG IS 'アカウントロックフラグ';
COMMENT ON COLUMN USER_INFO.LOCK_TIME IS 'アカウントロック時間';
COMMENT ON COLUMN USER_INFO.DAIRIKIHYOU_FLG IS '代理起票可能フラグ';
COMMENT ON COLUMN USER_INFO.HOUJIN_CARD_RIYOU_FLAG IS '法人カード利用';
COMMENT ON COLUMN USER_INFO.HOUJIN_CARD_SHIKIBETSUYOU_NUM IS '法人カード識別用番号';
COMMENT ON COLUMN USER_INFO.SECURITY_PATTERN IS 'セキュリティパターン';
COMMENT ON COLUMN USER_INFO.SECURITY_WFONLY_FLG IS 'セキュリティワークフロー限定フラグ';
COMMENT ON COLUMN USER_INFO.SHOUNIN_ROUTE_HENKOU_LEVEL IS '承認ルート変更権限レベル';
COMMENT ON COLUMN USER_INFO.MARUHI_KENGEN_FLG IS 'マル秘取り扱い可能権限';
INSERT 
INTO USER_INFO
SELECT
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME,
	DAIRIKIHYOU_FLG,
	HOUJIN_CARD_RIYOU_FLAG,
	HOUJIN_CARD_SHIKIBETSUYOU_NUM,
	SECURITY_PATTERN,
	SECURITY_WFONLY_FLG,
	'4',
	'0'
FROM
  USER_INFO_OLD;
DROP table USER_INFO_OLD;


-- メール通知 合議部署通知用設定の追加(元々メール通知設定を行っていたユーザーについてのみ合議通知用をOFFで登録)
INSERT INTO mail_tsuuchi
SELECT
  tmp.user_id,
  'RYG',
  '0'
FROM 
  (SELECT DISTINCT user_id FROM mail_tsuuchi) tmp;


-- 負担部門科目残高
ALTER TABLE BUMON_KAMOKU_ZANDAKA RENAME TO BUMON_KAMOKU_ZANDAKA_OLD;
CREATE TABLE BUMON_KAMOKU_ZANDAKA
(
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KESSANKI_BANGOU SMALLINT NOT NULL,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	CHOUHYOU_SHATURYOKU_NO SMALLINT,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	KAMOKU_NAME_SEISHIKI VARCHAR(40) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT,
	ZANDAKA_KARI00 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI00 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI01 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI01 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI02 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI02 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI03 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI03 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI03_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI03_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI04 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI04 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI05 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI05 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI06 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI06 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI06_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI06_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI07 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI07 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI08 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI08 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI09 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI09 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI09_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI09_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI10 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI10 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI11 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI11 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI12 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI12 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI12_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI12_SHU DECIMAL(19,0) NOT NULL,
	PRIMARY KEY (FUTAN_BUMON_CD, KAMOKU_GAIBU_CD, KESSANKI_BANGOU)
) WITHOUT OIDS;

COMMENT ON TABLE BUMON_KAMOKU_ZANDAKA IS '負担部門科目残高';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.CHOUHYOU_SHATURYOKU_NO IS '帳票出力順番号';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.KAMOKU_NAME_SEISHIKI IS '科目名（正式）';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI00 IS '期首残高(借方)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI00 IS '期首残高(貸方)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI01 IS '1ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI01 IS '1ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI02 IS '2ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI02 IS '2ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI03 IS '3ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI03 IS '3ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI03_SHU IS '3ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI03_SHU IS '3ｹ月目修正(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI04 IS '4ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI04 IS '4ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI05 IS '5ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI05 IS '5ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI06 IS '6ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI06 IS '6ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI06_SHU IS '6ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI06_SHU IS '6ｹ月目修正(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI07 IS '7ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI07 IS '7ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI08 IS '8ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI08 IS '8ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI09 IS '9ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI09 IS '9ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI09_SHU IS '9ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI09_SHU IS '9ｹ月目修正(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI10 IS '10ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI10 IS '10ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI11 IS '11ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI11 IS '11ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI12 IS '12ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI12 IS '12ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KARI12_SHU IS '12ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_ZANDAKA.ZANDAKA_KASHI12_SHU IS '12ｹ月目修正(貸)';

INSERT 
INTO BUMON_KAMOKU_ZANDAKA
SELECT
	FUTAN_BUMON_CD,
	KAMOKU_GAIBU_CD,
	KESSANKI_BANGOU,
	KAMOKU_NAIBU_CD,
	FUTAN_BUMON_NAME,
	CHOUHYOU_SHATURYOKU_NO,
	KAMOKU_NAME_RYAKUSHIKI,
	KAMOKU_NAME_SEISHIKI,
	TAISHAKU_ZOKUSEI,
	KISHU_ZANDAKA,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0
FROM
  BUMON_KAMOKU_ZANDAKA_OLD;
DROP table BUMON_KAMOKU_ZANDAKA_OLD;


-- 負担部門科目予算
CREATE TABLE BUMON_KAMOKU_YOSAN
(
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KESSANKI_BANGOU SMALLINT NOT NULL,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	CHOUHYOU_SHATURYOKU_NO SMALLINT,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	KAMOKU_NAME_SEISHIKI VARCHAR(40) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT,
	YOSAN_01 DECIMAL(19,0) NOT NULL,
	YOSAN_02 DECIMAL(19,0) NOT NULL,
	YOSAN_03 DECIMAL(19,0) NOT NULL,
	YOSAN_03_SHU DECIMAL(19,0) NOT NULL,
	YOSAN_04 DECIMAL(19,0) NOT NULL,
	YOSAN_05 DECIMAL(19,0) NOT NULL,
	YOSAN_06 DECIMAL(19,0) NOT NULL,
	YOSAN_06_SHU DECIMAL(19,0) NOT NULL,
	YOSAN_07 DECIMAL(19,0) NOT NULL,
	YOSAN_08 DECIMAL(19,0) NOT NULL,
	YOSAN_09 DECIMAL(19,0) NOT NULL,
	YOSAN_09_SHU DECIMAL(19,0) NOT NULL,
	YOSAN_10 DECIMAL(19,0) NOT NULL,
	YOSAN_11 DECIMAL(19,0) NOT NULL,
	YOSAN_12 DECIMAL(19,0) NOT NULL,
	YOSAN_12_SHU DECIMAL(19,0) NOT NULL,
	PRIMARY KEY (FUTAN_BUMON_CD, KAMOKU_GAIBU_CD, KESSANKI_BANGOU)
) WITHOUT OIDS;

COMMENT ON TABLE BUMON_KAMOKU_YOSAN IS '負担部門科目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.CHOUHYOU_SHATURYOKU_NO IS '帳票出力順番号';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.KAMOKU_NAME_SEISHIKI IS '科目名（正式）';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_01 IS '1ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_02 IS '2ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_03 IS '3ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_03_SHU IS '3ｹ月目修正予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_04 IS '4ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_05 IS '5ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_06 IS '6ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_06_SHU IS '6ｹ月目修正予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_07 IS '7ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_08 IS '8ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_09 IS '9ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_09_SHU IS '9ｹ月目修正予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_10 IS '10ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_11 IS '11ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_12 IS '12ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_YOSAN.YOSAN_12_SHU IS '12ｹ月目修正予算';


-- 負担部門科目枝番残高

CREATE TABLE BUMON_KAMOKU_EDABAN_ZANDAKA
(
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KESSANKI_BANGOU SMALLINT NOT NULL,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	EDABAN_CODE VARCHAR(12) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	CHOUHYOU_SHATURYOKU_NO SMALLINT,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	KAMOKU_NAME_SEISHIKI VARCHAR(40) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT,
	ZANDAKA_KARI00 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI00 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI01 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI01 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI02 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI02 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI03 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI03 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI03_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI03_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI04 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI04 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI05 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI05 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI06 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI06 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI06_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI06_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI07 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI07 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI08 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI08 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI09 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI09 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI09_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI09_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI10 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI10 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI11 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI11 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI12 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI12 DECIMAL(19,0) NOT NULL,
	ZANDAKA_KARI12_SHU DECIMAL(19,0) NOT NULL,
	ZANDAKA_KASHI12_SHU DECIMAL(19,0) NOT NULL,
	PRIMARY KEY (FUTAN_BUMON_CD, KAMOKU_GAIBU_CD, KESSANKI_BANGOU, EDABAN_CODE)
) WITHOUT OIDS;
COMMENT ON TABLE BUMON_KAMOKU_EDABAN_ZANDAKA IS '負担部門科目枝番残高';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.EDABAN_CODE IS '枝番コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.CHOUHYOU_SHATURYOKU_NO IS '帳票出力順番号';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.KAMOKU_NAME_SEISHIKI IS '科目名（正式）';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI00 IS '期首残高(借方)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI00 IS '期首残高(貸方)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI01 IS '1ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI01 IS '1ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI02 IS '2ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI02 IS '2ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI03 IS '3ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI03 IS '3ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI03_SHU IS '3ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI03_SHU IS '3ｹ月目修正(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI04 IS '4ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI04 IS '4ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI05 IS '5ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI05 IS '5ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI06 IS '6ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI06 IS '6ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI06_SHU IS '6ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI06_SHU IS '6ｹ月目修正(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI07 IS '7ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI07 IS '7ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI08 IS '8ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI08 IS '8ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI09 IS '9ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI09 IS '9ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI09_SHU IS '9ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI09_SHU IS '9ｹ月目修正(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI10 IS '10ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI10 IS '10ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI11 IS '11ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI11 IS '11ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI12 IS '12ｹ月目(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI12 IS '12ｹ月目(貸)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KARI12_SHU IS '12ｹ月目修正(借)';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_ZANDAKA.ZANDAKA_KASHI12_SHU IS '12ｹ月目修正(貸)';


-- 負担部門科目枝番予算
CREATE TABLE BUMON_KAMOKU_EDABAN_YOSAN
(
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KESSANKI_BANGOU SMALLINT NOT NULL,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	EDABAN_CODE VARCHAR(12) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	CHOUHYOU_SHATURYOKU_NO SMALLINT,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	KAMOKU_NAME_SEISHIKI VARCHAR(40) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT,
	YOSAN_01 DECIMAL(19,0) NOT NULL,
	YOSAN_02 DECIMAL(19,0) NOT NULL,
	YOSAN_03 DECIMAL(19,0) NOT NULL,
	YOSAN_03_SHU DECIMAL(19,0) NOT NULL,
	YOSAN_04 DECIMAL(19,0) NOT NULL,
	YOSAN_05 DECIMAL(19,0) NOT NULL,
	YOSAN_06 DECIMAL(19,0) NOT NULL,
	YOSAN_06_SHU DECIMAL(19,0) NOT NULL,
	YOSAN_07 DECIMAL(19,0) NOT NULL,
	YOSAN_08 DECIMAL(19,0) NOT NULL,
	YOSAN_09 DECIMAL(19,0) NOT NULL,
	YOSAN_09_SHU DECIMAL(19,0) NOT NULL,
	YOSAN_10 DECIMAL(19,0) NOT NULL,
	YOSAN_11 DECIMAL(19,0) NOT NULL,
	YOSAN_12 DECIMAL(19,0) NOT NULL,
	YOSAN_12_SHU DECIMAL(19,0) NOT NULL,
	PRIMARY KEY (FUTAN_BUMON_CD, KAMOKU_GAIBU_CD, KESSANKI_BANGOU, EDABAN_CODE)
) WITHOUT OIDS;
COMMENT ON TABLE BUMON_KAMOKU_EDABAN_YOSAN IS '負担部門科目枝番予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.EDABAN_CODE IS '枝番コード';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.CHOUHYOU_SHATURYOKU_NO IS '帳票出力順番号';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.KAMOKU_NAME_SEISHIKI IS '科目名（正式）';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_01 IS '1ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_02 IS '2ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_03 IS '3ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_03_SHU IS '3ｹ月目修正予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_04 IS '4ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_05 IS '5ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_06 IS '6ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_06_SHU IS '6ｹ月目修正予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_07 IS '7ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_08 IS '8ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_09 IS '9ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_09_SHU IS '9ｹ月目修正予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_10 IS '10ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_11 IS '11ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_12 IS '12ｹ月目予算';
COMMENT ON COLUMN BUMON_KAMOKU_EDABAN_YOSAN.YOSAN_12_SHU IS '12ｹ月目修正予算';


-- 集計部門マスター
CREATE TABLE SYUUKEI_BUMON
(
	SYUUKEI_BUMON_CD VARCHAR(8) NOT NULL,
	SYUUKEI_BUMON_NAME VARCHAR(20) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	SHAUKEI_BUMON_FLG SMALLINT NOT NULL,
	PRIMARY KEY (SYUUKEI_BUMON_CD)
) WITHOUT OIDS;
COMMENT ON TABLE SYUUKEI_BUMON IS '集計部門マスター';
COMMENT ON COLUMN SYUUKEI_BUMON.SYUUKEI_BUMON_CD IS '集計部門コード';
COMMENT ON COLUMN SYUUKEI_BUMON.SYUUKEI_BUMON_NAME IS '集計部門名';
COMMENT ON COLUMN SYUUKEI_BUMON.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN SYUUKEI_BUMON.SHAUKEI_BUMON_FLG IS '集計部門フラグ';


-- （期別）財務仕訳
ALTER TABLE KI_SHIWAKE RENAME TO KI_SHIWAKE_OLD;
CREATE TABLE KI_SHIWAKE
(
	KESN SMALLINT NOT NULL,
	DKEI SMALLINT NOT NULL,
	DSEQ INT NOT NULL,
	SSEQ INT NOT NULL,
	DYMD DATE NOT NULL,
	DCNO VARCHAR(8) NOT NULL,
	VALU DECIMAL(15) NOT NULL,
	RKMK VARCHAR(15) NOT NULL,
	REDA VARCHAR(12) NOT NULL,
	RBMN VARCHAR(8) NOT NULL,
	RTKY VARCHAR(60) NOT NULL,
	RTOR VARCHAR(12) NOT NULL,
	SKMK VARCHAR(15) NOT NULL,
	SEDA VARCHAR(12) NOT NULL,
	SBMN VARCHAR(8) NOT NULL,
	STKY VARCHAR(60) NOT NULL,
	STOR VARCHAR(12) NOT NULL,
	FWAY SMALLINT NOT NULL,
	PRIMARY KEY (KESN, DKEI, DSEQ, SSEQ)
) WITHOUT OIDS;
COMMENT ON TABLE KI_SHIWAKE IS '（期別）財務仕訳';
COMMENT ON COLUMN KI_SHIWAKE.KESN IS '内部決算期';
COMMENT ON COLUMN KI_SHIWAKE.DKEI IS '経過月';
COMMENT ON COLUMN KI_SHIWAKE.DSEQ IS '伝票SEQ';
COMMENT ON COLUMN KI_SHIWAKE.SSEQ IS '仕訳SEQ';
COMMENT ON COLUMN KI_SHIWAKE.DYMD IS '（オープン２１）伝票日付';
COMMENT ON COLUMN KI_SHIWAKE.DCNO IS '（オープン２１）伝票番号';
COMMENT ON COLUMN KI_SHIWAKE.VALU IS '（オープン２１）金額';
COMMENT ON COLUMN KI_SHIWAKE.RKMK IS '（オープン２１）借方　科目内部コード';
COMMENT ON COLUMN KI_SHIWAKE.REDA IS '（オープン２１）借方　枝番コード';
COMMENT ON COLUMN KI_SHIWAKE.RBMN IS '（オープン２１）借方　部門コード';
COMMENT ON COLUMN KI_SHIWAKE.RTKY IS '（オープン２１）借方　摘要';
COMMENT ON COLUMN KI_SHIWAKE.RTOR IS '（オープン２１）借方　取引先コード';
COMMENT ON COLUMN KI_SHIWAKE.SKMK IS '（オープン２１）貸方　科目内部コード';
COMMENT ON COLUMN KI_SHIWAKE.SEDA IS '（オープン２１）貸方　枝番コード';
COMMENT ON COLUMN KI_SHIWAKE.SBMN IS '（オープン２１）貸方　部門コード';
COMMENT ON COLUMN KI_SHIWAKE.STKY IS '（オープン２１）貸方　摘要';
COMMENT ON COLUMN KI_SHIWAKE.STOR IS '（オープン２１）貸方　取引先コード';
COMMENT ON COLUMN KI_SHIWAKE.FWAY IS '入力手段';

INSERT 
INTO KI_SHIWAKE
SELECT
	KESN,
	DKEI,
	DSEQ,
	SSEQ,
	DYMD,
	DCNO,
	VALU,
	RKMK,
	'',
	RBMN,
	RTKY,
	RTOR,
	SKMK,
	'',
	SBMN,
	STKY,
	STOR,
	FWAY
FROM
  KI_SHIWAKE_OLD;
DROP table KI_SHIWAKE_OLD;


-- （期別）科目枝番
CREATE TABLE KI_KAMOKU_EDABAN
(
	KESN SMALLINT NOT NULL,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	EDABAN_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (KESN, KAMOKU_NAIBU_CD, KAMOKU_EDABAN_CD)
) WITHOUT OIDS;
COMMENT ON TABLE KI_KAMOKU_EDABAN IS '（期別）科目枝番';
COMMENT ON COLUMN KI_KAMOKU_EDABAN.KESN IS '内部決算期';
COMMENT ON COLUMN KI_KAMOKU_EDABAN.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN KI_KAMOKU_EDABAN.KAMOKU_EDABAN_CD IS '科目枝番コード';
COMMENT ON COLUMN KI_KAMOKU_EDABAN.EDABAN_NAME IS '枝番名';


-- （期別）部門
ALTER TABLE KI_BUMON RENAME TO KI_BUMON_OLD;
CREATE TABLE KI_BUMON
(
	KESN SMALLINT NOT NULL,
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	OYA_SYUUKEI_BUMON_CD VARCHAR(8) NOT NULL,
	PRIMARY KEY (KESN, FUTAN_BUMON_CD)
) WITHOUT OIDS;
COMMENT ON TABLE KI_BUMON IS '（期別）部門';
COMMENT ON COLUMN KI_BUMON.KESN IS '内部決算期';
COMMENT ON COLUMN KI_BUMON.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN KI_BUMON.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON COLUMN KI_BUMON.OYA_SYUUKEI_BUMON_CD IS '親集計部門コード';

INSERT 
INTO KI_BUMON
SELECT
	KESN,
	FUTAN_BUMON_CD,
	FUTAN_BUMON_NAME,
	''
FROM
  KI_BUMON_OLD;
DROP table KI_BUMON_OLD;


-- マスター取込一覧・詳細テーブルの更新(SIASのみ)
DELETE FROM MASTER_TORIKOMI_ICHIRAN_SIAS;
\copy MASTER_TORIKOMI_ICHIRAN_SIAS FROM '.\files\csv\master_torikomi_ichiran_sias.csv'       WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM MASTER_TORIKOMI_SHOUSAI_SIAS;
\copy MASTER_TORIKOMI_SHOUSAI_SIAS FROM '.\files\csv\master_torikomi_shousai_sias.csv'       WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM master_torikomi_term_ichiran_sias;
\copy master_torikomi_term_ichiran_sias FROM '.\files\csv\master_torikomi_term_ichiran_sias.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM master_torikomi_term_shousai_sias;
\copy master_torikomi_term_shousai_sias FROM '.\files\csv\master_torikomi_term_shousai_sias.csv' WITH CSV header ENCODING 'SHIFT-JIS';


-- マスター管理版数・マスター管理一覧
\copy MASTER_KANRI_HANSUU          FROM '.\files\csv\master_kanri_hansuu_patch.csv'          WITH CSV header ENCODING 'SHIFT-JIS';
\copy MASTER_KANRI_ICHIRAN          FROM '.\files\csv\master_kanri_ichiran_patch.csv'          WITH CSV header ENCODING 'SHIFT-JIS';


commit;