SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- パスワード有効期間対応ここから
-- setting_info変更
CREATE TABLE setting_info_new AS
	SELECT setting_name,setting_name_wa,setting_val,category,hyouji_jun,editable_flg,hissu_flg,format_regex,description
	FROM SETTING_INFO;

DELETE FROM setting_info_new;

\copy setting_info_new FROM '.\files\csv\setting_info.csv' WITH CSV header ENCODING 'SHIFT-JIS';

CREATE TABLE setting_info_old AS 
	SELECT setting_name,setting_name_wa,setting_val,category,hyouji_jun,editable_flg,hissu_flg,format_regex,description
	FROM SETTING_INFO;

DELETE FROM setting_info;

insert into setting_info (select * from setting_info_new);

UPDATE SETTING_INFO N SET SETTING_VAL = (
	SELECT SETTING_VAL
	FROM SETTING_INFO_OLD O 
	WHERE O.SETTING_NAME = N.SETTING_NAME
) WHERE N.SETTING_NAME IN (
	SELECT SETTING_NAME FROM SETTING_INFO_OLD
);

DROP TABLE SETTING_INFO_OLD;
DROP TABLE setting_info_new;

DELETE FROM gamen_kengen_seigyo;

\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';


-- セキュリティログテーブル作成
CREATE TABLE SECURITY_LOG
(
	SERIAL_NO BIGSERIAL NOT NULL,
	EVENT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	IP VARCHAR(40) NOT NULL,
	IP_XFORWARDED VARCHAR(255),
	USER_ID VARCHAR(30),
	GYOUMU_ROLE_ID VARCHAR(5),
	TARGET VARCHAR(100) NOT NULL,
	TYPE VARCHAR(100) NOT NULL,
	DETAIL VARCHAR(100) NOT NULL,
	PRIMARY KEY (SERIAL_NO)
) WITHOUT OIDS;

COMMENT ON TABLE SECURITY_LOG IS 'セキュリティログ';
COMMENT ON COLUMN SECURITY_LOG.SERIAL_NO IS 'シリアル番号';
COMMENT ON COLUMN SECURITY_LOG.EVENT_TIME IS 'イベント時刻';
COMMENT ON COLUMN SECURITY_LOG.IP IS '接続元IPアドレス';
COMMENT ON COLUMN SECURITY_LOG.IP_XFORWARDED IS 'IPアドレス(X-FORWARDED-FOR)';
COMMENT ON COLUMN SECURITY_LOG.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN SECURITY_LOG.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN SECURITY_LOG.TARGET IS '操作対象';
COMMENT ON COLUMN SECURITY_LOG.TYPE IS 'ログ種別';
COMMENT ON COLUMN SECURITY_LOG.DETAIL IS 'ログ詳細';


-- ユーザーテーブル変更
-- テーブルバックアップ
ALTER TABLE user_info RENAME TO user_info_old;
	
-- テーブル作成
CREATE TABLE USER_INFO
(
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	MAIL_ADDRESS VARCHAR(50) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PASS_KOUSHIN_DATE DATE,
	PASS_FAILURE_COUNT INT DEFAULT 0 NOT NULL,
	PASS_FAILURE_TIME TIMESTAMP,
	TMP_LOCK_FLG VARCHAR(1) NOT NULL,
	TMP_LOCK_TIME TIMESTAMP,
	LOCK_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	LOCK_TIME TIMESTAMP,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;

COMMENT ON TABLE USER_INFO IS 'ユーザー情報';
COMMENT ON COLUMN USER_INFO.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN USER_INFO.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN USER_INFO.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN USER_INFO.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN USER_INFO.MAIL_ADDRESS IS 'メールアドレス';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN USER_INFO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN USER_INFO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN USER_INFO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN USER_INFO.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN USER_INFO.PASS_KOUSHIN_DATE IS 'パスワード変更日';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_COUNT IS 'パスワード誤り回数';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_TIME IS 'パスワード誤り時間';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_FLG IS 'アカウント一時ロックフラグ';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_TIME IS 'アカウント一時ロック時間';
COMMENT ON COLUMN USER_INFO.LOCK_FLG IS 'アカウントロックフラグ';
COMMENT ON COLUMN USER_INFO.LOCK_TIME IS 'アカウントロック時間';

-- データ移行
INSERT INTO user_info (
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME
)
SELECT 
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	current_date,
	0,
	NULL,
	'0',
	NULL,
	'0',
	NULL
FROM user_info_old;

DROP TABLE user_info_old;

-- パスワード有効期間対応ここまで



-- 伝票検索時承認者表示対応ここから
CREATE TABLE LIST_ITEM_CONTROL
(
	KBN VARCHAR(1) NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	GYOUMU_ROLE_ID VARCHAR(5) NOT NULL,
	INDEX INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DISPLAY_FLG VARCHAR(1) DEFAULT '1' NOT NULL,
	PRIMARY KEY (KBN, USER_ID, GYOUMU_ROLE_ID, INDEX)
) WITHOUT OIDS;

COMMENT ON TABLE LIST_ITEM_CONTROL IS '一覧表示項目制御';
COMMENT ON COLUMN LIST_ITEM_CONTROL.KBN IS '表示項目区分';
COMMENT ON COLUMN LIST_ITEM_CONTROL.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN LIST_ITEM_CONTROL.GYOUMU_ROLE_ID IS '業務ロールID';
COMMENT ON COLUMN LIST_ITEM_CONTROL.INDEX IS '項番';
COMMENT ON COLUMN LIST_ITEM_CONTROL.NAME IS '項目名';
COMMENT ON COLUMN LIST_ITEM_CONTROL.DISPLAY_FLG IS '表示フラグ';

-- 伝票検索時承認者表示対応ここまで


-- PJコード連携&社員コード連携対応ここから
-- プロジェクトマスター追加
CREATE TABLE PROJECT_MASTER
(
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (PROJECT_CD)
) WITHOUT OIDS;

COMMENT ON TABLE PROJECT_MASTER IS 'プロジェクトマスター';
COMMENT ON COLUMN PROJECT_MASTER.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PROJECT_MASTER.PROJECT_NAME IS 'プロジェクト名';

-- 会社情報テーブル変更
ALTER TABLE kaisha_info RENAME TO kaisha_info_old;

CREATE TABLE KAISHA_INFO
(
	KESSANKI_BANGOU SMALLINT NOT NULL,
	UF1_SHIYOU_FLG SMALLINT NOT NULL,
	UF1_NAME VARCHAR NOT NULL,
	UF2_SHIYOU_FLG SMALLINT NOT NULL,
	UF2_NAME VARCHAR NOT NULL,
	UF3_SHIYOU_FLG SMALLINT NOT NULL,
	UF3_NAME VARCHAR NOT NULL,
	PJCD_SHIYOU_FLG SMALLINT NOT NULL
) WITHOUT OIDS;

COMMENT ON TABLE KAISHA_INFO IS '会社情報';
COMMENT ON COLUMN KAISHA_INFO.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN KAISHA_INFO.UF1_SHIYOU_FLG IS 'UF1使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.UF1_NAME IS 'UF1名';
COMMENT ON COLUMN KAISHA_INFO.UF2_SHIYOU_FLG IS 'UF2使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.UF2_NAME IS 'UF2名';
COMMENT ON COLUMN KAISHA_INFO.UF3_SHIYOU_FLG IS 'UF3使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.UF3_NAME IS 'UF3名';
COMMENT ON COLUMN KAISHA_INFO.PJCD_SHIYOU_FLG IS 'プロジェクトコード使用フラグ';

INSERT INTO kaisha_info (
	KESSANKI_BANGOU,
	UF1_SHIYOU_FLG,
	UF1_NAME,
	UF2_SHIYOU_FLG,
	UF2_NAME,
	UF3_SHIYOU_FLG,
	UF3_NAME,
	PJCD_SHIYOU_FLG
)
SELECT 
	KESSANKI_BANGOU,
	UF1_SHIYOU_FLG,
	UF1_NAME,
	UF2_SHIYOU_FLG,
	UF2_NAME,
	UF3_SHIYOU_FLG,
	UF3_NAME,
	0
FROM kaisha_info_old;

DROP TABLE kaisha_info_old;

-- 仕訳パターンマスターテーブル変更
ALTER TABLE shiwake_pattern_master RENAME TO shiwake_pattern_master_old;

CREATE TABLE SHIWAKE_PATTERN_MASTER
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	DELETE_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	BUNRUI1 VARCHAR(20) NOT NULL,
	BUNRUI2 VARCHAR(20) NOT NULL,
	BUNRUI3 VARCHAR(20) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	DEFAULT_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KAKE_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	SHAIN_CD_RENKEI_FLG VARCHAR(1) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_PROJECT_CD VARCHAR NOT NULL,
	KARI_KAZEI_KBN VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD1 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD1 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN1 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD2 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD2 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN2 VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, SHIWAKE_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE SHIWAKE_PATTERN_MASTER IS '仕訳パターンマスター';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DELETE_FLG IS '削除フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI1 IS '分類1';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI2 IS '分類2';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI3 IS '分類3';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DEFAULT_HYOUJI_FLG IS 'デフォルト表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSAIHI_HYOUJI_FLG IS '交際費表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KAKE_FLG IS '掛けフラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHAIN_CD_RENKEI_FLG IS '社員コード連携フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_FUTAN_BUMON_CD IS '借方負担部門コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_CD IS '借方科目コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_TORIHIKISAKI_CD IS '借方取引先コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_PROJECT_CD IS '借方プロジェクトコード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAZEI_KBN IS '借方課税区分（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD1 IS '貸方負担部門コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD1 IS '貸方科目コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD1 IS '貸方科目枝番コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD1 IS '貸方取引先コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN1 IS '貸方課税区分１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD2 IS '貸方負担部門コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD2 IS '貸方取引先コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD2 IS '貸方科目コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD2 IS '貸方科目枝番コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN2 IS '貸方課税区分２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_TIME IS '更新日時';

INSERT INTO shiwake_pattern_master (
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	SHAIN_CD_RENKEI_FLG,
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	KARI_PROJECT_CD,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	KASHI_KAZEI_KBN2,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	'0',
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	'',
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	KASHI_KAZEI_KBN2,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM shiwake_pattern_master_old;

DROP TABLE shiwake_pattern_master_old;

-- 振替テーブル変更
ALTER TABLE furikae RENAME TO furikae_old;

CREATE TABLE FURIKAE
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_DATE DATE NOT NULL,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU DECIMAL(15),
	ZEIRITSU DECIMAL(3) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	BIKOU VARCHAR(40) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	KARI_TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	KASHI_TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_UF1_CD VARCHAR(20) NOT NULL,
	KARI_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_UF2_CD VARCHAR(20) NOT NULL,
	KARI_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_UF3_CD VARCHAR(20) NOT NULL,
	KARI_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KASHI_UF1_CD VARCHAR(20) NOT NULL,
	KASHI_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KASHI_UF2_CD VARCHAR(20) NOT NULL,
	KASHI_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KASHI_UF3_CD VARCHAR(20) NOT NULL,
	KASHI_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_PROJECT_CD VARCHAR(12) NOT NULL,
	KARI_PROJECT_NAME VARCHAR(20) NOT NULL,
	KASHI_PROJECT_CD VARCHAR(12) NOT NULL,
	KASHI_PROJECT_NAME VARCHAR(20) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE FURIKAE IS '振替';
COMMENT ON COLUMN FURIKAE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN FURIKAE.DENPYOU_DATE IS '伝票日付';
COMMENT ON COLUMN FURIKAE.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN FURIKAE.KINGAKU IS '金額';
COMMENT ON COLUMN FURIKAE.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN FURIKAE.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN FURIKAE.ZEIRITSU IS '税率';
COMMENT ON COLUMN FURIKAE.TEKIYOU IS '摘要';
COMMENT ON COLUMN FURIKAE.BIKOU IS '備考（会計伝票）';
COMMENT ON COLUMN FURIKAE.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN FURIKAE.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN FURIKAE.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN FURIKAE.KARI_TORIHIKISAKI_CD IS '借方取引先コード';
COMMENT ON COLUMN FURIKAE.KARI_TORIHIKISAKI_NAME_RYAKUSHIKI IS '借方取引先名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN FURIKAE.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN FURIKAE.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN FURIKAE.KASHI_TORIHIKISAKI_CD IS '貸方取引先コード';
COMMENT ON COLUMN FURIKAE.KASHI_TORIHIKISAKI_NAME_RYAKUSHIKI IS '貸方取引先名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_UF1_CD IS '借方UF1コード';
COMMENT ON COLUMN FURIKAE.KARI_UF1_NAME_RYAKUSHIKI IS '借方UF1名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_UF2_CD IS '借方UF2コード';
COMMENT ON COLUMN FURIKAE.KARI_UF2_NAME_RYAKUSHIKI IS '借方UF2名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_UF3_CD IS '借方UF3コード';
COMMENT ON COLUMN FURIKAE.KARI_UF3_NAME_RYAKUSHIKI IS '借方UF3名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_UF1_CD IS '貸方UF1コード';
COMMENT ON COLUMN FURIKAE.KASHI_UF1_NAME_RYAKUSHIKI IS '貸方UF1名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_UF2_CD IS '貸方UF2コード';
COMMENT ON COLUMN FURIKAE.KASHI_UF2_NAME_RYAKUSHIKI IS '貸方UF2名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_UF3_CD IS '貸方UF3コード';
COMMENT ON COLUMN FURIKAE.KASHI_UF3_NAME_RYAKUSHIKI IS '貸方UF3名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_PROJECT_CD IS '借方プロジェクトコード';
COMMENT ON COLUMN FURIKAE.KARI_PROJECT_NAME IS '借方プロジェクト名';
COMMENT ON COLUMN FURIKAE.KASHI_PROJECT_CD IS '貸方プロジェクトコード';
COMMENT ON COLUMN FURIKAE.KASHI_PROJECT_NAME IS '貸方プロジェクト名';
COMMENT ON COLUMN FURIKAE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN FURIKAE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN FURIKAE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN FURIKAE.KOUSHIN_TIME IS '更新日時';

INSERT INTO furikae (
	DENPYOU_ID,
	DENPYOU_DATE,
	SHOUHYOU_SHORUI_FLG,
	KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	ZEIRITSU,
	TEKIYOU,
	BIKOU,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KARI_TORIHIKISAKI_CD,
	KARI_TORIHIKISAKI_NAME_RYAKUSHIKI,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	KASHI_TORIHIKISAKI_CD,
	KASHI_TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_UF1_CD,
	KARI_UF1_NAME_RYAKUSHIKI,
	KARI_UF2_CD,
	KARI_UF2_NAME_RYAKUSHIKI,
	KARI_UF3_CD,
	KARI_UF3_NAME_RYAKUSHIKI,
	KASHI_UF1_CD,
	KASHI_UF1_NAME_RYAKUSHIKI,
	KASHI_UF2_CD,
	KASHI_UF2_NAME_RYAKUSHIKI,
	KASHI_UF3_CD,
	KASHI_UF3_NAME_RYAKUSHIKI,
	KARI_PROJECT_CD,
	KARI_PROJECT_NAME,
	KASHI_PROJECT_CD,
	KASHI_PROJECT_NAME,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	DENPYOU_DATE,
	SHOUHYOU_SHORUI_FLG,
	KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	ZEIRITSU,
	TEKIYOU,
	BIKOU,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KARI_TORIHIKISAKI_CD,
	KARI_TORIHIKISAKI_NAME_RYAKUSHIKI,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	KASHI_TORIHIKISAKI_CD,
	KASHI_TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_UF1_CD,
	KARI_UF1_NAME_RYAKUSHIKI,
	KARI_UF2_CD,
	KARI_UF2_NAME_RYAKUSHIKI,
	KARI_UF3_CD,
	KARI_UF3_NAME_RYAKUSHIKI,
	KASHI_UF1_CD,
	KASHI_UF1_NAME_RYAKUSHIKI,
	KASHI_UF2_CD,
	KASHI_UF2_NAME_RYAKUSHIKI,
	KASHI_UF3_CD,
	KASHI_UF3_NAME_RYAKUSHIKI,
	'',
	'',
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM furikae_old;

DROP TABLE furikae_old;

-- 付替テーブル変更
ALTER TABLE tsukekae RENAME TO tsukekae_old;

CREATE TABLE TSUKEKAE
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_DATE DATE NOT NULL,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TSUKEKAE_KBN VARCHAR(1) NOT NULL,
	MOTO_KAMOKU_CD VARCHAR(8) NOT NULL,
	MOTO_KAMOKU_NAME VARCHAR(22) NOT NULL,
	MOTO_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	MOTO_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	MOTO_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	MOTO_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	MOTO_TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	MOTO_TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	MOTO_KAZEI_KBN VARCHAR(3) NOT NULL,
	MOTO_UF1_CD VARCHAR(20) NOT NULL,
	MOTO_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	MOTO_UF2_CD VARCHAR(20) NOT NULL,
	MOTO_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	MOTO_UF3_CD VARCHAR(20) NOT NULL,
	MOTO_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	MOTO_PROJECT_CD VARCHAR(12) NOT NULL,
	MOTO_PROJECT_NAME VARCHAR(20) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE TSUKEKAE IS '付替';
COMMENT ON COLUMN TSUKEKAE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN TSUKEKAE.DENPYOU_DATE IS '伝票日付';
COMMENT ON COLUMN TSUKEKAE.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN TSUKEKAE.ZEIRITSU IS '税率';
COMMENT ON COLUMN TSUKEKAE.KINGAKU_GOUKEI IS '金額合計';
COMMENT ON COLUMN TSUKEKAE.HOSOKU IS '補足';
COMMENT ON COLUMN TSUKEKAE.TSUKEKAE_KBN IS '付替区分';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_CD IS '付替元科目コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_NAME IS '付替元科目名';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_EDABAN_CD IS '付替元科目枝番コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_EDABAN_NAME IS '付替元科目枝番名';
COMMENT ON COLUMN TSUKEKAE.MOTO_FUTAN_BUMON_CD IS '付替元負担部門コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_FUTAN_BUMON_NAME IS '付替元負担部門名';
COMMENT ON COLUMN TSUKEKAE.MOTO_TORIHIKISAKI_CD IS '付替元取引先コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_TORIHIKISAKI_NAME_RYAKUSHIKI IS '付替元取引先名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAZEI_KBN IS '付替元課税区分';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF1_CD IS '付替元UF1コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF1_NAME_RYAKUSHIKI IS '付替元UF1名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF2_CD IS '付替元UF2コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF2_NAME_RYAKUSHIKI IS '付替元UF2名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF3_CD IS '付替元UF3コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF3_NAME_RYAKUSHIKI IS '付替元UF3名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_PROJECT_CD IS '付替元プロジェクトコード';
COMMENT ON COLUMN TSUKEKAE.MOTO_PROJECT_NAME IS '付替元プロジェクト名';
COMMENT ON COLUMN TSUKEKAE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN TSUKEKAE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN TSUKEKAE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN TSUKEKAE.KOUSHIN_TIME IS '更新日時';

INSERT INTO tsukekae (
	DENPYOU_ID,
	DENPYOU_DATE,
	SHOUHYOU_SHORUI_FLG,
	ZEIRITSU,
	KINGAKU_GOUKEI,
	HOSOKU,
	TSUKEKAE_KBN,
	MOTO_KAMOKU_CD,
	MOTO_KAMOKU_NAME,
	MOTO_KAMOKU_EDABAN_CD,
	MOTO_KAMOKU_EDABAN_NAME,
	MOTO_FUTAN_BUMON_CD,
	MOTO_FUTAN_BUMON_NAME,
	MOTO_TORIHIKISAKI_CD,
	MOTO_TORIHIKISAKI_NAME_RYAKUSHIKI,
	MOTO_KAZEI_KBN,
	MOTO_UF1_CD,
	MOTO_UF1_NAME_RYAKUSHIKI,
	MOTO_UF2_CD,
	MOTO_UF2_NAME_RYAKUSHIKI,
	MOTO_UF3_CD,
	MOTO_UF3_NAME_RYAKUSHIKI,
	MOTO_PROJECT_CD,
	MOTO_PROJECT_NAME,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	DENPYOU_DATE,
	SHOUHYOU_SHORUI_FLG,
	ZEIRITSU,
	KINGAKU_GOUKEI,
	HOSOKU,
	TSUKEKAE_KBN,
	MOTO_KAMOKU_CD,
	MOTO_KAMOKU_NAME,
	MOTO_KAMOKU_EDABAN_CD,
	MOTO_KAMOKU_EDABAN_NAME,
	MOTO_FUTAN_BUMON_CD,
	MOTO_FUTAN_BUMON_NAME,
	MOTO_TORIHIKISAKI_CD,
	MOTO_TORIHIKISAKI_NAME_RYAKUSHIKI,
	MOTO_KAZEI_KBN,
	MOTO_UF1_CD,
	MOTO_UF1_NAME_RYAKUSHIKI,
	MOTO_UF2_CD,
	MOTO_UF2_NAME_RYAKUSHIKI,
	MOTO_UF3_CD,
	MOTO_UF3_NAME_RYAKUSHIKI,
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM tsukekae_old;

DROP TABLE tsukekae_old;

-- 付替明細テーブル変更
ALTER TABLE tsukekae_meisai RENAME TO tsukekae_meisai_old;

CREATE TABLE TSUKEKAE_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	BIKOU VARCHAR(40) NOT NULL,
	SAKI_KAMOKU_CD VARCHAR(6) NOT NULL,
	SAKI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	SAKI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	SAKI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	SAKI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	SAKI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	SAKI_TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	SAKI_TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	SAKI_KAZEI_KBN VARCHAR(3) NOT NULL,
	SAKI_UF1_CD VARCHAR(20) NOT NULL,
	SAKI_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	SAKI_UF2_CD VARCHAR(20) NOT NULL,
	SAKI_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	SAKI_UF3_CD VARCHAR(20) NOT NULL,
	SAKI_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	SAKI_PROJECT_CD VARCHAR(12) NOT NULL,
	SAKI_PROJECT_NAME VARCHAR(20) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE TSUKEKAE_MEISAI IS '付替明細';
COMMENT ON COLUMN TSUKEKAE_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN TSUKEKAE_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN TSUKEKAE_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN TSUKEKAE_MEISAI.KINGAKU IS '金額';
COMMENT ON COLUMN TSUKEKAE_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN TSUKEKAE_MEISAI.BIKOU IS '備考（会計伝票）';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_KAMOKU_CD IS '付替先科目コード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_KAMOKU_NAME IS '付替先科目名';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_KAMOKU_EDABAN_CD IS '付替先科目枝番コード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_KAMOKU_EDABAN_NAME IS '付替先科目枝番名';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_FUTAN_BUMON_CD IS '付替先負担部門コード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_FUTAN_BUMON_NAME IS '付替先負担部門名';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_TORIHIKISAKI_CD IS '付替先取引先コード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_TORIHIKISAKI_NAME_RYAKUSHIKI IS '付替先取引先名（略式）';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_KAZEI_KBN IS '付替先課税区分';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_UF1_CD IS '付替先UF1コード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_UF1_NAME_RYAKUSHIKI IS '付替先UF1名（略式）';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_UF2_CD IS '付替先UF2コード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_UF2_NAME_RYAKUSHIKI IS '付替先UF2名（略式）';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_UF3_CD IS '付替先UF3コード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_UF3_NAME_RYAKUSHIKI IS '付替先UF3名（略式）';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_PROJECT_CD IS '付替先プロジェクトコード';
COMMENT ON COLUMN TSUKEKAE_MEISAI.SAKI_PROJECT_NAME IS '付替先プロジェクト名';
COMMENT ON COLUMN TSUKEKAE_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN TSUKEKAE_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN TSUKEKAE_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN TSUKEKAE_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT INTO tsukekae_meisai (
	DENPYOU_ID,
	DENPYOU_EDANO,
	TEKIYOU,
	KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	BIKOU,
	SAKI_KAMOKU_CD,
	SAKI_KAMOKU_NAME,
	SAKI_KAMOKU_EDABAN_CD,
	SAKI_KAMOKU_EDABAN_NAME,
	SAKI_FUTAN_BUMON_CD,
	SAKI_FUTAN_BUMON_NAME,
	SAKI_TORIHIKISAKI_CD,
	SAKI_TORIHIKISAKI_NAME_RYAKUSHIKI,
	SAKI_KAZEI_KBN,
	SAKI_UF1_CD,
	SAKI_UF1_NAME_RYAKUSHIKI,
	SAKI_UF2_CD,
	SAKI_UF2_NAME_RYAKUSHIKI,
	SAKI_UF3_CD,
	SAKI_UF3_NAME_RYAKUSHIKI,
	SAKI_PROJECT_CD,
	SAKI_PROJECT_NAME,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	DENPYOU_EDANO,
	TEKIYOU,
	KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	BIKOU,
	SAKI_KAMOKU_CD,
	SAKI_KAMOKU_NAME,
	SAKI_KAMOKU_EDABAN_CD,
	SAKI_KAMOKU_EDABAN_NAME,
	SAKI_FUTAN_BUMON_CD,
	SAKI_FUTAN_BUMON_NAME,
	SAKI_TORIHIKISAKI_CD,
	SAKI_TORIHIKISAKI_NAME_RYAKUSHIKI,
	SAKI_KAZEI_KBN,
	SAKI_UF1_CD,
	SAKI_UF1_NAME_RYAKUSHIKI,
	SAKI_UF2_CD,
	SAKI_UF2_NAME_RYAKUSHIKI,
	SAKI_UF3_CD,
	SAKI_UF3_NAME_RYAKUSHIKI,
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM tsukekae_meisai_old;

DROP TABLE tsukekae_meisai_old;

-- 自動引落明細テーブル変更
ALTER TABLE jidouhikiotoshi_meisai RENAME TO jidouhikiotoshi_meisai_old;

CREATE TABLE JIDOUHIKIOTOSHI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE JIDOUHIKIOTOSHI_MEISAI IS '自動引落明細';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT INTO jidouhikiotoshi_meisai (
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	TEKIYOU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	TEKIYOU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	'',
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM jidouhikiotoshi_meisai_old;

DROP TABLE jidouhikiotoshi_meisai_old;

-- 経費精算明細テーブル変更
ALTER TABLE keihiseisan_meisai RENAME TO keihiseisan_meisai_old;

CREATE TABLE KEIHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE KEIHISEISAN_MEISAI IS '経費精算明細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT INTO keihiseisan_meisai (
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	TEKIYOU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	TEKIYOU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	'',
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM keihiseisan_meisai_old;

DROP TABLE keihiseisan_meisai_old;

-- 旅費精算テーブル変更
ALTER TABLE ryohiseisan RENAME TO ryohiseisan_old;

CREATE TABLE RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT INTO ryohiseisan (
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_TO,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_TO,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	'',
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM ryohiseisan_old;

DROP TABLE ryohiseisan_old;

-- 請求書払い明細
ALTER TABLE seikyuushobarai_meisai RENAME TO seikyuushobarai_meisai_old;

CREATE TABLE SEIKYUUSHOBARAI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE SEIKYUUSHOBARAI_MEISAI IS '請求書払い明細';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT INTO seikyuushobarai_meisai (
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	TEKIYOU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	TEKIYOU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	'',
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM seikyuushobarai_meisai_old;

DROP TABLE seikyuushobarai_meisai_old;

-- 仮払
ALTER TABLE karibarai RENAME TO karibarai_old;

CREATE TABLE KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	SEISAN_YOTEIBI DATE NOT NULL,
	SEISAN_KANRYOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE KARIBARAI IS '仮払';
COMMENT ON COLUMN KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KARIBARAI.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN KARIBARAI.SEISAN_KANRYOUBI IS '精算完了日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN KARIBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_TIME IS '更新日時';

INSERT INTO karibarai (
	DENPYOU_ID,
	SEISAN_YOTEIBI,
	SEISAN_KANRYOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	SEISAN_YOTEIBI,
	SEISAN_KANRYOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM karibarai_old;

DROP TABLE karibarai_old;


-- 旅費仮払
ALTER TABLE ryohi_karibarai RENAME TO ryohi_karibarai_old;

CREATE TABLE RYOHI_KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	SHUPPATSU_KBN VARCHAR(1) NOT NULL,
	KIKAN_TO DATE NOT NULL,
	KICHAKU_KBN VARCHAR(1) NOT NULL,
	SEISAN_YOTEIBI DATE NOT NULL,
	SEISAN_KANRYOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE RYOHI_KARIBARAI IS '旅費仮払';
COMMENT ON COLUMN RYOHI_KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHI_KARIBARAI.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHI_KARIBARAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHUPPATSU_KBN IS '出発区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.KICHAKU_KBN IS '帰着区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISAN_KANRYOUBI IS '精算完了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHI_KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_TIME IS '更新日時';

INSERT INTO ryohi_karibarai (
	DENPYOU_ID,
	MOKUTEKI,
	KIKAN_FROM,
	SHUPPATSU_KBN,
	KIKAN_TO,
	KICHAKU_KBN,
	SEISAN_YOTEIBI,
	SEISAN_KANRYOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	KINGAKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	MOKUTEKI,
	KIKAN_FROM,
	SHUPPATSU_KBN,
	KIKAN_TO,
	KICHAKU_KBN,
	SEISAN_YOTEIBI,
	SEISAN_KANRYOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	KINGAKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM ryohi_karibarai_old;

DROP TABLE ryohi_karibarai_old;

-- 通勤定期
ALTER TABLE tsuukinteiki RENAME TO tsuukinteiki_old;

CREATE TABLE TSUUKINTEIKI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	SHIYOU_KIKAN_KBN VARCHAR(2) NOT NULL,
	SHIYOU_KAISHIBI DATE NOT NULL,
	SHIYOU_SHUURYOUBI DATE NOT NULL,
	JYOUSHA_KUKAN VARCHAR(200) NOT NULL,
	SHIHARAIBI DATE,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	TENYUURYOKU_FLG VARCHAR(1) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE TSUUKINTEIKI IS '通勤定期';
COMMENT ON COLUMN TSUUKINTEIKI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_KIKAN_KBN IS '使用期間区分';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_KAISHIBI IS '使用開始日';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_SHUURYOUBI IS '使用終了日';
COMMENT ON COLUMN TSUUKINTEIKI.JYOUSHA_KUKAN IS '乗車区間';
COMMENT ON COLUMN TSUUKINTEIKI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN TSUUKINTEIKI.TEKIYOU IS '摘要';
COMMENT ON COLUMN TSUUKINTEIKI.ZEIRITSU IS '税率';
COMMENT ON COLUMN TSUUKINTEIKI.KINGAKU IS '金額';
COMMENT ON COLUMN TSUUKINTEIKI.TENYUURYOKU_FLG IS '手入力フラグ';
COMMENT ON COLUMN TSUUKINTEIKI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN TSUUKINTEIKI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN TSUUKINTEIKI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN TSUUKINTEIKI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN TSUUKINTEIKI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN TSUUKINTEIKI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN TSUUKINTEIKI.KOUSHIN_TIME IS '更新日時';


INSERT INTO tsuukinteiki (
	DENPYOU_ID,
	SHIYOU_KIKAN_KBN,
	SHIYOU_KAISHIBI,
	SHIYOU_SHUURYOUBI,
	JYOUSHA_KUKAN,
	SHIHARAIBI,
	TEKIYOU,
	ZEIRITSU,
	KINGAKU,
	TENYUURYOKU_FLG,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	SHIYOU_KIKAN_KBN,
	SHIYOU_KAISHIBI,
	SHIYOU_SHUURYOUBI,
	JYOUSHA_KUKAN,
	SHIHARAIBI,
	TEKIYOU,
	ZEIRITSU,
	KINGAKU,
	TENYUURYOKU_FLG,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM tsuukinteiki_old;

DROP TABLE tsuukinteiki_old;


-- マスター管理版数データ変更
\copy master_kanri_hansuu FROM '.\files\csv\master_kanri_hansuu_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター管理一覧データ変更
\copy master_kanri_ichiran FROM '.\files\csv\master_kanri_ichiran_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター取込一覧データ変更
DELETE FROM master_torikomi_ichiran WHERE master_id = 'bumon_master';
DELETE FROM master_torikomi_ichiran WHERE master_id = 'kaisha_info';

\copy master_torikomi_ichiran FROM '.\files\csv\master_torikomi_ichiran_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター取込詳細データ変更
\copy master_torikomi_shousai FROM '.\files\csv\master_torikomi_shousai_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 仕訳パターン設定データ変更
\copy shiwake_pattern_setting FROM '.\files\csv\shiwake_pattern_setting_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 仕訳パターン変数設定データ変更
\copy shiwake_pattern_var_setting FROM '.\files\csv\shiwake_pattern_var_setting_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 内部コード設定データ変更
DELETE FROM naibu_cd_setting;

\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- PJコード連携&社員コード連携対応ここまで

commit;
