package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.GyoumuRole;

/**
 * 業務ロールに対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class GyoumuRoleAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected GyoumuRole mapToDto(GMap map){
		return map == null ? null : new GyoumuRole(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<GyoumuRole> mapToDto(List<GMap> mapList){
		List<GyoumuRole> dtoList = new ArrayList<GyoumuRole>();
		for (var map : mapList) {
			dtoList.add(new GyoumuRole(map));
		}
		return dtoList;
	}
	
	/**
	 * 業務ロールのレコード有無を判定
	 * @param gyoumuRoleId 業務ロールID
	 * @return true:exist false:not exist
	 */
	public boolean exists(String gyoumuRoleId) {
		return this.find(gyoumuRoleId) == null ? false : true;
	}
	
	/**
	 * 業務ロールから主キー指定でレコードを取得
	 * @param gyoumuRoleId 業務ロールID
	 * @return 業務ロールDTO
	 */
	public GyoumuRole find(String gyoumuRoleId) {
		final String sql = "SELECT * FROM gyoumu_role WHERE gyoumu_role_id = ?";
		return mapToDto(connection.find(sql, gyoumuRoleId));
	}
	
	/**
	 * 業務ロールからレコードを全件取得 ※大量データ取得に注意
	 * @return List<業務ロールDTO>
	 */
	public List<GyoumuRole> load() {
		final String sql = "SELECT * FROM gyoumu_role ORDER BY gyoumu_role_id";
		return mapToDto(connection.load(sql));
	}

	/**
	* 業務ロール登録
	* @param dto 業務ロール
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int insert(
		GyoumuRole dto
		,String koushinUserId
	){
		final String sql =
				"INSERT INTO gyoumu_role "
			+ "VALUES(?, ?, ?, ?, current_timestamp, ?, current_timestamp "
			+ ")";
			return connection.update(sql,
					dto.gyoumuRoleId, dto.gyoumuRoleName, dto.hyoujiJun, koushinUserId, koushinUserId
					);
	}

	/**
	* 業務ロールの非キー全てと共通列を更新
	* 値設定漏れによるデータ消失防止のためDaoで取得したGyoumuRoleの使用を前提
	* @param dto 業務ロール
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int update(
		GyoumuRole dto
		,String koushinUserId
		 ){
		final String sql =
				"UPDATE gyoumu_role "
		    + "SET gyoumu_role_name = ?, hyouji_jun = ?, koushin_user_id = ?, koushin_time = current_timestamp "
	 		+ "WHERE koushin_time = ? AND gyoumu_role_id = ?";
			return connection.update(sql,
				dto.gyoumuRoleName, dto.hyoujiJun, koushinUserId
				,dto.koushinTime, dto.gyoumuRoleId);
    }

	/**
	* 業務ロール登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto 業務ロール
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int upsert(
		GyoumuRole dto
		,String koushinUserId
		 ){
		final String sql =
				"INSERT INTO gyoumu_role "
			+ "VALUES(?, ?, ?, ?, current_timestamp, ?, current_timestamp "
			+ ") ON CONFLICT ON CONSTRAINT gyoumu_role_pkey "
			+ "DO UPDATE SET gyoumu_role_name = ?, hyouji_jun = ?, koushin_user_id = ?, koushin_time = current_timestamp "
			+ "";
			return connection.update(sql,
				dto.gyoumuRoleId, dto.gyoumuRoleName, dto.hyoujiJun, koushinUserId, koushinUserId
				, dto.gyoumuRoleName, dto.hyoujiJun, koushinUserId
				);
    }
	
	/**
	 * 業務ロールから主キー指定でレコードを削除
	 * @param gyoumuRoleId 業務ロールID
	 * @return 削除件数
	 */
	public int delete(String gyoumuRoleId){
		final String sql = "DELETE FROM gyoumu_role WHERE gyoumu_role_id = ?";
		return connection.update(sql, gyoumuRoleId);
	}
}
