package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.Hf4Ichiran;

/**
 * ヘッダフィールド４一覧に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class Hf4IchiranAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected Hf4Ichiran mapToDto(GMap map){
		return map == null ? null : new Hf4Ichiran(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<Hf4Ichiran> mapToDto(List<GMap> mapList){
		List<Hf4Ichiran> dtoList = new ArrayList<Hf4Ichiran>();
		for (var map : mapList) {
			dtoList.add(new Hf4Ichiran(map));
		}
		return dtoList;
	}
	
	/**
	 * ヘッダフィールド４一覧のレコード有無を判定
	 * @param hf4Cd HF4コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String hf4Cd) {
		return this.find(hf4Cd) == null ? false : true;
	}
	
	/**
	 * ヘッダフィールド４一覧から主キー指定でレコードを取得
	 * @param hf4Cd HF4コード
	 * @return ヘッダフィールド４一覧DTO
	 */
	public Hf4Ichiran find(String hf4Cd) {
		final String sql = "SELECT * FROM hf4_ichiran WHERE hf4_cd = ?";
		return mapToDto(connection.find(sql, hf4Cd));
	}
	
	/**
	 * ヘッダフィールド４一覧からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ヘッダフィールド４一覧DTO>
	 */
	public List<Hf4Ichiran> load() {
		final String sql = "SELECT * FROM hf4_ichiran ORDER BY hf4_cd";
		return mapToDto(connection.load(sql));
	}

	/**
	* ヘッダフィールド４一覧登録
	* @param dto ヘッダフィールド４一覧
	* @return 件数
	*/
	public int insert(
		Hf4Ichiran dto
	){
		final String sql =
				"INSERT INTO hf4_ichiran "
			+ "VALUES(?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.hf4Cd, dto.hf4NameRyakushiki, dto.kessankiBangou
					);
	}

	/**
	* ヘッダフィールド４一覧登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ヘッダフィールド４一覧
	* @return 件数
	*/
	public int upsert(
		Hf4Ichiran dto
		 ){
		final String sql =
				"INSERT INTO hf4_ichiran "
			+ "VALUES(?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT hf4_ichiran_pkey "
			+ "DO UPDATE SET hf4_name_ryakushiki = ?, kessanki_bangou = ? "
			+ "";
			return connection.update(sql,
				dto.hf4Cd, dto.hf4NameRyakushiki, dto.kessankiBangou
				, dto.hf4NameRyakushiki, dto.kessankiBangou
				);
    }
	
	/**
	 * ヘッダフィールド４一覧から主キー指定でレコードを削除
	 * @param hf4Cd HF4コード
	 * @return 削除件数
	 */
	public int delete(String hf4Cd){
		final String sql = "DELETE FROM hf4_ichiran WHERE hf4_cd = ?";
		return connection.update(sql, hf4Cd);
	}
}
