package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.Hf5Ichiran;

/**
 * ヘッダフィールド５一覧に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class Hf5IchiranAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected Hf5Ichiran mapToDto(GMap map){
		return map == null ? null : new Hf5Ichiran(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<Hf5Ichiran> mapToDto(List<GMap> mapList){
		List<Hf5Ichiran> dtoList = new ArrayList<Hf5Ichiran>();
		for (var map : mapList) {
			dtoList.add(new Hf5Ichiran(map));
		}
		return dtoList;
	}
	
	/**
	 * ヘッダフィールド５一覧のレコード有無を判定
	 * @param hf5Cd HF5コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String hf5Cd) {
		return this.find(hf5Cd) == null ? false : true;
	}
	
	/**
	 * ヘッダフィールド５一覧から主キー指定でレコードを取得
	 * @param hf5Cd HF5コード
	 * @return ヘッダフィールド５一覧DTO
	 */
	public Hf5Ichiran find(String hf5Cd) {
		final String sql = "SELECT * FROM hf5_ichiran WHERE hf5_cd = ?";
		return mapToDto(connection.find(sql, hf5Cd));
	}
	
	/**
	 * ヘッダフィールド５一覧からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ヘッダフィールド５一覧DTO>
	 */
	public List<Hf5Ichiran> load() {
		final String sql = "SELECT * FROM hf5_ichiran ORDER BY hf5_cd";
		return mapToDto(connection.load(sql));
	}

	/**
	* ヘッダフィールド５一覧登録
	* @param dto ヘッダフィールド５一覧
	* @return 件数
	*/
	public int insert(
		Hf5Ichiran dto
	){
		final String sql =
				"INSERT INTO hf5_ichiran "
			+ "VALUES(?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.hf5Cd, dto.hf5NameRyakushiki, dto.kessankiBangou
					);
	}

	/**
	* ヘッダフィールド５一覧登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ヘッダフィールド５一覧
	* @return 件数
	*/
	public int upsert(
		Hf5Ichiran dto
		 ){
		final String sql =
				"INSERT INTO hf5_ichiran "
			+ "VALUES(?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT hf5_ichiran_pkey "
			+ "DO UPDATE SET hf5_name_ryakushiki = ?, kessanki_bangou = ? "
			+ "";
			return connection.update(sql,
				dto.hf5Cd, dto.hf5NameRyakushiki, dto.kessankiBangou
				, dto.hf5NameRyakushiki, dto.kessankiBangou
				);
    }
	
	/**
	 * ヘッダフィールド５一覧から主キー指定でレコードを削除
	 * @param hf5Cd HF5コード
	 * @return 削除件数
	 */
	public int delete(String hf5Cd){
		final String sql = "DELETE FROM hf5_ichiran WHERE hf5_cd = ?";
		return connection.update(sql, hf5Cd);
	}
}
