package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.HoujinCardImport;

/**
 * 法人カードインポートに対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class HoujinCardImportAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected HoujinCardImport mapToDto(GMap map){
		return map == null ? null : new HoujinCardImport(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<HoujinCardImport> mapToDto(List<GMap> mapList){
		List<HoujinCardImport> dtoList = new ArrayList<HoujinCardImport>();
		for (var map : mapList) {
			dtoList.add(new HoujinCardImport(map));
		}
		return dtoList;
	}
	
	/**
	 * 法人カードインポートのレコード有無を判定
	 * @param userId ユーザーID
	 * @return true:exist false:not exist
	 */
	public boolean exists(String userId) {
		return this.find(userId) == null ? false : true;
	}
	
	/**
	 * 法人カードインポートから主キー指定でレコードを取得
	 * @param userId ユーザーID
	 * @return 法人カードインポートDTO
	 */
	public HoujinCardImport find(String userId) {
		final String sql = "SELECT * FROM houjin_card_import WHERE user_id = ?";
		return mapToDto(connection.find(sql, userId));
	}
	
	/**
	 * 法人カードインポートからレコードを全件取得 ※大量データ取得に注意
	 * @return List<法人カードインポートDTO>
	 */
	public List<HoujinCardImport> load() {
		final String sql = "SELECT * FROM houjin_card_import ORDER BY user_id";
		return mapToDto(connection.load(sql));
	}

	/**
	* 法人カードインポート登録
	* @param dto 法人カードインポート
	* @return 件数
	*/
	public int insert(
		HoujinCardImport dto
	){
		final String sql =
				"INSERT INTO houjin_card_import "
			+ "VALUES(?, ? "
			+ ")";
			return connection.update(sql,
					dto.userId, dto.houjinCardShubetsu
					);
	}

	/**
	* 法人カードインポート登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto 法人カードインポート
	* @return 件数
	*/
	public int upsert(
		HoujinCardImport dto
		 ){
		final String sql =
				"INSERT INTO houjin_card_import "
			+ "VALUES(?, ? "
			+ ") ON CONFLICT ON CONSTRAINT houjin_card_import_pkey "
			+ "DO UPDATE SET houjin_card_shubetsu = ? "
			+ "";
			return connection.update(sql,
				dto.userId, dto.houjinCardShubetsu
				, dto.houjinCardShubetsu
				);
    }
	
	/**
	 * 法人カードインポートから主キー指定でレコードを削除
	 * @param userId ユーザーID
	 * @return 削除件数
	 */
	public int delete(String userId){
		final String sql = "DELETE FROM houjin_card_import WHERE user_id = ?";
		return connection.update(sql, userId);
	}
}
