package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.KaniTodokeListKo;

/**
 * 届出ジェネレータ項目リスト子に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class KaniTodokeListKoAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected KaniTodokeListKo mapToDto(GMap map){
		return map == null ? null : new KaniTodokeListKo(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<KaniTodokeListKo> mapToDto(List<GMap> mapList){
		List<KaniTodokeListKo> dtoList = new ArrayList<KaniTodokeListKo>();
		for (var map : mapList) {
			dtoList.add(new KaniTodokeListKo(map));
		}
		return dtoList;
	}
	
	/**
	 * 届出ジェネレータ項目リスト子のレコード有無を判定
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @param areaKbn エリア区分
	 * @param itemName 項目名
	 * @param hyoujiJun 表示順
	 * @return true:exist false:not exist
	 */
	public boolean exists(String denpyouKbn, int version, String areaKbn, String itemName, int hyoujiJun) {
		return this.find(denpyouKbn, version, areaKbn, itemName, hyoujiJun) == null ? false : true;
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から主キー指定でレコードを取得
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @param areaKbn エリア区分
	 * @param itemName 項目名
	 * @param hyoujiJun 表示順
	 * @return 届出ジェネレータ項目リスト子DTO
	 */
	public KaniTodokeListKo find(String denpyouKbn, int version, String areaKbn, String itemName, int hyoujiJun) {
		final String sql = "SELECT * FROM kani_todoke_list_ko WHERE denpyou_kbn = ? AND version = ? AND area_kbn = ? AND item_name = ? AND hyouji_jun = ?";
		return mapToDto(connection.find(sql, denpyouKbn, version, areaKbn, itemName, hyoujiJun));
	}
	
	/**
	 * 届出ジェネレータ項目リスト子からレコードを全件取得 ※大量データ取得に注意
	 * @return List<届出ジェネレータ項目リスト子DTO>
	 */
	public List<KaniTodokeListKo> load() {
		final String sql = "SELECT * FROM kani_todoke_list_ko ORDER BY denpyou_kbn, version, area_kbn, item_name, hyouji_jun";
		return mapToDto(connection.load(sql));
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを取得
	 * @param denpyouKbn 伝票区分
	 * @return List<届出ジェネレータ項目リスト子>DTO
	 */
	public List<KaniTodokeListKo> load(String denpyouKbn) {
		final String sql = "SELECT * FROM kani_todoke_list_ko WHERE denpyou_kbn = ? "
							+ "ORDER BY denpyou_kbn, version, area_kbn, item_name, hyouji_jun";
		return mapToDto(connection.load(sql, denpyouKbn));
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを取得
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @return List<届出ジェネレータ項目リスト子>DTO
	 */
	public List<KaniTodokeListKo> load(String denpyouKbn, int version) {
		final String sql = "SELECT * FROM kani_todoke_list_ko WHERE denpyou_kbn = ?  AND version = ? "
							+ "ORDER BY denpyou_kbn, version, area_kbn, item_name, hyouji_jun";
		return mapToDto(connection.load(sql, denpyouKbn, version));
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを取得
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @param areaKbn エリア区分
	 * @return List<届出ジェネレータ項目リスト子>DTO
	 */
	public List<KaniTodokeListKo> load(String denpyouKbn, int version, String areaKbn) {
		final String sql = "SELECT * FROM kani_todoke_list_ko WHERE denpyou_kbn = ?  AND version = ?  AND area_kbn = ? "
							+ "ORDER BY denpyou_kbn, version, area_kbn, item_name, hyouji_jun";
		return mapToDto(connection.load(sql, denpyouKbn, version, areaKbn));
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを取得
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @param areaKbn エリア区分
	 * @param itemName 項目名
	 * @return List<届出ジェネレータ項目リスト子>DTO
	 */
	public List<KaniTodokeListKo> load(String denpyouKbn, int version, String areaKbn, String itemName) {
		final String sql = "SELECT * FROM kani_todoke_list_ko WHERE denpyou_kbn = ?  AND version = ?  AND area_kbn = ?  AND item_name = ? "
							+ "ORDER BY denpyou_kbn, version, area_kbn, item_name, hyouji_jun";
		return mapToDto(connection.load(sql, denpyouKbn, version, areaKbn, itemName));
	}

	/**
	* 届出ジェネレータ項目リスト子登録
	* @param dto 届出ジェネレータ項目リスト子
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int insert(
		KaniTodokeListKo dto
		,String koushinUserId
	){
		final String sql =
				"INSERT INTO kani_todoke_list_ko "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, current_timestamp, ?, current_timestamp "
			+ ")";
			return connection.update(sql,
					dto.denpyouKbn, dto.version, dto.areaKbn, dto.itemName, dto.hyoujiJun, dto.text, dto.value, dto.selectItem, koushinUserId, koushinUserId
					);
	}

	/**
	* 届出ジェネレータ項目リスト子の非キー全てと共通列を更新
	* 値設定漏れによるデータ消失防止のためDaoで取得したKaniTodokeListKoの使用を前提
	* @param dto 届出ジェネレータ項目リスト子
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int update(
		KaniTodokeListKo dto
		,String koushinUserId
		 ){
		final String sql =
				"UPDATE kani_todoke_list_ko "
		    + "SET text = ?, value = ?, select_item = ?, koushin_user_id = ?, koushin_time = current_timestamp "
	 		+ "WHERE koushin_time = ? AND denpyou_kbn = ? AND version = ? AND area_kbn = ? AND item_name = ? AND hyouji_jun = ?";
			return connection.update(sql,
				dto.text, dto.value, dto.selectItem, koushinUserId
				,dto.koushinTime, dto.denpyouKbn, dto.version, dto.areaKbn, dto.itemName, dto.hyoujiJun);
    }

	/**
	* 届出ジェネレータ項目リスト子登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto 届出ジェネレータ項目リスト子
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int upsert(
		KaniTodokeListKo dto
		,String koushinUserId
		 ){
		final String sql =
				"INSERT INTO kani_todoke_list_ko "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, current_timestamp, ?, current_timestamp "
			+ ") ON CONFLICT ON CONSTRAINT kani_todoke_list_ko_pkey "
			+ "DO UPDATE SET text = ?, value = ?, select_item = ?, koushin_user_id = ?, koushin_time = current_timestamp "
			+ "";
			return connection.update(sql,
				dto.denpyouKbn, dto.version, dto.areaKbn, dto.itemName, dto.hyoujiJun, dto.text, dto.value, dto.selectItem, koushinUserId, koushinUserId
				, dto.text, dto.value, dto.selectItem, koushinUserId
				);
    }
	
	/**
	 * 届出ジェネレータ項目リスト子から主キー指定でレコードを削除
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @param areaKbn エリア区分
	 * @param itemName 項目名
	 * @param hyoujiJun 表示順
	 * @return 削除件数
	 */
	public int delete(String denpyouKbn, int version, String areaKbn, String itemName, int hyoujiJun){
		final String sql = "DELETE FROM kani_todoke_list_ko WHERE denpyou_kbn = ? AND version = ? AND area_kbn = ? AND item_name = ? AND hyouji_jun = ?";
		return connection.update(sql, denpyouKbn, version, areaKbn, itemName, hyoujiJun);
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを削除
	 * @param denpyouKbn 伝票区分
	 * @return 削除件数
	 */
	public int delete(String denpyouKbn) {
		final String sql = "DELETE FROM kani_todoke_list_ko WHERE denpyou_kbn = ? ";
		return connection.update(sql, denpyouKbn);
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを削除
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @return 削除件数
	 */
	public int delete(String denpyouKbn, int version) {
		final String sql = "DELETE FROM kani_todoke_list_ko WHERE denpyou_kbn = ?  AND version = ? ";
		return connection.update(sql, denpyouKbn, version);
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを削除
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @param areaKbn エリア区分
	 * @return 削除件数
	 */
	public int delete(String denpyouKbn, int version, String areaKbn) {
		final String sql = "DELETE FROM kani_todoke_list_ko WHERE denpyou_kbn = ?  AND version = ?  AND area_kbn = ? ";
		return connection.update(sql, denpyouKbn, version, areaKbn);
	}
	
	/**
	 * 届出ジェネレータ項目リスト子から一部キー指定でレコードを削除
	 * @param denpyouKbn 伝票区分
	 * @param version バージョン
	 * @param areaKbn エリア区分
	 * @param itemName 項目名
	 * @return 削除件数
	 */
	public int delete(String denpyouKbn, int version, String areaKbn, String itemName) {
		final String sql = "DELETE FROM kani_todoke_list_ko WHERE denpyou_kbn = ?  AND version = ?  AND area_kbn = ?  AND item_name = ? ";
		return connection.update(sql, denpyouKbn, version, areaKbn, itemName);
	}
}
