package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.MasterTorikomiTermShousaiSias;

/**
 * マスター取込期間詳細(SIAS)に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class MasterTorikomiTermShousaiSiasAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected MasterTorikomiTermShousaiSias mapToDto(GMap map){
		return map == null ? null : new MasterTorikomiTermShousaiSias(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<MasterTorikomiTermShousaiSias> mapToDto(List<GMap> mapList){
		List<MasterTorikomiTermShousaiSias> dtoList = new ArrayList<MasterTorikomiTermShousaiSias>();
		for (var map : mapList) {
			dtoList.add(new MasterTorikomiTermShousaiSias(map));
		}
		return dtoList;
	}
	
	/**
	 * マスター取込期間詳細(SIAS)のレコード有無を判定
	 * @param masterId マスターID
	 * @param etColumnId eTeamカラムID
	 * @return true:exist false:not exist
	 */
	public boolean exists(String masterId, String etColumnId) {
		return this.find(masterId, etColumnId) == null ? false : true;
	}
	
	/**
	 * マスター取込期間詳細(SIAS)から主キー指定でレコードを取得
	 * @param masterId マスターID
	 * @param etColumnId eTeamカラムID
	 * @return マスター取込期間詳細(SIAS)DTO
	 */
	public MasterTorikomiTermShousaiSias find(String masterId, String etColumnId) {
		final String sql = "SELECT * FROM master_torikomi_term_shousai_sias WHERE master_id = ? AND et_column_id = ?";
		return mapToDto(connection.find(sql, masterId, etColumnId));
	}
	
	/**
	 * マスター取込期間詳細(SIAS)からレコードを全件取得 ※大量データ取得に注意
	 * @return List<マスター取込期間詳細(SIAS)DTO>
	 */
	public List<MasterTorikomiTermShousaiSias> load() {
		final String sql = "SELECT * FROM master_torikomi_term_shousai_sias ORDER BY master_id, et_column_id";
		return mapToDto(connection.load(sql));
	}
	
	/**
	 * マスター取込期間詳細(SIAS)から一部キー指定でレコードを取得
	 * @param masterId マスターID
	 * @return List<マスター取込期間詳細(SIAS)>DTO
	 */
	public List<MasterTorikomiTermShousaiSias> load(String masterId) {
		final String sql = "SELECT * FROM master_torikomi_term_shousai_sias WHERE master_id = ? "
							+ "ORDER BY master_id, et_column_id";
		return mapToDto(connection.load(sql, masterId));
	}

	/**
	* マスター取込期間詳細(SIAS)登録
	* @param dto マスター取込期間詳細(SIAS)
	* @return 件数
	*/
	public int insert(
		MasterTorikomiTermShousaiSias dto
	){
		final String sql =
				"INSERT INTO master_torikomi_term_shousai_sias "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.masterId, dto.etColumnId, dto.etColumnName, dto.etDataType, dto.opColumeId, dto.opColumnName, dto.opDataType, dto.entryOrder, dto.pkFlg
					);
	}

	/**
	* マスター取込期間詳細(SIAS)登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto マスター取込期間詳細(SIAS)
	* @return 件数
	*/
	public int upsert(
		MasterTorikomiTermShousaiSias dto
		 ){
		final String sql =
				"INSERT INTO master_torikomi_term_shousai_sias "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT master_torikomi_term_shousai_sias_pkey "
			+ "DO UPDATE SET et_column_name = ?, et_data_type = ?, op_colume_id = ?, op_column_name = ?, op_data_type = ?, entry_order = ?, pk_flg = ? "
			+ "";
			return connection.update(sql,
				dto.masterId, dto.etColumnId, dto.etColumnName, dto.etDataType, dto.opColumeId, dto.opColumnName, dto.opDataType, dto.entryOrder, dto.pkFlg
				, dto.etColumnName, dto.etDataType, dto.opColumeId, dto.opColumnName, dto.opDataType, dto.entryOrder, dto.pkFlg
				);
    }
	
	/**
	 * マスター取込期間詳細(SIAS)から主キー指定でレコードを削除
	 * @param masterId マスターID
	 * @param etColumnId eTeamカラムID
	 * @return 削除件数
	 */
	public int delete(String masterId, String etColumnId){
		final String sql = "DELETE FROM master_torikomi_term_shousai_sias WHERE master_id = ? AND et_column_id = ?";
		return connection.update(sql, masterId, etColumnId);
	}
	
	/**
	 * マスター取込期間詳細(SIAS)から一部キー指定でレコードを削除
	 * @param masterId マスターID
	 * @return 削除件数
	 */
	public int delete(String masterId) {
		final String sql = "DELETE FROM master_torikomi_term_shousai_sias WHERE master_id = ? ";
		return connection.update(sql, masterId);
	}
}
