package eteam.database.abstractdao;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.ShouninJoukyou;

/**
 * 承認状況に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class ShouninJoukyouAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected ShouninJoukyou mapToDto(GMap map){
		return map == null ? null : new ShouninJoukyou(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<ShouninJoukyou> mapToDto(List<GMap> mapList){
		List<ShouninJoukyou> dtoList = new ArrayList<ShouninJoukyou>();
		for (var map : mapList) {
			dtoList.add(new ShouninJoukyou(map));
		}
		return dtoList;
	}
	
	/**
	 * 承認状況のレコード有無を判定
	 * @param denpyouId 伝票ID
	 * @param edano 枝番号
	 * @return true:exist false:not exist
	 */
	public boolean exists(String denpyouId, int edano) {
		return this.find(denpyouId, edano) == null ? false : true;
	}
	
	/**
	 * 承認状況から主キー指定でレコードを取得
	 * @param denpyouId 伝票ID
	 * @param edano 枝番号
	 * @return 承認状況DTO
	 */
	public ShouninJoukyou find(String denpyouId, int edano) {
		final String sql = "SELECT * FROM shounin_joukyou WHERE denpyou_id = ? AND edano = ?";
		return mapToDto(connection.find(sql, denpyouId, edano));
	}
	
	/**
	 * 承認状況からレコードを全件取得 ※大量データ取得に注意
	 * @return List<承認状況DTO>
	 */
	public List<ShouninJoukyou> load() {
		final String sql = "SELECT * FROM shounin_joukyou ORDER BY denpyou_id, edano";
		return mapToDto(connection.load(sql));
	}
	
	/**
	 * 承認状況から一部キー指定でレコードを取得
	 * @param denpyouId 伝票ID
	 * @return List<承認状況>DTO
	 */
	public List<ShouninJoukyou> load(String denpyouId) {
		final String sql = "SELECT * FROM shounin_joukyou WHERE denpyou_id = ? "
							+ "ORDER BY denpyou_id, edano";
		return mapToDto(connection.load(sql, denpyouId));
	}

	/**
	* 承認状況登録
	* @param dto 承認状況
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int insert(
		ShouninJoukyou dto
		,String koushinUserId
	){
		final String sql =
				"INSERT INTO shounin_joukyou "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, current_timestamp, ?, current_timestamp "
			+ ")";
			return connection.update(sql,
					dto.denpyouId, dto.edano, dto.userId, dto.userFullName, dto.bumonCd, dto.bumonFullName, dto.bumonRoleId, dto.bumonRoleName, dto.gyoumuRoleId, dto.gyoumuRoleName, dto.joukyouCd, dto.joukyou, dto.comment, dto.shouninRouteEdano, dto.shouninRouteGougiEdano, dto.shouninRouteGougiEdaedano, dto.shouninShoriKengenNo, dto.shouninShoriKengenName, koushinUserId, koushinUserId
					);
	}

	/**
	* 承認状況の非キー全てと共通列を更新
	* 値設定漏れによるデータ消失防止のためDaoで取得したShouninJoukyouの使用を前提
	* @param dto 承認状況
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int update(
		ShouninJoukyou dto
		,String koushinUserId
		 ){
		final String sql =
				"UPDATE shounin_joukyou "
		    + "SET user_id = ?, user_full_name = ?, bumon_cd = ?, bumon_full_name = ?, bumon_role_id = ?, bumon_role_name = ?, gyoumu_role_id = ?, gyoumu_role_name = ?, joukyou_cd = ?, joukyou = ?, comment = ?, shounin_route_edano = ?, shounin_route_gougi_edano = ?, shounin_route_gougi_edaedano = ?, shounin_shori_kengen_no = ?, shounin_shori_kengen_name = ?, koushin_user_id = ?, koushin_time = current_timestamp "
	 		+ "WHERE koushin_time = ? AND denpyou_id = ? AND edano = ?";
			return connection.update(sql,
				dto.userId, dto.userFullName, dto.bumonCd, dto.bumonFullName, dto.bumonRoleId, dto.bumonRoleName, dto.gyoumuRoleId, dto.gyoumuRoleName, dto.joukyouCd, dto.joukyou, dto.comment, dto.shouninRouteEdano, dto.shouninRouteGougiEdano, dto.shouninRouteGougiEdaedano, dto.shouninShoriKengenNo, dto.shouninShoriKengenName, koushinUserId
				,dto.koushinTime, dto.denpyouId, dto.edano);
    }

	/**
	* 承認状況登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto 承認状況
	* @param koushinUserId 更新ユーザーID
	* @return 件数
	*/
	public int upsert(
		ShouninJoukyou dto
		,String koushinUserId
		 ){
		final String sql =
				"INSERT INTO shounin_joukyou "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, current_timestamp, ?, current_timestamp "
			+ ") ON CONFLICT ON CONSTRAINT shounin_joukyou_pkey "
			+ "DO UPDATE SET user_id = ?, user_full_name = ?, bumon_cd = ?, bumon_full_name = ?, bumon_role_id = ?, bumon_role_name = ?, gyoumu_role_id = ?, gyoumu_role_name = ?, joukyou_cd = ?, joukyou = ?, comment = ?, shounin_route_edano = ?, shounin_route_gougi_edano = ?, shounin_route_gougi_edaedano = ?, shounin_shori_kengen_no = ?, shounin_shori_kengen_name = ?, koushin_user_id = ?, koushin_time = current_timestamp "
			+ "";
			return connection.update(sql,
				dto.denpyouId, dto.edano, dto.userId, dto.userFullName, dto.bumonCd, dto.bumonFullName, dto.bumonRoleId, dto.bumonRoleName, dto.gyoumuRoleId, dto.gyoumuRoleName, dto.joukyouCd, dto.joukyou, dto.comment, dto.shouninRouteEdano, dto.shouninRouteGougiEdano, dto.shouninRouteGougiEdaedano, dto.shouninShoriKengenNo, dto.shouninShoriKengenName, koushinUserId, koushinUserId
				, dto.userId, dto.userFullName, dto.bumonCd, dto.bumonFullName, dto.bumonRoleId, dto.bumonRoleName, dto.gyoumuRoleId, dto.gyoumuRoleName, dto.joukyouCd, dto.joukyou, dto.comment, dto.shouninRouteEdano, dto.shouninRouteGougiEdano, dto.shouninRouteGougiEdaedano, dto.shouninShoriKengenNo, dto.shouninShoriKengenName, koushinUserId
				);
    }
	
	/**
	 * 承認状況から主キー指定でレコードを削除
	 * @param denpyouId 伝票ID
	 * @param edano 枝番号
	 * @return 削除件数
	 */
	public int delete(String denpyouId, int edano){
		final String sql = "DELETE FROM shounin_joukyou WHERE denpyou_id = ? AND edano = ?";
		return connection.update(sql, denpyouId, edano);
	}
	
	/**
	 * 承認状況から一部キー指定でレコードを削除
	 * @param denpyouId 伝票ID
	 * @return 削除件数
	 */
	public int delete(String denpyouId) {
		final String sql = "DELETE FROM shounin_joukyou WHERE denpyou_id = ? ";
		return connection.update(sql, denpyouId);
	}
	
	/**
	 * 伝票IDをキーに最新の申請日付を取得する。
	 * 
	 * @param denpyouId 伝票ID
	 * @return 最新の申請日付（１レコード）
	 */
	public Timestamp selectShinseiDate(String denpyouId) {
		final String sql = "SELECT koushin_time FROM shounin_joukyou "
						+  " WHERE denpyou_id = ? AND joukyou_cd = '1' "
						+  " ORDER BY koushin_time DESC LIMIT 1; ";
		return connection.find(sql, denpyouId).get("koushin_time");
	}
}
