package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.Uf10Zandaka;

/**
 * ユニバーサルフィールド１０残高に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class Uf10ZandakaAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected Uf10Zandaka mapToDto(GMap map){
		return map == null ? null : new Uf10Zandaka(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<Uf10Zandaka> mapToDto(List<GMap> mapList){
		List<Uf10Zandaka> dtoList = new ArrayList<Uf10Zandaka>();
		for (var map : mapList) {
			dtoList.add(new Uf10Zandaka(map));
		}
		return dtoList;
	}
	
	/**
	 * ユニバーサルフィールド１０残高のレコード有無を判定
	 * @param uf10Cd UF10コード
	 * @param kamokuGaibuCd 科目外部コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String uf10Cd, String kamokuGaibuCd) {
		return this.find(uf10Cd, kamokuGaibuCd) == null ? false : true;
	}
	
	/**
	 * ユニバーサルフィールド１０残高から主キー指定でレコードを取得
	 * @param uf10Cd UF10コード
	 * @param kamokuGaibuCd 科目外部コード
	 * @return ユニバーサルフィールド１０残高DTO
	 */
	public Uf10Zandaka find(String uf10Cd, String kamokuGaibuCd) {
		final String sql = "SELECT * FROM uf10_zandaka WHERE uf10_cd = ? AND kamoku_gaibu_cd = ?";
		return mapToDto(connection.find(sql, uf10Cd, kamokuGaibuCd));
	}
	
	/**
	 * ユニバーサルフィールド１０残高からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ユニバーサルフィールド１０残高DTO>
	 */
	public List<Uf10Zandaka> load() {
		final String sql = "SELECT * FROM uf10_zandaka ORDER BY uf10_cd, kamoku_gaibu_cd";
		return mapToDto(connection.load(sql));
	}
	
	/**
	 * ユニバーサルフィールド１０残高から一部キー指定でレコードを取得
	 * @param uf10Cd UF10コード
	 * @return List<ユニバーサルフィールド１０残高>DTO
	 */
	public List<Uf10Zandaka> load(String uf10Cd) {
		final String sql = "SELECT * FROM uf10_zandaka WHERE uf10_cd = ? "
							+ "ORDER BY uf10_cd, kamoku_gaibu_cd";
		return mapToDto(connection.load(sql, uf10Cd));
	}

	/**
	* ユニバーサルフィールド１０残高登録
	* @param dto ユニバーサルフィールド１０残高
	* @return 件数
	*/
	public int insert(
		Uf10Zandaka dto
	){
		final String sql =
				"INSERT INTO uf10_zandaka "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.uf10Cd, dto.kamokuGaibuCd, dto.kessankiBangou, dto.kamokuNaibuCd, dto.uf10NameRyakushiki, dto.chouhyouShaturyokuNo, dto.kamokuNameRyakushiki, dto.kamokuNameSeishiki, dto.taishakuZokusei, dto.kishuZandaka
					);
	}

	/**
	* ユニバーサルフィールド１０残高登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ユニバーサルフィールド１０残高
	* @return 件数
	*/
	public int upsert(
		Uf10Zandaka dto
		 ){
		final String sql =
				"INSERT INTO uf10_zandaka "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT uf10_zandaka_pkey "
			+ "DO UPDATE SET kessanki_bangou = ?, kamoku_naibu_cd = ?, uf10_name_ryakushiki = ?, chouhyou_shaturyoku_no = ?, kamoku_name_ryakushiki = ?, kamoku_name_seishiki = ?, taishaku_zokusei = ?, kishu_zandaka = ? "
			+ "";
			return connection.update(sql,
				dto.uf10Cd, dto.kamokuGaibuCd, dto.kessankiBangou, dto.kamokuNaibuCd, dto.uf10NameRyakushiki, dto.chouhyouShaturyokuNo, dto.kamokuNameRyakushiki, dto.kamokuNameSeishiki, dto.taishakuZokusei, dto.kishuZandaka
				, dto.kessankiBangou, dto.kamokuNaibuCd, dto.uf10NameRyakushiki, dto.chouhyouShaturyokuNo, dto.kamokuNameRyakushiki, dto.kamokuNameSeishiki, dto.taishakuZokusei, dto.kishuZandaka
				);
    }
	
	/**
	 * ユニバーサルフィールド１０残高から主キー指定でレコードを削除
	 * @param uf10Cd UF10コード
	 * @param kamokuGaibuCd 科目外部コード
	 * @return 削除件数
	 */
	public int delete(String uf10Cd, String kamokuGaibuCd){
		final String sql = "DELETE FROM uf10_zandaka WHERE uf10_cd = ? AND kamoku_gaibu_cd = ?";
		return connection.update(sql, uf10Cd, kamokuGaibuCd);
	}
	
	/**
	 * ユニバーサルフィールド１０残高から一部キー指定でレコードを削除
	 * @param uf10Cd UF10コード
	 * @return 削除件数
	 */
	public int delete(String uf10Cd) {
		final String sql = "DELETE FROM uf10_zandaka WHERE uf10_cd = ? ";
		return connection.update(sql, uf10Cd);
	}
}
