package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.Uf5Ichiran;

/**
 * ユニバーサルフィールド５一覧に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class Uf5IchiranAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected Uf5Ichiran mapToDto(GMap map){
		return map == null ? null : new Uf5Ichiran(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<Uf5Ichiran> mapToDto(List<GMap> mapList){
		List<Uf5Ichiran> dtoList = new ArrayList<Uf5Ichiran>();
		for (var map : mapList) {
			dtoList.add(new Uf5Ichiran(map));
		}
		return dtoList;
	}
	
	/**
	 * ユニバーサルフィールド５一覧のレコード有無を判定
	 * @param uf5Cd UF5コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String uf5Cd) {
		return this.find(uf5Cd) == null ? false : true;
	}
	
	/**
	 * ユニバーサルフィールド５一覧から主キー指定でレコードを取得
	 * @param uf5Cd UF5コード
	 * @return ユニバーサルフィールド５一覧DTO
	 */
	public Uf5Ichiran find(String uf5Cd) {
		final String sql = "SELECT * FROM uf5_ichiran WHERE uf5_cd = ?";
		return mapToDto(connection.find(sql, uf5Cd));
	}
	
	/**
	 * ユニバーサルフィールド５一覧からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ユニバーサルフィールド５一覧DTO>
	 */
	public List<Uf5Ichiran> load() {
		final String sql = "SELECT * FROM uf5_ichiran ORDER BY uf5_cd";
		return mapToDto(connection.load(sql));
	}

	/**
	* ユニバーサルフィールド５一覧登録
	* @param dto ユニバーサルフィールド５一覧
	* @return 件数
	*/
	public int insert(
		Uf5Ichiran dto
	){
		final String sql =
				"INSERT INTO uf5_ichiran "
			+ "VALUES(?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.uf5Cd, dto.uf5NameRyakushiki, dto.kessankiBangou
					);
	}

	/**
	* ユニバーサルフィールド５一覧登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ユニバーサルフィールド５一覧
	* @return 件数
	*/
	public int upsert(
		Uf5Ichiran dto
		 ){
		final String sql =
				"INSERT INTO uf5_ichiran "
			+ "VALUES(?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT uf5_ichiran_pkey "
			+ "DO UPDATE SET uf5_name_ryakushiki = ?, kessanki_bangou = ? "
			+ "";
			return connection.update(sql,
				dto.uf5Cd, dto.uf5NameRyakushiki, dto.kessankiBangou
				, dto.uf5NameRyakushiki, dto.kessankiBangou
				);
    }
	
	/**
	 * ユニバーサルフィールド５一覧から主キー指定でレコードを削除
	 * @param uf5Cd UF5コード
	 * @return 削除件数
	 */
	public int delete(String uf5Cd){
		final String sql = "DELETE FROM uf5_ichiran WHERE uf5_cd = ?";
		return connection.update(sql, uf5Cd);
	}
}
