package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.Uf7Ichiran;

/**
 * ユニバーサルフィールド７一覧に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class Uf7IchiranAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected Uf7Ichiran mapToDto(GMap map){
		return map == null ? null : new Uf7Ichiran(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<Uf7Ichiran> mapToDto(List<GMap> mapList){
		List<Uf7Ichiran> dtoList = new ArrayList<Uf7Ichiran>();
		for (var map : mapList) {
			dtoList.add(new Uf7Ichiran(map));
		}
		return dtoList;
	}
	
	/**
	 * ユニバーサルフィールド７一覧のレコード有無を判定
	 * @param uf7Cd UF7コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String uf7Cd) {
		return this.find(uf7Cd) == null ? false : true;
	}
	
	/**
	 * ユニバーサルフィールド７一覧から主キー指定でレコードを取得
	 * @param uf7Cd UF7コード
	 * @return ユニバーサルフィールド７一覧DTO
	 */
	public Uf7Ichiran find(String uf7Cd) {
		final String sql = "SELECT * FROM uf7_ichiran WHERE uf7_cd = ?";
		return mapToDto(connection.find(sql, uf7Cd));
	}
	
	/**
	 * ユニバーサルフィールド７一覧からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ユニバーサルフィールド７一覧DTO>
	 */
	public List<Uf7Ichiran> load() {
		final String sql = "SELECT * FROM uf7_ichiran ORDER BY uf7_cd";
		return mapToDto(connection.load(sql));
	}

	/**
	* ユニバーサルフィールド７一覧登録
	* @param dto ユニバーサルフィールド７一覧
	* @return 件数
	*/
	public int insert(
		Uf7Ichiran dto
	){
		final String sql =
				"INSERT INTO uf7_ichiran "
			+ "VALUES(?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.uf7Cd, dto.uf7NameRyakushiki, dto.kessankiBangou
					);
	}

	/**
	* ユニバーサルフィールド７一覧登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ユニバーサルフィールド７一覧
	* @return 件数
	*/
	public int upsert(
		Uf7Ichiran dto
		 ){
		final String sql =
				"INSERT INTO uf7_ichiran "
			+ "VALUES(?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT uf7_ichiran_pkey "
			+ "DO UPDATE SET uf7_name_ryakushiki = ?, kessanki_bangou = ? "
			+ "";
			return connection.update(sql,
				dto.uf7Cd, dto.uf7NameRyakushiki, dto.kessankiBangou
				, dto.uf7NameRyakushiki, dto.kessankiBangou
				);
    }
	
	/**
	 * ユニバーサルフィールド７一覧から主キー指定でレコードを削除
	 * @param uf7Cd UF7コード
	 * @return 削除件数
	 */
	public int delete(String uf7Cd){
		final String sql = "DELETE FROM uf7_ichiran WHERE uf7_cd = ?";
		return connection.update(sql, uf7Cd);
	}
}
