package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.Uf9Zandaka;

/**
 * ユニバーサルフィールド９残高に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class Uf9ZandakaAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected Uf9Zandaka mapToDto(GMap map){
		return map == null ? null : new Uf9Zandaka(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<Uf9Zandaka> mapToDto(List<GMap> mapList){
		List<Uf9Zandaka> dtoList = new ArrayList<Uf9Zandaka>();
		for (var map : mapList) {
			dtoList.add(new Uf9Zandaka(map));
		}
		return dtoList;
	}
	
	/**
	 * ユニバーサルフィールド９残高のレコード有無を判定
	 * @param uf9Cd UF9コード
	 * @param kamokuGaibuCd 科目外部コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String uf9Cd, String kamokuGaibuCd) {
		return this.find(uf9Cd, kamokuGaibuCd) == null ? false : true;
	}
	
	/**
	 * ユニバーサルフィールド９残高から主キー指定でレコードを取得
	 * @param uf9Cd UF9コード
	 * @param kamokuGaibuCd 科目外部コード
	 * @return ユニバーサルフィールド９残高DTO
	 */
	public Uf9Zandaka find(String uf9Cd, String kamokuGaibuCd) {
		final String sql = "SELECT * FROM uf9_zandaka WHERE uf9_cd = ? AND kamoku_gaibu_cd = ?";
		return mapToDto(connection.find(sql, uf9Cd, kamokuGaibuCd));
	}
	
	/**
	 * ユニバーサルフィールド９残高からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ユニバーサルフィールド９残高DTO>
	 */
	public List<Uf9Zandaka> load() {
		final String sql = "SELECT * FROM uf9_zandaka ORDER BY uf9_cd, kamoku_gaibu_cd";
		return mapToDto(connection.load(sql));
	}
	
	/**
	 * ユニバーサルフィールド９残高から一部キー指定でレコードを取得
	 * @param uf9Cd UF9コード
	 * @return List<ユニバーサルフィールド９残高>DTO
	 */
	public List<Uf9Zandaka> load(String uf9Cd) {
		final String sql = "SELECT * FROM uf9_zandaka WHERE uf9_cd = ? "
							+ "ORDER BY uf9_cd, kamoku_gaibu_cd";
		return mapToDto(connection.load(sql, uf9Cd));
	}

	/**
	* ユニバーサルフィールド９残高登録
	* @param dto ユニバーサルフィールド９残高
	* @return 件数
	*/
	public int insert(
		Uf9Zandaka dto
	){
		final String sql =
				"INSERT INTO uf9_zandaka "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.uf9Cd, dto.kamokuGaibuCd, dto.kessankiBangou, dto.kamokuNaibuCd, dto.uf9NameRyakushiki, dto.chouhyouShaturyokuNo, dto.kamokuNameRyakushiki, dto.kamokuNameSeishiki, dto.taishakuZokusei, dto.kishuZandaka
					);
	}

	/**
	* ユニバーサルフィールド９残高登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ユニバーサルフィールド９残高
	* @return 件数
	*/
	public int upsert(
		Uf9Zandaka dto
		 ){
		final String sql =
				"INSERT INTO uf9_zandaka "
			+ "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT uf9_zandaka_pkey "
			+ "DO UPDATE SET kessanki_bangou = ?, kamoku_naibu_cd = ?, uf9_name_ryakushiki = ?, chouhyou_shaturyoku_no = ?, kamoku_name_ryakushiki = ?, kamoku_name_seishiki = ?, taishaku_zokusei = ?, kishu_zandaka = ? "
			+ "";
			return connection.update(sql,
				dto.uf9Cd, dto.kamokuGaibuCd, dto.kessankiBangou, dto.kamokuNaibuCd, dto.uf9NameRyakushiki, dto.chouhyouShaturyokuNo, dto.kamokuNameRyakushiki, dto.kamokuNameSeishiki, dto.taishakuZokusei, dto.kishuZandaka
				, dto.kessankiBangou, dto.kamokuNaibuCd, dto.uf9NameRyakushiki, dto.chouhyouShaturyokuNo, dto.kamokuNameRyakushiki, dto.kamokuNameSeishiki, dto.taishakuZokusei, dto.kishuZandaka
				);
    }
	
	/**
	 * ユニバーサルフィールド９残高から主キー指定でレコードを削除
	 * @param uf9Cd UF9コード
	 * @param kamokuGaibuCd 科目外部コード
	 * @return 削除件数
	 */
	public int delete(String uf9Cd, String kamokuGaibuCd){
		final String sql = "DELETE FROM uf9_zandaka WHERE uf9_cd = ? AND kamoku_gaibu_cd = ?";
		return connection.update(sql, uf9Cd, kamokuGaibuCd);
	}
	
	/**
	 * ユニバーサルフィールド９残高から一部キー指定でレコードを削除
	 * @param uf9Cd UF9コード
	 * @return 削除件数
	 */
	public int delete(String uf9Cd) {
		final String sql = "DELETE FROM uf9_zandaka WHERE uf9_cd = ? ";
		return connection.update(sql, uf9Cd);
	}
}
