package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.UfKotei10Ichiran;

/**
 * ユニバーサルフィールド１０一覧（固定値）に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class UfKotei10IchiranAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected UfKotei10Ichiran mapToDto(GMap map){
		return map == null ? null : new UfKotei10Ichiran(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<UfKotei10Ichiran> mapToDto(List<GMap> mapList){
		List<UfKotei10Ichiran> dtoList = new ArrayList<UfKotei10Ichiran>();
		for (var map : mapList) {
			dtoList.add(new UfKotei10Ichiran(map));
		}
		return dtoList;
	}
	
	/**
	 * ユニバーサルフィールド１０一覧（固定値）のレコード有無を判定
	 * @param ufKotei10Cd UF10コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String ufKotei10Cd) {
		return this.find(ufKotei10Cd) == null ? false : true;
	}
	
	/**
	 * ユニバーサルフィールド１０一覧（固定値）から主キー指定でレコードを取得
	 * @param ufKotei10Cd UF10コード
	 * @return ユニバーサルフィールド１０一覧（固定値）DTO
	 */
	public UfKotei10Ichiran find(String ufKotei10Cd) {
		final String sql = "SELECT * FROM uf_kotei10_ichiran WHERE uf_kotei10_cd = ?";
		return mapToDto(connection.find(sql, ufKotei10Cd));
	}
	
	/**
	 * ユニバーサルフィールド１０一覧（固定値）からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ユニバーサルフィールド１０一覧（固定値）DTO>
	 */
	public List<UfKotei10Ichiran> load() {
		final String sql = "SELECT * FROM uf_kotei10_ichiran ORDER BY uf_kotei10_cd";
		return mapToDto(connection.load(sql));
	}

	/**
	* ユニバーサルフィールド１０一覧（固定値）登録
	* @param dto ユニバーサルフィールド１０一覧（固定値）
	* @return 件数
	*/
	public int insert(
		UfKotei10Ichiran dto
	){
		final String sql =
				"INSERT INTO uf_kotei10_ichiran "
			+ "VALUES(?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.ufKotei10Cd, dto.ufKotei10NameRyakushiki, dto.kessankiBangou
					);
	}

	/**
	* ユニバーサルフィールド１０一覧（固定値）登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ユニバーサルフィールド１０一覧（固定値）
	* @return 件数
	*/
	public int upsert(
		UfKotei10Ichiran dto
		 ){
		final String sql =
				"INSERT INTO uf_kotei10_ichiran "
			+ "VALUES(?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT uf_kotei10_ichiran_pkey "
			+ "DO UPDATE SET uf_kotei10_name_ryakushiki = ?, kessanki_bangou = ? "
			+ "";
			return connection.update(sql,
				dto.ufKotei10Cd, dto.ufKotei10NameRyakushiki, dto.kessankiBangou
				, dto.ufKotei10NameRyakushiki, dto.kessankiBangou
				);
    }
	
	/**
	 * ユニバーサルフィールド１０一覧（固定値）から主キー指定でレコードを削除
	 * @param ufKotei10Cd UF10コード
	 * @return 削除件数
	 */
	public int delete(String ufKotei10Cd){
		final String sql = "DELETE FROM uf_kotei10_ichiran WHERE uf_kotei10_cd = ?";
		return connection.update(sql, ufKotei10Cd);
	}
}
