package eteam.database.abstractdao;

import java.util.ArrayList;
import java.util.List;

import eteam.base.EteamAbstractLogic;
import eteam.base.GMap;
import eteam.database.dto.UfKotei2Ichiran;

/**
 * ユニバーサルフィールド２一覧（固定値）に対する標準データ操作クラス
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
public abstract class UfKotei2IchiranAbstractDao extends EteamAbstractLogic {

	/**
	* @param map GMap
	* @return dto (レコードが存在しなければNull)
	*/
	protected UfKotei2Ichiran mapToDto(GMap map){
		return map == null ? null : new UfKotei2Ichiran(map);
	}

	/**
	* @param mapList 検索結果GMap
	* @return dtoList
	*/
	protected List<UfKotei2Ichiran> mapToDto(List<GMap> mapList){
		List<UfKotei2Ichiran> dtoList = new ArrayList<UfKotei2Ichiran>();
		for (var map : mapList) {
			dtoList.add(new UfKotei2Ichiran(map));
		}
		return dtoList;
	}
	
	/**
	 * ユニバーサルフィールド２一覧（固定値）のレコード有無を判定
	 * @param ufKotei2Cd UF2コード
	 * @return true:exist false:not exist
	 */
	public boolean exists(String ufKotei2Cd) {
		return this.find(ufKotei2Cd) == null ? false : true;
	}
	
	/**
	 * ユニバーサルフィールド２一覧（固定値）から主キー指定でレコードを取得
	 * @param ufKotei2Cd UF2コード
	 * @return ユニバーサルフィールド２一覧（固定値）DTO
	 */
	public UfKotei2Ichiran find(String ufKotei2Cd) {
		final String sql = "SELECT * FROM uf_kotei2_ichiran WHERE uf_kotei2_cd = ?";
		return mapToDto(connection.find(sql, ufKotei2Cd));
	}
	
	/**
	 * ユニバーサルフィールド２一覧（固定値）からレコードを全件取得 ※大量データ取得に注意
	 * @return List<ユニバーサルフィールド２一覧（固定値）DTO>
	 */
	public List<UfKotei2Ichiran> load() {
		final String sql = "SELECT * FROM uf_kotei2_ichiran ORDER BY uf_kotei2_cd";
		return mapToDto(connection.load(sql));
	}

	/**
	* ユニバーサルフィールド２一覧（固定値）登録
	* @param dto ユニバーサルフィールド２一覧（固定値）
	* @return 件数
	*/
	public int insert(
		UfKotei2Ichiran dto
	){
		final String sql =
				"INSERT INTO uf_kotei2_ichiran "
			+ "VALUES(?, ?, ? "
			+ ")";
			return connection.update(sql,
					dto.ufKotei2Cd, dto.ufKotei2NameRyakushiki, dto.kessankiBangou
					);
	}

	/**
	* ユニバーサルフィールド２一覧（固定値）登録or更新
	* 仕様上Insert/Updateの一方のみ処理される場合は使用不可
	* @param dto ユニバーサルフィールド２一覧（固定値）
	* @return 件数
	*/
	public int upsert(
		UfKotei2Ichiran dto
		 ){
		final String sql =
				"INSERT INTO uf_kotei2_ichiran "
			+ "VALUES(?, ?, ? "
			+ ") ON CONFLICT ON CONSTRAINT uf_kotei2_ichiran_pkey "
			+ "DO UPDATE SET uf_kotei2_name_ryakushiki = ?, kessanki_bangou = ? "
			+ "";
			return connection.update(sql,
				dto.ufKotei2Cd, dto.ufKotei2NameRyakushiki, dto.kessankiBangou
				, dto.ufKotei2NameRyakushiki, dto.kessankiBangou
				);
    }
	
	/**
	 * ユニバーサルフィールド２一覧（固定値）から主キー指定でレコードを削除
	 * @param ufKotei2Cd UF2コード
	 * @return 削除件数
	 */
	public int delete(String ufKotei2Cd){
		final String sql = "DELETE FROM uf_kotei2_ichiran WHERE uf_kotei2_cd = ?";
		return connection.update(sql, ufKotei2Cd);
	}
}
