SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- e文書ファイル・情報保持用テーブル作成。
CREATE TABLE EBUNSHO_DATA
(
	EBUNSHO_NO VARCHAR(19) NOT NULL,
	EBUNSHO_EDANO INT NOT NULL,
	EBUNSHO_SHUBETSU INT NOT NULL,
	EBUNSHO_NENGAPPI DATE NOT NULL,
	EBUNSHO_KINGAKU NUMERIC(15) NOT NULL,
	EBUNSHO_HAKKOUSHA VARCHAR(20) NOT NULL,
	PRIMARY KEY (EBUNSHO_NO, EBUNSHO_EDANO)
) WITHOUT OIDS;


CREATE TABLE EBUNSHO_FILE
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	EDANO INT NOT NULL,
	EBUNSHO_NO VARCHAR(19) NOT NULL UNIQUE,
	BINARY_DATA BYTEA NOT NULL,
	TOUROKU_USER_ID VARCHAR(30),
	TOUROKU_TIME TIMESTAMP,
	PRIMARY KEY (DENPYOU_ID, EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE EBUNSHO_DATA IS 'e文書データ';
COMMENT ON COLUMN EBUNSHO_DATA.EBUNSHO_NO IS 'e文書番号';
COMMENT ON COLUMN EBUNSHO_DATA.EBUNSHO_EDANO IS 'e文書枝番号';
COMMENT ON COLUMN EBUNSHO_DATA.EBUNSHO_SHUBETSU IS 'e文書種別';
COMMENT ON COLUMN EBUNSHO_DATA.EBUNSHO_NENGAPPI IS 'e文書年月日';
COMMENT ON COLUMN EBUNSHO_DATA.EBUNSHO_KINGAKU IS 'e文書金額';
COMMENT ON COLUMN EBUNSHO_DATA.EBUNSHO_HAKKOUSHA IS 'e文書発行者';
COMMENT ON TABLE EBUNSHO_FILE IS 'e文書ファイル';
COMMENT ON COLUMN EBUNSHO_FILE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN EBUNSHO_FILE.EDANO IS '枝番号';
COMMENT ON COLUMN EBUNSHO_FILE.EBUNSHO_NO IS 'e文書番号';
COMMENT ON COLUMN EBUNSHO_FILE.BINARY_DATA IS 'バイナリーデータ';
COMMENT ON COLUMN EBUNSHO_FILE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN EBUNSHO_FILE.TOUROKU_TIME IS '登録日時';

-- 設定情報データの追加
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info;

\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 伝票種別一覧テーブルに 関連伝票選択フラグ/関連伝票入力欄表示フラグ を追加
ALTER TABLE DENPYOU_SHUBETSU_ICHIRAN RENAME TO DENPYOU_SHUBETSU_ICHIRAN_OLD;

CREATE TABLE DENPYOU_SHUBETSU_ICHIRAN
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT DEFAULT 0 NOT NULL,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	NAIYOU VARCHAR(160) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	KANREN_SENTAKU_FLG VARCHAR(1) NOT NULL,
	KANREN_HYOUJI_FLG VARCHAR(1) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_SHUBETSU_ICHIRAN IS '伝票種別一覧';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.NAIYOU IS '内容（伝票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_SENTAKU_FLG IS '関連伝票選択フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_HYOUJI_FLG IS '関連伝票入力欄表示フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_TIME IS '更新日時';

INSERT INTO DENPYOU_SHUBETSU_ICHIRAN(
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	'0',
	'0',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM DENPYOU_SHUBETSU_ICHIRAN_OLD;

DROP TABLE DENPYOU_SHUBETSU_ICHIRAN_OLD;

-- 関連伝票と伝票のマッピング用テーブル追加
CREATE TABLE KANREN_DENPYOU
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KANREN_DENPYOU VARCHAR(19) NOT NULL,
	KANREN_DENPYOU_KBN VARCHAR(4) NOT NULL,
	KANREN_DENPYOU_KIHYOUBI DATE NOT NULL,
	KANREN_DENPYOU_SHOUNINBI DATE NOT NULL,
	PRIMARY KEY (DENPYOU_ID, KANREN_DENPYOU)
) WITHOUT OIDS;
COMMENT ON TABLE KANREN_DENPYOU IS '関連伝票';
COMMENT ON COLUMN KANREN_DENPYOU.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KANREN_DENPYOU.KANREN_DENPYOU IS '関連伝票';
COMMENT ON COLUMN KANREN_DENPYOU.KANREN_DENPYOU_KBN IS '関連伝票区分';
COMMENT ON COLUMN KANREN_DENPYOU.KANREN_DENPYOU_KIHYOUBI IS '関連伝票起票日';
COMMENT ON COLUMN KANREN_DENPYOU.KANREN_DENPYOU_SHOUNINBI IS '関連伝票承認日';

-- 関連伝票の画面制御追加
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';


commit;
