SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;


CREATE TABLE KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	SEISAN_YOTEIBI DATE NOT NULL,
	SEISAN_KANRYOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;


CREATE TABLE KEIHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	SHIYOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;


CREATE TABLE RYOHI_KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	SHUPPATSU_KBN VARCHAR(1) NOT NULL,
	KIKAN_TO DATE NOT NULL,
	KICHAKU_KBN VARCHAR(1) NOT NULL,
	SEISAN_YOTEIBI DATE NOT NULL,
	SEISAN_KANRYOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;


CREATE TABLE RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;


CREATE TABLE VERSION
(
	VERSION VARCHAR NOT NULL
) WITHOUT OIDS;



COMMENT ON TABLE KARIBARAI IS '仮払';
COMMENT ON COLUMN KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KARIBARAI.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN KARIBARAI.SEISAN_KANRYOUBI IS '精算完了日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN KARIBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_TIME IS '更新日時';

COMMENT ON TABLE KEIHISEISAN IS '経費精算';
COMMENT ON COLUMN KEIHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN KEIHISEISAN.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KEIHISEISAN.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KEIHISEISAN.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KEIHISEISAN.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KEIHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KEIHISEISAN.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN KEIHISEISAN.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN KEIHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN KEIHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_TIME IS '更新日時';

COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';

COMMENT ON TABLE RYOHI_KARIBARAI IS '旅費仮払';
COMMENT ON COLUMN RYOHI_KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHI_KARIBARAI.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHI_KARIBARAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHUPPATSU_KBN IS '出発区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.KICHAKU_KBN IS '帰着区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISAN_KANRYOUBI IS '精算完了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHI_KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_TIME IS '更新日時';

COMMENT ON TABLE VERSION IS 'ヴァージョン';
COMMENT ON COLUMN VERSION.VERSION IS 'ヴァージョン';
