SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 画面追加(画面項目管理)
DELETE FROM gamen_kengen_seigyo;
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 内部コード追加(部品形式)
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 画面項目制御用のテーブル作成
CREATE TABLE GAMEN_KOUMOKU_SEIGYO
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	KOUMOKU_ID VARCHAR NOT NULL,
	DEFAULT_KOUMOKU_NAME VARCHAR NOT NULL,
	KOUMOKU_NAME VARCHAR NOT NULL,
	HYOUJI_FLG VARCHAR(1) NOT NULL,
	HISSU_FLG VARCHAR(1) NOT NULL,
	HYOUJI_SEIGYO_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, KOUMOKU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE GAMEN_KOUMOKU_SEIGYO IS '画面項目制御';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.KOUMOKU_ID IS '項目ID';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.DEFAULT_KOUMOKU_NAME IS 'デフォルト項目名';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.KOUMOKU_NAME IS '項目名';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_FLG IS '表示フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HISSU_FLG IS '必須フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_SEIGYO_FLG IS '表示制御フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_JUN IS '表示順';
\copy gamen_koumoku_seigyo FROM '.\files\csv\gamen_koumoku_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 設定情報データ変更
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info;
\copy setting_info FROM '.\files\csv\setting_info_tmp.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 振込日ルール テーブル追加
CREATE TABLE FURIKOMI_BI_RULE
(
	KIJUN_DATE SMALLINT NOT NULL,
	FURIKOMI_DATE SMALLINT NOT NULL,
	PRIMARY KEY (KIJUN_DATE)
) WITHOUT OIDS;
COMMENT ON TABLE FURIKOMI_BI_RULE IS '振込日ルール';
COMMENT ON COLUMN FURIKOMI_BI_RULE.KIJUN_DATE IS '基準日';
COMMENT ON COLUMN FURIKOMI_BI_RULE.FURIKOMI_DATE IS '振込日';

-- ユーザー情報テーブルに代理起票可能フラグ、セキュリティパターン、セキュリティワークフロー限定フラグを追加
ALTER TABLE USER_INFO RENAME TO USER_INFO_OLD;
CREATE TABLE USER_INFO
(
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	MAIL_ADDRESS VARCHAR(50) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PASS_KOUSHIN_DATE DATE,
	PASS_FAILURE_COUNT INT DEFAULT 0 NOT NULL,
	PASS_FAILURE_TIME TIMESTAMP,
	TMP_LOCK_FLG VARCHAR(1) NOT NULL,
	TMP_LOCK_TIME TIMESTAMP,
	LOCK_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	LOCK_TIME TIMESTAMP,
	DAIRIKIHYOU_FLG VARCHAR(1) NOT NULL,
	SECURITY_PATTERN VARCHAR(4) NOT NULL,
	SECURITY_WFONLY_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE USER_INFO IS 'ユーザー情報';
COMMENT ON COLUMN USER_INFO.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN USER_INFO.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN USER_INFO.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN USER_INFO.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN USER_INFO.MAIL_ADDRESS IS 'メールアドレス';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN USER_INFO.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN USER_INFO.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN USER_INFO.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN USER_INFO.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN USER_INFO.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN USER_INFO.PASS_KOUSHIN_DATE IS 'パスワード変更日';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_COUNT IS 'パスワード誤り回数';
COMMENT ON COLUMN USER_INFO.PASS_FAILURE_TIME IS 'パスワード誤り時間';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_FLG IS 'アカウント一時ロックフラグ';
COMMENT ON COLUMN USER_INFO.TMP_LOCK_TIME IS 'アカウント一時ロック時間';
COMMENT ON COLUMN USER_INFO.LOCK_FLG IS 'アカウントロックフラグ';
COMMENT ON COLUMN USER_INFO.LOCK_TIME IS 'アカウントロック時間';
COMMENT ON COLUMN USER_INFO.DAIRIKIHYOU_FLG IS '代理起票可能フラグ';
COMMENT ON COLUMN USER_INFO.SECURITY_PATTERN IS 'セキュリティパターン';
COMMENT ON COLUMN USER_INFO.SECURITY_WFONLY_FLG IS 'セキュリティワークフロー限定フラグ';
INSERT INTO USER_INFO(
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME,
	DAIRIKIHYOU_FLG,
	SECURITY_PATTERN,
	SECURITY_WFONLY_FLG
)
SELECT
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	MAIL_ADDRESS,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME,
	PASS_KOUSHIN_DATE,
	PASS_FAILURE_COUNT,
	PASS_FAILURE_TIME,
	TMP_LOCK_FLG,
	TMP_LOCK_TIME,
	LOCK_FLG,
	LOCK_TIME,
	'0',
	'',
	'0'
FROM USER_INFO_OLD;
DROP TABLE USER_INFO_OLD;

-- 経費精算明細テーブルにユーザーID、社員番号、ユーザー姓、ユーザー名、税率、取引先コード、取引先名（略式）を追加
--（過去明細は親テーブルから引継ぎ、親テーブルの税率カラムは削除）
ALTER TABLE KEIHISEISAN_MEISAI RENAME TO KEIHISEISAN_MEISAI_OLD;

CREATE TABLE KEIHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE KEIHISEISAN_MEISAI IS '経費精算明細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT INTO KEIHISEISAN_MEISAI(
	DENPYOU_ID,
	DENPYOU_EDANO,
	SHIWAKE_EDANO,
	USER_ID,
	SHAIN_NO,
	USER_SEI,
	USER_MEI,
	TORIHIKI_NAME,
	TEKIYOU,
	ZEIRITSU,
	SHIHARAI_KINGAKU,
	HONTAI_KINGAKU,
	SHOUHIZEIGAKU,
	KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KOUSAIHI_SHOUSAI,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	KM.DENPYOU_ID,
	KM.DENPYOU_EDANO,
	KM.SHIWAKE_EDANO,
	COALESCE(U.USER_ID, ''),
	COALESCE(U.SHAIN_NO, ''),
	COALESCE(U.USER_SEI, ''),
	COALESCE(U.USER_MEI, ''),
	KM.TORIHIKI_NAME,
	KM.TEKIYOU,
	K.ZEIRITSU,
	KM.SHIHARAI_KINGAKU,
	KM.HONTAI_KINGAKU,
	KM.SHOUHIZEIGAKU,
	KM.KOUSAIHI_SHOUSAI_HYOUJI_FLG,
	KM.KOUSAIHI_SHOUSAI,
	KM.KARI_FUTAN_BUMON_CD,
	KM.KARI_FUTAN_BUMON_NAME,
	K.TORIHIKISAKI_CD,
	K.TORIHIKISAKI_NAME_RYAKUSHIKI,
	KM.KARI_KAMOKU_CD,
	KM.KARI_KAMOKU_NAME,
	KM.KARI_KAMOKU_EDABAN_CD,
	KM.KARI_KAMOKU_EDABAN_NAME,
	KM.KARI_KAZEI_KBN,
	KM.KASHI_FUTAN_BUMON_CD,
	KM.KASHI_FUTAN_BUMON_NAME,
	KM.KASHI_KAMOKU_CD,
	KM.KASHI_KAMOKU_NAME,
	KM.KASHI_KAMOKU_EDABAN_CD,
	KM.KASHI_KAMOKU_EDABAN_NAME,
	KM.KASHI_KAZEI_KBN,
	KM.UF1_CD,
	KM.UF1_NAME_RYAKUSHIKI,
	KM.UF2_CD,
	KM.UF2_NAME_RYAKUSHIKI,
	KM.UF3_CD,
	KM.UF3_NAME_RYAKUSHIKI,
	KM.PROJECT_CD,
	KM.PROJECT_NAME,
	KM.TEKIYOU_CD,
	KM.TOUROKU_USER_ID,
	KM.TOUROKU_TIME,
	KM.KOUSHIN_USER_ID,
	KM.KOUSHIN_TIME
FROM
  KEIHISEISAN_MEISAI_OLD KM
LEFT OUTER JOIN KEIHISEISAN K
ON KM.DENPYOU_ID = K.DENPYOU_ID
JOIN SHOUNIN_ROUTE S
ON KM.denpyou_id = S.denpyou_id AND S.edano = 1
LEFT OUTER JOIN USER_INFO U
ON S.user_id = U.user_id;

DROP TABLE KEIHISEISAN_MEISAI_OLD;

-- 経費精算テーブルに代理フラグを追加、税率、取引先コード、取引先名（略式）を削除
ALTER TABLE KEIHISEISAN RENAME TO KEIHISEISAN_OLD;

CREATE TABLE KEIHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	DAIRIFLG VARCHAR(1) DEFAULT '0' NOT NULL,
	SHIYOUBI DATE,
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE KEIHISEISAN IS '経費精算';
COMMENT ON COLUMN KEIHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN KEIHISEISAN.DAIRIFLG IS '代理フラグ';
COMMENT ON COLUMN KEIHISEISAN.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KEIHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KEIHISEISAN.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KEIHISEISAN.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN KEIHISEISAN.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN KEIHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN KEIHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KEIHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KEIHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KEIHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT INTO KEIHISEISAN(
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	DAIRIFLG,
	SHIYOUBI,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	SHOUHYOU_SHORUI_FLG,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	'0',
	SHIYOUBI,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	SHOUHYOU_SHORUI_FLG,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HF1_CD,
	HF1_NAME_RYAKUSHIKI,
	HF2_CD,
	HF2_NAME_RYAKUSHIKI,
	HF3_CD,
	HF3_NAME_RYAKUSHIKI,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KEIHISEISAN_OLD;

DROP TABLE KEIHISEISAN_OLD;

-- 請求書計上日締テーブル追加
CREATE TABLE SEIKYUUSHO_KEIJOUBI_SHIMEBI
(
	SHIMEBI DATE NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (SHIMEBI)
) WITHOUT OIDS;
COMMENT ON TABLE SEIKYUUSHO_KEIJOUBI_SHIMEBI IS '請求書計上日締日';
COMMENT ON COLUMN SEIKYUUSHO_KEIJOUBI_SHIMEBI.SHIMEBI IS '締日';
COMMENT ON COLUMN SEIKYUUSHO_KEIJOUBI_SHIMEBI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SEIKYUUSHO_KEIJOUBI_SHIMEBI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SEIKYUUSHO_KEIJOUBI_SHIMEBI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SEIKYUUSHO_KEIJOUBI_SHIMEBI.KOUSHIN_TIME IS '更新日時';

-- 出張旅費精算（仮払精算）に時刻カラムを追加
ALTER TABLE RYOHISEISAN RENAME TO RYOHISEISAN_OLD;

CREATE TABLE RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO ryohiseisan( 
  denpyou_id
  , karibarai_denpyou_id
  , karibarai_mishiyou_flg
  , houmonsaki
  , mokuteki
  , seisankikan_from
  , seisankikan_from_hour
  , seisankikan_from_min
  , seisankikan_to
  , seisankikan_to_hour
  , seisankikan_to_min
  , keijoubi
  , shiharaibi
  , shiharaikiboubi
  , shiharaihouhou
  , tekiyou
  , zeiritsu
  , goukei_kingaku
  , sashihiki_shikyuu_kingaku
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , hosoku
  , shiwake_edano
  , torihiki_name
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , project_cd
  , project_name
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  denpyou_id
  , karibarai_denpyou_id
  , karibarai_mishiyou_flg
  , houmonsaki
  , mokuteki
  , seisankikan_from
  , null
  , null
  , seisankikan_to
  , null
  , null
  , keijoubi
  , shiharaibi
  , shiharaikiboubi
  , shiharaihouhou
  , tekiyou
  , zeiritsu
  , goukei_kingaku
  , sashihiki_shikyuu_kingaku
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , hosoku
  , shiwake_edano
  , torihiki_name
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , project_cd
  , project_name
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time 
FROM
  ryohiseisan_old;

DROP TABLE ryohiseisan_old;



-- 仮払テーブルの清算予定日 NOT NULL削除
ALTER TABLE KARIBARAI ALTER COLUMN SEISAN_YOTEIBI DROP NOT NULL;

-- 旅費仮払テーブルの清算予定日 NOT NULL削除
ALTER TABLE RYOHI_KARIBARAI ALTER COLUMN SEISAN_YOTEIBI DROP NOT NULL;

-- 請求書払い申請の税率、取引先コード、取引先名（略式）、振込先情報を明細に追加
--（過去明細は親テーブルから引継ぎ、親テーブルの税率、取引先コード、取引先名（略式）、振込先情報カラムは削除）
ALTER TABLE seikyuushobarai_meisai RENAME TO seikyuushobarai_meisai_old;

CREATE TABLE SEIKYUUSHOBARAI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	FURIKOMISAKI_JOUHOU VARCHAR(240) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE SEIKYUUSHOBARAI_MEISAI IS '請求書払い明細';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.FURIKOMISAKI_JOUHOU IS '振込先情報';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO seikyuushobarai_meisai( 
  denpyou_id
  , denpyou_edano
  , shiwake_edano
  , torihiki_name
  , tekiyou
  , zeiritsu
  , shiharai_kingaku
  , hontai_kingaku
  , shouhizeigaku
  , kousaihi_shousai_hyouji_flg
  , kousaihi_shousai
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , torihikisaki_cd
  , torihikisaki_name_ryakushiki
  , furikomisaki_jouhou
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , project_cd
  , project_name
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  sm.denpyou_id
  , sm.denpyou_edano
  , sm.shiwake_edano
  , sm.torihiki_name
  , sm.tekiyou
  , s.zeiritsu
  , sm.shiharai_kingaku
  , sm.hontai_kingaku
  , sm.shouhizeigaku
  , sm.kousaihi_shousai_hyouji_flg
  , sm.kousaihi_shousai
  , sm.kari_futan_bumon_cd
  , sm.kari_futan_bumon_name
  , s.torihikisaki_cd
  , s.torihikisaki_name_ryakushiki
  , s.furikomisaki_jouhou
  , sm.kari_kamoku_cd
  , sm.kari_kamoku_name
  , sm.kari_kamoku_edaban_cd
  , sm.kari_kamoku_edaban_name
  , sm.kari_kazei_kbn
  , sm.kashi_futan_bumon_cd
  , sm.kashi_futan_bumon_name
  , sm.kashi_kamoku_cd
  , sm.kashi_kamoku_name
  , sm.kashi_kamoku_edaban_cd
  , sm.kashi_kamoku_edaban_name
  , sm.kashi_kazei_kbn
  , sm.uf1_cd
  , sm.uf1_name_ryakushiki
  , sm.uf2_cd
  , sm.uf2_name_ryakushiki
  , sm.uf3_cd
  , sm.uf3_name_ryakushiki
  , sm.project_cd
  , sm.project_name
  , sm.tekiyou_cd
  , sm.touroku_user_id
  , sm.touroku_time
  , sm.koushin_user_id
  , sm.koushin_time 
FROM
  seikyuushobarai_meisai_old sm
LEFT OUTER JOIN 
  seikyuushobarai s
ON sm.denpyou_id = s.denpyou_id;

DROP TABLE seikyuushobarai_meisai_old;


ALTER TABLE seikyuushobarai RENAME TO seikyuushobarai_old;

CREATE TABLE SEIKYUUSHOBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KEIJOUBI DATE,
	SHIHARAI_KIGEN DATE NOT NULL,
	SHIHARAIBI DATE,
	MASREF_FLG VARCHAR(1) NOT NULL,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	KAKE_FLG VARCHAR(1) NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE SEIKYUUSHOBARAI IS '請求書払い';
COMMENT ON COLUMN SEIKYUUSHOBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KEIJOUBI IS '計上日';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHIHARAI_KIGEN IS '支払期限';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN SEIKYUUSHOBARAI.MASREF_FLG IS 'マスター参照フラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KAKE_FLG IS '掛けフラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN SEIKYUUSHOBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO seikyuushobarai( 
  denpyou_id
  , keijoubi
  , shiharai_kigen
  , shiharaibi
  , masref_flg
  , shouhyou_shorui_flg
  , kake_flg
  , hontai_kingaku_goukei
  , shouhizeigaku_goukei
  , shiharai_kingaku_goukei
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , hosoku
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  denpyou_id
  , keijoubi
  , shiharai_kigen
  , shiharaibi
  , masref_flg
  , shouhyou_shorui_flg
  , kake_flg
  , hontai_kingaku_goukei
  , shouhizeigaku_goukei
  , shiharai_kingaku_goukei
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , hosoku
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time 
FROM
  seikyuushobarai_old;

DROP TABLE seikyuushobarai_old;

-- 自動引落の税率、取引先コード、取引先名（略式）を明細に追加
--（過去明細は親テーブルから引継ぎ、親テーブルの税率、取引先コード、取引先名（略式）カラムは削除）
ALTER TABLE JIDOUHIKIOTOSHI_MEISAI RENAME TO JIDOUHIKIOTOSHI_MEISAI_OLD;

CREATE TABLE JIDOUHIKIOTOSHI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE JIDOUHIKIOTOSHI_MEISAI IS '自動引落明細';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO jidouhikiotoshi_meisai( 
  denpyou_id
  , denpyou_edano
  , shiwake_edano
  , torihiki_name
  , tekiyou
  , zeiritsu
  , shiharai_kingaku
  , hontai_kingaku
  , shouhizeigaku
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , TORIHIKISAKI_CD
  , TORIHIKISAKI_NAME_RYAKUSHIKI
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , project_cd
  , project_name
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  jm.denpyou_id
  , jm.denpyou_edano
  , jm.shiwake_edano
  , jm.torihiki_name
  , jm.tekiyou
  , j.zeiritsu
  , jm.shiharai_kingaku
  , jm.hontai_kingaku
  , jm.shouhizeigaku
  , jm.kari_futan_bumon_cd
  , jm.kari_futan_bumon_name
  , j.TORIHIKISAKI_CD
  , j.TORIHIKISAKI_NAME_RYAKUSHIKI
  , jm.kari_kamoku_cd
  , jm.kari_kamoku_name
  , jm.kari_kamoku_edaban_cd
  , jm.kari_kamoku_edaban_name
  , jm.kari_kazei_kbn
  , jm.kashi_futan_bumon_cd
  , jm.kashi_futan_bumon_name
  , jm.kashi_kamoku_cd
  , jm.kashi_kamoku_name
  , jm.kashi_kamoku_edaban_cd
  , jm.kashi_kamoku_edaban_name
  , jm.kashi_kazei_kbn
  , jm.uf1_cd
  , jm.uf1_name_ryakushiki
  , jm.uf2_cd
  , jm.uf2_name_ryakushiki
  , jm.uf3_cd
  , jm.uf3_name_ryakushiki
  , jm.project_cd
  , jm.project_name
  , jm.tekiyou_cd
  , jm.touroku_user_id
  , jm.touroku_time
  , jm.koushin_user_id
  , jm.koushin_time 
FROM
  jidouhikiotoshi_meisai_old jm
LEFT OUTER JOIN jidouhikiotoshi j
ON jm.denpyou_id = j.denpyou_id;

DROP TABLE JIDOUHIKIOTOSHI_MEISAI_OLD;


ALTER TABLE JIDOUHIKIOTOSHI RENAME TO JIDOUHIKIOTOSHI_OLD;

CREATE TABLE JIDOUHIKIOTOSHI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KEIJOUBI DATE,
	HIKIOTOSHIBI DATE NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE JIDOUHIKIOTOSHI IS '自動引落';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KEIJOUBI IS '計上日';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HIKIOTOSHIBI IS '引落日';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HOSOKU IS '補足';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO jidouhikiotoshi( 
  denpyou_id
  , keijoubi
  , hikiotoshibi
  , hontai_kingaku_goukei
  , shouhizeigaku_goukei
  , shiharai_kingaku_goukei
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , hosoku
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  denpyou_id
  , keijoubi
  , hikiotoshibi
  , hontai_kingaku_goukei
  , shouhizeigaku_goukei
  , shiharai_kingaku_goukei
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , hosoku
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time 
FROM
  jidouhikiotoshi_old;

DROP TABLE jidouhikiotoshi_old;

-- 交通費精算に時刻カラムを追加
ALTER TABLE KOUTSUUHISEISAN RENAME TO KOUTSUUHISEISAN_OLD;

CREATE TABLE KOUTSUUHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON COLUMN KOUTSUUHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN KOUTSUUHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN KOUTSUUHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KOUTSUUHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO KOUTSUUHISEISAN( 
  DENPYOU_ID
  , MOKUTEKI
  , SEISANKIKAN_FROM
  , SEISANKIKAN_FROM_HOUR
  , SEISANKIKAN_FROM_MIN
  , SEISANKIKAN_TO
  , SEISANKIKAN_TO_HOUR
  , SEISANKIKAN_TO_MIN
  , KEIJOUBI
  , SHIHARAIBI
  , SHIHARAIKIBOUBI
  , SHIHARAIHOUHOU
  , TEKIYOU
  , ZEIRITSU
  , GOUKEI_KINGAKU
  , HF1_CD
  , HF1_NAME_RYAKUSHIKI
  , HF2_CD
  , HF2_NAME_RYAKUSHIKI
  , HF3_CD
  , HF3_NAME_RYAKUSHIKI
  , HOSOKU
  , SHIWAKE_EDANO
  , TORIHIKI_NAME
  , KARI_FUTAN_BUMON_CD
  , KARI_FUTAN_BUMON_NAME
  , KARI_KAMOKU_CD
  , KARI_KAMOKU_NAME
  , KARI_KAMOKU_EDABAN_CD
  , KARI_KAMOKU_EDABAN_NAME
  , KARI_KAZEI_KBN
  , KASHI_FUTAN_BUMON_CD
  , KASHI_FUTAN_BUMON_NAME
  , KASHI_KAMOKU_CD
  , KASHI_KAMOKU_NAME
  , KASHI_KAMOKU_EDABAN_CD
  , KASHI_KAMOKU_EDABAN_NAME
  , KASHI_KAZEI_KBN
  , UF1_CD
  , UF1_NAME_RYAKUSHIKI
  , UF2_CD
  , UF2_NAME_RYAKUSHIKI
  , UF3_CD
  , UF3_NAME_RYAKUSHIKI
  , PROJECT_CD
  , PROJECT_NAME
  , TEKIYOU_CD
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME
) 
SELECT
DENPYOU_ID
  , MOKUTEKI
  , SEISANKIKAN_FROM
  , NULL
  , NULL
  , SEISANKIKAN_TO
  , NULL
  , NULL
  , KEIJOUBI
  , SHIHARAIBI
  , SHIHARAIKIBOUBI
  , SHIHARAIHOUHOU
  , TEKIYOU
  , ZEIRITSU
  , GOUKEI_KINGAKU
  , HF1_CD
  , HF1_NAME_RYAKUSHIKI
  , HF2_CD
  , HF2_NAME_RYAKUSHIKI
  , HF3_CD
  , HF3_NAME_RYAKUSHIKI
  , HOSOKU
  , SHIWAKE_EDANO
  , TORIHIKI_NAME
  , KARI_FUTAN_BUMON_CD
  , KARI_FUTAN_BUMON_NAME
  , KARI_KAMOKU_CD
  , KARI_KAMOKU_NAME
  , KARI_KAMOKU_EDABAN_CD
  , KARI_KAMOKU_EDABAN_NAME
  , KARI_KAZEI_KBN
  , KASHI_FUTAN_BUMON_CD
  , KASHI_FUTAN_BUMON_NAME
  , KASHI_KAMOKU_CD
  , KASHI_KAMOKU_NAME
  , KASHI_KAMOKU_EDABAN_CD
  , KASHI_KAMOKU_EDABAN_NAME
  , KASHI_KAZEI_KBN
  , UF1_CD
  , UF1_NAME_RYAKUSHIKI
  , UF2_CD
  , UF2_NAME_RYAKUSHIKI
  , UF3_CD
  , UF3_NAME_RYAKUSHIKI
  , PROJECT_CD
  , PROJECT_NAME
  , TEKIYOU_CD
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME
FROM
  KOUTSUUHISEISAN_OLD;

DROP TABLE KOUTSUUHISEISAN_OLD;

-- マスター管理の処理対象テーブル追加(振込日ルール・仕訳以外の期関連)
\copy master_kanri_hansuu          FROM '.\files\csv\master_kanri_hansuu_patch.csv'          WITH CSV header ENCODING 'SHIFT-JIS';
\copy master_kanri_ichiran         FROM '.\files\csv\master_kanri_ichiran_patch.csv'         WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター取込の処理対象テーブル追加(振込日ルール・仕訳以外の期関連)
-- ※_siasは当パッチが初回インポートになる
DELETE FROM MASTER_TORIKOMI_ICHIRAN_DE3;
\copy MASTER_TORIKOMI_ICHIRAN_DE3  FROM '.\files\csv\master_torikomi_ichiran_de3.csv'  WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM MASTER_TORIKOMI_SHOUSAI_DE3;
\copy MASTER_TORIKOMI_SHOUSAI_DE3  FROM '.\files\csv\master_torikomi_shousai_de3.csv'  WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM MASTER_TORIKOMI_ICHIRAN_SIAS;
\copy MASTER_TORIKOMI_ICHIRAN_SIAS FROM '.\files\csv\master_torikomi_ichiran_sias.csv'       WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM MASTER_TORIKOMI_SHOUSAI_SIAS;
\copy MASTER_TORIKOMI_SHOUSAI_SIAS FROM '.\files\csv\master_torikomi_shousai_sias.csv'       WITH CSV header ENCODING 'SHIFT-JIS';

-- マスター取込(TERM)の処理対象テーブル追加、初期レコード(財務仕訳)追加
CREATE TABLE MASTER_TORIKOMI_TERM_ICHIRAN_DE3
(
	MASTER_ID VARCHAR(50) NOT NULL,
	MASTER_NAME VARCHAR(50) NOT NULL,
	OP_MASTER_ID VARCHAR NOT NULL,
	OP_MASTER_NAME VARCHAR NOT NULL,
	TORIKOMI_KAHI_FLG  VARCHAR(1) NOT NULL,
	PRIMARY KEY (MASTER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE MASTER_TORIKOMI_TERM_ICHIRAN_DE3 IS 'マスター取込期間一覧(de3)';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_DE3.MASTER_ID IS 'マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_DE3.MASTER_NAME IS 'マスター名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_DE3.OP_MASTER_ID IS 'OPEN21マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_DE3.OP_MASTER_NAME IS 'OPEN21マスター名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_DE3.TORIKOMI_KAHI_FLG  IS '取込可否フラグ';
CREATE TABLE MASTER_TORIKOMI_TERM_ICHIRAN_SIAS
(
	MASTER_ID VARCHAR(50) NOT NULL,
	MASTER_NAME VARCHAR(50) NOT NULL,
	OP_MASTER_ID VARCHAR NOT NULL,
	OP_MASTER_NAME VARCHAR NOT NULL,
	TORIKOMI_KAHI_FLG  VARCHAR(1) NOT NULL,
	PRIMARY KEY (MASTER_ID)
) WITHOUT OIDS;
COMMENT ON TABLE MASTER_TORIKOMI_TERM_ICHIRAN_SIAS IS 'マスター取込期間一覧(SIAS)';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_SIAS.MASTER_ID IS 'マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_SIAS.MASTER_NAME IS 'マスター名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_SIAS.OP_MASTER_ID IS 'OPEN21マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_SIAS.OP_MASTER_NAME IS 'OPEN21マスター名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_ICHIRAN_SIAS.TORIKOMI_KAHI_FLG  IS '取込可否フラグ';
CREATE TABLE MASTER_TORIKOMI_TERM_SHOUSAI_DE3
(
	MASTER_ID VARCHAR(50) NOT NULL,
	ET_COLUMN_ID VARCHAR NOT NULL,
	ET_COLUMN_NAME  VARCHAR NOT NULL,
	ET_DATA_TYPE VARCHAR NOT NULL,
	OP_COLUME_ID VARCHAR NOT NULL,
	OP_COLUMN_NAME VARCHAR NOT NULL,
	OP_DATA_TYPE VARCHAR NOT NULL,
	ENTRY_ORDER INT NOT NULL,
	PK_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (MASTER_ID, ET_COLUMN_ID)
) WITHOUT OIDS;
COMMENT ON TABLE MASTER_TORIKOMI_TERM_SHOUSAI_DE3 IS 'マスター取込期間詳細(de3)';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.MASTER_ID IS 'マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.ET_COLUMN_ID IS 'eTeamカラムID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.ET_COLUMN_NAME  IS 'eTeamカラム名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.ET_DATA_TYPE IS 'eTeamデータ型';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.OP_COLUME_ID IS 'OPEN21カラムID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.OP_COLUMN_NAME IS 'OPEN21カラム名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.OP_DATA_TYPE IS 'OPEN21データ型';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.ENTRY_ORDER IS '登録順';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_DE3.PK_FLG IS 'プライマリーキーフラグ';
CREATE TABLE MASTER_TORIKOMI_TERM_SHOUSAI_SIAS
(
	MASTER_ID VARCHAR(50) NOT NULL,
	ET_COLUMN_ID VARCHAR NOT NULL,
	ET_COLUMN_NAME  VARCHAR NOT NULL,
	ET_DATA_TYPE VARCHAR NOT NULL,
	OP_COLUME_ID VARCHAR NOT NULL,
	OP_COLUMN_NAME VARCHAR NOT NULL,
	OP_DATA_TYPE VARCHAR NOT NULL,
	ENTRY_ORDER INT NOT NULL,
	PK_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (MASTER_ID, ET_COLUMN_ID)
) WITHOUT OIDS;
COMMENT ON TABLE MASTER_TORIKOMI_TERM_SHOUSAI_SIAS IS 'マスター取込期間詳細(SIAS)';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.MASTER_ID IS 'マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.ET_COLUMN_ID IS 'eTeamカラムID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.ET_COLUMN_NAME  IS 'eTeamカラム名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.ET_DATA_TYPE IS 'eTeamデータ型';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.OP_COLUME_ID IS 'OPEN21カラムID';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.OP_COLUMN_NAME IS 'OPEN21カラム名';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.OP_DATA_TYPE IS 'OPEN21データ型';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.ENTRY_ORDER IS '登録順';
COMMENT ON COLUMN MASTER_TORIKOMI_TERM_SHOUSAI_SIAS.PK_FLG IS 'プライマリーキーフラグ';
\copy MASTER_TORIKOMI_TERM_ICHIRAN_DE3  FROM '.\files\csv\master_torikomi_term_ichiran_de3.csv'   WITH CSV header ENCODING 'SHIFT-JIS';
\copy MASTER_TORIKOMI_TERM_ICHIRAN_SIAS FROM '.\files\csv\master_torikomi_term_ichiran_sias.csv'  WITH CSV header ENCODING 'SHIFT-JIS';
\copy MASTER_TORIKOMI_TERM_SHOUSAI_DE3  FROM '.\files\csv\master_torikomi_term_shousai.csv' WITH CSV header ENCODING 'SHIFT-JIS';
\copy MASTER_TORIKOMI_TERM_SHOUSAI_SIAS FROM '.\files\csv\master_torikomi_term_shousai.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 経費明細関連テーブル追加
CREATE TABLE KI_BUMON
(
	KESN SMALLINT NOT NULL,
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (KESN, FUTAN_BUMON_CD)
) WITHOUT OIDS;
CREATE TABLE KI_BUMON_SECURITY
(
	KESN SMALLINT NOT NULL,
	SPTN INT NOT NULL,
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	PRIMARY KEY (KESN, SPTN, FUTAN_BUMON_CD)
) WITHOUT OIDS;
CREATE TABLE KI_KAMOKU
(
	KESN SMALLINT NOT NULL,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT NOT NULL,
	PRIMARY KEY (KESN, KAMOKU_NAIBU_CD)
) WITHOUT OIDS;
CREATE TABLE KI_KAMOKU_SECURITY
(
	KESN SMALLINT NOT NULL,
	SPTN INT NOT NULL,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	PRIMARY KEY (KESN, SPTN, KAMOKU_NAIBU_CD)
) WITHOUT OIDS;
CREATE TABLE KI_KESN
(
	KESN SMALLINT NOT NULL,
	KESSANKI_BANGOU SMALLINT NOT NULL,
	FROM_DATE DATE NOT NULL,
	TO_DATE DATE NOT NULL,
	PRIMARY KEY (KESN, KESSANKI_BANGOU, FROM_DATE, TO_DATE)
) WITHOUT OIDS;
CREATE TABLE KI_SHIWAKE
(
	KESN SMALLINT NOT NULL,
	DKEI SMALLINT NOT NULL,
	DSEQ INT NOT NULL,
	SSEQ INT NOT NULL,
	DYMD DATE NOT NULL,
	DCNO VARCHAR(8) NOT NULL,
	VALU DECIMAL(15) NOT NULL,
	RKMK VARCHAR(15) NOT NULL,
	RBMN VARCHAR(8) NOT NULL,
	RTKY VARCHAR(60) NOT NULL,
	RTOR VARCHAR(12) NOT NULL,
	SKMK VARCHAR(15) NOT NULL,
	SBMN VARCHAR(8) NOT NULL,
	STKY VARCHAR(60) NOT NULL,
	STOR VARCHAR(12) NOT NULL,
	FWAY SMALLINT NOT NULL,
	PRIMARY KEY (KESN, DKEI, DSEQ, SSEQ)
) WITHOUT OIDS;
CREATE TABLE KI_SYUUKEI_BUMON
(
	KESN SMALLINT NOT NULL,
	SYUUKEI_BUMON_CD VARCHAR(8) NOT NULL,
	FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	SYUUKEI_BUMON_NAME VARCHAR(20) NOT NULL,
	FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (KESN, SYUUKEI_BUMON_CD, FUTAN_BUMON_CD)
) WITHOUT OIDS;
COMMENT ON TABLE KI_BUMON IS '（期別）部門';
COMMENT ON COLUMN KI_BUMON.KESN IS '内部決算期';
COMMENT ON COLUMN KI_BUMON.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN KI_BUMON.FUTAN_BUMON_NAME IS '負担部門名';
COMMENT ON TABLE KI_BUMON_SECURITY IS '（期別）部門セキュリティ';
COMMENT ON COLUMN KI_BUMON_SECURITY.KESN IS '内部決算期';
COMMENT ON COLUMN KI_BUMON_SECURITY.SPTN IS 'セキュリティパターン';
COMMENT ON COLUMN KI_BUMON_SECURITY.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON TABLE KI_KAMOKU IS '（期別）科目';
COMMENT ON COLUMN KI_KAMOKU.KESN IS '内部決算期';
COMMENT ON COLUMN KI_KAMOKU.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN KI_KAMOKU.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN KI_KAMOKU.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN KI_KAMOKU.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON TABLE KI_KAMOKU_SECURITY IS '（期別）科目セキュリティ';
COMMENT ON COLUMN KI_KAMOKU_SECURITY.KESN IS '内部決算期';
COMMENT ON COLUMN KI_KAMOKU_SECURITY.SPTN IS 'セキュリティパターン';
COMMENT ON COLUMN KI_KAMOKU_SECURITY.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON TABLE KI_KESN IS '（期別）決算期';
COMMENT ON COLUMN KI_KESN.KESN IS '内部決算期';
COMMENT ON COLUMN KI_KESN.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN KI_KESN.FROM_DATE IS '開始日';
COMMENT ON COLUMN KI_KESN.TO_DATE IS '終了日';
COMMENT ON TABLE KI_SHIWAKE IS '（期別）財務仕訳';
COMMENT ON COLUMN KI_SHIWAKE.KESN IS '内部決算期';
COMMENT ON COLUMN KI_SHIWAKE.DKEI IS '経過月';
COMMENT ON COLUMN KI_SHIWAKE.DSEQ IS '伝票SEQ';
COMMENT ON COLUMN KI_SHIWAKE.SSEQ IS '仕訳SEQ';
COMMENT ON COLUMN KI_SHIWAKE.DYMD IS '（オープン２１）伝票日付';
COMMENT ON COLUMN KI_SHIWAKE.DCNO IS '（オープン２１）伝票番号';
COMMENT ON COLUMN KI_SHIWAKE.VALU IS '（オープン２１）金額';
COMMENT ON COLUMN KI_SHIWAKE.RKMK IS '（オープン２１）借方　科目内部コード';
COMMENT ON COLUMN KI_SHIWAKE.RBMN IS '（オープン２１）借方　部門コード';
COMMENT ON COLUMN KI_SHIWAKE.RTKY IS '（オープン２１）借方　摘要';
COMMENT ON COLUMN KI_SHIWAKE.RTOR IS '（オープン２１）借方　取引先コード';
COMMENT ON COLUMN KI_SHIWAKE.SKMK IS '（オープン２１）貸方　科目内部コード';
COMMENT ON COLUMN KI_SHIWAKE.SBMN IS '（オープン２１）貸方　部門コード';
COMMENT ON COLUMN KI_SHIWAKE.STKY IS '（オープン２１）貸方　摘要';
COMMENT ON COLUMN KI_SHIWAKE.STOR IS '（オープン２１）貸方　取引先コード';
COMMENT ON COLUMN KI_SHIWAKE.FWAY IS '入力手段';
COMMENT ON TABLE KI_SYUUKEI_BUMON IS '（期別）集計部門';
COMMENT ON COLUMN KI_SYUUKEI_BUMON.KESN IS '内部決算期';
COMMENT ON COLUMN KI_SYUUKEI_BUMON.SYUUKEI_BUMON_CD IS '集計部門コード';
COMMENT ON COLUMN KI_SYUUKEI_BUMON.FUTAN_BUMON_CD IS '負担部門コード';
COMMENT ON COLUMN KI_SYUUKEI_BUMON.SYUUKEI_BUMON_NAME IS '集計部門名';
COMMENT ON COLUMN KI_SYUUKEI_BUMON.FUTAN_BUMON_NAME IS '負担部門名';

-- 取引先テーブルの口座名義人・口座名義人ふり仮名カラム文字数を拡張
ALTER TABLE TORIHIKISAKI ALTER KOUZA_MEIGININ TYPE VARCHAR(44);
ALTER TABLE TORIHIKISAKI ALTER KOUZA_MEIGININ_FURIGANA TYPE VARCHAR(40);


commit;
