SET search_path TO :SCHEMA_NAME;

\copy (SELECT * FROM kamoku_zandaka) TO '.\csv\kamoku_zandaka.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM edaban_zandaka) TO '.\csv\edaban_zandaka.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM ki_shouhizei_setting) TO '.\csv\ki_shouhizei_setting.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM bumon_furikae) TO '.\csv\bumon_furikae.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM bumon_furikae_meisai) TO '.\csv\bumon_furikae_meisai.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM bumon_furikae_setting) TO '.\csv\bumon_furikae_setting.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM bumon_tsukekae_control) TO '.\csv\bumon_tsukekae_control.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM suitouchou) TO '.\csv\suitouchou.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM suitouchou_meisai) TO '.\csv\suitouchou_meisai.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM suitouchou_setting) TO '.\csv\suitouchou_setting.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM denpyou_ichiran_kyoten) TO '.\csv\denpyou_ichiran_kyoten.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM denpyou_ichiran_kyoten_meisai) TO '.\csv\denpyou_ichiran_kyoten_meisai.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM denpyou_serial_no_saiban_kyoten) TO '.\csv\denpyou_serial_no_saiban_kyoten.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM user_tenpu_file) TO '.\csv\user_tenpu_file.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM meisai_tenpu_file_himoduke) TO '.\csv\meisai_tenpu_file_himoduke.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM shiwake_pattern_master_zaimu_kyoten) TO '.\csv\shiwake_pattern_master_zaimu_kyoten.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM shounin_joukyou_kyoten) TO '.\csv\shounin_joukyou_kyoten.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM shounin_route_kyoten) TO '.\csv\shounin_route_kyoten.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM teikei_shiwake) TO '.\csv\teikei_shiwake.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM teikei_shiwake_meisai) TO '.\csv\teikei_shiwake_meisai.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_bumon_security) TO '.\csv\zaimu_kyoten_nyuryoku_bumon_security.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_haifu_bumon) TO '.\csv\zaimu_kyoten_nyuryoku_haifu_bumon.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_haifu_kamoku) TO '.\csv\zaimu_kyoten_nyuryoku_haifu_kamoku.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_haifu_pattern) TO '.\csv\zaimu_kyoten_nyuryoku_haifu_pattern.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_ichiran) TO '.\csv\zaimu_kyoten_nyuryoku_ichiran.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_kamoku_security) TO '.\csv\zaimu_kyoten_nyuryoku_kamoku_security.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_nyuryokusha) TO '.\csv\zaimu_kyoten_nyuryoku_nyuryokusha.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_shiwake_serial_no_saiban) TO '.\csv\zaimu_kyoten_nyuryoku_shiwake_serial_no_saiban.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_shounin_route) TO '.\csv\zaimu_kyoten_nyuryoku_shounin_route.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_tsukekaemoto) TO '.\csv\zaimu_kyoten_nyuryoku_tsukekaemoto.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_nyuryoku_user_info) TO '.\csv\zaimu_kyoten_nyuryoku_user_info.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_shiwake_de3) TO '.\csv\zaimu_kyoten_shiwake_de3.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM zaimu_kyoten_shiwake_sias) TO '.\csv\zaimu_kyoten_shiwake_sias.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM bumon_tsukekaesaki) TO '.\csv\bumon_tsukekaesaki.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM setting_info) TO '.\csv\setting_info.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM gamen_koumoku_seigyo WHERE denpyou_kbn='Z001' OR denpyou_kbn='Z002') TO '.\csv\gamen_koumoku_seigyo.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM denpyou WHERE denpyou_kbn='Z001' OR denpyou_kbn='Z002') TO '.\csv\denpyou.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
\copy (SELECT * FROM tsuuchi WHERE substr(denpyou_id, 8, 4)='Z001' OR substr(denpyou_id, 8, 4)='Z002') TO '.\csv\tsuuchi.csv' WITH CSV ENCODING 'SJIS' DELIMITER ','  FORCE QUOTE * ;
