package eteam.database.dto;


import java.sql.Date;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 負担部門DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class BumonMaster implements IEteamDTO {

	/**
	 * default constructor
	 */
	public BumonMaster() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public BumonMaster(GMap m) {
		this.futanBumonCd = m.get("futan_bumon_cd");
		this.futanBumonName = m.get("futan_bumon_name");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.shaukeiBumonFlg = m.get("shaukei_bumon_flg");
		this.shiireKbn = m.get("shiire_kbn") == null ? null : ((Integer)m.get("shiire_kbn")).shortValue();
		this.nyuryokuFromDate = m.get("nyuryoku_from_date");
		this.nyuryokuToDate = m.get("nyuryoku_to_date");
		this.map = m;
	}

	/** 負担部門コード */
	public String futanBumonCd;

	/** 負担部門名 */
	public String futanBumonName;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** 集計部門フラグ */
	public int shaukeiBumonFlg;

	/** 仕入区分 */
	public Short shiireKbn;

	/** 入力開始日 */
	public Date nyuryokuFromDate;

	/** 入力終了日 */
	public Date nyuryokuToDate;

	/** その他項目map */
	public GMap map;
}
