package eteam.database.dto;

import java.sql.Date;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 伝票ID採番DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class DenpyouIdSaiban implements IEteamDTO {

	/**
	 * default constructor
	 */
	public DenpyouIdSaiban() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public DenpyouIdSaiban(GMap m) {
		this.tourokuDate = m.get("touroku_date");
		this.denpyouKbn = m.get("denpyou_kbn");
		this.sequenceVal = m.get("sequence_val");
		this.map = m;
	}

	/** 登録日 */
	public Date tourokuDate;

	/** 伝票区分 */
	public String denpyouKbn;

	/** シーケンス値 */
	public Integer sequenceVal;

	/** その他項目map */
	public GMap map;
}
