package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 駅マスターDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class EkiMaster implements IEteamDTO {

	/**
	 * default constructor
	 */
	public EkiMaster() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public EkiMaster(GMap m) {
		this.regionCd = m.get("region_cd");
		this.lineCd = m.get("line_cd");
		this.ekiCd = m.get("eki_cd");
		this.lineName = m.get("line_name");
		this.ekiName = m.get("eki_name");
		this.map = m;
	}

	/** 地域コード */
	public String regionCd;

	/** 路線コード */
	public String lineCd;

	/** 駅コード */
	public String ekiCd;

	/** 路線名 */
	public String lineName;

	/** 駅名 */
	public String ekiName;

	/** その他項目map */
	public GMap map;
}
