package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 振込日ルール(日付)DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class FurikomiBiRuleHi implements IEteamDTO {

	/**
	 * default constructor
	 */
	public FurikomiBiRuleHi() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public FurikomiBiRuleHi(GMap m) {
		this.kijunDate = m.get("kijun_date");
		this.furikomiDate = m.get("furikomi_date");
		this.map = m;
	}

	/** 基準日 */
	public int kijunDate;

	/** 振込日 */
	public int furikomiDate;

	/** その他項目map */
	public GMap map;
}
