package eteam.database.dto;

import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 業務ロール機能制御DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class GyoumuRoleKinouSeigyo implements IEteamDTO {

	/**
	 * default constructor
	 */
	public GyoumuRoleKinouSeigyo() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public GyoumuRoleKinouSeigyo(GMap m) {
		this.gyoumuRoleId = m.get("gyoumu_role_id");
		this.gyoumuRoleKinouSeigyoCd = m.get("gyoumu_role_kinou_seigyo_cd");
		this.gyoumuRoleKinouSeigyoKbn = m.get("gyoumu_role_kinou_seigyo_kbn");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.map = m;
	}

	/** 業務ロールID */
	public String gyoumuRoleId;

	/** 業務ロール機能制御コード */
	public String gyoumuRoleKinouSeigyoCd;

	/** 業務ロール機能制御区分 */
	public String gyoumuRoleKinouSeigyoKbn;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** その他項目map */
	public GMap map;
}
