package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ヘッダフィールド１０一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Hf10Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Hf10Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Hf10Ichiran(GMap m) {
		this.hf10Cd = m.get("hf10_cd");
		this.hf10NameRyakushiki = m.get("hf10_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** HF10コード */
	public String hf10Cd;

	/** HF10名（略式） */
	public String hf10NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
