package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ヘッダフィールド１一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Hf1Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Hf1Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Hf1Ichiran(GMap m) {
		this.hf1Cd = m.get("hf1_cd");
		this.hf1NameRyakushiki = m.get("hf1_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** HF1コード */
	public String hf1Cd;

	/** HF1名（略式） */
	public String hf1NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
