package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ヘッダフィールド３一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Hf3Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Hf3Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Hf3Ichiran(GMap m) {
		this.hf3Cd = m.get("hf3_cd");
		this.hf3NameRyakushiki = m.get("hf3_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** HF3コード */
	public String hf3Cd;

	/** HF3名（略式） */
	public String hf3NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
