package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ヘッダフィールド４一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Hf4Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Hf4Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Hf4Ichiran(GMap m) {
		this.hf4Cd = m.get("hf4_cd");
		this.hf4NameRyakushiki = m.get("hf4_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** HF4コード */
	public String hf4Cd;

	/** HF4名（略式） */
	public String hf4NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
