package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ヘッダフィールド７一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Hf7Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Hf7Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Hf7Ichiran(GMap m) {
		this.hf7Cd = m.get("hf7_cd");
		this.hf7NameRyakushiki = m.get("hf7_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** HF7コード */
	public String hf7Cd;

	/** HF7名（略式） */
	public String hf7NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
