package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ヘッダフィールド８一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Hf8Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Hf8Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Hf8Ichiran(GMap m) {
		this.hf8Cd = m.get("hf8_cd");
		this.hf8NameRyakushiki = m.get("hf8_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** HF8コード */
	public String hf8Cd;

	/** HF8名（略式） */
	public String hf8NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
