package eteam.database.dto;

import java.sql.Date;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 日付コントロールDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class HizukeControl implements IEteamDTO {

	/**
	 * default constructor
	 */
	public HizukeControl() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public HizukeControl(GMap m) {
		this.systemKanriDate = m.get("system_kanri_date");
		this.fbDataSakuseibiFlg = m.get("fb_data_sakuseibi_flg");
		this.kojinseisanShiharaibi = m.get("kojinseisan_shiharaibi");
		this.kinyuukikanEigyoubiFlg = m.get("kinyuukikan_eigyoubi_flg");
		this.toujitsuKbnFlg = m.get("toujitsu_kbn_flg");
		this.keijoubiFlg = m.get("keijoubi_flg");
		this.map = m;
	}

	/** システム管理日付 */
	public Date systemKanriDate;

	/** FBデータ作成日フラグ */
	public String fbDataSakuseibiFlg;

	/** 個人精算支払日 */
	public Date kojinseisanShiharaibi;

	/** 金融機関営業日フラグ */
	public String kinyuukikanEigyoubiFlg;

	/** 当日区分フラグ */
	public String toujitsuKbnFlg;

	/** 計上日フラグ */
	public String keijoubiFlg;

	/** その他項目map */
	public GMap map;
}
