package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 法人カードインポートDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class HoujinCardImport implements IEteamDTO {

	/**
	 * default constructor
	 */
	public HoujinCardImport() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public HoujinCardImport(GMap m) {
		this.userId = m.get("user_id");
		this.houjinCardShubetsu = m.get("houjin_card_shubetsu");
		this.map = m;
	}

	/** ユーザーID */
	public String userId;

	/** 法人カード種別 */
	public String houjinCardShubetsu;

	/** その他項目map */
	public GMap map;
}
