package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ICカードDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class IcCard implements IEteamDTO {

	/**
	 * default constructor
	 */
	public IcCard() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public IcCard(GMap m) {
		this.icCardNo = m.get("ic_card_no");
		this.token = m.get("token");
		this.userId = m.get("user_id");
		this.map = m;
	}

	/** ICカード番号 */
	public String icCardNo;

	/** トークン */
	public String token;

	/** ユーザーID */
	public String userId;

	/** その他項目map */
	public GMap map;
}
