package eteam.database.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 海外旅費精算経費明細DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KaigaiRyohiseisanKeihiMeisai implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KaigaiRyohiseisanKeihiMeisai() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KaigaiRyohiseisanKeihiMeisai(GMap m) {
		this.denpyouId = m.get("denpyou_id");
		this.denpyouEdano = m.get("denpyou_edano");
		this.kaigaiFlg = m.get("kaigai_flg");
		this.shiwakeEdano = m.get("shiwake_edano");
		this.shiyoubi = m.get("shiyoubi");
		this.shouhyouShoruiFlg = m.get("shouhyou_shorui_flg");
		this.torihikiName = m.get("torihiki_name");
		this.tekiyou = m.get("tekiyou");
		this.zeiritsu = m.get("zeiritsu");
		this.keigenZeiritsuKbn = m.get("keigen_zeiritsu_kbn");
		this.kazeiFlg = m.get("kazei_flg");
		this.shiharaiKingaku = m.get("shiharai_kingaku");
		this.hontaiKingaku = m.get("hontai_kingaku");
		this.shouhizeigaku = m.get("shouhizeigaku");
		this.houjinCardRiyouFlg = m.get("houjin_card_riyou_flg");
		this.kaishaTehaiFlg = m.get("kaisha_tehai_flg");
		this.kousaihiShousaiHyoujiFlg = m.get("kousaihi_shousai_hyouji_flg");
		this.kousaihiNinzuuRiyouFlg = m.get("kousaihi_ninzuu_riyou_flg");
		this.kousaihiShousai = m.get("kousaihi_shousai");
		this.kousaihiNinzuu = m.get("kousaihi_ninzuu");
		this.kousaihiHitoriKingaku = m.get("kousaihi_hitori_kingaku");
		this.heishuCd = m.get("heishu_cd");
		this.rate = m.get("rate");
		this.gaika = m.get("gaika");
		this.currencyUnit = m.get("currency_unit");
		this.kariFutanBumonCd = m.get("kari_futan_bumon_cd");
		this.kariFutanBumonName = m.get("kari_futan_bumon_name");
		this.torihikisakiCd = m.get("torihikisaki_cd");
		this.torihikisakiNameRyakushiki = m.get("torihikisaki_name_ryakushiki");
		this.kariKamokuCd = m.get("kari_kamoku_cd");
		this.kariKamokuName = m.get("kari_kamoku_name");
		this.kariKamokuEdabanCd = m.get("kari_kamoku_edaban_cd");
		this.kariKamokuEdabanName = m.get("kari_kamoku_edaban_name");
		this.kariKazeiKbn = m.get("kari_kazei_kbn");
		this.kashiFutanBumonCd = m.get("kashi_futan_bumon_cd");
		this.kashiFutanBumonName = m.get("kashi_futan_bumon_name");
		this.kashiKamokuCd = m.get("kashi_kamoku_cd");
		this.kashiKamokuName = m.get("kashi_kamoku_name");
		this.kashiKamokuEdabanCd = m.get("kashi_kamoku_edaban_cd");
		this.kashiKamokuEdabanName = m.get("kashi_kamoku_edaban_name");
		this.kashiKazeiKbn = m.get("kashi_kazei_kbn");
		this.uf1Cd = m.get("uf1_cd");
		this.uf1NameRyakushiki = m.get("uf1_name_ryakushiki");
		this.uf2Cd = m.get("uf2_cd");
		this.uf2NameRyakushiki = m.get("uf2_name_ryakushiki");
		this.uf3Cd = m.get("uf3_cd");
		this.uf3NameRyakushiki = m.get("uf3_name_ryakushiki");
		this.uf4Cd = m.get("uf4_cd");
		this.uf4NameRyakushiki = m.get("uf4_name_ryakushiki");
		this.uf5Cd = m.get("uf5_cd");
		this.uf5NameRyakushiki = m.get("uf5_name_ryakushiki");
		this.uf6Cd = m.get("uf6_cd");
		this.uf6NameRyakushiki = m.get("uf6_name_ryakushiki");
		this.uf7Cd = m.get("uf7_cd");
		this.uf7NameRyakushiki = m.get("uf7_name_ryakushiki");
		this.uf8Cd = m.get("uf8_cd");
		this.uf8NameRyakushiki = m.get("uf8_name_ryakushiki");
		this.uf9Cd = m.get("uf9_cd");
		this.uf9NameRyakushiki = m.get("uf9_name_ryakushiki");
		this.uf10Cd = m.get("uf10_cd");
		this.uf10NameRyakushiki = m.get("uf10_name_ryakushiki");
		this.projectCd = m.get("project_cd");
		this.projectName = m.get("project_name");
		this.segmentCd = m.get("segment_cd");
		this.segmentNameRyakushiki = m.get("segment_name_ryakushiki");
		this.tekiyouCd = m.get("tekiyou_cd");
		this.himodukeCardMeisai = m.get("himoduke_card_meisai");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.shiharaisakiName = m.get("shiharaisaki_name");
		this.jigyoushaKbn = m.get("jigyousha_kbn");
		this.bunriKbn = m.get("bunri_kbn");
		this.kariShiireKbn = m.get("kari_shiire_kbn");
		this.kashiShiireKbn = m.get("kashi_shiire_kbn");
		this.map = m;
	}

	/** 伝票ID */
	public String denpyouId;

	/** 伝票枝番号 */
	public int denpyouEdano;

	/** 海外フラグ */
	public String kaigaiFlg;

	/** 仕訳枝番号 */
	public int shiwakeEdano;

	/** 使用日 */
	public Date shiyoubi;

	/** 証憑書類フラグ */
	public String shouhyouShoruiFlg;

	/** 取引名 */
	public String torihikiName;

	/** 摘要 */
	public String tekiyou;

	/** 税率 */
	public BigDecimal zeiritsu;

	/** 軽減税率区分 */
	public String keigenZeiritsuKbn;

	/** 課税フラグ */
	public String kazeiFlg;

	/** 支払金額 */
	public BigDecimal shiharaiKingaku;

	/** 本体金額 */
	public BigDecimal hontaiKingaku;

	/** 消費税額 */
	public BigDecimal shouhizeigaku;

	/** 法人カード利用フラグ */
	public String houjinCardRiyouFlg;

	/** 会社手配フラグ */
	public String kaishaTehaiFlg;

	/** 交際費詳細表示フラグ */
	public String kousaihiShousaiHyoujiFlg;

	/** 人数項目表示フラグ */
	public String kousaihiNinzuuRiyouFlg;

	/** 交際費詳細 */
	public String kousaihiShousai;

	/** 交際費人数 */
	public Integer kousaihiNinzuu;

	/** 交際費一人あたり金額 */
	public BigDecimal kousaihiHitoriKingaku;

	/** 幣種コード */
	public String heishuCd;

	/** レート */
	public BigDecimal rate;

	/** 外貨金額 */
	public BigDecimal gaika;

	/** 通貨単位 */
	public String currencyUnit;

	/** 借方負担部門コード */
	public String kariFutanBumonCd;

	/** 借方負担部門名 */
	public String kariFutanBumonName;

	/** 取引先コード */
	public String torihikisakiCd;

	/** 取引先名（略式） */
	public String torihikisakiNameRyakushiki;

	/** 借方科目コード */
	public String kariKamokuCd;

	/** 借方科目名 */
	public String kariKamokuName;

	/** 借方科目枝番コード */
	public String kariKamokuEdabanCd;

	/** 借方科目枝番名 */
	public String kariKamokuEdabanName;

	/** 借方課税区分 */
	public String kariKazeiKbn;

	/** 貸方負担部門コード */
	public String kashiFutanBumonCd;

	/** 貸方負担部門名 */
	public String kashiFutanBumonName;

	/** 貸方科目コード */
	public String kashiKamokuCd;

	/** 貸方科目名 */
	public String kashiKamokuName;

	/** 貸方科目枝番コード */
	public String kashiKamokuEdabanCd;

	/** 貸方科目枝番名 */
	public String kashiKamokuEdabanName;

	/** 貸方課税区分 */
	public String kashiKazeiKbn;

	/** UF1コード */
	public String uf1Cd;

	/** UF1名（略式） */
	public String uf1NameRyakushiki;

	/** UF2コード */
	public String uf2Cd;

	/** UF2名（略式） */
	public String uf2NameRyakushiki;

	/** UF3コード */
	public String uf3Cd;

	/** UF3名（略式） */
	public String uf3NameRyakushiki;

	/** UF4コード */
	public String uf4Cd;

	/** UF4名（略式） */
	public String uf4NameRyakushiki;

	/** UF5コード */
	public String uf5Cd;

	/** UF5名（略式） */
	public String uf5NameRyakushiki;

	/** UF6コード */
	public String uf6Cd;

	/** UF6名（略式） */
	public String uf6NameRyakushiki;

	/** UF7コード */
	public String uf7Cd;

	/** UF7名（略式） */
	public String uf7NameRyakushiki;

	/** UF8コード */
	public String uf8Cd;

	/** UF8名（略式） */
	public String uf8NameRyakushiki;

	/** UF9コード */
	public String uf9Cd;

	/** UF9名（略式） */
	public String uf9NameRyakushiki;

	/** UF10コード */
	public String uf10Cd;

	/** UF10名（略式） */
	public String uf10NameRyakushiki;

	/** プロジェクトコード */
	public String projectCd;

	/** プロジェクト名 */
	public String projectName;

	/** セグメントコード */
	public String segmentCd;

	/** セグメント名（略式） */
	public String segmentNameRyakushiki;

	/** 摘要コード */
	public String tekiyouCd;

	/** 紐付元カード明細 */
	public Long himodukeCardMeisai;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** 支払先名 */
	public String shiharaisakiName;

	/** 事業者区分 */
	public String jigyoushaKbn;

	/** 分離区分 */
	public String bunriKbn;

	/** 借方仕入区分 */
	public String kariShiireKbn;

	/** 貸方仕入区分 */
	public String kashiShiireKbn;

	/** その他項目map */
	public GMap map;
}