package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 科目マスターDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KamokuMaster implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KamokuMaster() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KamokuMaster(GMap m) {
		this.kamokuGaibuCd = m.get("kamoku_gaibu_cd");
		this.kamokuNaibuCd = m.get("kamoku_naibu_cd");
		this.kamokuNameRyakushiki = m.get("kamoku_name_ryakushiki");
		this.kamokuNameSeishiki = m.get("kamoku_name_seishiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.chouhyouShaturyokuNo = m.get("chouhyou_shaturyoku_no");
		this.taishakuZokusei = m.get("taishaku_zokusei");
		this.kamokuGroupKbn = m.get("kamoku_group_kbn");
		this.kamokuGroupBangou = m.get("kamoku_group_bangou");
		this.shoriGroup = m.get("shori_group");
		this.taikakingakuNyuuryokuFlg = m.get("taikakingaku_nyuuryoku_flg");
		this.kazeiKbn = m.get("kazei_kbn");
		this.bunriKbn = m.get("bunri_kbn");
		this.shiireKbn = m.get("shiire_kbn");
		this.gyoushaKbn = m.get("gyousha_kbn");
		this.zeiritsuKbn = m.get("zeiritsu_kbn");
		this.tokushaHyoujiKbn = m.get("tokusha_hyouji_kbn");
		this.edabanMinyuuryokuCheck = m.get("edaban_minyuuryoku_check");
		this.torihikisakiMinyuuryokuCheck = m.get("torihikisaki_minyuuryoku_check");
		this.bumonMinyuuryokuCheck = m.get("bumon_minyuuryoku_check");
		this.bumonEdabanFlg = m.get("bumon_edaban_flg");
		this.segmentMinyuuryokuCheck = m.get("segment_minyuuryoku_check");
		this.projectMinyuuryokuCheck = m.get("project_minyuuryoku_check");
		this.uf1MinyuuryokuCheck = m.get("uf1_minyuuryoku_check");
		this.uf2MinyuuryokuCheck = m.get("uf2_minyuuryoku_check");
		this.uf3MinyuuryokuCheck = m.get("uf3_minyuuryoku_check");
		this.uf4MinyuuryokuCheck = m.get("uf4_minyuuryoku_check");
		this.uf5MinyuuryokuCheck = m.get("uf5_minyuuryoku_check");
		this.uf6MinyuuryokuCheck = m.get("uf6_minyuuryoku_check");
		this.uf7MinyuuryokuCheck = m.get("uf7_minyuuryoku_check");
		this.uf8MinyuuryokuCheck = m.get("uf8_minyuuryoku_check");
		this.uf9MinyuuryokuCheck = m.get("uf9_minyuuryoku_check");
		this.uf10MinyuuryokuCheck = m.get("uf10_minyuuryoku_check");
		this.ufKotei1MinyuuryokuCheck = m.get("uf_kotei1_minyuuryoku_check");
		this.ufKotei2MinyuuryokuCheck = m.get("uf_kotei2_minyuuryoku_check");
		this.ufKotei3MinyuuryokuCheck = m.get("uf_kotei3_minyuuryoku_check");
		this.ufKotei4MinyuuryokuCheck = m.get("uf_kotei4_minyuuryoku_check");
		this.ufKotei5MinyuuryokuCheck = m.get("uf_kotei5_minyuuryoku_check");
		this.ufKotei6MinyuuryokuCheck = m.get("uf_kotei6_minyuuryoku_check");
		this.ufKotei7MinyuuryokuCheck = m.get("uf_kotei7_minyuuryoku_check");
		this.ufKotei8MinyuuryokuCheck = m.get("uf_kotei8_minyuuryoku_check");
		this.ufKotei9MinyuuryokuCheck = m.get("uf_kotei9_minyuuryoku_check");
		this.ufKotei10MinyuuryokuCheck = m.get("uf_kotei10_minyuuryoku_check");
		this.koujiMinyuuryokuCheck = m.get("kouji_minyuuryoku_check");
		this.koushaMinyuuryokuCheck = m.get("kousha_minyuuryoku_check");
		this.tekiyouCdMinyuuryokuCheck = m.get("tekiyou_cd_minyuuryoku_check");
		this.bumonTorhikisakiKamokuFlg = m.get("bumon_torhikisaki_kamoku_flg");
		this.bumonTorihikisakiEdabanShiyouFlg = m.get("bumon_torihikisaki_edaban_shiyou_flg");
		this.torihikisakiKamokuEdabanFlg = m.get("torihikisaki_kamoku_edaban_flg");
		this.segmentTorihikisakiKamokuFlg = m.get("segment_torihikisaki_kamoku_flg");
		this.karikanjouKeshikomiNoFlg = m.get("karikanjou_keshikomi_no_flg");
		this.gaikaFlg = m.get("gaika_flg");
		this.map = m;
	}

	/** 科目外部コード */
	public String kamokuGaibuCd;

	/** 科目内部コード */
	public String kamokuNaibuCd;

	/** 科目名（略式） */
	public String kamokuNameRyakushiki;

	/** 科目名（正式） */
	public String kamokuNameSeishiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** 帳票出力順番号 */
	public Integer chouhyouShaturyokuNo;

	/** 貸借属性 */
	public Integer taishakuZokusei;

	/** 科目グループ区分 */
	public Integer kamokuGroupKbn;

	/** 科目グループ番号 */
	public Integer kamokuGroupBangou;

	/** 処理グループ */
	public Integer shoriGroup;

	/** 対価金額入力フラグ */
	public Integer taikakingakuNyuuryokuFlg;

	/** 課税区分 */
	public Integer kazeiKbn;

	/** 分離区分 */
	public Integer bunriKbn;

	/** 仕入区分 */
	public Integer shiireKbn;

	/** 業種区分 */
	public Integer gyoushaKbn;

	/** 税率区分 */
	public Integer zeiritsuKbn;

	/** 特殊表示区分 */
	public Integer tokushaHyoujiKbn;

	/** 枝番未入力チェック */
	public Integer edabanMinyuuryokuCheck;

	/** 取引先未入力チェック */
	public Integer torihikisakiMinyuuryokuCheck;

	/** 部門未入力チェック */
	public Integer bumonMinyuuryokuCheck;

	/** 部門科目枝番使用フラグ */
	public Integer bumonEdabanFlg;

	/** セグメント未入力チェック */
	public Integer segmentMinyuuryokuCheck;

	/** プロジェクト未入力チェック */
	public Integer projectMinyuuryokuCheck;

	/** ユニバーサルフィールド１未入力チェック */
	public Integer uf1MinyuuryokuCheck;

	/** ユニバーサルフィールド２未入力チェック */
	public Integer uf2MinyuuryokuCheck;

	/** ユニバーサルフィールド３未入力チェック */
	public Integer uf3MinyuuryokuCheck;

	/** ユニバーサルフィールド４未入力チェック */
	public Integer uf4MinyuuryokuCheck;

	/** ユニバーサルフィールド５未入力チェック */
	public Integer uf5MinyuuryokuCheck;

	/** ユニバーサルフィールド６未入力チェック */
	public Integer uf6MinyuuryokuCheck;

	/** ユニバーサルフィールド７未入力チェック */
	public Integer uf7MinyuuryokuCheck;

	/** ユニバーサルフィールド８未入力チェック */
	public Integer uf8MinyuuryokuCheck;

	/** ユニバーサルフィールド９未入力チェック */
	public Integer uf9MinyuuryokuCheck;

	/** ユニバーサルフィールド１０未入力チェック */
	public Integer uf10MinyuuryokuCheck;

	/** ユニバーサルフィールド１未入力チェック(固定値) */
	public Integer ufKotei1MinyuuryokuCheck;

	/** ユニバーサルフィールド２未入力チェック(固定値) */
	public Integer ufKotei2MinyuuryokuCheck;

	/** ユニバーサルフィールド３未入力チェック(固定値) */
	public Integer ufKotei3MinyuuryokuCheck;

	/** ユニバーサルフィールド４未入力チェック(固定値) */
	public Integer ufKotei4MinyuuryokuCheck;

	/** ユニバーサルフィールド５未入力チェック(固定値) */
	public Integer ufKotei5MinyuuryokuCheck;

	/** ユニバーサルフィールド６未入力チェック(固定値) */
	public Integer ufKotei6MinyuuryokuCheck;

	/** ユニバーサルフィールド７未入力チェック(固定値) */
	public Integer ufKotei7MinyuuryokuCheck;

	/** ユニバーサルフィールド８未入力チェック(固定値) */
	public Integer ufKotei8MinyuuryokuCheck;

	/** ユニバーサルフィールド９未入力チェック(固定値) */
	public Integer ufKotei9MinyuuryokuCheck;

	/** ユニバーサルフィールド１０未入力チェック(固定値) */
	public Integer ufKotei10MinyuuryokuCheck;

	/** 工事未入力チェック */
	public Integer koujiMinyuuryokuCheck;

	/** 工種未入力チェック */
	public Integer koushaMinyuuryokuCheck;

	/** 摘要コード未入力チェック */
	public Integer tekiyouCdMinyuuryokuCheck;

	/** 部門取引先科目使用フラグ */
	public Integer bumonTorhikisakiKamokuFlg;

	/** 部門取引先科目枝番使用フラグ */
	public Integer bumonTorihikisakiEdabanShiyouFlg;

	/** 取引先科目枝番使用フラグ */
	public Integer torihikisakiKamokuEdabanFlg;

	/** セグメント取引先科目使用フラグ */
	public Integer segmentTorihikisakiKamokuFlg;

	/** 仮勘定消込No使用フラグ */
	public Integer karikanjouKeshikomiNoFlg;

	/** 外貨使用フラグ */
	public Integer gaikaFlg;

	/** その他項目map */
	public GMap map;
}
