package eteam.database.dto;

import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 届出ジェネレータバージョンDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KaniTodokeVersion implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KaniTodokeVersion() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KaniTodokeVersion(GMap m) {
		this.denpyouKbn = m.get("denpyou_kbn");
		this.version = m.get("version");
		this.denpyouShubetsu = m.get("denpyou_shubetsu");
		this.naiyou = m.get("naiyou");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.map = m;
	}

	/** 伝票区分 */
	public String denpyouKbn;

	/** バージョン */
	public int version;

	/** 伝票種別 */
	public String denpyouShubetsu;

	/** 内容（伝票） */
	public String naiyou;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** その他項目map */
	public GMap map;
}
