package eteam.database.dto;

import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 届出ジェネレータ項目マスターDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KaniTodokeMaster implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KaniTodokeMaster() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KaniTodokeMaster(GMap m) {
		this.denpyouKbn = m.get("denpyou_kbn");
		this.version = m.get("version");
		this.areaKbn = m.get("area_kbn");
		this.itemName = m.get("item_name");
		this.labelName = m.get("label_name");
		this.hissuFlg = m.get("hissu_flg");
		this.masterKbn = m.get("master_kbn");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.map = m;
	}

	/** 伝票区分 */
	public String denpyouKbn;

	/** バージョン */
	public int version;

	/** エリア区分 */
	public String areaKbn;

	/** 項目名 */
	public String itemName;

	/** ラベル名 */
	public String labelName;

	/** 必須フラグ */
	public String hissuFlg;

	/** マスター区分 */
	public String masterKbn;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** その他項目map */
	public GMap map;
}
