package eteam.database.dto;

import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 届出ジェネレータ項目テキストエリアDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KaniTodokeTextarea implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KaniTodokeTextarea() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KaniTodokeTextarea(GMap m) {
		this.denpyouKbn = m.get("denpyou_kbn");
		this.version = m.get("version");
		this.areaKbn = m.get("area_kbn");
		this.itemName = m.get("item_name");
		this.labelName = m.get("label_name");
		this.hissuFlg = m.get("hissu_flg");
		this.buhinWidth = m.get("buhin_width");
		this.buhinHeight = m.get("buhin_height");
		this.maxLength = m.get("max_length");
		this.koteiHyouji = m.get("kotei_hyouji");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.map = m;
	}

	/** 伝票区分 */
	public String denpyouKbn;

	/** バージョン */
	public int version;

	/** エリア区分 */
	public String areaKbn;

	/** 項目名 */
	public String itemName;

	/** ラベル名 */
	public String labelName;

	/** 必須フラグ */
	public String hissuFlg;

	/** 部品幅 */
	public String buhinWidth;

	/** 部品高さ */
	public String buhinHeight;

	/** 最大桁数 */
	public int maxLength;

	/** 固定表示フラグ */
	public String koteiHyouji;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** その他項目map */
	public GMap map;
}
