package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 届出ジェネレータ一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KaniTodokeIchiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KaniTodokeIchiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KaniTodokeIchiran(GMap m) {
		this.denpyouId = m.get("denpyou_id");
		this.shinsei01 = m.get("shinsei01");
		this.shinsei02 = m.get("shinsei02");
		this.shinsei03 = m.get("shinsei03");
		this.shinsei04 = m.get("shinsei04");
		this.shinsei05 = m.get("shinsei05");
		this.shinsei06 = m.get("shinsei06");
		this.shinsei07 = m.get("shinsei07");
		this.shinsei08 = m.get("shinsei08");
		this.shinsei09 = m.get("shinsei09");
		this.shinsei10 = m.get("shinsei10");
		this.shinsei11 = m.get("shinsei11");
		this.shinsei12 = m.get("shinsei12");
		this.shinsei13 = m.get("shinsei13");
		this.shinsei14 = m.get("shinsei14");
		this.shinsei15 = m.get("shinsei15");
		this.shinsei16 = m.get("shinsei16");
		this.shinsei17 = m.get("shinsei17");
		this.shinsei18 = m.get("shinsei18");
		this.shinsei19 = m.get("shinsei19");
		this.shinsei20 = m.get("shinsei20");
		this.shinsei21 = m.get("shinsei21");
		this.shinsei22 = m.get("shinsei22");
		this.shinsei23 = m.get("shinsei23");
		this.shinsei24 = m.get("shinsei24");
		this.shinsei25 = m.get("shinsei25");
		this.shinsei26 = m.get("shinsei26");
		this.shinsei27 = m.get("shinsei27");
		this.shinsei28 = m.get("shinsei28");
		this.shinsei29 = m.get("shinsei29");
		this.shinsei30 = m.get("shinsei30");
		this.map = m;
	}

	/** 伝票ID */
	public String denpyouId;

	/** 申請内容01 */
	public String shinsei01;

	/** 申請内容02 */
	public String shinsei02;

	/** 申請内容03 */
	public String shinsei03;

	/** 申請内容04 */
	public String shinsei04;

	/** 申請内容05 */
	public String shinsei05;

	/** 申請内容06 */
	public String shinsei06;

	/** 申請内容07 */
	public String shinsei07;

	/** 申請内容08 */
	public String shinsei08;

	/** 申請内容09 */
	public String shinsei09;

	/** 申請内容10 */
	public String shinsei10;

	/** 申請内容11 */
	public String shinsei11;

	/** 申請内容12 */
	public String shinsei12;

	/** 申請内容13 */
	public String shinsei13;

	/** 申請内容14 */
	public String shinsei14;

	/** 申請内容15 */
	public String shinsei15;

	/** 申請内容16 */
	public String shinsei16;

	/** 申請内容17 */
	public String shinsei17;

	/** 申請内容18 */
	public String shinsei18;

	/** 申請内容19 */
	public String shinsei19;

	/** 申請内容20 */
	public String shinsei20;

	/** 申請内容21 */
	public String shinsei21;

	/** 申請内容22 */
	public String shinsei22;

	/** 申請内容23 */
	public String shinsei23;

	/** 申請内容24 */
	public String shinsei24;

	/** 申請内容25 */
	public String shinsei25;

	/** 申請内容26 */
	public String shinsei26;

	/** 申請内容27 */
	public String shinsei27;

	/** 申請内容28 */
	public String shinsei28;

	/** 申請内容29 */
	public String shinsei29;

	/** 申請内容30 */
	public String shinsei30;

	/** その他項目map */
	public GMap map;
}
