package eteam.database.dto;

import java.sql.Date;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 起案番号簿DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KianBangouBo implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KianBangouBo() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KianBangouBo(GMap m) {
		this.bumonCd = m.get("bumon_cd");
		this.nendo = m.get("nendo");
		this.ryakugou = m.get("ryakugou");
		this.kianBangouFrom = m.get("kian_bangou_from");
		this.kianBangouTo = m.get("kian_bangou_to");
		this.kbnNaiyou = m.get("kbn_naiyou");
		this.kianbangouBoSentakuHyoujiFlg = m.get("kianbangou_bo_sentaku_hyouji_flg");
		this.denpyouKensakuHyoujiFlg = m.get("denpyou_kensaku_hyouji_flg");
		this.yuukouKigenFrom = m.get("yuukou_kigen_from");
		this.yuukouKigenTo = m.get("yuukou_kigen_to");
		this.hyoujiJun = m.get("hyouji_jun");
		this.map = m;
	}

	/** 部門コード */
	public String bumonCd;

	/** 年度 */
	public String nendo;

	/** 略号 */
	public String ryakugou;

	/** 開始起案番号 */
	public int kianBangouFrom;

	/** 終了起案番号 */
	public int kianBangouTo;

	/** 区分内容 */
	public String kbnNaiyou;

	/** 起案番号簿選択表示フラグ */
	public String kianbangouBoSentakuHyoujiFlg;

	/** 伝票検索表示フラグ */
	public String denpyouKensakuHyoujiFlg;

	/** 有効期限開始日 */
	public Date yuukouKigenFrom;

	/** 有効期限終了日 */
	public Date yuukouKigenTo;

	/** 表示順 */
	public int hyoujiJun;

	/** その他項目map */
	public GMap map;
}
