package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * （期別）科目DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class KiKamoku implements IEteamDTO {

	/**
	 * default constructor
	 */
	public KiKamoku() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public KiKamoku(GMap m) {
		this.kesn = m.get("kesn");
		this.kamokuNaibuCd = m.get("kamoku_naibu_cd");
		this.kamokuGaibuCd = m.get("kamoku_gaibu_cd");
		this.kamokuNameRyakushiki = m.get("kamoku_name_ryakushiki");
		this.taishakuZokusei = m.get("taishaku_zokusei");
		this.map = m;
	}

	/** 内部決算期 */
	public int kesn;

	/** 科目内部コード */
	public String kamokuNaibuCd;

	/** 科目外部コード */
	public String kamokuGaibuCd;

	/** 科目名（略式） */
	public String kamokuNameRyakushiki;

	/** 貸借属性 */
	public int taishakuZokusei;

	/** その他項目map */
	public GMap map;
}
