package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 一覧表示項目制御DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class ListItemControl implements IEteamDTO {

	/**
	 * default constructor
	 */
	public ListItemControl() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public ListItemControl(GMap m) {
		this.kbn = m.get("kbn");
		this.userId = m.get("user_id");
		this.gyoumuRoleId = m.get("gyoumu_role_id");
		this.index = m.get("index");
		this.name = m.get("name");
		this.displayFlg = m.get("display_flg");
		this.map = m;
	}

	/** 表示項目区分 */
	public String kbn;

	/** ユーザーID */
	public String userId;

	/** 業務ロールID */
	public String gyoumuRoleId;

	/** 項番 */
	public int index;

	/** 項目名 */
	public String name;

	/** 表示フラグ */
	public String displayFlg;

	/** その他項目map */
	public GMap map;
}
