package eteam.database.dto;

import java.math.BigDecimal;
import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 支払依頼明細DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class ShiharaiIraiMeisai implements IEteamDTO {

	/**
	 * default constructor
	 */
	public ShiharaiIraiMeisai() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public ShiharaiIraiMeisai(GMap m) {
		this.denpyouId = m.get("denpyou_id");
		this.denpyouEdano = m.get("denpyou_edano");
		this.shiwakeEdano = m.get("shiwake_edano");
		this.torihikiName = m.get("torihiki_name");
		this.tekiyou = m.get("tekiyou");
		this.shiharaiKingaku = m.get("shiharai_kingaku");
		this.kariFutanBumonCd = m.get("kari_futan_bumon_cd");
		this.kariFutanBumonName = m.get("kari_futan_bumon_name");
		this.kariKamokuCd = m.get("kari_kamoku_cd");
		this.kariKamokuName = m.get("kari_kamoku_name");
		this.kariKamokuEdabanCd = m.get("kari_kamoku_edaban_cd");
		this.kariKamokuEdabanName = m.get("kari_kamoku_edaban_name");
		this.kariKazeiKbn = m.get("kari_kazei_kbn");
		this.zeiritsu = m.get("zeiritsu");
		this.keigenZeiritsuKbn = m.get("keigen_zeiritsu_kbn");
		this.uf1Cd = m.get("uf1_cd");
		this.uf1NameRyakushiki = m.get("uf1_name_ryakushiki");
		this.uf2Cd = m.get("uf2_cd");
		this.uf2NameRyakushiki = m.get("uf2_name_ryakushiki");
		this.uf3Cd = m.get("uf3_cd");
		this.uf3NameRyakushiki = m.get("uf3_name_ryakushiki");
		this.uf4Cd = m.get("uf4_cd");
		this.uf4NameRyakushiki = m.get("uf4_name_ryakushiki");
		this.uf5Cd = m.get("uf5_cd");
		this.uf5NameRyakushiki = m.get("uf5_name_ryakushiki");
		this.uf6Cd = m.get("uf6_cd");
		this.uf6NameRyakushiki = m.get("uf6_name_ryakushiki");
		this.uf7Cd = m.get("uf7_cd");
		this.uf7NameRyakushiki = m.get("uf7_name_ryakushiki");
		this.uf8Cd = m.get("uf8_cd");
		this.uf8NameRyakushiki = m.get("uf8_name_ryakushiki");
		this.uf9Cd = m.get("uf9_cd");
		this.uf9NameRyakushiki = m.get("uf9_name_ryakushiki");
		this.uf10Cd = m.get("uf10_cd");
		this.uf10NameRyakushiki = m.get("uf10_name_ryakushiki");
		this.projectCd = m.get("project_cd");
		this.projectName = m.get("project_name");
		this.segmentCd = m.get("segment_cd");
		this.segmentNameRyakushiki = m.get("segment_name_ryakushiki");
		this.tekiyouCd = m.get("tekiyou_cd");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.bunriKbn = m.get("bunri_kbn");
		this.kariShiireKbn = m.get("kari_shiire_kbn");
		this.zeinukiKingaku = m.get("zeinuki_kingaku");
		this.shouhizeigaku = m.get("shouhizeigaku");
		this.map = m;
	}

	/** 伝票ID */
	public String denpyouId;

	/** 伝票枝番号 */
	public int denpyouEdano;

	/** 仕訳枝番号 */
	public int shiwakeEdano;

	/** 取引名 */
	public String torihikiName;

	/** 摘要 */
	public String tekiyou;

	/** 支払金額 */
	public BigDecimal shiharaiKingaku;

	/** 借方負担部門コード */
	public String kariFutanBumonCd;

	/** 借方負担部門名 */
	public String kariFutanBumonName;

	/** 借方科目コード */
	public String kariKamokuCd;

	/** 借方科目名 */
	public String kariKamokuName;

	/** 借方科目枝番コード */
	public String kariKamokuEdabanCd;

	/** 借方科目枝番名 */
	public String kariKamokuEdabanName;

	/** 借方課税区分 */
	public String kariKazeiKbn;

	/** 税率 */
	public BigDecimal zeiritsu;

	/** 軽減税率区分 */
	public String keigenZeiritsuKbn;

	/** UF1コード */
	public String uf1Cd;

	/** UF1名（略式） */
	public String uf1NameRyakushiki;

	/** UF2コード */
	public String uf2Cd;

	/** UF2名（略式） */
	public String uf2NameRyakushiki;

	/** UF3コード */
	public String uf3Cd;

	/** UF3名（略式） */
	public String uf3NameRyakushiki;

	/** UF4コード */
	public String uf4Cd;

	/** UF4名（略式） */
	public String uf4NameRyakushiki;

	/** UF5コード */
	public String uf5Cd;

	/** UF5名（略式） */
	public String uf5NameRyakushiki;

	/** UF6コード */
	public String uf6Cd;

	/** UF6名（略式） */
	public String uf6NameRyakushiki;

	/** UF7コード */
	public String uf7Cd;

	/** UF7名（略式） */
	public String uf7NameRyakushiki;

	/** UF8コード */
	public String uf8Cd;

	/** UF8名（略式） */
	public String uf8NameRyakushiki;

	/** UF9コード */
	public String uf9Cd;

	/** UF9名（略式） */
	public String uf9NameRyakushiki;

	/** UF10コード */
	public String uf10Cd;

	/** UF10名（略式） */
	public String uf10NameRyakushiki;

	/** プロジェクトコード */
	public String projectCd;

	/** プロジェクト名 */
	public String projectName;

	/** セグメントコード */
	public String segmentCd;

	/** セグメント名（略式） */
	public String segmentNameRyakushiki;

	/** 摘要コード */
	public String tekiyouCd;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** 分離区分 */
	public String bunriKbn;

	/** 借方仕入区分 */
	public String kariShiireKbn;

	/** 税抜金額 */
	public BigDecimal zeinukiKingaku;

	/** 消費税額 */
	public BigDecimal shouhizeigaku;

	/** その他項目map */
	public GMap map;
}