package eteam.database.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 支払依頼DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class ShiharaiIrai implements IEteamDTO {

	/**
	 * default constructor
	 */
	public ShiharaiIrai() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public ShiharaiIrai(GMap m) {
		this.denpyouId = m.get("denpyou_id");
		this.keijoubi = m.get("keijoubi");
		this.yoteibi = m.get("yoteibi");
		this.shiharaibi = m.get("shiharaibi");
		this.shiharaiKijitsu = m.get("shiharai_kijitsu");
		this.torihikisakiCd = m.get("torihikisaki_cd");
		this.torihikisakiNameRyakushiki = m.get("torihikisaki_name_ryakushiki");
		this.ichigensakiTorihikisakiName = m.get("ichigensaki_torihikisaki_name");
		this.edi = m.get("edi");
		this.shiharaiGoukei = m.get("shiharai_goukei");
		this.sousaiGoukei = m.get("sousai_goukei");
		this.sashihikiShiharai = m.get("sashihiki_shiharai");
		this.manekinGensen = m.get("manekin_gensen");
		this.shouhyouShoruiFlg = m.get("shouhyou_shorui_flg");
		this.hf1Cd = m.get("hf1_cd");
		this.hf1NameRyakushiki = m.get("hf1_name_ryakushiki");
		this.hf2Cd = m.get("hf2_cd");
		this.hf2NameRyakushiki = m.get("hf2_name_ryakushiki");
		this.hf3Cd = m.get("hf3_cd");
		this.hf3NameRyakushiki = m.get("hf3_name_ryakushiki");
		this.hf4Cd = m.get("hf4_cd");
		this.hf4NameRyakushiki = m.get("hf4_name_ryakushiki");
		this.hf5Cd = m.get("hf5_cd");
		this.hf5NameRyakushiki = m.get("hf5_name_ryakushiki");
		this.hf6Cd = m.get("hf6_cd");
		this.hf6NameRyakushiki = m.get("hf6_name_ryakushiki");
		this.hf7Cd = m.get("hf7_cd");
		this.hf7NameRyakushiki = m.get("hf7_name_ryakushiki");
		this.hf8Cd = m.get("hf8_cd");
		this.hf8NameRyakushiki = m.get("hf8_name_ryakushiki");
		this.hf9Cd = m.get("hf9_cd");
		this.hf9NameRyakushiki = m.get("hf9_name_ryakushiki");
		this.hf10Cd = m.get("hf10_cd");
		this.hf10NameRyakushiki = m.get("hf10_name_ryakushiki");
		this.shiharaiHouhou = m.get("shiharai_houhou");
		this.shiharaiShubetsu = m.get("shiharai_shubetsu");
		this.furikomiGinkouCd = m.get("furikomi_ginkou_cd");
		this.furikomiGinkouName = m.get("furikomi_ginkou_name");
		this.furikomiGinkouShitenCd = m.get("furikomi_ginkou_shiten_cd");
		this.furikomiGinkouShitenName = m.get("furikomi_ginkou_shiten_name");
		this.yokinShubetsu = m.get("yokin_shubetsu");
		this.kouzaBangou = m.get("kouza_bangou");
		this.kouzaMeiginin = m.get("kouza_meiginin");
		this.tesuuryou = m.get("tesuuryou");
		this.hosoku = m.get("hosoku");
		this.gyakuShiwakeFlg = m.get("gyaku_shiwake_flg");
		this.shutsuryokuFlg = m.get("shutsuryoku_flg");
		this.csvUploadFlg = m.get("csv_upload_flg");
		this.hasseiShubetsu = m.get("hassei_shubetsu");
		this.saimuMadeFlg = m.get("saimu_made_flg");
		this.fbMadeFlg = m.get("fb_made_flg");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.nyuryokuHoushiki = m.get("nyuryoku_houshiki");
		this.jigyoushaKbn = m.get("jigyousha_kbn");
		this.jigyoushaNo = m.get("jigyousha_no");
		this.invoiceDenpyou = m.get("invoice_denpyou");
		this.map = m;
	}

	/** 伝票ID */
	public String denpyouId;

	/** 計上日 */
	public Date keijoubi;

	/** 予定日 */
	public Date yoteibi;

	/** 支払日 */
	public Date shiharaibi;

	/** 支払期日 */
	public Date shiharaiKijitsu;

	/** 取引先コード */
	public String torihikisakiCd;

	/** 取引先名（略式） */
	public String torihikisakiNameRyakushiki;

	/** 一見先取引先名 */
	public String ichigensakiTorihikisakiName;

	/** EDI */
	public String edi;

	/** 支払合計 */
	public BigDecimal shiharaiGoukei;

	/** 相殺合計 */
	public BigDecimal sousaiGoukei;

	/** 差引支払額 */
	public BigDecimal sashihikiShiharai;

	/** 控除項目 */
	public BigDecimal manekinGensen;

	/** 証憑書類フラグ */
	public String shouhyouShoruiFlg;

	/** HF1コード */
	public String hf1Cd;

	/** HF1名（略式） */
	public String hf1NameRyakushiki;

	/** HF2コード */
	public String hf2Cd;

	/** HF2名（略式） */
	public String hf2NameRyakushiki;

	/** HF3コード */
	public String hf3Cd;

	/** HF3名（略式） */
	public String hf3NameRyakushiki;

	/** HF4コード */
	public String hf4Cd;

	/** HF4名（略式） */
	public String hf4NameRyakushiki;

	/** HF5コード */
	public String hf5Cd;

	/** HF5名（略式） */
	public String hf5NameRyakushiki;

	/** HF6コード */
	public String hf6Cd;

	/** HF6名（略式） */
	public String hf6NameRyakushiki;

	/** HF7コード */
	public String hf7Cd;

	/** HF7名（略式） */
	public String hf7NameRyakushiki;

	/** HF8コード */
	public String hf8Cd;

	/** HF8名（略式） */
	public String hf8NameRyakushiki;

	/** HF9コード */
	public String hf9Cd;

	/** HF9名（略式） */
	public String hf9NameRyakushiki;

	/** HF10コード */
	public String hf10Cd;

	/** HF10名（略式） */
	public String hf10NameRyakushiki;

	/** 支払方法 */
	public String shiharaiHouhou;

	/** 支払種別 */
	public String shiharaiShubetsu;

	/** 振込銀行コード */
	public String furikomiGinkouCd;

	/** 振込銀行名称 */
	public String furikomiGinkouName;

	/** 振込銀行支店コード */
	public String furikomiGinkouShitenCd;

	/** 振込銀行支店名称 */
	public String furikomiGinkouShitenName;

	/** 預金種別 */
	public String yokinShubetsu;

	/** 口座番号 */
	public String kouzaBangou;

	/** 口座名義人 */
	public String kouzaMeiginin;

	/** 手数料 */
	public String tesuuryou;

	/** 補足 */
	public String hosoku;

	/** 逆仕訳フラグ */
	public String gyakuShiwakeFlg;

	/** 出力フラグ */
	public String shutsuryokuFlg;

	/** CSVアップロードフラグ */
	public String csvUploadFlg;

	/** 発生種別 */
	public String hasseiShubetsu;

	/** 債務支払データ作成済フラグ */
	public String saimuMadeFlg;

	/** FBデータ作成済フラグ */
	public String fbMadeFlg;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** 入力方式 */
	public String nyuryokuHoushiki;

	/** 事業者区分 */
	public String jigyoushaKbn;

	/** 事業者登録番号 */
	public String jigyoushaNo;

	/** インボイス対応伝票 */
	public String invoiceDenpyou;

	/** その他項目map */
	public GMap map;
}