package eteam.database.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 仕訳パターンマスターDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class ShiwakePatternMaster implements IEteamDTO {

	/**
	 * default constructor
	 */
	public ShiwakePatternMaster() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public ShiwakePatternMaster(GMap m) {
		this.denpyouKbn = m.get("denpyou_kbn");
		this.shiwakeEdano = m.get("shiwake_edano");
		this.deleteFlg = m.get("delete_flg");
		this.yuukouKigenFrom = m.get("yuukou_kigen_from");
		this.yuukouKigenTo = m.get("yuukou_kigen_to");
		this.bunrui1 = m.get("bunrui1");
		this.bunrui2 = m.get("bunrui2");
		this.bunrui3 = m.get("bunrui3");
		this.torihikiName = m.get("torihiki_name");
		this.tekiyouFlg = m.get("tekiyou_flg");
		this.tekiyou = m.get("tekiyou");
		this.defaultHyoujiFlg = m.get("default_hyouji_flg");
		this.kousaihiHyoujiFlg = m.get("kousaihi_hyouji_flg");
		this.kousaihiNinzuuRiyouFlg = m.get("kousaihi_ninzuu_riyou_flg");
		this.kousaihiKijunGaku = m.get("kousaihi_kijun_gaku");
		this.kousaihiCheckHouhou = m.get("kousaihi_check_houhou");
		this.kousaihiCheckResult = m.get("kousaihi_check_result");
		this.kakeFlg = m.get("kake_flg");
		this.hyoujiJun = m.get("hyouji_jun");
		this.shainCdRenkeiFlg = m.get("shain_cd_renkei_flg");
		this.edabanRenkeiFlg = m.get("edaban_renkei_flg");
		this.kariFutanBumonCd = m.get("kari_futan_bumon_cd");
		this.kariKamokuCd = m.get("kari_kamoku_cd");
		this.kariKamokuEdabanCd = m.get("kari_kamoku_edaban_cd");
		this.kariTorihikisakiCd = m.get("kari_torihikisaki_cd");
		this.kariProjectCd = m.get("kari_project_cd");
		this.kariSegmentCd = m.get("kari_segment_cd");
		this.kariUf1Cd = m.get("kari_uf1_cd");
		this.kariUf2Cd = m.get("kari_uf2_cd");
		this.kariUf3Cd = m.get("kari_uf3_cd");
		this.kariUf4Cd = m.get("kari_uf4_cd");
		this.kariUf5Cd = m.get("kari_uf5_cd");
		this.kariUf6Cd = m.get("kari_uf6_cd");
		this.kariUf7Cd = m.get("kari_uf7_cd");
		this.kariUf8Cd = m.get("kari_uf8_cd");
		this.kariUf9Cd = m.get("kari_uf9_cd");
		this.kariUf10Cd = m.get("kari_uf10_cd");
		this.kariUfKotei1Cd = m.get("kari_uf_kotei1_cd");
		this.kariUfKotei2Cd = m.get("kari_uf_kotei2_cd");
		this.kariUfKotei3Cd = m.get("kari_uf_kotei3_cd");
		this.kariUfKotei4Cd = m.get("kari_uf_kotei4_cd");
		this.kariUfKotei5Cd = m.get("kari_uf_kotei5_cd");
		this.kariUfKotei6Cd = m.get("kari_uf_kotei6_cd");
		this.kariUfKotei7Cd = m.get("kari_uf_kotei7_cd");
		this.kariUfKotei8Cd = m.get("kari_uf_kotei8_cd");
		this.kariUfKotei9Cd = m.get("kari_uf_kotei9_cd");
		this.kariUfKotei10Cd = m.get("kari_uf_kotei10_cd");
		this.kariKazeiKbn = m.get("kari_kazei_kbn");
		this.kariZeiritsu = m.get("kari_zeiritsu");
		this.kariKeigenZeiritsuKbn = m.get("kari_keigen_zeiritsu_kbn");
		this.kashiFutanBumonCd1 = m.get("kashi_futan_bumon_cd1");
		this.kashiKamokuCd1 = m.get("kashi_kamoku_cd1");
		this.kashiKamokuEdabanCd1 = m.get("kashi_kamoku_edaban_cd1");
		this.kashiTorihikisakiCd1 = m.get("kashi_torihikisaki_cd1");
		this.kashiProjectCd1 = m.get("kashi_project_cd1");
		this.kashiSegmentCd1 = m.get("kashi_segment_cd1");
		this.kashiUf1Cd1 = m.get("kashi_uf1_cd1");
		this.kashiUf2Cd1 = m.get("kashi_uf2_cd1");
		this.kashiUf3Cd1 = m.get("kashi_uf3_cd1");
		this.kashiUf4Cd1 = m.get("kashi_uf4_cd1");
		this.kashiUf5Cd1 = m.get("kashi_uf5_cd1");
		this.kashiUf6Cd1 = m.get("kashi_uf6_cd1");
		this.kashiUf7Cd1 = m.get("kashi_uf7_cd1");
		this.kashiUf8Cd1 = m.get("kashi_uf8_cd1");
		this.kashiUf9Cd1 = m.get("kashi_uf9_cd1");
		this.kashiUf10Cd1 = m.get("kashi_uf10_cd1");
		this.kashiUfKotei1Cd1 = m.get("kashi_uf_kotei1_cd1");
		this.kashiUfKotei2Cd1 = m.get("kashi_uf_kotei2_cd1");
		this.kashiUfKotei3Cd1 = m.get("kashi_uf_kotei3_cd1");
		this.kashiUfKotei4Cd1 = m.get("kashi_uf_kotei4_cd1");
		this.kashiUfKotei5Cd1 = m.get("kashi_uf_kotei5_cd1");
		this.kashiUfKotei6Cd1 = m.get("kashi_uf_kotei6_cd1");
		this.kashiUfKotei7Cd1 = m.get("kashi_uf_kotei7_cd1");
		this.kashiUfKotei8Cd1 = m.get("kashi_uf_kotei8_cd1");
		this.kashiUfKotei9Cd1 = m.get("kashi_uf_kotei9_cd1");
		this.kashiUfKotei10Cd1 = m.get("kashi_uf_kotei10_cd1");
		this.kashiKazeiKbn1 = m.get("kashi_kazei_kbn1");
		this.kashiFutanBumonCd2 = m.get("kashi_futan_bumon_cd2");
		this.kashiTorihikisakiCd2 = m.get("kashi_torihikisaki_cd2");
		this.kashiKamokuCd2 = m.get("kashi_kamoku_cd2");
		this.kashiKamokuEdabanCd2 = m.get("kashi_kamoku_edaban_cd2");
		this.kashiProjectCd2 = m.get("kashi_project_cd2");
		this.kashiSegmentCd2 = m.get("kashi_segment_cd2");
		this.kashiUf1Cd2 = m.get("kashi_uf1_cd2");
		this.kashiUf2Cd2 = m.get("kashi_uf2_cd2");
		this.kashiUf3Cd2 = m.get("kashi_uf3_cd2");
		this.kashiUf4Cd2 = m.get("kashi_uf4_cd2");
		this.kashiUf5Cd2 = m.get("kashi_uf5_cd2");
		this.kashiUf6Cd2 = m.get("kashi_uf6_cd2");
		this.kashiUf7Cd2 = m.get("kashi_uf7_cd2");
		this.kashiUf8Cd2 = m.get("kashi_uf8_cd2");
		this.kashiUf9Cd2 = m.get("kashi_uf9_cd2");
		this.kashiUf10Cd2 = m.get("kashi_uf10_cd2");
		this.kashiUfKotei1Cd2 = m.get("kashi_uf_kotei1_cd2");
		this.kashiUfKotei2Cd2 = m.get("kashi_uf_kotei2_cd2");
		this.kashiUfKotei3Cd2 = m.get("kashi_uf_kotei3_cd2");
		this.kashiUfKotei4Cd2 = m.get("kashi_uf_kotei4_cd2");
		this.kashiUfKotei5Cd2 = m.get("kashi_uf_kotei5_cd2");
		this.kashiUfKotei6Cd2 = m.get("kashi_uf_kotei6_cd2");
		this.kashiUfKotei7Cd2 = m.get("kashi_uf_kotei7_cd2");
		this.kashiUfKotei8Cd2 = m.get("kashi_uf_kotei8_cd2");
		this.kashiUfKotei9Cd2 = m.get("kashi_uf_kotei9_cd2");
		this.kashiUfKotei10Cd2 = m.get("kashi_uf_kotei10_cd2");
		this.kashiKazeiKbn2 = m.get("kashi_kazei_kbn2");
		this.kashiFutanBumonCd3 = m.get("kashi_futan_bumon_cd3");
		this.kashiTorihikisakiCd3 = m.get("kashi_torihikisaki_cd3");
		this.kashiKamokuCd3 = m.get("kashi_kamoku_cd3");
		this.kashiKamokuEdabanCd3 = m.get("kashi_kamoku_edaban_cd3");
		this.kashiProjectCd3 = m.get("kashi_project_cd3");
		this.kashiSegmentCd3 = m.get("kashi_segment_cd3");
		this.kashiUf1Cd3 = m.get("kashi_uf1_cd3");
		this.kashiUf2Cd3 = m.get("kashi_uf2_cd3");
		this.kashiUf3Cd3 = m.get("kashi_uf3_cd3");
		this.kashiUf4Cd3 = m.get("kashi_uf4_cd3");
		this.kashiUf5Cd3 = m.get("kashi_uf5_cd3");
		this.kashiUf6Cd3 = m.get("kashi_uf6_cd3");
		this.kashiUf7Cd3 = m.get("kashi_uf7_cd3");
		this.kashiUf8Cd3 = m.get("kashi_uf8_cd3");
		this.kashiUf9Cd3 = m.get("kashi_uf9_cd3");
		this.kashiUf10Cd3 = m.get("kashi_uf10_cd3");
		this.kashiUfKotei1Cd3 = m.get("kashi_uf_kotei1_cd3");
		this.kashiUfKotei2Cd3 = m.get("kashi_uf_kotei2_cd3");
		this.kashiUfKotei3Cd3 = m.get("kashi_uf_kotei3_cd3");
		this.kashiUfKotei4Cd3 = m.get("kashi_uf_kotei4_cd3");
		this.kashiUfKotei5Cd3 = m.get("kashi_uf_kotei5_cd3");
		this.kashiUfKotei6Cd3 = m.get("kashi_uf_kotei6_cd3");
		this.kashiUfKotei7Cd3 = m.get("kashi_uf_kotei7_cd3");
		this.kashiUfKotei8Cd3 = m.get("kashi_uf_kotei8_cd3");
		this.kashiUfKotei9Cd3 = m.get("kashi_uf_kotei9_cd3");
		this.kashiUfKotei10Cd3 = m.get("kashi_uf_kotei10_cd3");
		this.kashiKazeiKbn3 = m.get("kashi_kazei_kbn3");
		this.kashiFutanBumonCd4 = m.get("kashi_futan_bumon_cd4");
		this.kashiTorihikisakiCd4 = m.get("kashi_torihikisaki_cd4");
		this.kashiKamokuCd4 = m.get("kashi_kamoku_cd4");
		this.kashiKamokuEdabanCd4 = m.get("kashi_kamoku_edaban_cd4");
		this.kashiProjectCd4 = m.get("kashi_project_cd4");
		this.kashiSegmentCd4 = m.get("kashi_segment_cd4");
		this.kashiUf1Cd4 = m.get("kashi_uf1_cd4");
		this.kashiUf2Cd4 = m.get("kashi_uf2_cd4");
		this.kashiUf3Cd4 = m.get("kashi_uf3_cd4");
		this.kashiUf4Cd4 = m.get("kashi_uf4_cd4");
		this.kashiUf5Cd4 = m.get("kashi_uf5_cd4");
		this.kashiUf6Cd4 = m.get("kashi_uf6_cd4");
		this.kashiUf7Cd4 = m.get("kashi_uf7_cd4");
		this.kashiUf8Cd4 = m.get("kashi_uf8_cd4");
		this.kashiUf9Cd4 = m.get("kashi_uf9_cd4");
		this.kashiUf10Cd4 = m.get("kashi_uf10_cd4");
		this.kashiUfKotei1Cd4 = m.get("kashi_uf_kotei1_cd4");
		this.kashiUfKotei2Cd4 = m.get("kashi_uf_kotei2_cd4");
		this.kashiUfKotei3Cd4 = m.get("kashi_uf_kotei3_cd4");
		this.kashiUfKotei4Cd4 = m.get("kashi_uf_kotei4_cd4");
		this.kashiUfKotei5Cd4 = m.get("kashi_uf_kotei5_cd4");
		this.kashiUfKotei6Cd4 = m.get("kashi_uf_kotei6_cd4");
		this.kashiUfKotei7Cd4 = m.get("kashi_uf_kotei7_cd4");
		this.kashiUfKotei8Cd4 = m.get("kashi_uf_kotei8_cd4");
		this.kashiUfKotei9Cd4 = m.get("kashi_uf_kotei9_cd4");
		this.kashiUfKotei10Cd4 = m.get("kashi_uf_kotei10_cd4");
		this.kashiKazeiKbn4 = m.get("kashi_kazei_kbn4");
		this.kashiFutanBumonCd5 = m.get("kashi_futan_bumon_cd5");
		this.kashiTorihikisakiCd5 = m.get("kashi_torihikisaki_cd5");
		this.kashiKamokuCd5 = m.get("kashi_kamoku_cd5");
		this.kashiKamokuEdabanCd5 = m.get("kashi_kamoku_edaban_cd5");
		this.kashiProjectCd5 = m.get("kashi_project_cd5");
		this.kashiSegmentCd5 = m.get("kashi_segment_cd5");
		this.kashiUf1Cd5 = m.get("kashi_uf1_cd5");
		this.kashiUf2Cd5 = m.get("kashi_uf2_cd5");
		this.kashiUf3Cd5 = m.get("kashi_uf3_cd5");
		this.kashiUf4Cd5 = m.get("kashi_uf4_cd5");
		this.kashiUf5Cd5 = m.get("kashi_uf5_cd5");
		this.kashiUf6Cd5 = m.get("kashi_uf6_cd5");
		this.kashiUf7Cd5 = m.get("kashi_uf7_cd5");
		this.kashiUf8Cd5 = m.get("kashi_uf8_cd5");
		this.kashiUf9Cd5 = m.get("kashi_uf9_cd5");
		this.kashiUf10Cd5 = m.get("kashi_uf10_cd5");
		this.kashiUfKotei1Cd5 = m.get("kashi_uf_kotei1_cd5");
		this.kashiUfKotei2Cd5 = m.get("kashi_uf_kotei2_cd5");
		this.kashiUfKotei3Cd5 = m.get("kashi_uf_kotei3_cd5");
		this.kashiUfKotei4Cd5 = m.get("kashi_uf_kotei4_cd5");
		this.kashiUfKotei5Cd5 = m.get("kashi_uf_kotei5_cd5");
		this.kashiUfKotei6Cd5 = m.get("kashi_uf_kotei6_cd5");
		this.kashiUfKotei7Cd5 = m.get("kashi_uf_kotei7_cd5");
		this.kashiUfKotei8Cd5 = m.get("kashi_uf_kotei8_cd5");
		this.kashiUfKotei9Cd5 = m.get("kashi_uf_kotei9_cd5");
		this.kashiUfKotei10Cd5 = m.get("kashi_uf_kotei10_cd5");
		this.kashiKazeiKbn5 = m.get("kashi_kazei_kbn5");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.oldKariKazeiKbn = m.get("old_kari_kazei_kbn");
		this.oldKashiKazeiKbn1 = m.get("old_kashi_kazei_kbn1");
		this.oldKashiKazeiKbn2 = m.get("old_kashi_kazei_kbn2");
		this.oldKashiKazeiKbn3 = m.get("old_kashi_kazei_kbn3");
		this.oldKashiKazeiKbn4 = m.get("old_kashi_kazei_kbn4");
		this.oldKashiKazeiKbn5 = m.get("old_kashi_kazei_kbn5");
		this.kariBunriKbn = m.get("kari_bunri_kbn");
		this.kashiBunriKbn1 = m.get("kashi_bunri_kbn1");
		this.kashiBunriKbn2 = m.get("kashi_bunri_kbn2");
		this.kashiBunriKbn3 = m.get("kashi_bunri_kbn3");
		this.kashiBunriKbn4 = m.get("kashi_bunri_kbn4");
		this.kashiBunriKbn5 = m.get("kashi_bunri_kbn5");
		this.kariShiireKbn = m.get("kari_shiire_kbn");
		this.kashiShiireKbn1 = m.get("kashi_shiire_kbn1");
		this.kashiShiireKbn2 = m.get("kashi_shiire_kbn2");
		this.kashiShiireKbn3 = m.get("kashi_shiire_kbn3");
		this.kashiShiireKbn4 = m.get("kashi_shiire_kbn4");
		this.kashiShiireKbn5 = m.get("kashi_shiire_kbn5");
		this.map = m;
	}

	/** 伝票区分 */
	public String denpyouKbn;

	/** 仕訳枝番号 */
	public int shiwakeEdano;

	/** 削除フラグ */
	public String deleteFlg;

	/** 有効期限開始日 */
	public Date yuukouKigenFrom;

	/** 有効期限終了日 */
	public Date yuukouKigenTo;

	/** 分類1 */
	public String bunrui1;

	/** 分類2 */
	public String bunrui2;

	/** 分類3 */
	public String bunrui3;

	/** 取引名 */
	public String torihikiName;

	/** 摘要フラグ */
	public String tekiyouFlg;

	/** 摘要 */
	public String tekiyou;

	/** デフォルト表示フラグ */
	public String defaultHyoujiFlg;

	/** 交際費表示フラグ */
	public String kousaihiHyoujiFlg;

	/** 人数項目表示フラグ */
	public String kousaihiNinzuuRiyouFlg;

	/** 交際費基準額 */
	public BigDecimal kousaihiKijunGaku;

	/** 交際費チェック方法 */
	public String kousaihiCheckHouhou;

	/** 交際費チェック後登録許可 */
	public String kousaihiCheckResult;

	/** 掛けフラグ */
	public String kakeFlg;

	/** 表示順 */
	public int hyoujiJun;

	/** 社員コード連携フラグ */
	public String shainCdRenkeiFlg;

	/** 財務枝番コード連携フラグ */
	public String edabanRenkeiFlg;

	/** 借方負担部門コード（仕訳パターン） */
	public String kariFutanBumonCd;

	/** 借方科目コード（仕訳パターン） */
	public String kariKamokuCd;

	/** 借方科目枝番コード（仕訳パターン） */
	public String kariKamokuEdabanCd;

	/** 借方取引先コード（仕訳パターン） */
	public String kariTorihikisakiCd;

	/** 借方プロジェクトコード（仕訳パターン） */
	public String kariProjectCd;

	/** 借方セグメントコード */
	public String kariSegmentCd;

	/** 借方UF1コード */
	public String kariUf1Cd;

	/** 借方UF2コード */
	public String kariUf2Cd;

	/** 借方UF3コード */
	public String kariUf3Cd;

	/** 借方UF4コード */
	public String kariUf4Cd;

	/** 借方UF5コード */
	public String kariUf5Cd;

	/** 借方UF6コード */
	public String kariUf6Cd;

	/** 借方UF7コード */
	public String kariUf7Cd;

	/** 借方UF8コード */
	public String kariUf8Cd;

	/** 借方UF9コード */
	public String kariUf9Cd;

	/** 借方UF10コード */
	public String kariUf10Cd;

	/** 借方UF1コード（固定） */
	public String kariUfKotei1Cd;

	/** 借方UF2コード（固定） */
	public String kariUfKotei2Cd;

	/** 借方UF3コード（固定） */
	public String kariUfKotei3Cd;

	/** 借方UF4コード（固定） */
	public String kariUfKotei4Cd;

	/** 借方UF5コード（固定） */
	public String kariUfKotei5Cd;

	/** 借方UF6コード（固定） */
	public String kariUfKotei6Cd;

	/** 借方UF7コード（固定） */
	public String kariUfKotei7Cd;

	/** 借方UF8コード（固定） */
	public String kariUfKotei8Cd;

	/** 借方UF9コード（固定） */
	public String kariUfKotei9Cd;

	/** 借方UF10コード（固定） */
	public String kariUfKotei10Cd;

	/** 借方課税区分（仕訳パターン） */
	public String kariKazeiKbn;

	/** 借方消費税率（仕訳パターン） */
	public String kariZeiritsu;

	/** 借方軽減税率区分（仕訳パターン） */
	public String kariKeigenZeiritsuKbn;

	/** 貸方負担部門コード１（仕訳パターン） */
	public String kashiFutanBumonCd1;

	/** 貸方科目コード１（仕訳パターン） */
	public String kashiKamokuCd1;

	/** 貸方科目枝番コード１（仕訳パターン） */
	public String kashiKamokuEdabanCd1;

	/** 貸方取引先コード１（仕訳パターン） */
	public String kashiTorihikisakiCd1;

	/** 貸方プロジェクトコード１（仕訳パターン） */
	public String kashiProjectCd1;

	/** 貸方セグメントコード１（仕訳パターン） */
	public String kashiSegmentCd1;

	/** 貸方UF1コード１ */
	public String kashiUf1Cd1;

	/** 貸方UF2コード１ */
	public String kashiUf2Cd1;

	/** 貸方UF3コード１ */
	public String kashiUf3Cd1;

	/** 貸方UF4コード１ */
	public String kashiUf4Cd1;

	/** 貸方UF5コード１ */
	public String kashiUf5Cd1;

	/** 貸方UF6コード１ */
	public String kashiUf6Cd1;

	/** 貸方UF7コード１ */
	public String kashiUf7Cd1;

	/** 貸方UF8コード１ */
	public String kashiUf8Cd1;

	/** 貸方UF9コード１ */
	public String kashiUf9Cd1;

	/** 貸方UF10コード１ */
	public String kashiUf10Cd1;

	/** 貸方UF1コード１（固定） */
	public String kashiUfKotei1Cd1;

	/** 貸方UF2コード１（固定） */
	public String kashiUfKotei2Cd1;

	/** 貸方UF3コード１（固定） */
	public String kashiUfKotei3Cd1;

	/** 貸方UF4コード１（固定） */
	public String kashiUfKotei4Cd1;

	/** 貸方UF5コード１（固定） */
	public String kashiUfKotei5Cd1;

	/** 貸方UF6コード１（固定） */
	public String kashiUfKotei6Cd1;

	/** 貸方UF7コード１（固定） */
	public String kashiUfKotei7Cd1;

	/** 貸方UF8コード１（固定） */
	public String kashiUfKotei8Cd1;

	/** 貸方UF9コード１（固定） */
	public String kashiUfKotei9Cd1;

	/** 貸方UF10コード１（固定） */
	public String kashiUfKotei10Cd1;

	/** 貸方課税区分１（仕訳パターン） */
	public String kashiKazeiKbn1;

	/** 貸方負担部門コード２（仕訳パターン） */
	public String kashiFutanBumonCd2;

	/** 貸方取引先コード２（仕訳パターン） */
	public String kashiTorihikisakiCd2;

	/** 貸方科目コード２（仕訳パターン） */
	public String kashiKamokuCd2;

	/** 貸方科目枝番コード２（仕訳パターン） */
	public String kashiKamokuEdabanCd2;

	/** 貸方プロジェクトコード２（仕訳パターン） */
	public String kashiProjectCd2;

	/** 貸方セグメントコード２（仕訳パターン） */
	public String kashiSegmentCd2;

	/** 貸方UF1コード２ */
	public String kashiUf1Cd2;

	/** 貸方UF2コード２ */
	public String kashiUf2Cd2;

	/** 貸方UF3コード２ */
	public String kashiUf3Cd2;

	/** 貸方UF4コード２ */
	public String kashiUf4Cd2;

	/** 貸方UF5コード２ */
	public String kashiUf5Cd2;

	/** 貸方UF6コード２ */
	public String kashiUf6Cd2;

	/** 貸方UF7コード２ */
	public String kashiUf7Cd2;

	/** 貸方UF8コード２ */
	public String kashiUf8Cd2;

	/** 貸方UF9コード２ */
	public String kashiUf9Cd2;

	/** 貸方UF10コード２ */
	public String kashiUf10Cd2;

	/** 貸方UF1コード２（固定） */
	public String kashiUfKotei1Cd2;

	/** 貸方UF2コード２（固定） */
	public String kashiUfKotei2Cd2;

	/** 貸方UF3コード２（固定） */
	public String kashiUfKotei3Cd2;

	/** 貸方UF4コード２（固定） */
	public String kashiUfKotei4Cd2;

	/** 貸方UF5コード２（固定） */
	public String kashiUfKotei5Cd2;

	/** 貸方UF6コード２（固定） */
	public String kashiUfKotei6Cd2;

	/** 貸方UF7コード２（固定） */
	public String kashiUfKotei7Cd2;

	/** 貸方UF8コード２（固定） */
	public String kashiUfKotei8Cd2;

	/** 貸方UF9コード２（固定） */
	public String kashiUfKotei9Cd2;

	/** 貸方UF10コード２（固定） */
	public String kashiUfKotei10Cd2;

	/** 貸方課税区分２（仕訳パターン） */
	public String kashiKazeiKbn2;

	/** 貸方負担部門コード３（仕訳パターン） */
	public String kashiFutanBumonCd3;

	/** 貸方取引先コード３（仕訳パターン） */
	public String kashiTorihikisakiCd3;

	/** 貸方科目コード３（仕訳パターン） */
	public String kashiKamokuCd3;

	/** 貸方科目枝番コード３（仕訳パターン） */
	public String kashiKamokuEdabanCd3;

	/** 貸方プロジェクトコード３（仕訳パターン） */
	public String kashiProjectCd3;

	/** 貸方セグメントコード３（仕訳パターン） */
	public String kashiSegmentCd3;

	/** 貸方UF1コード３ */
	public String kashiUf1Cd3;

	/** 貸方UF2コード３ */
	public String kashiUf2Cd3;

	/** 貸方UF3コード３ */
	public String kashiUf3Cd3;

	/** 貸方UF4コード３ */
	public String kashiUf4Cd3;

	/** 貸方UF5コード３ */
	public String kashiUf5Cd3;

	/** 貸方UF6コード３ */
	public String kashiUf6Cd3;

	/** 貸方UF7コード３ */
	public String kashiUf7Cd3;

	/** 貸方UF8コード３ */
	public String kashiUf8Cd3;

	/** 貸方UF9コード３ */
	public String kashiUf9Cd3;

	/** 貸方UF10コード３ */
	public String kashiUf10Cd3;

	/** 貸方UF1コード３（固定） */
	public String kashiUfKotei1Cd3;

	/** 貸方UF2コード３（固定） */
	public String kashiUfKotei2Cd3;

	/** 貸方UF3コード３（固定） */
	public String kashiUfKotei3Cd3;

	/** 貸方UF4コード３（固定） */
	public String kashiUfKotei4Cd3;

	/** 貸方UF5コード３（固定） */
	public String kashiUfKotei5Cd3;

	/** 貸方UF6コード３（固定） */
	public String kashiUfKotei6Cd3;

	/** 貸方UF7コード３（固定） */
	public String kashiUfKotei7Cd3;

	/** 貸方UF8コード３（固定） */
	public String kashiUfKotei8Cd3;

	/** 貸方UF9コード３（固定） */
	public String kashiUfKotei9Cd3;

	/** 貸方UF10コード３（固定） */
	public String kashiUfKotei10Cd3;

	/** 貸方課税区分３（仕訳パターン） */
	public String kashiKazeiKbn3;

	/** 貸方負担部門コード４（仕訳パターン） */
	public String kashiFutanBumonCd4;

	/** 貸方取引先コード４（仕訳パターン） */
	public String kashiTorihikisakiCd4;

	/** 貸方科目コード４（仕訳パターン） */
	public String kashiKamokuCd4;

	/** 貸方科目枝番コード４（仕訳パターン） */
	public String kashiKamokuEdabanCd4;

	/** 貸方プロジェクトコード４（仕訳パターン） */
	public String kashiProjectCd4;

	/** 貸方セグメントコード４（仕訳パターン） */
	public String kashiSegmentCd4;

	/** 貸方UF1コード４ */
	public String kashiUf1Cd4;

	/** 貸方UF2コード４ */
	public String kashiUf2Cd4;

	/** 貸方UF3コード４ */
	public String kashiUf3Cd4;

	/** 貸方UF4コード４ */
	public String kashiUf4Cd4;

	/** 貸方UF5コード４ */
	public String kashiUf5Cd4;

	/** 貸方UF6コード４ */
	public String kashiUf6Cd4;

	/** 貸方UF7コード４ */
	public String kashiUf7Cd4;

	/** 貸方UF8コード４ */
	public String kashiUf8Cd4;

	/** 貸方UF9コード４ */
	public String kashiUf9Cd4;

	/** 貸方UF10コード４ */
	public String kashiUf10Cd4;

	/** 貸方UF1コード４（固定） */
	public String kashiUfKotei1Cd4;

	/** 貸方UF2コード４（固定） */
	public String kashiUfKotei2Cd4;

	/** 貸方UF3コード４（固定） */
	public String kashiUfKotei3Cd4;

	/** 貸方UF4コード４（固定） */
	public String kashiUfKotei4Cd4;

	/** 貸方UF5コード４（固定） */
	public String kashiUfKotei5Cd4;

	/** 貸方UF6コード４（固定） */
	public String kashiUfKotei6Cd4;

	/** 貸方UF7コード４（固定） */
	public String kashiUfKotei7Cd4;

	/** 貸方UF8コード４（固定） */
	public String kashiUfKotei8Cd4;

	/** 貸方UF9コード４（固定） */
	public String kashiUfKotei9Cd4;

	/** 貸方UF10コード４（固定） */
	public String kashiUfKotei10Cd4;

	/** 貸方課税区分４（仕訳パターン） */
	public String kashiKazeiKbn4;

	/** 貸方負担部門コード５（仕訳パターン） */
	public String kashiFutanBumonCd5;

	/** 貸方取引先コード５（仕訳パターン） */
	public String kashiTorihikisakiCd5;

	/** 貸方科目コード５（仕訳パターン） */
	public String kashiKamokuCd5;

	/** 貸方科目枝番コード５（仕訳パターン） */
	public String kashiKamokuEdabanCd5;

	/** 貸方プロジェクトコード５（仕訳パターン） */
	public String kashiProjectCd5;

	/** 貸方セグメントコード５（仕訳パターン） */
	public String kashiSegmentCd5;

	/** 貸方UF1コード５ */
	public String kashiUf1Cd5;

	/** 貸方UF2コード５ */
	public String kashiUf2Cd5;

	/** 貸方UF3コード５ */
	public String kashiUf3Cd5;

	/** 貸方UF4コード５ */
	public String kashiUf4Cd5;

	/** 貸方UF5コード５ */
	public String kashiUf5Cd5;

	/** 貸方UF6コード５ */
	public String kashiUf6Cd5;

	/** 貸方UF7コード５ */
	public String kashiUf7Cd5;

	/** 貸方UF8コード５ */
	public String kashiUf8Cd5;

	/** 貸方UF9コード５ */
	public String kashiUf9Cd5;

	/** 貸方UF10コード５ */
	public String kashiUf10Cd5;

	/** 貸方UF1コード５（固定） */
	public String kashiUfKotei1Cd5;

	/** 貸方UF2コード５（固定） */
	public String kashiUfKotei2Cd5;

	/** 貸方UF3コード５（固定） */
	public String kashiUfKotei3Cd5;

	/** 貸方UF4コード５（固定） */
	public String kashiUfKotei4Cd5;

	/** 貸方UF5コード５（固定） */
	public String kashiUfKotei5Cd5;

	/** 貸方UF6コード５（固定） */
	public String kashiUfKotei6Cd5;

	/** 貸方UF7コード５（固定） */
	public String kashiUfKotei7Cd5;

	/** 貸方UF8コード５（固定） */
	public String kashiUfKotei8Cd5;

	/** 貸方UF9コード５（固定） */
	public String kashiUfKotei9Cd5;

	/** 貸方UF10コード５（固定） */
	public String kashiUfKotei10Cd5;

	/** 貸方課税区分５（仕訳パターン） */
	public String kashiKazeiKbn5;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** 旧借方課税区分（仕訳パターン） */
	public String oldKariKazeiKbn;

	/** 旧貸方課税区分１（仕訳パターン） */
	public String oldKashiKazeiKbn1;

	/** 旧貸方課税区分２（仕訳パターン） */
	public String oldKashiKazeiKbn2;

	/** 旧貸方課税区分３（仕訳パターン） */
	public String oldKashiKazeiKbn3;

	/** 旧貸方課税区分４（仕訳パターン） */
	public String oldKashiKazeiKbn4;

	/** 旧貸方課税区分５（仕訳パターン） */
	public String oldKashiKazeiKbn5;

	/** 借方分離区分（仕訳パターン） */
	public String kariBunriKbn;

	/** 貸方分離区分１（仕訳パターン） */
	public String kashiBunriKbn1;

	/** 貸方分離区分２（仕訳パターン） */
	public String kashiBunriKbn2;

	/** 貸方分離区分３（仕訳パターン） */
	public String kashiBunriKbn3;

	/** 貸方分離区分４（仕訳パターン） */
	public String kashiBunriKbn4;

	/** 貸方分離区分５（仕訳パターン） */
	public String kashiBunriKbn5;

	/** 借方仕入区分（仕訳パターン） */
	public String kariShiireKbn;

	/** 貸方仕入区分１（仕訳パターン） */
	public String kashiShiireKbn1;

	/** 貸方仕入区分２（仕訳パターン） */
	public String kashiShiireKbn2;

	/** 貸方仕入区分３（仕訳パターン） */
	public String kashiShiireKbn3;

	/** 貸方仕入区分４（仕訳パターン） */
	public String kashiShiireKbn4;

	/** 貸方仕入区分５（仕訳パターン） */
	public String kashiShiireKbn5;

	/** その他項目map */
	public GMap map;
}