package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 承認ルート合議子DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class ShouninRouteGougiKo implements IEteamDTO {

	/**
	 * default constructor
	 */
	public ShouninRouteGougiKo() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public ShouninRouteGougiKo(GMap m) {
		this.denpyouId = m.get("denpyou_id");
		this.edano = m.get("edano");
		this.gougiEdano = m.get("gougi_edano");
		this.gougiEdaedano = m.get("gougi_edaedano");
		this.userId = m.get("user_id");
		this.userFullName = m.get("user_full_name");
		this.bumonCd = m.get("bumon_cd");
		this.bumonFullName = m.get("bumon_full_name");
		this.bumonRoleId = m.get("bumon_role_id");
		this.bumonRoleName = m.get("bumon_role_name");
		this.gougiGenzaiFlg = m.get("gougi_genzai_flg");
		this.shouninShoriKengenNo = m.get("shounin_shori_kengen_no");
		this.shouninShoriKengenName = m.get("shounin_shori_kengen_name");
		this.kihonModelCd = m.get("kihon_model_cd");
		this.shouninHissuFlg = m.get("shounin_hissu_flg");
		this.shouninKenFlg = m.get("shounin_ken_flg");
		this.henkouFlg = m.get("henkou_flg");
		this.shouninNinzuuCd = m.get("shounin_ninzuu_cd");
		this.shouninNinzuuHiritsu = m.get("shounin_ninzuu_hiritsu");
		this.syoriCd = m.get("syori_cd");
		this.gouginaiGroup = m.get("gouginai_group");
		this.joukyouEdano = m.get("joukyou_edano");
		this.map = m;
	}

	/** 伝票ID */
	public String denpyouId;

	/** 枝番号 */
	public int edano;

	/** 合議枝番号 */
	public int gougiEdano;

	/** 合議枝々番号 */
	public int gougiEdaedano;

	/** ユーザーID */
	public String userId;

	/** ユーザーフル名 */
	public String userFullName;

	/** 部門コード */
	public String bumonCd;

	/** 部門フル名 */
	public String bumonFullName;

	/** 部門ロールID */
	public String bumonRoleId;

	/** 部門ロール名 */
	public String bumonRoleName;

	/** 合議現在フラグ */
	public String gougiGenzaiFlg;

	/** 承認処理権限番号 */
	public long shouninShoriKengenNo;

	/** 承認処理権限名 */
	public String shouninShoriKengenName;

	/** 基本モデルコード */
	public String kihonModelCd;

	/** 承認必須フラグ */
	public String shouninHissuFlg;

	/** 承認権フラグ */
	public String shouninKenFlg;

	/** 変更フラグ */
	public String henkouFlg;

	/** 承認人数コード */
	public String shouninNinzuuCd;

	/** 承認人数比率 */
	public Integer shouninNinzuuHiritsu;

	/** 処理コード */
	public String syoriCd;

	/** 合議内グループ */
	public int gouginaiGroup;

	/** 承認状況枝番 */
	public Integer joukyouEdano;

	/** その他項目map */
	public GMap map;
}
