package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * CSV作成用一時テーブルDTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class TempCsvmake implements IEteamDTO {

	/**
	 * default constructor
	 */
	public TempCsvmake() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public TempCsvmake(GMap m) {
		this.rowNum = m.get("row_num");
		this.dataRowbinary = m.get("data_rowbinary");
		this.map = m;
	}

	/** 行番号 */
	public int rowNum;

	/** 行バイナリデータ */
	@ToString.Exclude
	public byte [] dataRowbinary;

	/** その他項目map */
	public GMap map;
}
