package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 添付伝票除外DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class TenpuDenpyouJyogai implements IEteamDTO {

	/**
	 * default constructor
	 */
	public TenpuDenpyouJyogai() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public TenpuDenpyouJyogai(GMap m) {
		this.denpyouId = m.get("denpyou_id");
		this.map = m;
	}

	/** 伝票ID */
	public String denpyouId;

	/** その他項目map */
	public GMap map;
}
