package eteam.database.dto;

import java.math.BigDecimal;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 取引先科目残高DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class TorihikisakiKamokuZandaka implements IEteamDTO {

	/**
	 * default constructor
	 */
	public TorihikisakiKamokuZandaka() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public TorihikisakiKamokuZandaka(GMap m) {
		this.torihikisakiCd = m.get("torihikisaki_cd");
		this.kamokuGaibuCd = m.get("kamoku_gaibu_cd");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.kamokuNaibuCd = m.get("kamoku_naibu_cd");
		this.torihikisakiNameRyakushiki = m.get("torihikisaki_name_ryakushiki");
		this.torihikisakiNameSeishiki = m.get("torihikisaki_name_seishiki");
		this.chouhyouShaturyokuNo = m.get("chouhyou_shaturyoku_no");
		this.kamokuNameRyakushiki = m.get("kamoku_name_ryakushiki");
		this.kamokuNameSeishiki = m.get("kamoku_name_seishiki");
		this.taishakuZokusei = m.get("taishaku_zokusei");
		this.kishuZandaka = m.get("kishu_zandaka");
		this.map = m;
	}

	/** 取引先コード */
	public String torihikisakiCd;

	/** 科目外部コード */
	public String kamokuGaibuCd;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** 科目内部コード */
	public String kamokuNaibuCd;

	/** 取引先名（略式） */
	public String torihikisakiNameRyakushiki;

	/** 取引先名（正式） */
	public String torihikisakiNameSeishiki;

	/** 帳票出力順番号 */
	public Integer chouhyouShaturyokuNo;

	/** 科目名（略式） */
	public String kamokuNameRyakushiki;

	/** 科目名（正式） */
	public String kamokuNameSeishiki;

	/** 貸借属性 */
	public int taishakuZokusei;

	/** 期首残高 */
	public BigDecimal kishuZandaka;

	/** その他項目map */
	public GMap map;
}
