package eteam.database.dto;

import java.math.BigDecimal;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 取引先DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Torihikisaki implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Torihikisaki() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Torihikisaki(GMap m) {
		this.torihikisakiCd = m.get("torihikisaki_cd");
		this.yuubinBangou = m.get("yuubin_bangou");
		this.juusho1 = m.get("juusho1");
		this.juusho2 = m.get("juusho2");
		this.telno = m.get("telno");
		this.faxno = m.get("faxno");
		this.kouzaMeiginin = m.get("kouza_meiginin");
		this.kouzaMeigininFurigana = m.get("kouza_meiginin_furigana");
		this.shiharaiShubetsu = m.get("shiharai_shubetsu");
		this.yokinShubetsu = m.get("yokin_shubetsu");
		this.kouzaBangou = m.get("kouza_bangou");
		this.tesuuryouFutanKbn = m.get("tesuuryou_futan_kbn");
		this.furikomiKbn = m.get("furikomi_kbn");
		this.furikomiGinkouCd = m.get("furikomi_ginkou_cd");
		this.furikomiGinkouShitenCd = m.get("furikomi_ginkou_shiten_cd");
		this.shiharaibi = m.get("shiharaibi");
		this.shiharaiKijitsu = m.get("shiharai_kijitsu");
		this.yakujouKingaku = m.get("yakujou_kingaku");
		this.torihikisakiNameHankana = m.get("torihikisaki_name_hankana");
		this.sbusyo = m.get("sbusyo");
		this.stanto = m.get("stanto");
		this.keicd = m.get("keicd");
		this.nayose = m.get("nayose");
		this.fSetuin = m.get("f_setuin");
		this.stan = m.get("stan");
		this.sbcod = m.get("sbcod");
		this.skicd = m.get("skicd");
		this.fSoufu = m.get("f_soufu");
		this.annai = m.get("annai");
		this.tsokbn = m.get("tsokbn");
		this.fShitu = m.get("f_shitu");
		this.cdm2 = m.get("cdm2");
		this.dm1 = m.get("dm1");
		this.dm2 = m.get("dm2");
		this.dm3 = m.get("dm3");
		this.gendo = m.get("gendo");
		this.map = m;
	}

	/** 取引先コード */
	public String torihikisakiCd;

	/** 郵便番号 */
	public String yuubinBangou;

	/** 住所１ */
	public String juusho1;

	/** 住所２ */
	public String juusho2;

	/** 電話番号 */
	public String telno;

	/** FAX番号 */
	public String faxno;

	/** 口座名義人 */
	public String kouzaMeiginin;

	/** 口座名義人ふり仮名 */
	public String kouzaMeigininFurigana;

	/** 支払種別 */
	public Integer shiharaiShubetsu;

	/** 預金種別 */
	public String yokinShubetsu;

	/** 口座番号 */
	public String kouzaBangou;

	/** 手数料負担区分 */
	public Integer tesuuryouFutanKbn;

	/** 振込区分 */
	public String furikomiKbn;

	/** 振込銀行コード */
	public String furikomiGinkouCd;

	/** 振込銀行支店コード */
	public String furikomiGinkouShitenCd;

	/** 支払日 */
	public Integer shiharaibi;

	/** 支払期日 */
	public Integer shiharaiKijitsu;

	/** 約定金額 */
	public BigDecimal yakujouKingaku;

	/** 取引先名（半角カナ） */
	public String torihikisakiNameHankana;

	/** 相手先部署 */
	public String sbusyo;

	/** 相手先担当者 */
	public String stanto;

	/** 敬称 */
	public Integer keicd;

	/** 名寄せフラグ */
	public int nayose;

	/** 節印実行フラグ */
	public Integer fSetuin;

	/** 主担当者 */
	public String stan;

	/** 部門コード */
	public String sbcod;

	/** 科目コード */
	public String skicd;

	/** 送付案内 */
	public Integer fSoufu;

	/** 案内文 */
	public Integer annai;

	/** 送料負担区分 */
	public Integer tsokbn;

	/** 支払通知 */
	public Integer fShitu;

	/** 仕入先番号 */
	public String cdm2;

	/** 補助コード１ */
	public String dm1;

	/** 補助コード２ */
	public Integer dm2;

	/** 補助コード３ */
	public Integer dm3;

	/** 負担限度額 */
	public BigDecimal gendo;

	/** その他項目map */
	public GMap map;
}
