package eteam.database.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 付替DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Tsukekae implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Tsukekae() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Tsukekae(GMap m) {
		this.denpyouId = m.get("denpyou_id");
		this.denpyouDate = m.get("denpyou_date");
		this.shouhyouShoruiFlg = m.get("shouhyou_shorui_flg");
		this.zeiritsu = m.get("zeiritsu");
		this.keigenZeiritsuKbn = m.get("keigen_zeiritsu_kbn");
		this.kingakuGoukei = m.get("kingaku_goukei");
		this.hf1Cd = m.get("hf1_cd");
		this.hf1NameRyakushiki = m.get("hf1_name_ryakushiki");
		this.hf2Cd = m.get("hf2_cd");
		this.hf2NameRyakushiki = m.get("hf2_name_ryakushiki");
		this.hf3Cd = m.get("hf3_cd");
		this.hf3NameRyakushiki = m.get("hf3_name_ryakushiki");
		this.hf4Cd = m.get("hf4_cd");
		this.hf4NameRyakushiki = m.get("hf4_name_ryakushiki");
		this.hf5Cd = m.get("hf5_cd");
		this.hf5NameRyakushiki = m.get("hf5_name_ryakushiki");
		this.hf6Cd = m.get("hf6_cd");
		this.hf6NameRyakushiki = m.get("hf6_name_ryakushiki");
		this.hf7Cd = m.get("hf7_cd");
		this.hf7NameRyakushiki = m.get("hf7_name_ryakushiki");
		this.hf8Cd = m.get("hf8_cd");
		this.hf8NameRyakushiki = m.get("hf8_name_ryakushiki");
		this.hf9Cd = m.get("hf9_cd");
		this.hf9NameRyakushiki = m.get("hf9_name_ryakushiki");
		this.hf10Cd = m.get("hf10_cd");
		this.hf10NameRyakushiki = m.get("hf10_name_ryakushiki");
		this.hosoku = m.get("hosoku");
		this.tsukekaeKbn = m.get("tsukekae_kbn");
		this.motoKamokuCd = m.get("moto_kamoku_cd");
		this.motoKamokuName = m.get("moto_kamoku_name");
		this.motoKamokuEdabanCd = m.get("moto_kamoku_edaban_cd");
		this.motoKamokuEdabanName = m.get("moto_kamoku_edaban_name");
		this.motoFutanBumonCd = m.get("moto_futan_bumon_cd");
		this.motoFutanBumonName = m.get("moto_futan_bumon_name");
		this.motoTorihikisakiCd = m.get("moto_torihikisaki_cd");
		this.motoTorihikisakiNameRyakushiki = m.get("moto_torihikisaki_name_ryakushiki");
		this.motoKazeiKbn = m.get("moto_kazei_kbn");
		this.motoUf1Cd = m.get("moto_uf1_cd");
		this.motoUf1NameRyakushiki = m.get("moto_uf1_name_ryakushiki");
		this.motoUf2Cd = m.get("moto_uf2_cd");
		this.motoUf2NameRyakushiki = m.get("moto_uf2_name_ryakushiki");
		this.motoUf3Cd = m.get("moto_uf3_cd");
		this.motoUf3NameRyakushiki = m.get("moto_uf3_name_ryakushiki");
		this.motoUf4Cd = m.get("moto_uf4_cd");
		this.motoUf4NameRyakushiki = m.get("moto_uf4_name_ryakushiki");
		this.motoUf5Cd = m.get("moto_uf5_cd");
		this.motoUf5NameRyakushiki = m.get("moto_uf5_name_ryakushiki");
		this.motoUf6Cd = m.get("moto_uf6_cd");
		this.motoUf6NameRyakushiki = m.get("moto_uf6_name_ryakushiki");
		this.motoUf7Cd = m.get("moto_uf7_cd");
		this.motoUf7NameRyakushiki = m.get("moto_uf7_name_ryakushiki");
		this.motoUf8Cd = m.get("moto_uf8_cd");
		this.motoUf8NameRyakushiki = m.get("moto_uf8_name_ryakushiki");
		this.motoUf9Cd = m.get("moto_uf9_cd");
		this.motoUf9NameRyakushiki = m.get("moto_uf9_name_ryakushiki");
		this.motoUf10Cd = m.get("moto_uf10_cd");
		this.motoUf10NameRyakushiki = m.get("moto_uf10_name_ryakushiki");
		this.motoProjectCd = m.get("moto_project_cd");
		this.motoProjectName = m.get("moto_project_name");
		this.motoSegmentCd = m.get("moto_segment_cd");
		this.motoSegmentNameRyakushiki = m.get("moto_segment_name_ryakushiki");
		this.tourokuUserId = m.get("touroku_user_id");
		this.tourokuTime = m.get("touroku_time");
		this.koushinUserId = m.get("koushin_user_id");
		this.koushinTime = m.get("koushin_time");
		this.motoJigyoushaKbn = m.get("moto_jigyousha_kbn");
		this.motoBunriKbn = m.get("moto_bunri_kbn");
		this.motoShiireKbn = m.get("moto_shiire_kbn");
		this.motoZeigakuHoushiki = m.get("moto_zeigaku_houshiki");
		this.invoiceDenpyou = m.get("invoice_denpyou");
		this.map = m;
	}

	/** 伝票ID */
	public String denpyouId;

	/** 伝票日付 */
	public Date denpyouDate;

	/** 証憑書類フラグ */
	public String shouhyouShoruiFlg;

	/** 税率 */
	public BigDecimal zeiritsu;

	/** 軽減税率区分 */
	public String keigenZeiritsuKbn;

	/** 金額合計 */
	public BigDecimal kingakuGoukei;

	/** HF1コード */
	public String hf1Cd;

	/** HF1名（略式） */
	public String hf1NameRyakushiki;

	/** HF2コード */
	public String hf2Cd;

	/** HF2名（略式） */
	public String hf2NameRyakushiki;

	/** HF3コード */
	public String hf3Cd;

	/** HF3名（略式） */
	public String hf3NameRyakushiki;

	/** HF4コード */
	public String hf4Cd;

	/** HF4名（略式） */
	public String hf4NameRyakushiki;

	/** HF5コード */
	public String hf5Cd;

	/** HF5名（略式） */
	public String hf5NameRyakushiki;

	/** HF6コード */
	public String hf6Cd;

	/** HF6名（略式） */
	public String hf6NameRyakushiki;

	/** HF7コード */
	public String hf7Cd;

	/** HF7名（略式） */
	public String hf7NameRyakushiki;

	/** HF8コード */
	public String hf8Cd;

	/** HF8名（略式） */
	public String hf8NameRyakushiki;

	/** HF9コード */
	public String hf9Cd;

	/** HF9名（略式） */
	public String hf9NameRyakushiki;

	/** HF10コード */
	public String hf10Cd;

	/** HF10名（略式） */
	public String hf10NameRyakushiki;

	/** 補足 */
	public String hosoku;

	/** 付替区分 */
	public String tsukekaeKbn;

	/** 付替元科目コード */
	public String motoKamokuCd;

	/** 付替元科目名 */
	public String motoKamokuName;

	/** 付替元科目枝番コード */
	public String motoKamokuEdabanCd;

	/** 付替元科目枝番名 */
	public String motoKamokuEdabanName;

	/** 付替元負担部門コード */
	public String motoFutanBumonCd;

	/** 付替元負担部門名 */
	public String motoFutanBumonName;

	/** 付替元取引先コード */
	public String motoTorihikisakiCd;

	/** 付替元取引先名（略式） */
	public String motoTorihikisakiNameRyakushiki;

	/** 付替元課税区分 */
	public String motoKazeiKbn;

	/** 付替元UF1コード */
	public String motoUf1Cd;

	/** 付替元UF1名（略式） */
	public String motoUf1NameRyakushiki;

	/** 付替元UF2コード */
	public String motoUf2Cd;

	/** 付替元UF2名（略式） */
	public String motoUf2NameRyakushiki;

	/** 付替元UF3コード */
	public String motoUf3Cd;

	/** 付替元UF3名（略式） */
	public String motoUf3NameRyakushiki;

	/** 付替元UF4コード */
	public String motoUf4Cd;

	/** 付替元UF4名（略式） */
	public String motoUf4NameRyakushiki;

	/** 付替元UF5コード */
	public String motoUf5Cd;

	/** 付替元UF5名（略式） */
	public String motoUf5NameRyakushiki;

	/** 付替元UF6コード */
	public String motoUf6Cd;

	/** 付替元UF6名（略式） */
	public String motoUf6NameRyakushiki;

	/** 付替元UF7コード */
	public String motoUf7Cd;

	/** 付替元UF7名（略式） */
	public String motoUf7NameRyakushiki;

	/** 付替元UF8コード */
	public String motoUf8Cd;

	/** 付替元UF8名（略式） */
	public String motoUf8NameRyakushiki;

	/** 付替元UF9コード */
	public String motoUf9Cd;

	/** 付替元UF9名（略式） */
	public String motoUf9NameRyakushiki;

	/** 付替元UF10コード */
	public String motoUf10Cd;

	/** 付替元UF10名（略式） */
	public String motoUf10NameRyakushiki;

	/** 付替元プロジェクトコード */
	public String motoProjectCd;

	/** 付替元プロジェクト名 */
	public String motoProjectName;

	/** 付替元セグメントコード */
	public String motoSegmentCd;

	/** 付替元セグメント名（略式） */
	public String motoSegmentNameRyakushiki;

	/** 登録ユーザーID */
	public String tourokuUserId;

	/** 登録日時 */
	public Timestamp tourokuTime;

	/** 更新ユーザーID */
	public String koushinUserId;

	/** 更新日時 */
	public Timestamp koushinTime;

	/** 付替元事業者区分 */
	public String motoJigyoushaKbn;

	/** 付替元分離区分 */
	public String motoBunriKbn;

	/** 付替元仕入区分 */
	public String motoShiireKbn;

	/** 付替元税額計算方式 */
	public String motoZeigakuHoushiki;

	/** インボイス対応伝票 */
	public String invoiceDenpyou;

	/** その他項目map */
	public GMap map;
}