package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ユニバーサルフィールド５一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Uf5Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Uf5Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Uf5Ichiran(GMap m) {
		this.uf5Cd = m.get("uf5_cd");
		this.uf5NameRyakushiki = m.get("uf5_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** UF5コード */
	public String uf5Cd;

	/** UF5名（略式） */
	public String uf5NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
