package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ユニバーサルフィールド６一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Uf6Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Uf6Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Uf6Ichiran(GMap m) {
		this.uf6Cd = m.get("uf6_cd");
		this.uf6NameRyakushiki = m.get("uf6_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** UF6コード */
	public String uf6Cd;

	/** UF6名（略式） */
	public String uf6NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
