package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ユニバーサルフィールド７一覧DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class Uf7Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public Uf7Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public Uf7Ichiran(GMap m) {
		this.uf7Cd = m.get("uf7_cd");
		this.uf7NameRyakushiki = m.get("uf7_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** UF7コード */
	public String uf7Cd;

	/** UF7名（略式） */
	public String uf7NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
