package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ユニバーサルフィールド３一覧（固定値）DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class UfKotei3Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public UfKotei3Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public UfKotei3Ichiran(GMap m) {
		this.ufKotei3Cd = m.get("uf_kotei3_cd");
		this.ufKotei3NameRyakushiki = m.get("uf_kotei3_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** UF3コード */
	public String ufKotei3Cd;

	/** UF3名（略式） */
	public String ufKotei3NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
