package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ユニバーサルフィールド７一覧（固定値）DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class UfKotei7Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public UfKotei7Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public UfKotei7Ichiran(GMap m) {
		this.ufKotei7Cd = m.get("uf_kotei7_cd");
		this.ufKotei7NameRyakushiki = m.get("uf_kotei7_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** UF7コード */
	public String ufKotei7Cd;

	/** UF7名（略式） */
	public String ufKotei7NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
