package eteam.database.dto;


import eteam.base.GMap;
import eteam.base.IEteamDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * ユニバーサルフィールド５一覧（固定値）DTO
 * This code was generated by the tool.
 * This code can not be changed.
 * @author CodeGenerator
 */
@Getter @Setter @ToString
public class UfKotei5Ichiran implements IEteamDTO {

	/**
	 * default constructor
	 */
	public UfKotei5Ichiran() {}

	 /**
	 * GMapからDTOを生成
	 * @param m GMap
	 */
	public UfKotei5Ichiran(GMap m) {
		this.ufKotei5Cd = m.get("uf_kotei5_cd");
		this.ufKotei5NameRyakushiki = m.get("uf_kotei5_name_ryakushiki");
		this.kessankiBangou = m.get("kessanki_bangou");
		this.map = m;
	}

	/** UF5コード */
	public String ufKotei5Cd;

	/** UF5名（略式） */
	public String ufKotei5NameRyakushiki;

	/** 決算期番号 */
	public Integer kessankiBangou;

	/** その他項目map */
	public GMap map;
}
