SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;


-- 旅費精算に経費明細のテーブル追加
CREATE TABLE RYOHISEISAN_KEIHI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN_KEIHI_MEISAI IS '旅費精算経費明細';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_KEIHI_MEISAI.KOUSHIN_TIME IS '更新日時';


-- 旅費仮払に経費明細の追加
CREATE TABLE RYOHI_KARIBARAI_KEIHI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1),
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHI_KARIBARAI_KEIHI_MEISAI IS '旅費仮払経費明細';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI_KEIHI_MEISAI.KOUSHIN_TIME IS '更新日時';


-- 旅費精算明細に休日日数を追加
ALTER TABLE ryohiseisan_meisai RENAME TO ryohiseisan_meisai_old;
CREATE TABLE RYOHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	KYUUJITSU_NISSUU NUMERIC,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU NUMERIC,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN_MEISAI IS '旅費精算明細';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KYUUJITSU_NISSUU IS '休日日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT 
INTO ryohiseisan_meisai( 
  denpyou_id
  , denpyou_edano
  , kikan_from
  , kikan_to
  , kyuujitsu_nissuu
  , shubetsu_cd
  , shubetsu1
  , shubetsu2
  , koutsuu_shudan
  , shouhyou_shorui_hissu_flg
  , ryoushuusho_seikyuusho_tou_flg
  , naiyou
  , bikou
  , oufuku_flg
  , jidounyuuryoku_flg
  , nissuu
  , tanka
  , meisai_kingaku
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  denpyou_id
  , denpyou_edano
  , kikan_from
  , kikan_to
  , NULL
  , shubetsu_cd
  , shubetsu1
  , shubetsu2
  , koutsuu_shudan
  , shouhyou_shorui_hissu_flg
  , ryoushuusho_seikyuusho_tou_flg
  , naiyou
  , bikou
  , oufuku_flg
  , jidounyuuryoku_flg
  , nissuu
  , tanka
  , meisai_kingaku
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time 
FROM
  ryohiseisan_meisai_old;

DROP TABLE ryohiseisan_meisai_old;


-- 経費明細に使用日／証憑の追加
ALTER TABLE KEIHISEISAN_MEISAI RENAME TO KEIHISEISAN_MEISAI_OLD;

CREATE TABLE KEIHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	USER_ID VARCHAR(30) NOT NULL,
	SHAIN_NO VARCHAR(15) NOT NULL,
	USER_SEI VARCHAR(10) NOT NULL,
	USER_MEI VARCHAR(10) NOT NULL,
	SHIYOUBI DATE,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	SHIHARAI_KINGAKU DECIMAL(15) NOT NULL,
	HONTAI_KINGAKU DECIMAL(15),
	SHOUHIZEIGAKU DECIMAL(15),
	KOUSAIHI_SHOUSAI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_SHOUSAI VARCHAR(240),
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KEIHISEISAN_MEISAI IS '経費精算明細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHAIN_NO IS '社員番号';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_SEI IS 'ユーザー姓';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.USER_MEI IS 'ユーザー名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHIHARAI_KINGAKU IS '支払金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI_HYOUJI_FLG IS '交際費詳細表示フラグ';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSAIHI_SHOUSAI IS '交際費詳細';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO keihiseisan_meisai( 
  denpyou_id
  , denpyou_edano
  , shiwake_edano
  , user_id
  , shain_no
  , user_sei
  , user_mei
  , shiyoubi
  , shouhyou_shorui_flg
  , torihiki_name
  , tekiyou
  , zeiritsu
  , shiharai_kingaku
  , hontai_kingaku
  , shouhizeigaku
  , kousaihi_shousai_hyouji_flg
  , kousaihi_shousai
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , torihikisaki_cd
  , torihikisaki_name_ryakushiki
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , project_cd
  , project_name
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  denpyou_id
  , denpyou_edano
  , shiwake_edano
  , user_id
  , shain_no
  , user_sei
  , user_mei
  , (SELECT shiyoubi FROM keihiseisan WHERE denpyou_id = kmo.denpyou_id)
  , (SELECT shouhyou_shorui_flg FROM keihiseisan WHERE denpyou_id = kmo.denpyou_id)
  , torihiki_name
  , tekiyou
  , zeiritsu
  , shiharai_kingaku
  , hontai_kingaku
  , shouhizeigaku
  , kousaihi_shousai_hyouji_flg
  , kousaihi_shousai
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , torihikisaki_cd
  , torihikisaki_name_ryakushiki
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , project_cd
  , project_name
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time 
FROM
  keihiseisan_meisai_old kmo;

DROP TABLE keihiseisan_meisai_old CASCADE;


-- 旅費仮払・明細の修正
ALTER TABLE RYOHI_KARIBARAI RENAME TO RYOHI_KARIBARAI_OLD;
ALTER TABLE ryohi_karibarai_meisai RENAME TO ryohi_karibarai_meisai_old;

CREATE TABLE RYOHI_KARIBARAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1) DEFAULT '0' NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	KINGAKU DECIMAL(15) NOT NULL,
	KARIBARAI_KINGAKU DECIMAL(15),
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHI_KARIBARAI IS '旅費仮払';
COMMENT ON COLUMN RYOHI_KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHI_KARIBARAI.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHI_KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARIBARAI_KINGAKU IS '仮払金額';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO ryohi_karibarai( 
  denpyou_id
  , karibarai_on
  , houmonsaki
  , mokuteki
  , seisankikan_from
  , seisankikan_from_hour
  , seisankikan_from_min
  , seisankikan_to
  , seisankikan_to_hour
  , seisankikan_to_min
  , shiharaibi
  , shiharaikiboubi
  , shiharaihouhou
  , tekiyou
  , kingaku
  , karibarai_kingaku
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , hosoku
  , shiwake_edano
  , torihiki_name
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT
  denpyou_id
  , '1'
  , SUBSTR(ARRAY_TO_STRING(ARRAY(SELECT shutchousaki FROM ryohi_karibarai_meisai_old WHERE denpyou_id = rko.denpyou_id),'、'),1,120)
  , SUBSTR(ARRAY_TO_STRING(ARRAY(SELECT youken FROM ryohi_karibarai_meisai_old WHERE denpyou_id = rko.denpyou_id),'、'),1,240)
  , kikan_from
  , NULL
  , NULL
  , kikan_to
  , NULL
  , NULL
  , shiharaibi
  , shiharaikiboubi
  , shiharaihouhou
  , tekiyou
  , 0
  , kingaku
  , hf1_cd
  , hf1_name_ryakushiki
  , hf2_cd
  , hf2_name_ryakushiki
  , hf3_cd
  , hf3_name_ryakushiki
  , mokuteki
  , shiwake_edano
  , torihiki_name
  , kari_futan_bumon_cd
  , kari_futan_bumon_name
  , kari_kamoku_cd
  , kari_kamoku_name
  , kari_kamoku_edaban_cd
  , kari_kamoku_edaban_name
  , kari_kazei_kbn
  , kashi_futan_bumon_cd
  , kashi_futan_bumon_name
  , kashi_kamoku_cd
  , kashi_kamoku_name
  , kashi_kamoku_edaban_cd
  , kashi_kamoku_edaban_name
  , kashi_kazei_kbn
  , uf1_cd
  , uf1_name_ryakushiki
  , uf2_cd
  , uf2_name_ryakushiki
  , uf3_cd
  , uf3_name_ryakushiki
  , tekiyou_cd
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
FROM ryohi_karibarai_old rko;


-- 旅費仮払明細の作成
CREATE TABLE RYOHI_KARIBARAI_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	KYUUJITSU_NISSUU NUMERIC,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU NUMERIC,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHI_KARIBARAI_MEISAI IS '旅費仮払明細';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.KYUUJITSU_NISSUU IS '休日日数';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI_MEISAI.KOUSHIN_TIME IS '更新日時';

INSERT 
INTO ryohi_karibarai_meisai( 
  denpyou_id
  , denpyou_edano
  , kikan_from
  , kikan_to
  , kyuujitsu_nissuu
  , shubetsu_cd
  , shubetsu1
  , shubetsu2
  , koutsuu_shudan
  , shouhyou_shorui_hissu_flg
  , naiyou
  , bikou
  , oufuku_flg
  , jidounyuuryoku_flg
  , nissuu
  , tanka
  , meisai_kingaku
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
) 
SELECT 
  denpyou_id
  , denpyou_edano
  , yoteibi
  , NULL
  , NULL
  , '1'
  , '交通費'
  , '手入力'
  , SUBSTR(koutsuu_shudan, 1, 10)
  , COALESCE((SELECT shouhyou_shorui_hissu_flg FROM koutsuu_shudan_master ksm WHERE ksm.koutsuu_shudan = rkm.koutsuu_shudan), '0')
  , (SELECT shutchousaki || chr(13) || youken FROM ryohi_karibarai_meisai_old WHERE denpyou_id = rkm.denpyou_id AND denpyou_edano = rkm.denpyou_edano)
  , ''
  , '0'
  , '0'
  , NULL
  , 0
  , 0
  , touroku_user_id
  , touroku_time
  , koushin_user_id
  , koushin_time
FROM ryohi_karibarai_meisai_old rkm;

DROP TABLE ryohi_karibarai_old;
DROP TABLE ryohi_karibarai_meisai_old;


-- 旅費精算に仮払申請フラグを追加
ALTER TABLE RYOHISEISAN RENAME TO RYOHISEISAN_OLD;

CREATE TABLE RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_ON VARCHAR(1) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_FROM_HOUR VARCHAR(2),
	SEISANKIKAN_FROM_MIN VARCHAR(2),
	SEISANKIKAN_TO DATE,
	SEISANKIKAN_TO_HOUR VARCHAR(2),
	SEISANKIKAN_TO_MIN VARCHAR(2),
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_ON IS '仮払申請フラグ';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_HOUR IS '精算期間開始時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM_MIN IS '精算期間開始時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_HOUR IS '精算期間終了時刻（時）';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO_MIN IS '精算期間終了時刻（分）';
COMMENT ON COLUMN RYOHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';

INSERT
INTO RYOHISEISAN (
	DENPYOU_ID
,	KARIBARAI_DENPYOU_ID
,	KARIBARAI_ON
,	KARIBARAI_MISHIYOU_FLG
,	HOUMONSAKI
,	MOKUTEKI
,	SEISANKIKAN_FROM
,	SEISANKIKAN_FROM_HOUR
,	SEISANKIKAN_FROM_MIN
,	SEISANKIKAN_TO
,	SEISANKIKAN_TO_HOUR
,	SEISANKIKAN_TO_MIN
,	KEIJOUBI
,	SHIHARAIBI
,	SHIHARAIKIBOUBI
,	SHIHARAIHOUHOU
,	TEKIYOU
,	ZEIRITSU
,	GOUKEI_KINGAKU
,	SASHIHIKI_SHIKYUU_KINGAKU
,	HF1_CD
,	HF1_NAME_RYAKUSHIKI
,	HF2_CD
,	HF2_NAME_RYAKUSHIKI
,	HF3_CD
,	HF3_NAME_RYAKUSHIKI
,	HOSOKU
,	SHIWAKE_EDANO
,	TORIHIKI_NAME
,	KARI_FUTAN_BUMON_CD
,	KARI_FUTAN_BUMON_NAME
,	KARI_KAMOKU_CD
,	KARI_KAMOKU_NAME
,	KARI_KAMOKU_EDABAN_CD
,	KARI_KAMOKU_EDABAN_NAME
,	KARI_KAZEI_KBN
,	KASHI_FUTAN_BUMON_CD
,	KASHI_FUTAN_BUMON_NAME
,	KASHI_KAMOKU_CD
,	KASHI_KAMOKU_NAME
,	KASHI_KAMOKU_EDABAN_CD
,	KASHI_KAMOKU_EDABAN_NAME
,	KASHI_KAZEI_KBN
,	UF1_CD
,	UF1_NAME_RYAKUSHIKI
,	UF2_CD
,	UF2_NAME_RYAKUSHIKI
,	UF3_CD
,	UF3_NAME_RYAKUSHIKI
,	PROJECT_CD
,	PROJECT_NAME
,	TEKIYOU_CD
,	TOUROKU_USER_ID
,	TOUROKU_TIME
,	KOUSHIN_USER_ID
,	KOUSHIN_TIME
)
SELECT
	DENPYOU_ID
,	KARIBARAI_DENPYOU_ID
,	COALESCE((SELECT karibarai_on FROM ryohi_karibarai WHERE DENPYOU_ID = ro.KARIBARAI_DENPYOU_ID), '')
,	KARIBARAI_MISHIYOU_FLG
,	HOUMONSAKI
,	MOKUTEKI
,	SEISANKIKAN_FROM
,	SEISANKIKAN_FROM_HOUR
,	SEISANKIKAN_FROM_MIN
,	SEISANKIKAN_TO
,	SEISANKIKAN_TO_HOUR
,	SEISANKIKAN_TO_MIN
,	KEIJOUBI
,	SHIHARAIBI
,	SHIHARAIKIBOUBI
,	SHIHARAIHOUHOU
,	TEKIYOU
,	ZEIRITSU
,	GOUKEI_KINGAKU
,	SASHIHIKI_SHIKYUU_KINGAKU
,	HF1_CD
,	HF1_NAME_RYAKUSHIKI
,	HF2_CD
,	HF2_NAME_RYAKUSHIKI
,	HF3_CD
,	HF3_NAME_RYAKUSHIKI
,	HOSOKU
,	SHIWAKE_EDANO
,	TORIHIKI_NAME
,	KARI_FUTAN_BUMON_CD
,	KARI_FUTAN_BUMON_NAME
,	KARI_KAMOKU_CD
,	KARI_KAMOKU_NAME
,	KARI_KAMOKU_EDABAN_CD
,	KARI_KAMOKU_EDABAN_NAME
,	KARI_KAZEI_KBN
,	KASHI_FUTAN_BUMON_CD
,	KASHI_FUTAN_BUMON_NAME
,	KASHI_KAMOKU_CD
,	KASHI_KAMOKU_NAME
,	KASHI_KAMOKU_EDABAN_CD
,	KASHI_KAMOKU_EDABAN_NAME
,	KASHI_KAZEI_KBN
,	UF1_CD
,	UF1_NAME_RYAKUSHIKI
,	UF2_CD
,	UF2_NAME_RYAKUSHIKI
,	UF3_CD
,	UF3_NAME_RYAKUSHIKI
,	PROJECT_CD
,	PROJECT_NAME
,	TEKIYOU_CD
,	TOUROKU_USER_ID
,	TOUROKU_TIME
,	KOUSHIN_USER_ID
,	KOUSHIN_TIME
FROM RYOHISEISAN_OLD ro;

DROP TABLE RYOHISEISAN_OLD;


-- 経費立替申請に使用日／証憑カラムを消去
ALTER TABLE keihiseisan DROP shiyoubi CASCADE;
ALTER TABLE keihiseisan DROP shouhyou_shorui_flg CASCADE;


-- 画面項目制御の修正
CREATE TABLE gamen_koumoku_seigyo_tmp AS SELECT * FROM gamen_koumoku_seigyo;
DELETE FROM gamen_koumoku_seigyo WHERE denpyou_kbn LIKE 'A%';
\copy gamen_koumoku_seigyo FROM '.\files\csv\gamen_koumoku_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE gamen_koumoku_seigyo new SET
  koumoku_name = (SELECT koumoku_name FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
  ,hyouji_flg  = (SELECT hyouji_flg   FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
  ,hissu_flg   = (SELECT hissu_flg    FROM gamen_koumoku_seigyo_tmp tmp WHERE (tmp.denpyou_kbn,tmp.koumoku_id) = (new.denpyou_kbn,new.koumoku_id))
WHERE
  (new.denpyou_kbn,new.koumoku_id) IN (SELECT denpyou_kbn,koumoku_id FROM gamen_koumoku_seigyo_tmp);
DROP TABLE gamen_koumoku_seigyo_tmp;


--会社設定の修正
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info WHERE hyouji_jun < 900;
\copy setting_info FROM '.\files\csv\setting_info_sias.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new 
SET
  setting_val = (SELECT setting_val FROM setting_info_tmp tmp WHERE tmp.setting_name = new.setting_name)
WHERE
  new.setting_name IN (SELECT setting_name FROM setting_info_tmp); 
DROP TABLE setting_info_tmp;

-- 内部コード設定データ変更
DELETE FROM naibu_cd_setting WHERE naibu_cd = 'A005';
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting_patch.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 伝票種別一覧のカラム追加
ALTER TABLE DENPYOU_SHUBETSU_ICHIRAN RENAME TO DENPYOU_SHUBETSU_ICHIRAN_OLD;
CREATE TABLE DENPYOU_SHUBETSU_ICHIRAN
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT DEFAULT 0 NOT NULL,
	DENPYOU_SHUBETSU VARCHAR(20) NOT NULL,
	DENPYOU_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_SHUBETSU VARCHAR(20),
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU VARCHAR(20),
	HYOUJI_JUN INT NOT NULL,
	GYOUMU_SHUBETSU VARCHAR(20) NOT NULL,
	NAIYOU VARCHAR(160) NOT NULL,
	DENPYOU_SHUBETSU_URL VARCHAR(240) NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	KANREN_SENTAKU_FLG VARCHAR(1) NOT NULL,
	KANREN_HYOUJI_FLG VARCHAR(1) NOT NULL,
	DENPYOU_PRINT_FLG VARCHAR(1) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN)
) WITHOUT OIDS;
COMMENT ON TABLE DENPYOU_SHUBETSU_ICHIRAN IS '伝票種別一覧';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.VERSION IS 'バージョン';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU IS '伝票種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_SHUBETSU IS '伝票種別（帳票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU IS '伝票種別（帳票・仮払なし）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.GYOUMU_SHUBETSU IS '業務種別';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.NAIYOU IS '内容（伝票）';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_SHUBETSU_URL IS '伝票種別URL';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_SENTAKU_FLG IS '関連伝票選択フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KANREN_HYOUJI_FLG IS '関連伝票入力欄表示フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.DENPYOU_PRINT_FLG IS '申請時帳票出力フラグ';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN DENPYOU_SHUBETSU_ICHIRAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO DENPYOU_SHUBETSU_ICHIRAN
SELECT
	DENPYOU_KBN,
	VERSION,
	DENPYOU_SHUBETSU,
	DENPYOU_SHUBETSU,
	DENPYOU_SHUBETSU,
	DENPYOU_SHUBETSU,
	HYOUJI_JUN,
	GYOUMU_SHUBETSU,
	NAIYOU,
	DENPYOU_SHUBETSU_URL,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	KANREN_SENTAKU_FLG,
	KANREN_HYOUJI_FLG,
	DENPYOU_PRINT_FLG,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM DENPYOU_SHUBETSU_ICHIRAN_OLD ro;
UPDATE DENPYOU_SHUBETSU_ICHIRAN SET 
	DENPYOU_PRINT_SHUBETSU					= DENPYOU_SHUBETSU || '書',
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU	= DENPYOU_SHUBETSU || '書'
WHERE denpyou_kbn IN ('A001','A002','A003','A004','A006','A010');
UPDATE DENPYOU_SHUBETSU_ICHIRAN SET 
	DENPYOU_KARIBARAI_NASHI_SHUBETSU		= '', 
	DENPYOU_PRINT_SHUBETSU					= '',
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU	= ''
WHERE denpyou_kbn LIKE 'B%';
UPDATE DENPYOU_SHUBETSU_ICHIRAN SET 
	DENPYOU_SHUBETSU						= '出張伺い申請（仮払申請）',
	DENPYOU_KARIBARAI_NASHI_SHUBETSU		= '出張伺い申請（仮払申請）', 
	DENPYOU_PRINT_SHUBETSU					= '出張伺い申請（仮払申請）書',
	DENPYOU_PRINT_KARIBARAI_NASHI_SHUBETSU	= '出張伺い申請（仮払申請）書'
WHERE denpyou_kbn = 'A005';
DROP TABLE DENPYOU_SHUBETSU_ICHIRAN_OLD;


commit;
