SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- エラーログテーブル作成
CREATE TABLE BATCH_LOG_INVALID_LOG_HIMODUKE
(
	SERIAL_NO BIGINT NOT NULL,
	EDABAN INT NOT NULL,
	FILE_NAME VARCHAR NOT NULL,
	PRIMARY KEY (SERIAL_NO, EDABAN)
) WITHOUT OIDS;
COMMENT ON TABLE BATCH_LOG_INVALID_LOG_HIMODUKE IS 'バッチログ不良ログ紐づけ';
COMMENT ON COLUMN BATCH_LOG_INVALID_LOG_HIMODUKE.SERIAL_NO IS 'シリアル番号';
COMMENT ON COLUMN BATCH_LOG_INVALID_LOG_HIMODUKE.EDABAN IS '枝番';
COMMENT ON COLUMN BATCH_LOG_INVALID_LOG_HIMODUKE.FILE_NAME IS 'ファイル名';

CREATE TABLE BATCH_LOG_INVALID_DENPYOU_LOG
(
	FILE_NAME VARCHAR NOT NULL,
	DENPYOU_START_GYOU INT NOT NULL,
	DENPYOU_END_GYOU INT NOT NULL,
	DENPYOU_DATE DATE NOT NULL,
	DENPYOU_BANGOU VARCHAR(8) NOT NULL,
	TAISHAKU_SAGAKU_KINGAKU NUMERIC(19) NOT NULL,
	GAIYOU VARCHAR NOT NULL,
	NAIYOU VARCHAR NOT NULL
) WITHOUT OIDS;
COMMENT ON TABLE BATCH_LOG_INVALID_DENPYOU_LOG IS '不良伝票ログ';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.DENPYOU_START_GYOU IS '伝票開始行';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.DENPYOU_END_GYOU IS '伝票終了行';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.DENPYOU_DATE IS '伝票日付';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.DENPYOU_BANGOU IS '伝票番号';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.TAISHAKU_SAGAKU_KINGAKU IS '貸借差額金額';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.GAIYOU IS '概要';
COMMENT ON COLUMN BATCH_LOG_INVALID_DENPYOU_LOG.NAIYOU IS '内容';

CREATE TABLE BATCH_LOG_INVALID_FILE_LOG
(
	FILE_NAME VARCHAR NOT NULL,
	GYOU_NO INT NOT NULL,
	KOUMOKU_NO INT NOT NULL,
	KOUMOKU_NAME VARCHAR NOT NULL,
	INVALID_VALUE VARCHAR NOT NULL,
	ERROR_NAIYOU VARCHAR NOT NULL
) WITHOUT OIDS;
COMMENT ON TABLE BATCH_LOG_INVALID_FILE_LOG IS '不良データログ';
COMMENT ON COLUMN BATCH_LOG_INVALID_FILE_LOG.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN BATCH_LOG_INVALID_FILE_LOG.GYOU_NO IS '行No';
COMMENT ON COLUMN BATCH_LOG_INVALID_FILE_LOG.KOUMOKU_NO IS '項目No';
COMMENT ON COLUMN BATCH_LOG_INVALID_FILE_LOG.KOUMOKU_NAME IS '項目名称';
COMMENT ON COLUMN BATCH_LOG_INVALID_FILE_LOG.INVALID_VALUE IS '不正な値';
COMMENT ON COLUMN BATCH_LOG_INVALID_FILE_LOG.ERROR_NAIYOU IS 'エラー内容';

-- 画面権限制御の追加
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';

--ICSP連絡票_0293_帳票出力で取引・科目・枝番・部門・取引先・プロジェクト・セグメントのコードも印字
-- 画面項目制御
ALTER TABLE GAMEN_KOUMOKU_SEIGYO RENAME TO GAMEN_KOUMOKU_SEIGYO_OLD;
CREATE TABLE GAMEN_KOUMOKU_SEIGYO
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	KOUMOKU_ID VARCHAR NOT NULL,
	DEFAULT_KOUMOKU_NAME VARCHAR NOT NULL,
	KOUMOKU_NAME VARCHAR NOT NULL,
	HYOUJI_FLG VARCHAR(1) NOT NULL,
	HISSU_FLG VARCHAR(1) NOT NULL,
	HYOUJI_SEIGYO_FLG VARCHAR(1) NOT NULL,
	PDF_HYOUJI_FLG VARCHAR(1) NOT NULL,
	PDF_HYOUJI_SEIGYO_FLG VARCHAR(1) NOT NULL,
	CODE_OUTPUT_FLG VARCHAR(1) NOT NULL,
	CODE_OUTPUT_SEIGYO_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, KOUMOKU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE GAMEN_KOUMOKU_SEIGYO IS '画面項目制御';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.KOUMOKU_ID IS '項目ID';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.DEFAULT_KOUMOKU_NAME IS 'デフォルト項目名';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.KOUMOKU_NAME IS '項目名';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_FLG IS '表示フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HISSU_FLG IS '必須フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_SEIGYO_FLG IS '表示制御フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.PDF_HYOUJI_FLG IS '帳票表示フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.PDF_HYOUJI_SEIGYO_FLG IS '帳票表示制御フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.CODE_OUTPUT_FLG IS '帳票コード印字フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.CODE_OUTPUT_SEIGYO_FLG IS '帳票コード印字制御フラグ';
COMMENT ON COLUMN GAMEN_KOUMOKU_SEIGYO.HYOUJI_JUN IS '表示順';
INSERT INTO GAMEN_KOUMOKU_SEIGYO(
	DENPYOU_KBN,
	KOUMOKU_ID,
	DEFAULT_KOUMOKU_NAME,
	KOUMOKU_NAME,
	HYOUJI_FLG,
	HISSU_FLG,
	HYOUJI_SEIGYO_FLG,
	PDF_HYOUJI_FLG,
	PDF_HYOUJI_SEIGYO_FLG,
	CODE_OUTPUT_FLG,
	CODE_OUTPUT_SEIGYO_FLG,
	HYOUJI_JUN
)
SELECT
	DENPYOU_KBN,
	KOUMOKU_ID,
	DEFAULT_KOUMOKU_NAME,
	KOUMOKU_NAME,
	HYOUJI_FLG,
	HISSU_FLG,
	HYOUJI_SEIGYO_FLG,
	PDF_HYOUJI_FLG,
	PDF_HYOUJI_SEIGYO_FLG,
	'0', --CODE_OUTPUT_FLG,
	'0', --CODE_OUTPUT_SEIGYO_FLG,
	HYOUJI_JUN
FROM GAMEN_KOUMOKU_SEIGYO_OLD;
DROP TABLE GAMEN_KOUMOKU_SEIGYO_OLD;

-- 帳票コード印字制御フラグ
UPDATE gamen_koumoku_seigyo
SET code_output_seigyo_flg = '1'
WHERE
	(denpyou_kbn = 'A001'
		AND koumoku_id in ('torihiki_name','kari_kamoku_name','kari_kamoku_edaban_name','kari_futan_bumon_name','torihikisaki_name_ryakushiki','project_name')
	)
	OR (denpyou_kbn = 'A002'
	AND koumoku_id in ('torihiki_name','kari_futan_bumon_name')
	)
	OR (denpyou_kbn = 'A003'
	AND koumoku_id in ('torihiki_name','kari_kamoku_name','kari_kamoku_edaban_name','kari_futan_bumon_name','torihikisaki_name_ryakushiki','project_name')
	)
	OR (denpyou_kbn = 'A009'
	AND koumoku_id in ('torihiki_name','kari_kamoku_name','kari_kamoku_edaban_name','kari_futan_bumon_name','torihikisaki_name_ryakushiki','project_name')
	)
	OR (denpyou_kbn = 'A010'
	AND koumoku_id in ('torihiki_name','kari_futan_bumon_name','project_name')
	)
	OR (denpyou_kbn = 'A004'
	AND koumoku_id in ('torihiki_name','kari_futan_bumon_name','project_name')
	)
	OR (denpyou_kbn = 'A005'
	AND koumoku_id in ('torihiki_name','kari_futan_bumon_name')
	)
	OR (denpyou_kbn = 'A011'
	AND koumoku_id in ('torihiki_name','kari_futan_bumon_name','project_name')
	)
	OR (denpyou_kbn = 'A012'
	AND koumoku_id in ('torihiki_name','kari_futan_bumon_name')
	)
	OR (denpyou_kbn = 'A006'
	AND koumoku_id in ('torihiki_name','kari_futan_bumon_name')
	)
	OR (denpyou_kbn = 'A007'
	AND koumoku_id in ('kamoku_name','kamoku_edaban_name','futan_bumon_name','torihikisaki_name_ryakushiki','project_name')
	)
	OR (denpyou_kbn = 'A008'
	AND koumoku_id in ('kamoku_name','kamoku_edaban_name','futan_bumon_name','torihikisaki_name_ryakushiki','project_name')
	)
;

-- 帳票コード印字フラグ
UPDATE gamen_koumoku_seigyo
SET code_output_flg = '1'
WHERE denpyou_kbn = 'A003'
AND koumoku_id in ('torihikisaki_name_ryakushiki')
AND pdf_hyouji_flg='1';
;

-- 内部コード ※オプション用レコードはパッチ前になければ削除
CREATE TABLE naibu_cd_setting_tmp AS SELECT * FROM naibu_cd_setting;
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM naibu_cd_setting WHERE naibu_cd='A003' AND (SELECT COUNT(*) FROM naibu_cd_setting_tmp WHERE naibu_cd='A003')=0;
DROP TABLE naibu_cd_setting_tmp;

-- 簡易届テキストテーブルにDECIMAL_POINTカラム・KOTEI_HYOUJIカラムを追加
ALTER TABLE KANI_TODOKE_TEXT RENAME TO KANI_TODOKE_TEXT_OLD;
CREATE TABLE KANI_TODOKE_TEXT
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT NOT NULL,
	AREA_KBN VARCHAR NOT NULL,
	ITEM_NAME VARCHAR NOT NULL,
	LABEL_NAME VARCHAR NOT NULL,
	HISSU_FLG VARCHAR NOT NULL,
	BUHIN_FORMAT VARCHAR NOT NULL,
	BUHIN_WIDTH VARCHAR NOT NULL,
	MAX_LENGTH INT NOT NULL,
	DECIMAL_POINT VARCHAR NOT NULL,
	KOTEI_HYOUJI VARCHAR NOT NULL,
	MIN_VALUE DECIMAL(15) NOT NULL,
	MAX_VALUE DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, VERSION, AREA_KBN, ITEM_NAME)
) WITHOUT OIDS;
COMMENT ON TABLE KANI_TODOKE_TEXT IS '届出ジェネレータ項目テキスト';
COMMENT ON COLUMN KANI_TODOKE_TEXT.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN KANI_TODOKE_TEXT.VERSION IS 'バージョン';
COMMENT ON COLUMN KANI_TODOKE_TEXT.AREA_KBN IS 'エリア区分';
COMMENT ON COLUMN KANI_TODOKE_TEXT.ITEM_NAME IS '項目名';
COMMENT ON COLUMN KANI_TODOKE_TEXT.LABEL_NAME IS 'ラベル名';
COMMENT ON COLUMN KANI_TODOKE_TEXT.HISSU_FLG IS '必須フラグ';
COMMENT ON COLUMN KANI_TODOKE_TEXT.BUHIN_FORMAT IS '部品形式';
COMMENT ON COLUMN KANI_TODOKE_TEXT.BUHIN_WIDTH IS '部品幅';
COMMENT ON COLUMN KANI_TODOKE_TEXT.MAX_LENGTH IS '最大桁数';
COMMENT ON COLUMN KANI_TODOKE_TEXT.DECIMAL_POINT IS '小数点以下桁数';
COMMENT ON COLUMN KANI_TODOKE_TEXT.KOTEI_HYOUJI IS '固定表示フラグ';
COMMENT ON COLUMN KANI_TODOKE_TEXT.MIN_VALUE IS '最小値';
COMMENT ON COLUMN KANI_TODOKE_TEXT.MAX_VALUE IS '最大値';
COMMENT ON COLUMN KANI_TODOKE_TEXT.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KANI_TODOKE_TEXT.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KANI_TODOKE_TEXT.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KANI_TODOKE_TEXT.KOUSHIN_TIME IS '更新日時';
INSERT 
INTO KANI_TODOKE_TEXT( 
  DENPYOU_KBN
  , VERSION
  , AREA_KBN
  , ITEM_NAME
  , LABEL_NAME
  , HISSU_FLG
  , BUHIN_FORMAT
  , BUHIN_WIDTH
  , MAX_LENGTH
  , DECIMAL_POINT
  , KOTEI_HYOUJI
  , MIN_VALUE
  , MAX_VALUE
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME
) 
SELECT
    DENPYOU_KBN
  , VERSION
  , AREA_KBN
  , ITEM_NAME
  , LABEL_NAME
  , HISSU_FLG
  , BUHIN_FORMAT
  , BUHIN_WIDTH
  , MAX_LENGTH
  , '0' -- DECIMAL_POINT
  , '0' -- KOTEI_HYOUJI
  , MIN_VALUE
  , MAX_VALUE
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME 
FROM
  KANI_TODOKE_TEXT_OLD;
DROP TABLE KANI_TODOKE_TEXT_OLD;

-- 簡易届テキストエリアテーブルにKOTEI_HYOUJIカラムを追加
ALTER TABLE KANI_TODOKE_TEXTAREA RENAME TO KANI_TODOKE_TEXTAREA_OLD;
CREATE TABLE KANI_TODOKE_TEXTAREA
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	VERSION INT NOT NULL,
	AREA_KBN VARCHAR NOT NULL,
	ITEM_NAME VARCHAR NOT NULL,
	LABEL_NAME VARCHAR NOT NULL,
	HISSU_FLG VARCHAR NOT NULL,
	BUHIN_WIDTH VARCHAR NOT NULL,
	BUHIN_HEIGHT VARCHAR NOT NULL,
	MAX_LENGTH INT NOT NULL,
	KOTEI_HYOUJI VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, VERSION, AREA_KBN, ITEM_NAME)
) WITHOUT OIDS;
COMMENT ON TABLE KANI_TODOKE_TEXTAREA IS '届出ジェネレータ項目テキストエリア';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.VERSION IS 'バージョン';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.AREA_KBN IS 'エリア区分';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.ITEM_NAME IS '項目名';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.LABEL_NAME IS 'ラベル名';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.HISSU_FLG IS '必須フラグ';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.BUHIN_WIDTH IS '部品幅';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.BUHIN_HEIGHT IS '部品高さ';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.MAX_LENGTH IS '最大桁数';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.KOTEI_HYOUJI IS '固定表示フラグ';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KANI_TODOKE_TEXTAREA.KOUSHIN_TIME IS '更新日時';
INSERT 
INTO KANI_TODOKE_TEXTAREA( 
  DENPYOU_KBN
  , VERSION
  , AREA_KBN
  , ITEM_NAME
  , LABEL_NAME
  , HISSU_FLG
  , BUHIN_WIDTH
  , BUHIN_HEIGHT
  , MAX_LENGTH
  , KOTEI_HYOUJI
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME
) 
SELECT
    DENPYOU_KBN
  , VERSION
  , AREA_KBN
  , ITEM_NAME
  , LABEL_NAME
  , HISSU_FLG
  , BUHIN_WIDTH
  , BUHIN_HEIGHT
  , MAX_LENGTH
  , '0' -- KOTEI_HYOUJI
  , TOUROKU_USER_ID
  , TOUROKU_TIME
  , KOUSHIN_USER_ID
  , KOUSHIN_TIME 
FROM
  KANI_TODOKE_TEXTAREA_OLD;
DROP TABLE KANI_TODOKE_TEXTAREA_OLD;

-- 届出ジェネレータ一覧
CREATE TABLE KANI_TODOKE_ICHIRAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	SHINSEI01 VARCHAR NOT NULL,
	SHINSEI02 VARCHAR NOT NULL,
	SHINSEI03 VARCHAR NOT NULL,
	SHINSEI04 VARCHAR NOT NULL,
	SHINSEI05 VARCHAR NOT NULL,
	SHINSEI06 VARCHAR NOT NULL,
	SHINSEI07 VARCHAR NOT NULL,
	SHINSEI08 VARCHAR NOT NULL,
	SHINSEI09 VARCHAR NOT NULL,
	SHINSEI10 VARCHAR NOT NULL,
	SHINSEI11 VARCHAR NOT NULL,
	SHINSEI12 VARCHAR NOT NULL,
	SHINSEI13 VARCHAR NOT NULL,
	SHINSEI14 VARCHAR NOT NULL,
	SHINSEI15 VARCHAR NOT NULL,
	SHINSEI16 VARCHAR NOT NULL,
	SHINSEI17 VARCHAR NOT NULL,
	SHINSEI18 VARCHAR NOT NULL,
	SHINSEI19 VARCHAR NOT NULL,
	SHINSEI20 VARCHAR NOT NULL,
	SHINSEI21 VARCHAR NOT NULL,
	SHINSEI22 VARCHAR NOT NULL,
	SHINSEI23 VARCHAR NOT NULL,
	SHINSEI24 VARCHAR NOT NULL,
	SHINSEI25 VARCHAR NOT NULL,
	SHINSEI26 VARCHAR NOT NULL,
	SHINSEI27 VARCHAR NOT NULL,
	SHINSEI28 VARCHAR NOT NULL,
	SHINSEI29 VARCHAR NOT NULL,
	SHINSEI30 VARCHAR NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KANI_TODOKE_ICHIRAN IS '届出ジェネレータ一覧';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI01 IS '申請内容01';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI02 IS '申請内容02';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI03 IS '申請内容03';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI04 IS '申請内容04';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI05 IS '申請内容05';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI06 IS '申請内容06';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI07 IS '申請内容07';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI08 IS '申請内容08';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI09 IS '申請内容09';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI10 IS '申請内容10';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI11 IS '申請内容11';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI12 IS '申請内容12';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI13 IS '申請内容13';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI14 IS '申請内容14';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI15 IS '申請内容15';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI16 IS '申請内容16';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI17 IS '申請内容17';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI18 IS '申請内容18';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI19 IS '申請内容19';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI20 IS '申請内容20';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI21 IS '申請内容21';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI22 IS '申請内容22';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI23 IS '申請内容23';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI24 IS '申請内容24';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI25 IS '申請内容25';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI26 IS '申請内容26';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI27 IS '申請内容27';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI28 IS '申請内容28';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI29 IS '申請内容29';
COMMENT ON COLUMN KANI_TODOKE_ICHIRAN.SHINSEI30 IS '申請内容30';


-- 届出ジェネレータ明細一覧
CREATE TABLE KANI_TODOKE_MEISAI_ICHIRAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	MEISAI01 VARCHAR NOT NULL,
	MEISAI02 VARCHAR NOT NULL,
	MEISAI03 VARCHAR NOT NULL,
	MEISAI04 VARCHAR NOT NULL,
	MEISAI05 VARCHAR NOT NULL,
	MEISAI06 VARCHAR NOT NULL,
	MEISAI07 VARCHAR NOT NULL,
	MEISAI08 VARCHAR NOT NULL,
	MEISAI09 VARCHAR NOT NULL,
	MEISAI10 VARCHAR NOT NULL,
	MEISAI11 VARCHAR NOT NULL,
	MEISAI12 VARCHAR NOT NULL,
	MEISAI13 VARCHAR NOT NULL,
	MEISAI14 VARCHAR NOT NULL,
	MEISAI15 VARCHAR NOT NULL,
	MEISAI16 VARCHAR NOT NULL,
	MEISAI17 VARCHAR NOT NULL,
	MEISAI18 VARCHAR NOT NULL,
	MEISAI19 VARCHAR NOT NULL,
	MEISAI20 VARCHAR NOT NULL,
	MEISAI21 VARCHAR NOT NULL,
	MEISAI22 VARCHAR NOT NULL,
	MEISAI23 VARCHAR NOT NULL,
	MEISAI24 VARCHAR NOT NULL,
	MEISAI25 VARCHAR NOT NULL,
	MEISAI26 VARCHAR NOT NULL,
	MEISAI27 VARCHAR NOT NULL,
	MEISAI28 VARCHAR NOT NULL,
	MEISAI29 VARCHAR NOT NULL,
	MEISAI30 VARCHAR NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KANI_TODOKE_MEISAI_ICHIRAN IS '届出ジェネレータ明細一覧';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI01 IS '明細01';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI02 IS '明細02';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI03 IS '明細03';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI04 IS '明細04';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI05 IS '明細05';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI06 IS '明細06';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI07 IS '明細07';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI08 IS '明細08';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI09 IS '明細09';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI10 IS '明細10';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI11 IS '明細11';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI12 IS '明細12';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI13 IS '明細13';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI14 IS '明細14';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI15 IS '明細15';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI16 IS '明細16';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI17 IS '明細17';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI18 IS '明細18';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI19 IS '明細19';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI20 IS '明細20';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI21 IS '明細21';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI22 IS '明細22';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI23 IS '明細23';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI24 IS '明細24';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI25 IS '明細25';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI26 IS '明細26';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI27 IS '明細27';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI28 IS '明細28';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI29 IS '明細29';
COMMENT ON COLUMN KANI_TODOKE_MEISAI_ICHIRAN.MEISAI30 IS '明細30';

commit;