SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- マスター取込一覧・詳細テーブルをSIAS版とDE3版に分ける。
-- 今までのものはDE3に変更。
ALTER TABLE MASTER_TORIKOMI_ICHIRAN RENAME TO MASTER_TORIKOMI_ICHIRAN_DE3;
ALTER TABLE MASTER_TORIKOMI_SHOUSAI RENAME TO MASTER_TORIKOMI_SHOUSAI_DE3;

COMMENT ON TABLE MASTER_TORIKOMI_ICHIRAN_DE3 IS 'マスター取込一覧(de3)';
COMMENT ON TABLE MASTER_TORIKOMI_SHOUSAI_DE3 IS 'マスター取込詳細(de3)';

CREATE TABLE MASTER_TORIKOMI_ICHIRAN_SIAS
(
	MASTER_ID VARCHAR(50) NOT NULL,
	MASTER_NAME VARCHAR(50) NOT NULL,
	OP_MASTER_ID VARCHAR NOT NULL,
	OP_MASTER_NAME VARCHAR NOT NULL,
	TORIKOMI_KAHI_FLG  VARCHAR(1) NOT NULL,
	PRIMARY KEY (MASTER_ID)
) WITHOUT OIDS;

COMMENT ON TABLE MASTER_TORIKOMI_ICHIRAN_SIAS IS 'マスター取込一覧(SIAS)';
COMMENT ON COLUMN MASTER_TORIKOMI_ICHIRAN_SIAS.MASTER_ID IS 'マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_ICHIRAN_SIAS.MASTER_NAME IS 'マスター名';
COMMENT ON COLUMN MASTER_TORIKOMI_ICHIRAN_SIAS.OP_MASTER_ID IS 'OPEN21マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_ICHIRAN_SIAS.OP_MASTER_NAME IS 'OPEN21マスター名';
COMMENT ON COLUMN MASTER_TORIKOMI_ICHIRAN_SIAS.TORIKOMI_KAHI_FLG  IS '取込可否フラグ';

CREATE TABLE MASTER_TORIKOMI_SHOUSAI_SIAS
(
	MASTER_ID VARCHAR(50) NOT NULL,
	ET_COLUMN_ID VARCHAR NOT NULL,
	ET_COLUMN_NAME  VARCHAR NOT NULL,
	ET_DATA_TYPE VARCHAR NOT NULL,
	OP_COLUME_ID VARCHAR NOT NULL,
	OP_COLUMN_NAME VARCHAR NOT NULL,
	OP_DATA_TYPE VARCHAR NOT NULL,
	ENTRY_ORDER INT NOT NULL,
	PK_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (MASTER_ID, ET_COLUMN_ID)
) WITHOUT OIDS;

COMMENT ON TABLE MASTER_TORIKOMI_SHOUSAI_SIAS IS 'マスター取込詳細(SIAS)';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.MASTER_ID IS 'マスターID';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.ET_COLUMN_ID IS 'eTeamカラムID';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.ET_COLUMN_NAME  IS 'eTeamカラム名';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.ET_DATA_TYPE IS 'eTeamデータ型';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.OP_COLUME_ID IS 'OPEN21カラムID';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.OP_COLUMN_NAME IS 'OPEN21カラム名';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.OP_DATA_TYPE IS 'OPEN21データ型';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.ENTRY_ORDER IS '登録順';
COMMENT ON COLUMN MASTER_TORIKOMI_SHOUSAI_SIAS.PK_FLG IS 'プライマリーキーフラグ';

TRUNCATE TABLE master_torikomi_ichiran_de3;
\copy master_torikomi_ichiran_de3 FROM '.\files\csv\master_torikomi_ichiran_de3.csv' WITH CSV header ENCODING 'SHIFT-JIS';
TRUNCATE TABLE master_torikomi_shousai_de3;
\copy master_torikomi_shousai_de3 FROM '.\files\csv\master_torikomi_shousai_de3.csv' WITH CSV header ENCODING 'SHIFT-JIS';

\copy master_torikomi_ichiran_sias FROM '.\files\csv\master_torikomi_ichiran_sias.csv' WITH CSV header ENCODING 'SHIFT-JIS';
\copy master_torikomi_shousai_sias FROM '.\files\csv\master_torikomi_shousai_sias.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 仕訳テーブルをSIAS版とDE3版に分ける。
-- 今までのものはDE3に変更。
ALTER TABLE SHIWAKE RENAME TO SHIWAKE_DE3;

COMMENT ON TABLE SHIWAKE_DE3 IS '仕訳抽出(de3)';

CREATE TABLE SHIWAKE_SIAS
(
	SERIAL_NO BIGSERIAL NOT NULL,
	DENPYOU_ID VARCHAR(19) NOT NULL,
	SHIWAKE_STATUS VARCHAR(1) NOT NULL,
	TOUROKU_TIME TIMESTAMP,
	KOUSHIN_TIME TIMESTAMP,
	DYMD DATE,
	SEIRI VARCHAR(1) NOT NULL,
	DCNO VARCHAR(8) NOT NULL,
	KYMD DATE,
	KBMN VARCHAR(8) NOT NULL,
	KUSR VARCHAR(12) NOT NULL,
	SGNO VARCHAR(4) NOT NULL,
	HF1 VARCHAR(20) NOT NULL,
	HF2 VARCHAR(20) NOT NULL,
	HF3 VARCHAR(20) NOT NULL,
	HF4 VARCHAR(20) NOT NULL,
	HF5 VARCHAR(20) NOT NULL,
	HF6 VARCHAR(20) NOT NULL,
	HF7 VARCHAR(20) NOT NULL,
	HF8 VARCHAR(20) NOT NULL,
	HF9 VARCHAR(20) NOT NULL,
	HF10 VARCHAR(20) NOT NULL,
	RBMN VARCHAR(8) NOT NULL,
	RTOR VARCHAR(12) NOT NULL,
	RKMK VARCHAR(6) NOT NULL,
	REDA VARCHAR(12) NOT NULL,
	RKOJ VARCHAR(10) NOT NULL,
	RKOS VARCHAR(6) NOT NULL,
	RPRJ VARCHAR(12) NOT NULL,
	RSEG VARCHAR(8) NOT NULL,
	RDM1 VARCHAR(20) NOT NULL,
	RDM2 VARCHAR(20) NOT NULL,
	RDM3 VARCHAR(20) NOT NULL,
	RDM4 VARCHAR(20) NOT NULL,
	RDM5 VARCHAR(20) NOT NULL,
	RDM6 VARCHAR(20) NOT NULL,
	RDM7 VARCHAR(20) NOT NULL,
	RDM8 VARCHAR(20) NOT NULL,
	RDM9 VARCHAR(20) NOT NULL,
	RDM10 VARCHAR(20) NOT NULL,
	RDM11 VARCHAR(20) NOT NULL,
	RDM12 VARCHAR(20) NOT NULL,
	RDM13 VARCHAR(20) NOT NULL,
	RDM14 VARCHAR(20) NOT NULL,
	RDM15 VARCHAR(20) NOT NULL,
	RDM16 VARCHAR(20) NOT NULL,
	RDM17 VARCHAR(20) NOT NULL,
	RDM18 VARCHAR(20) NOT NULL,
	RDM19 VARCHAR(20) NOT NULL,
	RDM20 VARCHAR(20) NOT NULL,
	RRIT DECIMAL(3),
	RZKB VARCHAR(3) NOT NULL,
	RGYO VARCHAR(1) NOT NULL,
	RSRE VARCHAR(1) NOT NULL,
	RTKY VARCHAR(60) NOT NULL,
	RTNO VARCHAR(4) NOT NULL,
	SBMN VARCHAR(8) NOT NULL,
	STOR VARCHAR(12) NOT NULL,
	SKMK VARCHAR(6) NOT NULL,
	SEDA VARCHAR(12) NOT NULL,
	SKOJ VARCHAR(10) NOT NULL,
	SKOS VARCHAR(6) NOT NULL,
	SPRJ VARCHAR(12) NOT NULL,
	SSEG VARCHAR(8) NOT NULL,
	SDM1 VARCHAR(20) NOT NULL,
	SDM2 VARCHAR(20) NOT NULL,
	SDM3 VARCHAR(20) NOT NULL,
	SDM4 VARCHAR(20) NOT NULL,
	SDM5 VARCHAR(20) NOT NULL,
	SDM6 VARCHAR(20) NOT NULL,
	SDM7 VARCHAR(20) NOT NULL,
	SDM8 VARCHAR(20) NOT NULL,
	SDM9 VARCHAR(20) NOT NULL,
	SDM10 VARCHAR(20) NOT NULL,
	SDM11 VARCHAR(20) NOT NULL,
	SDM12 VARCHAR(20) NOT NULL,
	SDM13 VARCHAR(20) NOT NULL,
	SDM14 VARCHAR(20) NOT NULL,
	SDM15 VARCHAR(20) NOT NULL,
	SDM16 VARCHAR(20) NOT NULL,
	SDM17 VARCHAR(20) NOT NULL,
	SDM18 VARCHAR(20) NOT NULL,
	SDM19 VARCHAR(20) NOT NULL,
	SDM20 VARCHAR(20) NOT NULL,
	SRIT DECIMAL(3),
	SZKB VARCHAR(3) NOT NULL,
	SGYO VARCHAR(1) NOT NULL,
	SSRE VARCHAR(1) NOT NULL,
	STKY VARCHAR(60) NOT NULL,
	STNO VARCHAR(4) NOT NULL,
	ZKMK VARCHAR(6) NOT NULL,
	ZRIT DECIMAL(3),
	ZZKB VARCHAR(3) NOT NULL,
	ZGYO VARCHAR(1) NOT NULL,
	ZSRE VARCHAR(1) NOT NULL,
	EXVL DECIMAL(15),
	VALU DECIMAL(15),
	SYMD DATE,
	SKBN VARCHAR(2) NOT NULL,
	SKIZ DATE,
	UYMD DATE,
	UKBN VARCHAR(2) NOT NULL,
	UKIZ DATE,
	DKEC VARCHAR(12) NOT NULL,
	FUSR VARCHAR(4) NOT NULL,
	FSEN VARCHAR(2) NOT NULL,
	TKFLG VARCHAR(1) NOT NULL,
	BUNRI VARCHAR(1) NOT NULL,
	HEIC VARCHAR(4) NOT NULL,
	RATE VARCHAR(12) NOT NULL,
	GEXVL VARCHAR(14) NOT NULL,
	GVALU VARCHAR(14) NOT NULL,
	GSEP VARCHAR(1) NOT NULL,
	PRIMARY KEY (SERIAL_NO)
) WITHOUT OIDS;

COMMENT ON TABLE SHIWAKE_SIAS IS '仕訳抽出(SIAS)';
COMMENT ON COLUMN SHIWAKE_SIAS.SERIAL_NO IS 'シリアル番号';
COMMENT ON COLUMN SHIWAKE_SIAS.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SHIWAKE_SIAS.SHIWAKE_STATUS IS '仕訳抽出状態';
COMMENT ON COLUMN SHIWAKE_SIAS.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHIWAKE_SIAS.KOUSHIN_TIME IS '更新日時';
COMMENT ON COLUMN SHIWAKE_SIAS.DYMD IS '（オープン２１）伝票日付';
COMMENT ON COLUMN SHIWAKE_SIAS.SEIRI IS '（オープン２１）整理月フラグ';
COMMENT ON COLUMN SHIWAKE_SIAS.DCNO IS '（オープン２１）伝票番号';
COMMENT ON COLUMN SHIWAKE_SIAS.KYMD IS '（オープン２１）起票年月日';
COMMENT ON COLUMN SHIWAKE_SIAS.KBMN IS '（オープン２１）起票部門コード';
COMMENT ON COLUMN SHIWAKE_SIAS.KUSR IS '（オープン２１）起票者コード';
COMMENT ON COLUMN SHIWAKE_SIAS.SGNO IS '（オープン２１）承認グループNo.';
COMMENT ON COLUMN SHIWAKE_SIAS.HF1 IS '（オープン２１）ヘッダーフィールド１';
COMMENT ON COLUMN SHIWAKE_SIAS.HF2 IS '（オープン２１）ヘッダーフィールド２';
COMMENT ON COLUMN SHIWAKE_SIAS.HF3 IS '（オープン２１）ヘッダーフィールド３';
COMMENT ON COLUMN SHIWAKE_SIAS.HF4 IS '（オープン２１）ヘッダーフィールド４';
COMMENT ON COLUMN SHIWAKE_SIAS.HF5 IS '（オープン２１）ヘッダーフィールド５';
COMMENT ON COLUMN SHIWAKE_SIAS.HF6 IS '（オープン２１）ヘッダーフィールド６';
COMMENT ON COLUMN SHIWAKE_SIAS.HF7 IS '（オープン２１）ヘッダーフィールド７';
COMMENT ON COLUMN SHIWAKE_SIAS.HF8 IS '（オープン２１）ヘッダーフィールド８';
COMMENT ON COLUMN SHIWAKE_SIAS.HF9 IS '（オープン２１）ヘッダーフィールド９';
COMMENT ON COLUMN SHIWAKE_SIAS.HF10 IS '（オープン２１）ヘッダーフィールド１０';
COMMENT ON COLUMN SHIWAKE_SIAS.RBMN IS '（オープン２１）借方　部門コード';
COMMENT ON COLUMN SHIWAKE_SIAS.RTOR IS '（オープン２１）借方　取引先コード';
COMMENT ON COLUMN SHIWAKE_SIAS.RKMK IS '（オープン２１）借方　科目コード';
COMMENT ON COLUMN SHIWAKE_SIAS.REDA IS '（オープン２１）借方　枝番コード';
COMMENT ON COLUMN SHIWAKE_SIAS.RKOJ IS '（オープン２１）借方　工事コード';
COMMENT ON COLUMN SHIWAKE_SIAS.RKOS IS '（オープン２１）借方　工種コード';
COMMENT ON COLUMN SHIWAKE_SIAS.RPRJ IS '（オープン２１）借方　プロジェクトコード';
COMMENT ON COLUMN SHIWAKE_SIAS.RSEG IS '（オープン２１）借方　セグメントコード';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM1 IS '（オープン２１）借方　ユニバーサルフィールド１';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM2 IS '（オープン２１）借方　ユニバーサルフィールド２';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM3 IS '（オープン２１）借方　ユニバーサルフィールド３';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM4 IS '（オープン２１）借方　ユニバーサルフィールド４';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM5 IS '（オープン２１）借方　ユニバーサルフィールド５';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM6 IS '（オープン２１）借方　ユニバーサルフィールド６';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM7 IS '（オープン２１）借方　ユニバーサルフィールド７';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM8 IS '（オープン２１）借方　ユニバーサルフィールド８';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM9 IS '（オープン２１）借方　ユニバーサルフィールド９';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM10 IS '（オープン２１）借方　ユニバーサルフィールド１０';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM11 IS '（オープン２１）借方　ユニバーサルフィールド１１';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM12 IS '（オープン２１）借方　ユニバーサルフィールド１２';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM13 IS '（オープン２１）借方　ユニバーサルフィールド１３';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM14 IS '（オープン２１）借方　ユニバーサルフィールド１４';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM15 IS '（オープン２１）借方　ユニバーサルフィールド１５';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM16 IS '（オープン２１）借方　ユニバーサルフィールド１６';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM17 IS '（オープン２１）借方　ユニバーサルフィールド１７';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM18 IS '（オープン２１）借方　ユニバーサルフィールド１８';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM19 IS '（オープン２１）借方　ユニバーサルフィールド１９';
COMMENT ON COLUMN SHIWAKE_SIAS.RDM20 IS '（オープン２１）借方　ユニバーサルフィールド２０';
COMMENT ON COLUMN SHIWAKE_SIAS.RRIT IS '（オープン２１）借方　税率';
COMMENT ON COLUMN SHIWAKE_SIAS.RZKB IS '（オープン２１）借方　課税区分';
COMMENT ON COLUMN SHIWAKE_SIAS.RGYO IS '（オープン２１）借方　業種区分';
COMMENT ON COLUMN SHIWAKE_SIAS.RSRE IS '（オープン２１）借方　仕入区分';
COMMENT ON COLUMN SHIWAKE_SIAS.RTKY IS '（オープン２１）借方　摘要';
COMMENT ON COLUMN SHIWAKE_SIAS.RTNO IS '（オープン２１）借方　摘要コード';
COMMENT ON COLUMN SHIWAKE_SIAS.SBMN IS '（オープン２１）貸方　部門コード';
COMMENT ON COLUMN SHIWAKE_SIAS.STOR IS '（オープン２１）貸方　取引先コード';
COMMENT ON COLUMN SHIWAKE_SIAS.SKMK IS '（オープン２１）貸方　科目コード';
COMMENT ON COLUMN SHIWAKE_SIAS.SEDA IS '（オープン２１）貸方　枝番コード';
COMMENT ON COLUMN SHIWAKE_SIAS.SKOJ IS '（オープン２１）貸方　工事コード';
COMMENT ON COLUMN SHIWAKE_SIAS.SKOS IS '（オープン２１）貸方　工種コード';
COMMENT ON COLUMN SHIWAKE_SIAS.SPRJ IS '（オープン２１）貸方　プロジェクトコード';
COMMENT ON COLUMN SHIWAKE_SIAS.SSEG IS '（オープン２１）貸方　セグメントコード';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM1 IS '（オープン２１）貸方　ユニバーサルフィールド１';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM2 IS '（オープン２１）貸方　ユニバーサルフィールド２';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM3 IS '（オープン２１）貸方　ユニバーサルフィールド３';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM4 IS '（オープン２１）貸方　ユニバーサルフィールド４';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM5 IS '（オープン２１）貸方　ユニバーサルフィールド５';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM6 IS '（オープン２１）貸方　ユニバーサルフィールド６';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM7 IS '（オープン２１）貸方　ユニバーサルフィールド７';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM8 IS '（オープン２１）貸方　ユニバーサルフィールド８';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM9 IS '（オープン２１）貸方　ユニバーサルフィールド９';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM10 IS '（オープン２１）貸方　ユニバーサルフィールド１０';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM11 IS '（オープン２１）貸方　ユニバーサルフィールド１１';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM12 IS '（オープン２１）貸方　ユニバーサルフィールド１２';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM13 IS '（オープン２１）貸方　ユニバーサルフィールド１３';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM14 IS '（オープン２１）貸方　ユニバーサルフィールド１４';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM15 IS '（オープン２１）貸方　ユニバーサルフィールド１５';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM16 IS '（オープン２１）貸方　ユニバーサルフィールド１６';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM17 IS '（オープン２１）貸方　ユニバーサルフィールド１７';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM18 IS '（オープン２１）貸方　ユニバーサルフィールド１８';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM19 IS '（オープン２１）貸方　ユニバーサルフィールド１９';
COMMENT ON COLUMN SHIWAKE_SIAS.SDM20 IS '（オープン２１）貸方　ユニバーサルフィールド２０';
COMMENT ON COLUMN SHIWAKE_SIAS.SRIT IS '（オープン２１）貸方　税率';
COMMENT ON COLUMN SHIWAKE_SIAS.SZKB IS '（オープン２１）貸方　課税区分';
COMMENT ON COLUMN SHIWAKE_SIAS.SGYO IS '（オープン２１）貸方　業種区分';
COMMENT ON COLUMN SHIWAKE_SIAS.SSRE IS '（オープン２１）貸方　仕入区分';
COMMENT ON COLUMN SHIWAKE_SIAS.STKY IS '（オープン２１）貸方　摘要';
COMMENT ON COLUMN SHIWAKE_SIAS.STNO IS '（オープン２１）貸方　摘要コード';
COMMENT ON COLUMN SHIWAKE_SIAS.ZKMK IS '（オープン２１）消費税対象科目コード';
COMMENT ON COLUMN SHIWAKE_SIAS.ZRIT IS '（オープン２１）消費税対象科目税率';
COMMENT ON COLUMN SHIWAKE_SIAS.ZZKB IS '（オープン２１）消費税対象科目　課税区分';
COMMENT ON COLUMN SHIWAKE_SIAS.ZGYO IS '（オープン２１）消費税対象科目　業種区分';
COMMENT ON COLUMN SHIWAKE_SIAS.ZSRE IS '（オープン２１）消費税対象科目　仕入区分';
COMMENT ON COLUMN SHIWAKE_SIAS.EXVL IS '（オープン２１）対価金額';
COMMENT ON COLUMN SHIWAKE_SIAS.VALU IS '（オープン２１）金額';
COMMENT ON COLUMN SHIWAKE_SIAS.SYMD IS '（オープン２１）支払日';
COMMENT ON COLUMN SHIWAKE_SIAS.SKBN IS '（オープン２１）支払区分';
COMMENT ON COLUMN SHIWAKE_SIAS.SKIZ IS '（オープン２１）支払期日';
COMMENT ON COLUMN SHIWAKE_SIAS.UYMD IS '（オープン２１）回収日';
COMMENT ON COLUMN SHIWAKE_SIAS.UKBN IS '（オープン２１）入金区分';
COMMENT ON COLUMN SHIWAKE_SIAS.UKIZ IS '（オープン２１）回収期日';
COMMENT ON COLUMN SHIWAKE_SIAS.DKEC IS '（オープン２１）消込コード';
COMMENT ON COLUMN SHIWAKE_SIAS.FUSR IS '（オープン２１）入力者コード';
COMMENT ON COLUMN SHIWAKE_SIAS.FSEN IS '（オープン２１）付箋番号';
COMMENT ON COLUMN SHIWAKE_SIAS.TKFLG IS '（オープン２１）貸借別摘要フラグ';
COMMENT ON COLUMN SHIWAKE_SIAS.BUNRI IS '（オープン２１）分離区分';
COMMENT ON COLUMN SHIWAKE_SIAS.HEIC IS '（オープン２１）幣種';
COMMENT ON COLUMN SHIWAKE_SIAS.RATE IS '（オープン２１）レート';
COMMENT ON COLUMN SHIWAKE_SIAS.GEXVL IS '（オープン２１）外貨対価金額';
COMMENT ON COLUMN SHIWAKE_SIAS.GVALU IS '（オープン２１）外貨金額';
COMMENT ON COLUMN SHIWAKE_SIAS.GSEP IS '（オープン２１）行区切り';

-- 画面権限制御の変更
TRUNCATE TABLE gamen_kengen_seigyo;
\copy gamen_kengen_seigyo FROM '.\files\csv\gamen_kengen_seigyo.csv' WITH CSV header ENCODING 'SHIFT-JIS';

-- 設定情報データ変更(de3版からの移行のみ)
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info;
\copy setting_info FROM '.\files\csv\setting_info_de3.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 設定情報テーブルの「ユニバーサルフィールド伝票ID反映」「社員コード連携」設定値を新設定値向けに変更
UPDATE setting_info SET setting_val = '0' WHERE setting_name = 'uf1_denpyou_id_hanei' AND setting_val = '0';
UPDATE setting_info SET setting_val = 'UF1' WHERE setting_name = 'uf1_denpyou_id_hanei' AND setting_val = '1';

UPDATE setting_info SET setting_val = '0' WHERE setting_name = 'shain_cd_renkei' AND setting_val = '0';
UPDATE setting_info SET setting_val = 'UF1' WHERE setting_name = 'shain_cd_renkei' AND setting_val = '1';
UPDATE setting_info SET setting_val = 'UF2' WHERE setting_name = 'shain_cd_renkei' AND setting_val = '2';
UPDATE setting_info SET setting_val = 'UF3' WHERE setting_name = 'shain_cd_renkei' AND setting_val = '3';
UPDATE setting_info SET setting_val = 'T' WHERE setting_name = 'shain_cd_renkei' AND setting_val = '4';


-- ユニバーサルフィールドの正式名称カラムを消去
-- UF1
ALTER TABLE UF1_ICHIRAN RENAME TO UF1_ICHIRAN_OLD;

CREATE TABLE UF1_ICHIRAN
(
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	PRIMARY KEY (UF1_CD)
) WITHOUT OIDS;

COMMENT ON TABLE UF1_ICHIRAN IS 'ユニバーサルフィールド１一覧';
COMMENT ON COLUMN UF1_ICHIRAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN UF1_ICHIRAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN UF1_ICHIRAN.KESSANKI_BANGOU IS '決算期番号';

INSERT INTO UF1_ICHIRAN(
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	KESSANKI_BANGOU
)
SELECT
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	KESSANKI_BANGOU
FROM UF1_ICHIRAN_OLD;

DROP TABLE UF1_ICHIRAN_OLD;


-- UF2
ALTER TABLE UF2_ICHIRAN RENAME TO UF2_ICHIRAN_OLD;

CREATE TABLE UF2_ICHIRAN
(
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	PRIMARY KEY (UF2_CD)
) WITHOUT OIDS;

COMMENT ON TABLE UF2_ICHIRAN IS 'ユニバーサルフィールド２一覧';
COMMENT ON COLUMN UF2_ICHIRAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN UF2_ICHIRAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN UF2_ICHIRAN.KESSANKI_BANGOU IS '決算期番号';

INSERT INTO UF2_ICHIRAN(
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	KESSANKI_BANGOU
)
SELECT
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	KESSANKI_BANGOU
FROM UF2_ICHIRAN_OLD;

DROP TABLE UF2_ICHIRAN_OLD;


-- UF3
ALTER TABLE UF3_ICHIRAN RENAME TO UF3_ICHIRAN_OLD;

CREATE TABLE UF3_ICHIRAN
(
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	PRIMARY KEY (UF3_CD)
) WITHOUT OIDS;

COMMENT ON TABLE UF3_ICHIRAN IS 'ユニバーサルフィールド３一覧';
COMMENT ON COLUMN UF3_ICHIRAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN UF3_ICHIRAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN UF3_ICHIRAN.KESSANKI_BANGOU IS '決算期番号';

INSERT INTO UF3_ICHIRAN(
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	KESSANKI_BANGOU
)
SELECT
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	KESSANKI_BANGOU
FROM UF3_ICHIRAN_OLD;

DROP TABLE UF3_ICHIRAN_OLD;

-- UF1
ALTER TABLE UF1_ZANDAKA RENAME TO UF1_ZANDAKA_OLD;

CREATE TABLE UF1_ZANDAKA
(
	UF1_CD VARCHAR(20) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	CHOUHYOU_SHATURYOKU_NO SMALLINT,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	KAMOKU_NAME_SEISHIKI VARCHAR(40) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT NOT NULL,
	KISHU_ZANDAKA DECIMAL(19,0) NOT NULL,
	PRIMARY KEY (UF1_CD, KAMOKU_GAIBU_CD)
) WITHOUT OIDS;

COMMENT ON TABLE UF1_ZANDAKA IS 'ユニバーサルフィールド１残高';
COMMENT ON COLUMN UF1_ZANDAKA.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN UF1_ZANDAKA.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN UF1_ZANDAKA.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN UF1_ZANDAKA.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN UF1_ZANDAKA.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN UF1_ZANDAKA.CHOUHYOU_SHATURYOKU_NO IS '帳票出力順番号';
COMMENT ON COLUMN UF1_ZANDAKA.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN UF1_ZANDAKA.KAMOKU_NAME_SEISHIKI IS '科目名（正式）';
COMMENT ON COLUMN UF1_ZANDAKA.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON COLUMN UF1_ZANDAKA.KISHU_ZANDAKA IS '期首残高';

INSERT INTO UF1_ZANDAKA(
	UF1_CD,
	KAMOKU_GAIBU_CD,
	KESSANKI_BANGOU,
	KAMOKU_NAIBU_CD,
	UF1_NAME_RYAKUSHIKI,
	CHOUHYOU_SHATURYOKU_NO,
	KAMOKU_NAME_RYAKUSHIKI,
	KAMOKU_NAME_SEISHIKI,
	TAISHAKU_ZOKUSEI,
	KISHU_ZANDAKA
)
SELECT
	UF1_CD,
	KAMOKU_GAIBU_CD,
	KESSANKI_BANGOU,
	KAMOKU_NAIBU_CD,
	UF1_NAME_RYAKUSHIKI,
	CHOUHYOU_SHATURYOKU_NO,
	KAMOKU_NAME_RYAKUSHIKI,
	KAMOKU_NAME_SEISHIKI,
	TAISHAKU_ZOKUSEI,
	KISHU_ZANDAKA
FROM UF1_ZANDAKA_OLD;

DROP TABLE UF1_ZANDAKA_OLD;

-- UF2
ALTER TABLE UF2_ZANDAKA RENAME TO UF2_ZANDAKA_OLD;

CREATE TABLE UF2_ZANDAKA
(
	UF2_CD VARCHAR(20) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	CHOUHYOU_SHATURYOKU_NO SMALLINT,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	KAMOKU_NAME_SEISHIKI VARCHAR(40) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT NOT NULL,
	KISHU_ZANDAKA DECIMAL(19,0) NOT NULL,
	PRIMARY KEY (UF2_CD, KAMOKU_GAIBU_CD)
) WITHOUT OIDS;
COMMENT ON TABLE UF2_ZANDAKA IS 'ユニバーサルフィールド２残高';
COMMENT ON COLUMN UF2_ZANDAKA.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN UF2_ZANDAKA.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN UF2_ZANDAKA.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN UF2_ZANDAKA.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN UF2_ZANDAKA.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN UF2_ZANDAKA.CHOUHYOU_SHATURYOKU_NO IS '帳票出力順番号';
COMMENT ON COLUMN UF2_ZANDAKA.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN UF2_ZANDAKA.KAMOKU_NAME_SEISHIKI IS '科目名（正式）';
COMMENT ON COLUMN UF2_ZANDAKA.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON COLUMN UF2_ZANDAKA.KISHU_ZANDAKA IS '期首残高';

INSERT INTO UF2_ZANDAKA(
	UF2_CD,
	KAMOKU_GAIBU_CD,
	KESSANKI_BANGOU,
	KAMOKU_NAIBU_CD,
	UF2_NAME_RYAKUSHIKI,
	CHOUHYOU_SHATURYOKU_NO,
	KAMOKU_NAME_RYAKUSHIKI,
	KAMOKU_NAME_SEISHIKI,
	TAISHAKU_ZOKUSEI,
	KISHU_ZANDAKA
)
SELECT
	UF2_CD,
	KAMOKU_GAIBU_CD,
	KESSANKI_BANGOU,
	KAMOKU_NAIBU_CD,
	UF2_NAME_RYAKUSHIKI,
	CHOUHYOU_SHATURYOKU_NO,
	KAMOKU_NAME_RYAKUSHIKI,
	KAMOKU_NAME_SEISHIKI,
	TAISHAKU_ZOKUSEI,
	KISHU_ZANDAKA
FROM UF2_ZANDAKA_OLD;

DROP TABLE UF2_ZANDAKA_OLD;

--UF3
ALTER TABLE UF3_ZANDAKA RENAME TO UF3_ZANDAKA_OLD;

CREATE TABLE UF3_ZANDAKA
(
	UF3_CD VARCHAR(20) NOT NULL,
	KAMOKU_GAIBU_CD VARCHAR(8) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	KAMOKU_NAIBU_CD VARCHAR(15) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	CHOUHYOU_SHATURYOKU_NO SMALLINT,
	KAMOKU_NAME_RYAKUSHIKI VARCHAR(22) NOT NULL,
	KAMOKU_NAME_SEISHIKI VARCHAR(40) NOT NULL,
	TAISHAKU_ZOKUSEI SMALLINT NOT NULL,
	KISHU_ZANDAKA DECIMAL(19,0) NOT NULL,
	PRIMARY KEY (UF3_CD, KAMOKU_GAIBU_CD)
) WITHOUT OIDS;
COMMENT ON TABLE UF3_ZANDAKA IS 'ユニバーサルフィールド３残高';
COMMENT ON COLUMN UF3_ZANDAKA.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN UF3_ZANDAKA.KAMOKU_GAIBU_CD IS '科目外部コード';
COMMENT ON COLUMN UF3_ZANDAKA.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN UF3_ZANDAKA.KAMOKU_NAIBU_CD IS '科目内部コード';
COMMENT ON COLUMN UF3_ZANDAKA.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN UF3_ZANDAKA.CHOUHYOU_SHATURYOKU_NO IS '帳票出力順番号';
COMMENT ON COLUMN UF3_ZANDAKA.KAMOKU_NAME_RYAKUSHIKI IS '科目名（略式）';
COMMENT ON COLUMN UF3_ZANDAKA.KAMOKU_NAME_SEISHIKI IS '科目名（正式）';
COMMENT ON COLUMN UF3_ZANDAKA.TAISHAKU_ZOKUSEI IS '貸借属性';
COMMENT ON COLUMN UF3_ZANDAKA.KISHU_ZANDAKA IS '期首残高';

INSERT INTO UF3_ZANDAKA(
	UF3_CD,
	KAMOKU_GAIBU_CD,
	KESSANKI_BANGOU,
	KAMOKU_NAIBU_CD,
	UF3_NAME_RYAKUSHIKI,
	CHOUHYOU_SHATURYOKU_NO,
	KAMOKU_NAME_RYAKUSHIKI,
	KAMOKU_NAME_SEISHIKI,
	TAISHAKU_ZOKUSEI,
	KISHU_ZANDAKA
)
SELECT
	UF3_CD,
	KAMOKU_GAIBU_CD,
	KESSANKI_BANGOU,
	KAMOKU_NAIBU_CD,
	UF3_NAME_RYAKUSHIKI,
	CHOUHYOU_SHATURYOKU_NO,
	KAMOKU_NAME_RYAKUSHIKI,
	KAMOKU_NAME_SEISHIKI,
	TAISHAKU_ZOKUSEI,
	KISHU_ZANDAKA
FROM UF3_ZANDAKA_OLD;

DROP TABLE UF3_ZANDAKA_OLD;

-- 会社情報のHFとUFを1～3のみにする。
ALTER TABLE KAISHA_INFO RENAME TO KAISHA_INFO_OLD;

CREATE TABLE KAISHA_INFO
(
	KESSANKI_BANGOU SMALLINT NOT NULL,
	HF1_SHIYOU_FLG SMALLINT NOT NULL,
	HF1_HISSU_FLG VARCHAR(1) NOT NULL,
	HF1_NAME VARCHAR NOT NULL,
	HF2_SHIYOU_FLG SMALLINT NOT NULL,
	HF2_HISSU_FLG VARCHAR(1) NOT NULL,
	HF2_NAME VARCHAR NOT NULL,
	HF3_SHIYOU_FLG SMALLINT NOT NULL,
	HF3_HISSU_FLG VARCHAR(1) NOT NULL,
	HF3_NAME VARCHAR NOT NULL,
	UF1_SHIYOU_FLG SMALLINT NOT NULL,
	UF1_NAME VARCHAR NOT NULL,
	UF2_SHIYOU_FLG SMALLINT NOT NULL,
	UF2_NAME VARCHAR NOT NULL,
	UF3_SHIYOU_FLG SMALLINT NOT NULL,
	UF3_NAME VARCHAR NOT NULL,
	PJCD_SHIYOU_FLG SMALLINT NOT NULL
) WITHOUT OIDS;

COMMENT ON TABLE KAISHA_INFO IS '会社情報';
COMMENT ON COLUMN KAISHA_INFO.KESSANKI_BANGOU IS '決算期番号';
COMMENT ON COLUMN KAISHA_INFO.HF1_SHIYOU_FLG IS 'HF1使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.HF1_HISSU_FLG IS 'HF1必須フラグ';
COMMENT ON COLUMN KAISHA_INFO.HF1_NAME IS 'HF1名';
COMMENT ON COLUMN KAISHA_INFO.HF2_SHIYOU_FLG IS 'HF2使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.HF2_HISSU_FLG IS 'HF2必須フラグ';
COMMENT ON COLUMN KAISHA_INFO.HF2_NAME IS 'HF2名';
COMMENT ON COLUMN KAISHA_INFO.HF3_SHIYOU_FLG IS 'HF3使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.HF3_HISSU_FLG IS 'HF3必須フラグ';
COMMENT ON COLUMN KAISHA_INFO.HF3_NAME IS 'HF3名';
COMMENT ON COLUMN KAISHA_INFO.UF1_SHIYOU_FLG IS 'UF1使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.UF1_NAME IS 'UF1名';
COMMENT ON COLUMN KAISHA_INFO.UF2_SHIYOU_FLG IS 'UF2使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.UF2_NAME IS 'UF2名';
COMMENT ON COLUMN KAISHA_INFO.UF3_SHIYOU_FLG IS 'UF3使用フラグ';
COMMENT ON COLUMN KAISHA_INFO.UF3_NAME IS 'UF3名';
COMMENT ON COLUMN KAISHA_INFO.PJCD_SHIYOU_FLG IS 'プロジェクトコード使用フラグ';

INSERT INTO KAISHA_INFO(
	KESSANKI_BANGOU,
	HF1_SHIYOU_FLG,
	HF1_HISSU_FLG,
	HF1_NAME,
	HF2_SHIYOU_FLG,
	HF2_HISSU_FLG,
	HF2_NAME,
	HF3_SHIYOU_FLG,
	HF3_HISSU_FLG,
	HF3_NAME,
	UF1_SHIYOU_FLG,
	UF1_NAME,
	UF2_SHIYOU_FLG,
	UF2_NAME,
	UF3_SHIYOU_FLG,
	UF3_NAME,
	PJCD_SHIYOU_FLG
)SELECT
	KESSANKI_BANGOU,
	0,
	0,
	'',
	0,
	0,
	'',
	0,
	0,
	'',
	UF1_SHIYOU_FLG,
	UF1_NAME,
	UF2_SHIYOU_FLG,
	UF2_NAME,
	UF3_SHIYOU_FLG,
	UF3_NAME,
	PJCD_SHIYOU_FLG
FROM KAISHA_INFO_OLD;

DROP TABLE KAISHA_INFO_OLD;


-- ヘッダフィールドの追加
-- HF1
CREATE TABLE HF1_ICHIRAN
(
	HF1_CD VARCHAR(20) NOT NULL,
	HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	PRIMARY KEY (HF1_CD)
) WITHOUT OIDS;
COMMENT ON TABLE HF1_ICHIRAN IS 'ヘッダフィールド１一覧';
COMMENT ON COLUMN HF1_ICHIRAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN HF1_ICHIRAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN HF1_ICHIRAN.KESSANKI_BANGOU IS '決算期番号';

CREATE TABLE HF2_ICHIRAN
(
	HF2_CD VARCHAR(20) NOT NULL,
	HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	PRIMARY KEY (HF2_CD)
) WITHOUT OIDS;
COMMENT ON TABLE HF2_ICHIRAN IS 'ヘッダフィールド２一覧';
COMMENT ON COLUMN HF2_ICHIRAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN HF2_ICHIRAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN HF2_ICHIRAN.KESSANKI_BANGOU IS '決算期番号';

CREATE TABLE HF3_ICHIRAN
(
	HF3_CD VARCHAR(20) NOT NULL,
	HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	KESSANKI_BANGOU SMALLINT,
	PRIMARY KEY (HF3_CD)
) WITHOUT OIDS;
COMMENT ON TABLE HF3_ICHIRAN IS 'ヘッダフィールド３一覧';
COMMENT ON COLUMN HF3_ICHIRAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN HF3_ICHIRAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN HF3_ICHIRAN.KESSANKI_BANGOU IS '決算期番号';

-- 拡張子設定取込
CREATE TABLE EXTENSION_SETTING
(
	EXTENSION_CD VARCHAR(20) NOT NULL,
	EXTENSION_FLG VARCHAR(1) NOT NULL,
	PRIMARY KEY (EXTENSION_CD)
) WITHOUT OIDS;
COMMENT ON TABLE EXTENSION_SETTING IS '拡張子設定';
COMMENT ON COLUMN EXTENSION_SETTING.EXTENSION_CD IS '拡張子コード';
COMMENT ON COLUMN EXTENSION_SETTING.EXTENSION_FLG IS '有効フラグ';

-- 経費立替精算　ヘッダーフィールド追加
ALTER TABLE KEIHISEISAN RENAME TO KEIHISEISAN_OLD;
CREATE TABLE KEIHISEISAN
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
 KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
 SHIYOUBI DATE,
 KEIJOUBI DATE,
 SHIHARAIBI DATE,
 SHIHARAIKIBOUBI DATE,
 SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
 SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
 TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
 TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 ZEIRITSU DECIMAL(3) NOT NULL,
 HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
 SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
 SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
 SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HOSOKU VARCHAR(240) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KEIHISEISAN IS '経費精算';
COMMENT ON COLUMN KEIHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN KEIHISEISAN.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KEIHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KEIHISEISAN.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KEIHISEISAN.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KEIHISEISAN.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KEIHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KEIHISEISAN.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN KEIHISEISAN.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN KEIHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN KEIHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KEIHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KEIHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KEIHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KEIHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO KEIHISEISAN
SELECT
 DENPYOU_ID,
 KARIBARAI_DENPYOU_ID,
 KARIBARAI_MISHIYOU_FLG,
 SHIYOUBI,
 KEIJOUBI,
 SHIHARAIBI,
 SHIHARAIKIBOUBI,
 SHIHARAIHOUHOU,
 SHOUHYOU_SHORUI_FLG,
 TORIHIKISAKI_CD,
 TORIHIKISAKI_NAME_RYAKUSHIKI,
 ZEIRITSU,
 HONTAI_KINGAKU_GOUKEI,
 SHOUHIZEIGAKU_GOUKEI,
 SHIHARAI_KINGAKU_GOUKEI,
 SASHIHIKI_SHIKYUU_KINGAKU,
 '',
 '',
 '',
 '',
 '',
 '',
 HOSOKU,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM KEIHISEISAN_OLD;
DROP TABLE KEIHISEISAN_OLD;

-- 仮払申請　ヘッダーフィールド追加
ALTER TABLE KARIBARAI RENAME TO KARIBARAI_OLD;
CREATE TABLE KARIBARAI
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 SEISAN_YOTEIBI DATE NOT NULL,
 SEISAN_KANRYOUBI DATE,
 SHIHARAIBI DATE,
 SHIHARAIKIBOUBI DATE,
 SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
 TEKIYOU VARCHAR(60) NOT NULL,
 KINGAKU DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HOSOKU VARCHAR(240) NOT NULL,
 SHIWAKE_EDANO INT NOT NULL,
 TORIHIKI_NAME VARCHAR(20) NOT NULL,
 KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
 KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
 UF1_CD VARCHAR(20) NOT NULL,
 UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF2_CD VARCHAR(20) NOT NULL,
 UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF3_CD VARCHAR(20) NOT NULL,
 UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 TEKIYOU_CD VARCHAR(4) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KARIBARAI IS '仮払';
COMMENT ON COLUMN KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KARIBARAI.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN KARIBARAI.SEISAN_KANRYOUBI IS '精算完了日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN KARIBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KARIBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KARIBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KARIBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KARIBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KARIBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KARIBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KARIBARAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO KARIBARAI
SELECT
 DENPYOU_ID,
 SEISAN_YOTEIBI,
 SEISAN_KANRYOUBI,
 SHIHARAIBI,
 SHIHARAIKIBOUBI,
 SHIHARAIHOUHOU,
 TEKIYOU,
 KINGAKU,
 '',
 '',
 '',
 '',
 '',
 '',
 HOSOKU,
 SHIWAKE_EDANO,
 TORIHIKI_NAME,
 KARI_FUTAN_BUMON_CD,
 KARI_FUTAN_BUMON_NAME,
 KARI_KAMOKU_CD,
 KARI_KAMOKU_NAME,
 KARI_KAMOKU_EDABAN_CD,
 KARI_KAMOKU_EDABAN_NAME,
 KARI_KAZEI_KBN,
 KASHI_FUTAN_BUMON_CD,
 KASHI_FUTAN_BUMON_NAME,
 KASHI_KAMOKU_CD,
 KASHI_KAMOKU_NAME,
 KASHI_KAMOKU_EDABAN_CD,
 KASHI_KAMOKU_EDABAN_NAME,
 KASHI_KAZEI_KBN,
 UF1_CD,
 UF1_NAME_RYAKUSHIKI,
 UF2_CD,
 UF2_NAME_RYAKUSHIKI,
 UF3_CD,
 UF3_NAME_RYAKUSHIKI,
 TEKIYOU_CD,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM KARIBARAI_OLD;
DROP TABLE KARIBARAI_OLD;

-- 請求書払い申請　ヘッダーフィールド追加
ALTER TABLE SEIKYUUSHOBARAI RENAME TO SEIKYUUSHOBARAI_OLD;
CREATE TABLE SEIKYUUSHOBARAI
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 KEIJOUBI DATE,
 SHIHARAI_KIGEN DATE NOT NULL,
 SHIHARAIBI DATE,
 MASREF_FLG VARCHAR(1) NOT NULL,
 SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
 KAKE_FLG VARCHAR(1) NOT NULL,
 TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
 TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 FURIKOMISAKI_JOUHOU VARCHAR(240) NOT NULL,
 ZEIRITSU DECIMAL(3) NOT NULL,
 HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
 SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
 SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HOSOKU VARCHAR(240) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE SEIKYUUSHOBARAI IS '請求書払い';
COMMENT ON COLUMN SEIKYUUSHOBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KEIJOUBI IS '計上日';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHIHARAI_KIGEN IS '支払期限';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN SEIKYUUSHOBARAI.MASREF_FLG IS 'マスター参照フラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KAKE_FLG IS '掛けフラグ';
COMMENT ON COLUMN SEIKYUUSHOBARAI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI.FURIKOMISAKI_JOUHOU IS '振込先情報';
COMMENT ON COLUMN SEIKYUUSHOBARAI.ZEIRITSU IS '税率';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN SEIKYUUSHOBARAI.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN SEIKYUUSHOBARAI.HOSOKU IS '補足';
COMMENT ON COLUMN SEIKYUUSHOBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SEIKYUUSHOBARAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO SEIKYUUSHOBARAI
SELECT
 DENPYOU_ID,
 KEIJOUBI,
 SHIHARAI_KIGEN,
 SHIHARAIBI,
 MASREF_FLG,
 SHOUHYOU_SHORUI_FLG,
 KAKE_FLG,
 TORIHIKISAKI_CD,
 TORIHIKISAKI_NAME_RYAKUSHIKI,
 FURIKOMISAKI_JOUHOU,
 ZEIRITSU,
 HONTAI_KINGAKU_GOUKEI,
 SHOUHIZEIGAKU_GOUKEI,
 SHIHARAI_KINGAKU_GOUKEI,
 '',
 '',
 '',
 '',
 '',
 '',
 HOSOKU,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM SEIKYUUSHOBARAI_OLD;
DROP TABLE SEIKYUUSHOBARAI_OLD;

-- 自動引落伝票　ヘッダーフィールド追加
ALTER TABLE JIDOUHIKIOTOSHI RENAME TO JIDOUHIKIOTOSHI_OLD;
CREATE TABLE JIDOUHIKIOTOSHI
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 KEIJOUBI DATE,
 HIKIOTOSHIBI DATE NOT NULL,
 TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
 TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 ZEIRITSU DECIMAL(3) NOT NULL,
 HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
 SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
 SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HOSOKU VARCHAR(240) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE JIDOUHIKIOTOSHI IS '自動引落';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KEIJOUBI IS '計上日';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HIKIOTOSHIBI IS '引落日';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.ZEIRITSU IS '税率';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HOSOKU IS '補足';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KOUSHIN_TIME IS '更新日時';
INSERT INTO JIDOUHIKIOTOSHI
SELECT
 DENPYOU_ID,
 KEIJOUBI,
 HIKIOTOSHIBI,
 TORIHIKISAKI_CD,
 TORIHIKISAKI_NAME_RYAKUSHIKI,
 ZEIRITSU,
 HONTAI_KINGAKU_GOUKEI,
 SHOUHIZEIGAKU_GOUKEI,
 SHIHARAI_KINGAKU_GOUKEI,
 '',
 '',
 '',
 '',
 '',
 '',
 HOSOKU,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM JIDOUHIKIOTOSHI_OLD;
DROP TABLE JIDOUHIKIOTOSHI_OLD;

-- 出張旅費精算（仮払精算）　ヘッダーフィールド追加
ALTER TABLE RYOHISEISAN RENAME TO RYOHISEISAN_OLD;
CREATE TABLE RYOHISEISAN
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
 KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
 HOUMONSAKI VARCHAR(120) NOT NULL,
 MOKUTEKI VARCHAR(240) NOT NULL,
 SEISANKIKAN_FROM DATE,
 SEISANKIKAN_TO DATE,
 KEIJOUBI DATE,
 SHIHARAIBI DATE,
 SHIHARAIKIBOUBI DATE,
 SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
 TEKIYOU VARCHAR(60) NOT NULL,
 ZEIRITSU DECIMAL(3) NOT NULL,
 GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
 SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HOSOKU VARCHAR(240) NOT NULL,
 SHIWAKE_EDANO INT,
 TORIHIKI_NAME VARCHAR(20) NOT NULL,
 KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
 KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
 UF1_CD VARCHAR(20) NOT NULL,
 UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF2_CD VARCHAR(20) NOT NULL,
 UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF3_CD VARCHAR(20) NOT NULL,
 UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 PROJECT_CD VARCHAR(12) NOT NULL,
 PROJECT_NAME VARCHAR(20) NOT NULL,
 TEKIYOU_CD VARCHAR(4) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO RYOHISEISAN
SELECT
 DENPYOU_ID,
 KARIBARAI_DENPYOU_ID,
 KARIBARAI_MISHIYOU_FLG,
 HOUMONSAKI,
 MOKUTEKI,
 SEISANKIKAN_FROM,
 SEISANKIKAN_TO,
 KEIJOUBI,
 SHIHARAIBI,
 SHIHARAIKIBOUBI,
 SHIHARAIHOUHOU,
 TEKIYOU,
 ZEIRITSU,
 GOUKEI_KINGAKU,
 SASHIHIKI_SHIKYUU_KINGAKU,
 '',
 '',
 '',
 '',
 '',
 '',
 HOSOKU,
 SHIWAKE_EDANO,
 TORIHIKI_NAME,
 KARI_FUTAN_BUMON_CD,
 KARI_FUTAN_BUMON_NAME,
 KARI_KAMOKU_CD,
 KARI_KAMOKU_NAME,
 KARI_KAMOKU_EDABAN_CD,
 KARI_KAMOKU_EDABAN_NAME,
 KARI_KAZEI_KBN,
 KASHI_FUTAN_BUMON_CD,
 KASHI_FUTAN_BUMON_NAME,
 KASHI_KAMOKU_CD,
 KASHI_KAMOKU_NAME,
 KASHI_KAMOKU_EDABAN_CD,
 KASHI_KAMOKU_EDABAN_NAME,
 KASHI_KAZEI_KBN,
 UF1_CD,
 UF1_NAME_RYAKUSHIKI,
 UF2_CD,
 UF2_NAME_RYAKUSHIKI,
 UF3_CD,
 UF3_NAME_RYAKUSHIKI,
 PROJECT_CD,
 PROJECT_NAME,
 TEKIYOU_CD,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM RYOHISEISAN_OLD;
DROP TABLE RYOHISEISAN_OLD;

-- 交通費精算　ヘッダーフィールド追加
ALTER TABLE KOUTSUUHISEISAN RENAME TO KOUTSUUHISEISAN_OLD;
CREATE TABLE KOUTSUUHISEISAN
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 MOKUTEKI VARCHAR(240) NOT NULL,
 SEISANKIKAN_FROM DATE,
 SEISANKIKAN_TO DATE,
 KEIJOUBI DATE,
 SHIHARAIBI DATE,
 SHIHARAIKIBOUBI DATE,
 SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
 TEKIYOU VARCHAR(60) NOT NULL,
 ZEIRITSU DECIMAL(3) NOT NULL,
 GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HOSOKU VARCHAR(240) NOT NULL,
 SHIWAKE_EDANO INT,
 TORIHIKI_NAME VARCHAR(20) NOT NULL,
 KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
 KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
 UF1_CD VARCHAR(20) NOT NULL,
 UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF2_CD VARCHAR(20) NOT NULL,
 UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF3_CD VARCHAR(20) NOT NULL,
 UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 PROJECT_CD VARCHAR(12) NOT NULL,
 PROJECT_NAME VARCHAR(20) NOT NULL,
 TEKIYOU_CD VARCHAR(4) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE KOUTSUUHISEISAN IS '交通費精算';
COMMENT ON COLUMN KOUTSUUHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN KOUTSUUHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN KOUTSUUHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KOUTSUUHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_TIME IS '更新日時';
INSERT INTO KOUTSUUHISEISAN
SELECT
 DENPYOU_ID,
 MOKUTEKI,
 SEISANKIKAN_FROM,
 SEISANKIKAN_TO,
 KEIJOUBI,
 SHIHARAIBI,
 SHIHARAIKIBOUBI,
 SHIHARAIHOUHOU,
 TEKIYOU,
 ZEIRITSU,
 GOUKEI_KINGAKU,
 '',
 '',
 '',
 '',
 '',
 '',
 HOSOKU,
 SHIWAKE_EDANO,
 TORIHIKI_NAME,
 KARI_FUTAN_BUMON_CD,
 KARI_FUTAN_BUMON_NAME,
 KARI_KAMOKU_CD,
 KARI_KAMOKU_NAME,
 KARI_KAMOKU_EDABAN_CD,
 KARI_KAMOKU_EDABAN_NAME,
 KARI_KAZEI_KBN,
 KASHI_FUTAN_BUMON_CD,
 KASHI_FUTAN_BUMON_NAME,
 KASHI_KAMOKU_CD,
 KASHI_KAMOKU_NAME,
 KASHI_KAMOKU_EDABAN_CD,
 KASHI_KAMOKU_EDABAN_NAME,
 KASHI_KAZEI_KBN,
 UF1_CD,
 UF1_NAME_RYAKUSHIKI,
 UF2_CD,
 UF2_NAME_RYAKUSHIKI,
 UF3_CD,
 UF3_NAME_RYAKUSHIKI,
 PROJECT_CD,
 PROJECT_NAME,
 TEKIYOU_CD,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM KOUTSUUHISEISAN_OLD;
DROP TABLE KOUTSUUHISEISAN_OLD;

-- 旅費仮払申請　ヘッダーフィールド追加
ALTER TABLE RYOHI_KARIBARAI RENAME TO RYOHI_KARIBARAI_OLD;
CREATE TABLE RYOHI_KARIBARAI
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 MOKUTEKI VARCHAR(240) NOT NULL,
 KIKAN_FROM DATE NOT NULL,
 SHUPPATSU_KBN VARCHAR(1) NOT NULL,
 KIKAN_TO DATE NOT NULL,
 KICHAKU_KBN VARCHAR(1) NOT NULL,
 SEISAN_YOTEIBI DATE NOT NULL,
 SEISAN_KANRYOUBI DATE,
 SHIHARAIBI DATE,
 SHIHARAIKIBOUBI DATE,
 SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
 TEKIYOU VARCHAR(60) NOT NULL,
 KINGAKU DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 SHIWAKE_EDANO INT NOT NULL,
 TORIHIKI_NAME VARCHAR(20) NOT NULL,
 KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
 KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
 UF1_CD VARCHAR(20) NOT NULL,
 UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF2_CD VARCHAR(20) NOT NULL,
 UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF3_CD VARCHAR(20) NOT NULL,
 UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 TEKIYOU_CD VARCHAR(4) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHI_KARIBARAI IS '旅費仮払';
COMMENT ON COLUMN RYOHI_KARIBARAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHI_KARIBARAI.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHI_KARIBARAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHUPPATSU_KBN IS '出発区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.KICHAKU_KBN IS '帰着区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISAN_YOTEIBI IS '精算予定日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SEISAN_KANRYOUBI IS '精算完了日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHI_KARIBARAI.KINGAKU IS '金額';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHI_KARIBARAI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHI_KARIBARAI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHI_KARIBARAI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHI_KARIBARAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO RYOHI_KARIBARAI
SELECT
 DENPYOU_ID,
 MOKUTEKI,
 KIKAN_FROM,
 SHUPPATSU_KBN,
 KIKAN_TO,
 KICHAKU_KBN,
 SEISAN_YOTEIBI,
 SEISAN_KANRYOUBI,
 SHIHARAIBI,
 SHIHARAIKIBOUBI,
 SHIHARAIHOUHOU,
 TEKIYOU,
 KINGAKU,
 '',
 '',
 '',
 '',
 '',
 '',
 SHIWAKE_EDANO,
 TORIHIKI_NAME,
 KARI_FUTAN_BUMON_CD,
 KARI_FUTAN_BUMON_NAME,
 KARI_KAMOKU_CD,
 KARI_KAMOKU_NAME,
 KARI_KAMOKU_EDABAN_CD,
 KARI_KAMOKU_EDABAN_NAME,
 KARI_KAZEI_KBN,
 KASHI_FUTAN_BUMON_CD,
 KASHI_FUTAN_BUMON_NAME,
 KASHI_KAMOKU_CD,
 KASHI_KAMOKU_NAME,
 KASHI_KAMOKU_EDABAN_CD,
 KASHI_KAMOKU_EDABAN_NAME,
 KASHI_KAZEI_KBN,
 UF1_CD,
 UF1_NAME_RYAKUSHIKI,
 UF2_CD,
 UF2_NAME_RYAKUSHIKI,
 UF3_CD,
 UF3_NAME_RYAKUSHIKI,
 TEKIYOU_CD,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM RYOHI_KARIBARAI_OLD;
DROP TABLE RYOHI_KARIBARAI_OLD;

-- 通勤定期申請　ヘッダーフィールド追加
ALTER TABLE TSUUKINTEIKI RENAME TO TSUUKINTEIKI_OLD;
CREATE TABLE TSUUKINTEIKI
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 SHIYOU_KIKAN_KBN VARCHAR(2) NOT NULL,
 SHIYOU_KAISHIBI DATE NOT NULL,
 SHIYOU_SHUURYOUBI DATE NOT NULL,
 JYOUSHA_KUKAN VARCHAR(200) NOT NULL,
 SHIHARAIBI DATE,
 TEKIYOU VARCHAR(60) NOT NULL,
 ZEIRITSU DECIMAL(3) NOT NULL,
 KINGAKU DECIMAL(15) NOT NULL,
 TENYUURYOKU_FLG VARCHAR(1) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 SHIWAKE_EDANO INT NOT NULL,
 TORIHIKI_NAME VARCHAR(20) NOT NULL,
 KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
 KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
 UF1_CD VARCHAR(20) NOT NULL,
 UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF2_CD VARCHAR(20) NOT NULL,
 UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 UF3_CD VARCHAR(20) NOT NULL,
 UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 TEKIYOU_CD VARCHAR(4) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE TSUUKINTEIKI IS '通勤定期';
COMMENT ON COLUMN TSUUKINTEIKI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_KIKAN_KBN IS '使用期間区分';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_KAISHIBI IS '使用開始日';
COMMENT ON COLUMN TSUUKINTEIKI.SHIYOU_SHUURYOUBI IS '使用終了日';
COMMENT ON COLUMN TSUUKINTEIKI.JYOUSHA_KUKAN IS '乗車区間';
COMMENT ON COLUMN TSUUKINTEIKI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN TSUUKINTEIKI.TEKIYOU IS '摘要';
COMMENT ON COLUMN TSUUKINTEIKI.ZEIRITSU IS '税率';
COMMENT ON COLUMN TSUUKINTEIKI.KINGAKU IS '金額';
COMMENT ON COLUMN TSUUKINTEIKI.TENYUURYOKU_FLG IS '手入力フラグ';
COMMENT ON COLUMN TSUUKINTEIKI.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN TSUUKINTEIKI.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN TSUUKINTEIKI.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN TSUUKINTEIKI.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN TSUUKINTEIKI.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN TSUUKINTEIKI.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN TSUUKINTEIKI.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN TSUUKINTEIKI.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN TSUUKINTEIKI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN TSUUKINTEIKI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN TSUUKINTEIKI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN TSUUKINTEIKI.KOUSHIN_TIME IS '更新日時';
INSERT INTO TSUUKINTEIKI
SELECT
 DENPYOU_ID,
 SHIYOU_KIKAN_KBN,
 SHIYOU_KAISHIBI,
 SHIYOU_SHUURYOUBI,
 JYOUSHA_KUKAN,
 SHIHARAIBI,
 TEKIYOU,
 ZEIRITSU,
 KINGAKU,
 TENYUURYOKU_FLG,
 '',
 '',
 '',
 '',
 '',
 '',
 SHIWAKE_EDANO,
 TORIHIKI_NAME,
 KARI_FUTAN_BUMON_CD,
 KARI_FUTAN_BUMON_NAME,
 KARI_KAMOKU_CD,
 KARI_KAMOKU_NAME,
 KARI_KAMOKU_EDABAN_CD,
 KARI_KAMOKU_EDABAN_NAME,
 KARI_KAZEI_KBN,
 KASHI_FUTAN_BUMON_CD,
 KASHI_FUTAN_BUMON_NAME,
 KASHI_KAMOKU_CD,
 KASHI_KAMOKU_NAME,
 KASHI_KAMOKU_EDABAN_CD,
 KASHI_KAMOKU_EDABAN_NAME,
 KASHI_KAZEI_KBN,
 UF1_CD,
 UF1_NAME_RYAKUSHIKI,
 UF2_CD,
 UF2_NAME_RYAKUSHIKI,
 UF3_CD,
 UF3_NAME_RYAKUSHIKI,
 TEKIYOU_CD,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM TSUUKINTEIKI_OLD;
DROP TABLE TSUUKINTEIKI_OLD;

-- 振替伝票　ヘッダーフィールド追加
ALTER TABLE FURIKAE RENAME TO FURIKAE_OLD;
CREATE TABLE FURIKAE
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 DENPYOU_DATE DATE NOT NULL,
 SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
 KINGAKU DECIMAL(15) NOT NULL,
 HONTAI_KINGAKU DECIMAL(15) NOT NULL,
 SHOUHIZEIGAKU DECIMAL(15),
 ZEIRITSU DECIMAL(3) NOT NULL,
 TEKIYOU VARCHAR(60) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 BIKOU VARCHAR(40) NOT NULL,
 KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
 KARI_TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
 KARI_TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
 KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
 KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
 KASHI_TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
 KASHI_TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KARI_UF1_CD VARCHAR(20) NOT NULL,
 KARI_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KARI_UF2_CD VARCHAR(20) NOT NULL,
 KARI_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KARI_UF3_CD VARCHAR(20) NOT NULL,
 KARI_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KASHI_UF1_CD VARCHAR(20) NOT NULL,
 KASHI_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KASHI_UF2_CD VARCHAR(20) NOT NULL,
 KASHI_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KASHI_UF3_CD VARCHAR(20) NOT NULL,
 KASHI_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 KARI_PROJECT_CD VARCHAR(12) NOT NULL,
 KARI_PROJECT_NAME VARCHAR(20) NOT NULL,
 KASHI_PROJECT_CD VARCHAR(12) NOT NULL,
 KASHI_PROJECT_NAME VARCHAR(20) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE FURIKAE IS '振替';
COMMENT ON COLUMN FURIKAE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN FURIKAE.DENPYOU_DATE IS '伝票日付';
COMMENT ON COLUMN FURIKAE.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN FURIKAE.KINGAKU IS '金額';
COMMENT ON COLUMN FURIKAE.HONTAI_KINGAKU IS '本体金額';
COMMENT ON COLUMN FURIKAE.SHOUHIZEIGAKU IS '消費税額';
COMMENT ON COLUMN FURIKAE.ZEIRITSU IS '税率';
COMMENT ON COLUMN FURIKAE.TEKIYOU IS '摘要';
COMMENT ON COLUMN FURIKAE.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN FURIKAE.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN FURIKAE.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN FURIKAE.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN FURIKAE.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN FURIKAE.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN FURIKAE.BIKOU IS '備考（会計伝票）';
COMMENT ON COLUMN FURIKAE.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN FURIKAE.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN FURIKAE.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN FURIKAE.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN FURIKAE.KARI_TORIHIKISAKI_CD IS '借方取引先コード';
COMMENT ON COLUMN FURIKAE.KARI_TORIHIKISAKI_NAME_RYAKUSHIKI IS '借方取引先名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN FURIKAE.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN FURIKAE.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN FURIKAE.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN FURIKAE.KASHI_TORIHIKISAKI_CD IS '貸方取引先コード';
COMMENT ON COLUMN FURIKAE.KASHI_TORIHIKISAKI_NAME_RYAKUSHIKI IS '貸方取引先名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_UF1_CD IS '借方UF1コード';
COMMENT ON COLUMN FURIKAE.KARI_UF1_NAME_RYAKUSHIKI IS '借方UF1名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_UF2_CD IS '借方UF2コード';
COMMENT ON COLUMN FURIKAE.KARI_UF2_NAME_RYAKUSHIKI IS '借方UF2名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_UF3_CD IS '借方UF3コード';
COMMENT ON COLUMN FURIKAE.KARI_UF3_NAME_RYAKUSHIKI IS '借方UF3名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_UF1_CD IS '貸方UF1コード';
COMMENT ON COLUMN FURIKAE.KASHI_UF1_NAME_RYAKUSHIKI IS '貸方UF1名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_UF2_CD IS '貸方UF2コード';
COMMENT ON COLUMN FURIKAE.KASHI_UF2_NAME_RYAKUSHIKI IS '貸方UF2名（略式）';
COMMENT ON COLUMN FURIKAE.KASHI_UF3_CD IS '貸方UF3コード';
COMMENT ON COLUMN FURIKAE.KASHI_UF3_NAME_RYAKUSHIKI IS '貸方UF3名（略式）';
COMMENT ON COLUMN FURIKAE.KARI_PROJECT_CD IS '借方プロジェクトコード';
COMMENT ON COLUMN FURIKAE.KARI_PROJECT_NAME IS '借方プロジェクト名';
COMMENT ON COLUMN FURIKAE.KASHI_PROJECT_CD IS '貸方プロジェクトコード';
COMMENT ON COLUMN FURIKAE.KASHI_PROJECT_NAME IS '貸方プロジェクト名';
COMMENT ON COLUMN FURIKAE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN FURIKAE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN FURIKAE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN FURIKAE.KOUSHIN_TIME IS '更新日時';
INSERT INTO FURIKAE
SELECT
 DENPYOU_ID,
 DENPYOU_DATE,
 SHOUHYOU_SHORUI_FLG,
 KINGAKU,
 HONTAI_KINGAKU,
 SHOUHIZEIGAKU,
 ZEIRITSU,
 TEKIYOU,
 '',
 '',
 '',
 '',
 '',
 '',
 BIKOU,
 KARI_FUTAN_BUMON_CD,
 KARI_FUTAN_BUMON_NAME,
 KARI_KAMOKU_CD,
 KARI_KAMOKU_NAME,
 KARI_KAMOKU_EDABAN_CD,
 KARI_KAMOKU_EDABAN_NAME,
 KARI_KAZEI_KBN,
 KARI_TORIHIKISAKI_CD,
 KARI_TORIHIKISAKI_NAME_RYAKUSHIKI,
 KASHI_FUTAN_BUMON_CD,
 KASHI_FUTAN_BUMON_NAME,
 KASHI_KAMOKU_CD,
 KASHI_KAMOKU_NAME,
 KASHI_KAMOKU_EDABAN_CD,
 KASHI_KAMOKU_EDABAN_NAME,
 KASHI_KAZEI_KBN,
 KASHI_TORIHIKISAKI_CD,
 KASHI_TORIHIKISAKI_NAME_RYAKUSHIKI,
 KARI_UF1_CD,
 KARI_UF1_NAME_RYAKUSHIKI,
 KARI_UF2_CD,
 KARI_UF2_NAME_RYAKUSHIKI,
 KARI_UF3_CD,
 KARI_UF3_NAME_RYAKUSHIKI,
 KASHI_UF1_CD,
 KASHI_UF1_NAME_RYAKUSHIKI,
 KASHI_UF2_CD,
 KASHI_UF2_NAME_RYAKUSHIKI,
 KASHI_UF3_CD,
 KASHI_UF3_NAME_RYAKUSHIKI,
 KARI_PROJECT_CD,
 KARI_PROJECT_NAME,
 KASHI_PROJECT_CD,
 KASHI_PROJECT_NAME,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM FURIKAE_OLD;
DROP TABLE FURIKAE_OLD;

-- 総合付替伝票　ヘッダーフィールド追加
ALTER TABLE TSUKEKAE RENAME TO TSUKEKAE_OLD;
CREATE TABLE TSUKEKAE
(
 DENPYOU_ID VARCHAR(19) NOT NULL,
 DENPYOU_DATE DATE NOT NULL,
 SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
 ZEIRITSU DECIMAL(3) NOT NULL,
 KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
 HF1_CD VARCHAR(20) NOT NULL,
 HF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF2_CD VARCHAR(20) NOT NULL,
 HF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HF3_CD VARCHAR(20) NOT NULL,
 HF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 HOSOKU VARCHAR(240) NOT NULL,
 TSUKEKAE_KBN VARCHAR(1) NOT NULL,
 MOTO_KAMOKU_CD VARCHAR(8) NOT NULL,
 MOTO_KAMOKU_NAME VARCHAR(22) NOT NULL,
 MOTO_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
 MOTO_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
 MOTO_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
 MOTO_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
 MOTO_TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
 MOTO_TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 MOTO_KAZEI_KBN VARCHAR(3) NOT NULL,
 MOTO_UF1_CD VARCHAR(20) NOT NULL,
 MOTO_UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 MOTO_UF2_CD VARCHAR(20) NOT NULL,
 MOTO_UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 MOTO_UF3_CD VARCHAR(20) NOT NULL,
 MOTO_UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
 MOTO_PROJECT_CD VARCHAR(12) NOT NULL,
 MOTO_PROJECT_NAME VARCHAR(20) NOT NULL,
 TOUROKU_USER_ID VARCHAR(30) NOT NULL,
 TOUROKU_TIME TIMESTAMP NOT NULL,
 KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
 KOUSHIN_TIME TIMESTAMP NOT NULL,
 PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;
COMMENT ON TABLE TSUKEKAE IS '付替';
COMMENT ON COLUMN TSUKEKAE.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN TSUKEKAE.DENPYOU_DATE IS '伝票日付';
COMMENT ON COLUMN TSUKEKAE.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN TSUKEKAE.ZEIRITSU IS '税率';
COMMENT ON COLUMN TSUKEKAE.KINGAKU_GOUKEI IS '金額合計';
COMMENT ON COLUMN TSUKEKAE.HF1_CD IS 'HF1コード';
COMMENT ON COLUMN TSUKEKAE.HF1_NAME_RYAKUSHIKI IS 'HF1名（略式）';
COMMENT ON COLUMN TSUKEKAE.HF2_CD IS 'HF2コード';
COMMENT ON COLUMN TSUKEKAE.HF2_NAME_RYAKUSHIKI IS 'HF2名（略式）';
COMMENT ON COLUMN TSUKEKAE.HF3_CD IS 'HF3コード';
COMMENT ON COLUMN TSUKEKAE.HF3_NAME_RYAKUSHIKI IS 'HF3名（略式）';
COMMENT ON COLUMN TSUKEKAE.HOSOKU IS '補足';
COMMENT ON COLUMN TSUKEKAE.TSUKEKAE_KBN IS '付替区分';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_CD IS '付替元科目コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_NAME IS '付替元科目名';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_EDABAN_CD IS '付替元科目枝番コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAMOKU_EDABAN_NAME IS '付替元科目枝番名';
COMMENT ON COLUMN TSUKEKAE.MOTO_FUTAN_BUMON_CD IS '付替元負担部門コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_FUTAN_BUMON_NAME IS '付替元負担部門名';
COMMENT ON COLUMN TSUKEKAE.MOTO_TORIHIKISAKI_CD IS '付替元取引先コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_TORIHIKISAKI_NAME_RYAKUSHIKI IS '付替元取引先名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_KAZEI_KBN IS '付替元課税区分';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF1_CD IS '付替元UF1コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF1_NAME_RYAKUSHIKI IS '付替元UF1名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF2_CD IS '付替元UF2コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF2_NAME_RYAKUSHIKI IS '付替元UF2名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF3_CD IS '付替元UF3コード';
COMMENT ON COLUMN TSUKEKAE.MOTO_UF3_NAME_RYAKUSHIKI IS '付替元UF3名（略式）';
COMMENT ON COLUMN TSUKEKAE.MOTO_PROJECT_CD IS '付替元プロジェクトコード';
COMMENT ON COLUMN TSUKEKAE.MOTO_PROJECT_NAME IS '付替元プロジェクト名';
COMMENT ON COLUMN TSUKEKAE.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN TSUKEKAE.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN TSUKEKAE.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN TSUKEKAE.KOUSHIN_TIME IS '更新日時';
INSERT INTO TSUKEKAE
SELECT
 DENPYOU_ID,
 DENPYOU_DATE,
 SHOUHYOU_SHORUI_FLG,
 ZEIRITSU,
 KINGAKU_GOUKEI,
 '',
 '',
 '',
 '',
 '',
 '',
 HOSOKU,
 TSUKEKAE_KBN,
 MOTO_KAMOKU_CD,
 MOTO_KAMOKU_NAME,
 MOTO_KAMOKU_EDABAN_CD,
 MOTO_KAMOKU_EDABAN_NAME,
 MOTO_FUTAN_BUMON_CD,
 MOTO_FUTAN_BUMON_NAME,
 MOTO_TORIHIKISAKI_CD,
 MOTO_TORIHIKISAKI_NAME_RYAKUSHIKI,
 MOTO_KAZEI_KBN,
 MOTO_UF1_CD,
 MOTO_UF1_NAME_RYAKUSHIKI,
 MOTO_UF2_CD,
 MOTO_UF2_NAME_RYAKUSHIKI,
 MOTO_UF3_CD,
 MOTO_UF3_NAME_RYAKUSHIKI,
 MOTO_PROJECT_CD,
 MOTO_PROJECT_NAME,
 TOUROKU_USER_ID,
 TOUROKU_TIME,
 KOUSHIN_USER_ID,
 KOUSHIN_TIME
FROM TSUKEKAE_OLD;
DROP TABLE TSUKEKAE_OLD;

commit;
