SET client_encoding TO 'SJIS';
SET search_path TO :SCHEMA_NAME;

start transaction;

-- 仕訳パターンマスター（カラム追加）
-- テーブルバックアップ
ALTER TABLE SHIWAKE_PATTERN_MASTER RENAME TO SHIWAKE_PATTERN_MASTER_OLD;

-- テーブル作成
CREATE TABLE SHIWAKE_PATTERN_MASTER
(
	DENPYOU_KBN VARCHAR(4) NOT NULL,
	SHIWAKE_EDANO INT NOT NULL,
	DELETE_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	YUUKOU_KIGEN_FROM DATE NOT NULL,
	YUUKOU_KIGEN_TO DATE NOT NULL,
	BUNRUI1 VARCHAR(20) NOT NULL,
	BUNRUI2 VARCHAR(20) NOT NULL,
	BUNRUI3 VARCHAR(20) NOT NULL,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	DEFAULT_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KOUSAIHI_HYOUJI_FLG VARCHAR(1) NOT NULL,
	KAKE_FLG VARCHAR(1) NOT NULL,
	HYOUJI_JUN INT NOT NULL,
	SHAIN_CD_RENKEI_FLG VARCHAR(1) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR NOT NULL,
	KARI_KAMOKU_CD VARCHAR NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR NOT NULL,
	KARI_TORIHIKISAKI_CD VARCHAR NOT NULL,
	KARI_PROJECT_CD VARCHAR NOT NULL,
	KARI_KAZEI_KBN VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD1 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD1 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD1 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN1 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD2 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD2 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD2 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN2 VARCHAR NOT NULL,
	KASHI_FUTAN_BUMON_CD3 VARCHAR NOT NULL,
	KASHI_TORIHIKISAKI_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_CD3 VARCHAR NOT NULL,
	KASHI_KAMOKU_EDABAN_CD3 VARCHAR NOT NULL,
	KASHI_KAZEI_KBN3 VARCHAR NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_KBN, SHIWAKE_EDANO)
) WITHOUT OIDS;

COMMENT ON TABLE SHIWAKE_PATTERN_MASTER IS '仕訳パターンマスター';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DENPYOU_KBN IS '伝票区分';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DELETE_FLG IS '削除フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_FROM IS '有効期限開始日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.YUUKOU_KIGEN_TO IS '有効期限終了日';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI1 IS '分類1';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI2 IS '分類2';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.BUNRUI3 IS '分類3';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.DEFAULT_HYOUJI_FLG IS 'デフォルト表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSAIHI_HYOUJI_FLG IS '交際費表示フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KAKE_FLG IS '掛けフラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.HYOUJI_JUN IS '表示順';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.SHAIN_CD_RENKEI_FLG IS '社員コード連携フラグ';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_FUTAN_BUMON_CD IS '借方負担部門コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_CD IS '借方科目コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_TORIHIKISAKI_CD IS '借方取引先コード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_PROJECT_CD IS '借方プロジェクトコード（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KARI_KAZEI_KBN IS '借方課税区分（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD1 IS '貸方負担部門コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD1 IS '貸方科目コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD1 IS '貸方科目枝番コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD1 IS '貸方取引先コード１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN1 IS '貸方課税区分１（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD2 IS '貸方負担部門コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD2 IS '貸方取引先コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD2 IS '貸方科目コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD2 IS '貸方科目枝番コード２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN2 IS '貸方課税区分２（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_FUTAN_BUMON_CD3 IS '貸方負担部門コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_TORIHIKISAKI_CD3 IS '貸方取引先コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_CD3 IS '貸方科目コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAMOKU_EDABAN_CD3 IS '貸方科目枝番コード３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KASHI_KAZEI_KBN3 IS '貸方課税区分３（仕訳パターン）';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN SHIWAKE_PATTERN_MASTER.KOUSHIN_TIME IS '更新日時';

-- データ移行
INSERT INTO SHIWAKE_PATTERN_MASTER (
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	SHAIN_CD_RENKEI_FLG,
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	KARI_PROJECT_CD,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	KASHI_KAZEI_KBN2,
	KASHI_FUTAN_BUMON_CD3,
	KASHI_TORIHIKISAKI_CD3,
	KASHI_KAMOKU_CD3,
	KASHI_KAMOKU_EDABAN_CD3,
	KASHI_KAZEI_KBN3,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_KBN,
	SHIWAKE_EDANO,
	DELETE_FLG,
	YUUKOU_KIGEN_FROM,
	YUUKOU_KIGEN_TO,
	BUNRUI1,
	BUNRUI2,
	BUNRUI3,
	TORIHIKI_NAME,
	DEFAULT_HYOUJI_FLG,
	KOUSAIHI_HYOUJI_FLG,
	KAKE_FLG,
	HYOUJI_JUN,
	SHAIN_CD_RENKEI_FLG,
	KARI_FUTAN_BUMON_CD,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_EDABAN_CD,
	KARI_TORIHIKISAKI_CD,
	KARI_PROJECT_CD,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD1,
	KASHI_KAMOKU_CD1,
	KASHI_KAMOKU_EDABAN_CD1,
	KASHI_TORIHIKISAKI_CD1,
	KASHI_KAZEI_KBN1,
	KASHI_FUTAN_BUMON_CD2,
	KASHI_TORIHIKISAKI_CD2,
	KASHI_KAMOKU_CD2,
	KASHI_KAMOKU_EDABAN_CD2,
	KASHI_KAZEI_KBN2,
	'',
	'',
	'',
	'',
	'',
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM SHIWAKE_PATTERN_MASTER_OLD;
DROP TABLE SHIWAKE_PATTERN_MASTER_OLD;

-- 経費精算（カラム追加）
-- テーブルバックアップ
ALTER TABLE KEIHISEISAN RENAME TO KEIHISEISAN_OLD;

-- テーブル作成
CREATE TABLE KEIHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	SHIYOUBI DATE,
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	SHOUHYOU_SHORUI_FLG VARCHAR(1) NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE KEIHISEISAN IS '経費精算';
COMMENT ON COLUMN KEIHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN KEIHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN KEIHISEISAN.SHIYOUBI IS '使用日';
COMMENT ON COLUMN KEIHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KEIHISEISAN.SHOUHYOU_SHORUI_FLG IS '証憑書類フラグ';
COMMENT ON COLUMN KEIHISEISAN.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN KEIHISEISAN.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN KEIHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KEIHISEISAN.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN KEIHISEISAN.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN KEIHISEISAN.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN KEIHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN KEIHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KEIHISEISAN.KOUSHIN_TIME IS '更新日時';

-- データ移行
INSERT INTO KEIHISEISAN (
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	SHIYOUBI,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	ZEIRITSU,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	SHIYOUBI,
	SHIYOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	SHOUHYOU_SHORUI_FLG,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	ZEIRITSU,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KEIHISEISAN_OLD;
DROP TABLE KEIHISEISAN_OLD;

-- 旅費精算（カラム追加）
-- テーブルバックアップ
ALTER TABLE RYOHISEISAN RENAME TO RYOHISEISAN_OLD;

CREATE TABLE RYOHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_DENPYOU_ID VARCHAR(19) NOT NULL,
	KARIBARAI_MISHIYOU_FLG VARCHAR(1) DEFAULT '0' NOT NULL,
	HOUMONSAKI VARCHAR(120) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	SASHIHIKI_SHIKYUU_KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE RYOHISEISAN IS '旅費精算';
COMMENT ON COLUMN RYOHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_DENPYOU_ID IS '仮払伝票ID';
COMMENT ON COLUMN RYOHISEISAN.KARIBARAI_MISHIYOU_FLG IS '仮払金未使用フラグ';
COMMENT ON COLUMN RYOHISEISAN.HOUMONSAKI IS '訪問先';
COMMENT ON COLUMN RYOHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN RYOHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN RYOHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN RYOHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN RYOHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN RYOHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN RYOHISEISAN.SASHIHIKI_SHIKYUU_KINGAKU IS '差引支給金額';
COMMENT ON COLUMN RYOHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN RYOHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN RYOHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN RYOHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN RYOHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN RYOHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN RYOHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN RYOHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN RYOHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN RYOHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN RYOHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN.KOUSHIN_TIME IS '更新日時';

-- データ移行
INSERT INTO RYOHISEISAN (
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_TO,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME

)
SELECT 
	DENPYOU_ID,
	KARIBARAI_DENPYOU_ID,
	KARIBARAI_MISHIYOU_FLG,
	HOUMONSAKI,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	SASHIHIKI_SHIKYUU_KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM RYOHISEISAN_OLD;
DROP TABLE RYOHISEISAN_OLD;

-- 交通費精算（カラム追加）
-- テーブルバックアップ
ALTER TABLE KOUTSUUHISEISAN RENAME TO KOUTSUUHISEISAN_OLD;

CREATE TABLE KOUTSUUHISEISAN
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	MOKUTEKI VARCHAR(240) NOT NULL,
	SEISANKIKAN_FROM DATE,
	SEISANKIKAN_TO DATE,
	KEIJOUBI DATE,
	SHIHARAIBI DATE,
	SHIHARAIKIBOUBI DATE,
	SHIHARAIHOUHOU VARCHAR(1) NOT NULL,
	TEKIYOU VARCHAR(60) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	GOUKEI_KINGAKU DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	SHIWAKE_EDANO INT,
	TORIHIKI_NAME VARCHAR(20) NOT NULL,
	KARI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KARI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KARI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KARI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KARI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KARI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KARI_KAZEI_KBN VARCHAR(3) NOT NULL,
	KASHI_FUTAN_BUMON_CD VARCHAR(8) NOT NULL,
	KASHI_FUTAN_BUMON_NAME VARCHAR(20) NOT NULL,
	KASHI_KAMOKU_CD VARCHAR(6) NOT NULL,
	KASHI_KAMOKU_NAME VARCHAR(22) NOT NULL,
	KASHI_KAMOKU_EDABAN_CD VARCHAR(12) NOT NULL,
	KASHI_KAMOKU_EDABAN_NAME VARCHAR(20) NOT NULL,
	KASHI_KAZEI_KBN VARCHAR(3) NOT NULL,
	UF1_CD VARCHAR(20) NOT NULL,
	UF1_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF2_CD VARCHAR(20) NOT NULL,
	UF2_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	UF3_CD VARCHAR(20) NOT NULL,
	UF3_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	PROJECT_CD VARCHAR(12) NOT NULL,
	PROJECT_NAME VARCHAR(20) NOT NULL,
	TEKIYOU_CD VARCHAR(4) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE KOUTSUUHISEISAN IS '交通費精算';
COMMENT ON COLUMN KOUTSUUHISEISAN.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN.MOKUTEKI IS '目的';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_FROM IS '精算期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SEISANKIKAN_TO IS '精算期間終了日';
COMMENT ON COLUMN KOUTSUUHISEISAN.KEIJOUBI IS '計上日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIKIBOUBI IS '支払希望日';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIHARAIHOUHOU IS '支払方法';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU IS '摘要';
COMMENT ON COLUMN KOUTSUUHISEISAN.ZEIRITSU IS '税率';
COMMENT ON COLUMN KOUTSUUHISEISAN.GOUKEI_KINGAKU IS '合計金額';
COMMENT ON COLUMN KOUTSUUHISEISAN.HOSOKU IS '補足';
COMMENT ON COLUMN KOUTSUUHISEISAN.SHIWAKE_EDANO IS '仕訳枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN.TORIHIKI_NAME IS '取引名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_CD IS '借方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_FUTAN_BUMON_NAME IS '借方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_CD IS '借方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_NAME IS '借方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_CD IS '借方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAMOKU_EDABAN_NAME IS '借方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KARI_KAZEI_KBN IS '借方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_CD IS '貸方負担部門コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_FUTAN_BUMON_NAME IS '貸方負担部門名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_CD IS '貸方科目コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_NAME IS '貸方科目名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_CD IS '貸方科目枝番コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAMOKU_EDABAN_NAME IS '貸方科目枝番名';
COMMENT ON COLUMN KOUTSUUHISEISAN.KASHI_KAZEI_KBN IS '貸方課税区分';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_CD IS 'UF1コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF1_NAME_RYAKUSHIKI IS 'UF1名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_CD IS 'UF2コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF2_NAME_RYAKUSHIKI IS 'UF2名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_CD IS 'UF3コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.UF3_NAME_RYAKUSHIKI IS 'UF3名（略式）';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_CD IS 'プロジェクトコード';
COMMENT ON COLUMN KOUTSUUHISEISAN.PROJECT_NAME IS 'プロジェクト名';
COMMENT ON COLUMN KOUTSUUHISEISAN.TEKIYOU_CD IS '摘要コード';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN.KOUSHIN_TIME IS '更新日時';

-- データ移行
INSERT INTO KOUTSUUHISEISAN (
	DENPYOU_ID,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_TO,
	KEIJOUBI,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
)
SELECT 
	DENPYOU_ID,
	MOKUTEKI,
	SEISANKIKAN_FROM,
	SEISANKIKAN_TO,
	SEISANKIKAN_TO,
	SHIHARAIBI,
	SHIHARAIKIBOUBI,
	SHIHARAIHOUHOU,
	TEKIYOU,
	ZEIRITSU,
	GOUKEI_KINGAKU,
	HOSOKU,
	SHIWAKE_EDANO,
	TORIHIKI_NAME,
	KARI_FUTAN_BUMON_CD,
	KARI_FUTAN_BUMON_NAME,
	KARI_KAMOKU_CD,
	KARI_KAMOKU_NAME,
	KARI_KAMOKU_EDABAN_CD,
	KARI_KAMOKU_EDABAN_NAME,
	KARI_KAZEI_KBN,
	KASHI_FUTAN_BUMON_CD,
	KASHI_FUTAN_BUMON_NAME,
	KASHI_KAMOKU_CD,
	KASHI_KAMOKU_NAME,
	KASHI_KAMOKU_EDABAN_CD,
	KASHI_KAMOKU_EDABAN_NAME,
	KASHI_KAZEI_KBN,
	UF1_CD,
	UF1_NAME_RYAKUSHIKI,
	UF2_CD,
	UF2_NAME_RYAKUSHIKI,
	UF3_CD,
	UF3_NAME_RYAKUSHIKI,
	PROJECT_CD,
	PROJECT_NAME,
	TEKIYOU_CD,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM KOUTSUUHISEISAN_OLD;
DROP TABLE KOUTSUUHISEISAN_OLD;

-- 自動引落（カラム追加）
-- テーブルバックアップ
ALTER TABLE JIDOUHIKIOTOSHI RENAME TO JIDOUHIKIOTOSHI_OLD;

CREATE TABLE JIDOUHIKIOTOSHI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	KEIJOUBI DATE,
	HIKIOTOSHIBI DATE NOT NULL,
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	TORIHIKISAKI_NAME_RYAKUSHIKI VARCHAR(20) NOT NULL,
	ZEIRITSU DECIMAL(3) NOT NULL,
	HONTAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHOUHIZEIGAKU_GOUKEI DECIMAL(15) NOT NULL,
	SHIHARAI_KINGAKU_GOUKEI DECIMAL(15) NOT NULL,
	HOSOKU VARCHAR(240) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID)
) WITHOUT OIDS;

COMMENT ON TABLE JIDOUHIKIOTOSHI IS '自動引落';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KEIJOUBI IS '計上日';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HIKIOTOSHIBI IS '引落日';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TORIHIKISAKI_NAME_RYAKUSHIKI IS '取引先名（略式）';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.ZEIRITSU IS '税率';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HONTAI_KINGAKU_GOUKEI IS '本体金額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.SHOUHIZEIGAKU_GOUKEI IS '消費税額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.SHIHARAI_KINGAKU_GOUKEI IS '支払金額合計';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.HOSOKU IS '補足';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN JIDOUHIKIOTOSHI.KOUSHIN_TIME IS '更新日時';

-- データ移行
INSERT INTO JIDOUHIKIOTOSHI (
	DENPYOU_ID,
	KEIJOUBI,
	HIKIOTOSHIBI,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	ZEIRITSU,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
KOUSHIN_TIME
)
	SELECT 
	DENPYOU_ID,
	HIKIOTOSHIBI,
	HIKIOTOSHIBI,
	TORIHIKISAKI_CD,
	TORIHIKISAKI_NAME_RYAKUSHIKI,
	ZEIRITSU,
	HONTAI_KINGAKU_GOUKEI,
	SHOUHIZEIGAKU_GOUKEI,
	SHIHARAI_KINGAKU_GOUKEI,
	HOSOKU,
	TOUROKU_USER_ID,
	TOUROKU_TIME,
	KOUSHIN_USER_ID,
	KOUSHIN_TIME
FROM JIDOUHIKIOTOSHI_OLD;
DROP TABLE JIDOUHIKIOTOSHI_OLD;

-- 内部コード設定データ変更
CREATE TABLE naibu_cd_setting_tmp AS SELECT * FROM naibu_cd_setting;
DELETE FROM naibu_cd_setting;
\copy naibu_cd_setting FROM '.\files\csv\naibu_cd_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM naibu_cd_setting
	WHERE NOT EXISTS (SELECT naibu_cd_name FROM naibu_cd_setting_tmp WHERE naibu_cd_name = 'denpyou_kbn' AND naibu_cd = 'A003') 
	      AND naibu_cd_name = 'denpyou_kbn' AND naibu_cd = 'A003';
DELETE FROM naibu_cd_setting 
	WHERE NOT EXISTS (SELECT naibu_cd_name FROM naibu_cd_setting_tmp WHERE naibu_cd_name = 'shiwake_pattern_denpyou_kbn' AND naibu_cd = 'A003') 
	      AND naibu_cd_name = 'shiwake_pattern_denpyou_kbn' AND naibu_cd = 'A003';
DROP TABLE naibu_cd_setting_tmp;

-- 設定情報データ変更
CREATE TABLE setting_info_tmp AS SELECT * FROM setting_info;
DELETE FROM setting_info;
\copy setting_info FROM '.\files\csv\setting_info.csv' WITH CSV header ENCODING 'SHIFT-JIS';
UPDATE setting_info new SET setting_val = (
 SELECT setting_val
 FROM setting_info_tmp tmp
 WHERE tmp.setting_name = new.setting_name
) WHERE new.setting_name IN (
 SELECT setting_name FROM setting_info_tmp
);
DROP TABLE setting_info_tmp;

-- 仕訳パターン設定データ変更
CREATE TABLE shiwake_pattern_setting_tmp AS SELECT * FROM shiwake_pattern_setting;
DELETE FROM shiwake_pattern_setting;
\copy shiwake_pattern_setting FROM '.\files\csv\shiwake_pattern_setting.csv' WITH CSV header ENCODING 'SHIFT-JIS';
DELETE FROM shiwake_pattern_setting WHERE NOT EXISTS (SELECT denpyou_kbn FROM shiwake_pattern_setting_tmp WHERE denpyou_kbn = 'A003') AND denpyou_kbn = 'A003';
DROP TABLE shiwake_pattern_setting_tmp;

-- 旅費精算明細カラム追加
CREATE TABLE ryohiseisan_meisai_tmp AS SELECT * FROM ryohiseisan_meisai;
DROP TABLE ryohiseisan_meisai;
CREATE TABLE RYOHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	KIKAN_TO DATE,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	NISSUU INT,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE RYOHISEISAN_MEISAI IS '旅費精算明細';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KIKAN_TO IS '期間終了日';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.NISSUU IS '日数';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN RYOHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO ryohiseisan_meisai
SELECT
  denpyou_id
  ,denpyou_edano
  ,kikan_from
  ,kikan_to
  ,shubetsu_cd
  ,shubetsu1
  ,shubetsu2
  ,koutsuu_shudan
  ,'0'
  ,ryoushuusho_seikyuusho_tou_flg
  ,naiyou
  ,bikou
  ,oufuku_flg
  ,jidounyuuryoku_flg
  ,nissuu
  ,tanka
  ,meisai_kingaku
  ,touroku_user_id
  ,touroku_time
  ,koushin_user_id
  ,koushin_time
FROM ryohiseisan_meisai_tmp;
DROP TABLE ryohiseisan_meisai_tmp;

-- 旅費精算明細.証憑書類必須フラグ更新（交通手段分）
UPDATE ryohiseisan_meisai rm SET shouhyou_shorui_hissu_flg = (
 SELECT shouhyou_shorui_hissu_flg
 FROM koutsuu_shudan_master ko
 WHERE ko.koutsuu_shudan = rm.koutsuu_shudan
) WHERE rm.koutsuu_shudan IN (
 SELECT koutsuu_shudan FROM koutsuu_shudan_master
);

-- 旅費精算明細.証憑書類必須フラグ更新（日当等分）
-- tmpテーブル作成
CREATE TABLE user_tmp AS (
SELECT r.denpyou_id, r.denpyou_edano, sh.yakushoku_cd
FROM shounin_route s 
INNER JOIN ryohiseisan_meisai r
ON s.denpyou_id = r.denpyou_id AND s.edano = '1'
LEFT OUTER JOIN user_info u 
ON s.user_id = u.user_id
LEFT OUTER JOIN shain sh
ON u.shain_no = sh.shain_no
WHERE r.shubetsu_cd = '2'
);
-- 更新
UPDATE ryohiseisan_meisai ryohi SET shouhyou_shorui_hissu_flg = '1'
FROM (SELECT rym.denpyou_id, rym.denpyou_edano
	FROM ryohiseisan_meisai rym
	INNER JOIN user_tmp ut
	ON rym.denpyou_id = ut.denpyou_id AND rym.denpyou_edano = ut.denpyou_edano
	LEFT OUTER JOIN nittou_nado_master nnm
	ON rym.shubetsu1 = nnm.shubetsu1 
		AND CASE rym.shubetsu2 WHEN  '' THEN nnm.shubetsu2 = '-'
							   ELSE rym.shubetsu2 = nnm.shubetsu2 END
		AND CASE 
			(SELECT count(1) FROM nittou_nado_master nnm2
				WHERE rym.shubetsu1 = nnm2.shubetsu1 
					AND CASE rym.shubetsu2 WHEN  '' THEN nnm2.shubetsu2 = '-'
							   ELSE rym.shubetsu2 = nnm2.shubetsu2 END
					AND nnm2.yakushoku_cd = ut.yakushoku_cd
			) WHEN 0 THEN nnm.yakushoku_cd = '-'
			ELSE nnm.yakushoku_cd = ut.yakushoku_cd END
	WHERE rym.shubetsu_cd = '2' 
		AND nnm.shouhyou_shorui_hissu_flg = '1'
	) AS tmp1
WHERE ryohi.denpyou_id = tmp1.denpyou_id AND ryohi.denpyou_edano = tmp1.denpyou_edano;
-- tmpテーブル削除
DROP TABLE user_tmp;


-- 交通費精算明細カラム追加
CREATE TABLE koutsuuhiseisan_meisai_tmp AS SELECT * from koutsuuhiseisan_meisai;
DROP TABLE koutsuuhiseisan_meisai;
CREATE TABLE KOUTSUUHISEISAN_MEISAI
(
	DENPYOU_ID VARCHAR(19) NOT NULL,
	DENPYOU_EDANO INT NOT NULL,
	KIKAN_FROM DATE NOT NULL,
	SHUBETSU_CD VARCHAR(1) NOT NULL,
	SHUBETSU1 VARCHAR(20) NOT NULL,
	SHUBETSU2 VARCHAR(20) NOT NULL,
	KOUTSUU_SHUDAN VARCHAR(10) NOT NULL,
	SHOUHYOU_SHORUI_HISSU_FLG VARCHAR(1) NOT NULL,
	RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG CHAR(1) NOT NULL,
	NAIYOU VARCHAR(512) NOT NULL,
	BIKOU VARCHAR(200) NOT NULL,
	OUFUKU_FLG VARCHAR(1) NOT NULL,
	JIDOUNYUURYOKU_FLG VARCHAR(1) NOT NULL,
	TANKA DECIMAL(15) NOT NULL,
	MEISAI_KINGAKU DECIMAL(15) NOT NULL,
	TOUROKU_USER_ID VARCHAR(30) NOT NULL,
	TOUROKU_TIME TIMESTAMP NOT NULL,
	KOUSHIN_USER_ID VARCHAR(30) NOT NULL,
	KOUSHIN_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (DENPYOU_ID, DENPYOU_EDANO)
) WITHOUT OIDS;
COMMENT ON TABLE KOUTSUUHISEISAN_MEISAI IS '交通費精算明細';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_ID IS '伝票ID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.DENPYOU_EDANO IS '伝票枝番号';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KIKAN_FROM IS '期間開始日';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU_CD IS '種別コード';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU1 IS '種別１';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHUBETSU2 IS '種別２';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUTSUU_SHUDAN IS '交通手段';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.SHOUHYOU_SHORUI_HISSU_FLG IS '証憑書類必須フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.RYOUSHUUSHO_SEIKYUUSHO_TOU_FLG IS '領収書・請求書等フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.NAIYOU IS '内容（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.BIKOU IS '備考（旅費精算）';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.OUFUKU_FLG IS '往復フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.JIDOUNYUURYOKU_FLG IS '自動入力フラグ';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TANKA IS '単価';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.MEISAI_KINGAKU IS '明細金額';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_USER_ID IS '登録ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.TOUROKU_TIME IS '登録日時';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_USER_ID IS '更新ユーザーID';
COMMENT ON COLUMN KOUTSUUHISEISAN_MEISAI.KOUSHIN_TIME IS '更新日時';
INSERT INTO koutsuuhiseisan_meisai
SELECT
  denpyou_id
  ,denpyou_edano
  ,kikan_from
  ,shubetsu_cd
  ,shubetsu1
  ,shubetsu2
  ,koutsuu_shudan
  ,'0'
  ,ryoushuusho_seikyuusho_tou_flg
  ,naiyou
  ,bikou
  ,oufuku_flg
  ,jidounyuuryoku_flg
  ,tanka
  ,meisai_kingaku
  ,touroku_user_id
  ,touroku_time
  ,koushin_user_id
  ,koushin_time
FROM koutsuuhiseisan_meisai_tmp;
DROP TABLE koutsuuhiseisan_meisai_tmp;

-- 交通費精算.証憑書類必須フラグ更新
UPDATE koutsuuhiseisan_meisai km SET shouhyou_shorui_hissu_flg = (
 SELECT shouhyou_shorui_hissu_flg
 FROM koutsuu_shudan_master ko
 WHERE ko.koutsuu_shudan = km.koutsuu_shudan
) WHERE km.koutsuu_shudan IN (
 SELECT koutsuu_shudan FROM koutsuu_shudan_master
);

-- 取引先　型変更
CREATE TABLE torihikisaki_tmp AS SELECT * from torihikisaki;
DROP TABLE torihikisaki;
CREATE TABLE TORIHIKISAKI
(
	TORIHIKISAKI_CD VARCHAR(12) NOT NULL,
	YUUBIN_BANGOU VARCHAR(7) NOT NULL,
	JUUSHO1 VARCHAR(40) NOT NULL,
	JUUSHO2 VARCHAR(40) NOT NULL,
	TELNO VARCHAR(20) NOT NULL,
	FAXNO VARCHAR(20) NOT NULL,
	KOUZA_MEIGININ VARCHAR(40) NOT NULL,
	KOUZA_MEIGININ_FURIGANA VARCHAR(30) NOT NULL,
	SHIHARAI_SHUBETSU SMALLINT,
	YOKIN_SHUBETSU VARCHAR(1) NOT NULL,
	KOUZA_BANGOU VARCHAR(7) NOT NULL,
	TESUURYOU_FUTAN_KBN SMALLINT,
	FURIKOMI_KBN VARCHAR(1) NOT NULL,
	FURIKOMI_GINKOU_CD VARCHAR(4) NOT NULL,
	FURIKOMI_GINKOU_SHITEN_CD VARCHAR(3) NOT NULL,
	SHIHARAIBI SMALLINT,
	SHIHARAI_KIJITSU SMALLINT,
	YAKUJOU_KINGAKU DECIMAL(15),
	PRIMARY KEY (TORIHIKISAKI_CD)
) WITHOUT OIDS;
COMMENT ON TABLE TORIHIKISAKI IS '取引先';
COMMENT ON COLUMN TORIHIKISAKI.TORIHIKISAKI_CD IS '取引先コード';
COMMENT ON COLUMN TORIHIKISAKI.YUUBIN_BANGOU IS '郵便番号';
COMMENT ON COLUMN TORIHIKISAKI.JUUSHO1 IS '住所１';
COMMENT ON COLUMN TORIHIKISAKI.JUUSHO2 IS '住所２';
COMMENT ON COLUMN TORIHIKISAKI.TELNO IS '電話番号';
COMMENT ON COLUMN TORIHIKISAKI.FAXNO IS 'FAX番号';
COMMENT ON COLUMN TORIHIKISAKI.KOUZA_MEIGININ IS '口座名義人';
COMMENT ON COLUMN TORIHIKISAKI.KOUZA_MEIGININ_FURIGANA IS '口座名義人ふり仮名';
COMMENT ON COLUMN TORIHIKISAKI.SHIHARAI_SHUBETSU IS '支払種別';
COMMENT ON COLUMN TORIHIKISAKI.YOKIN_SHUBETSU IS '預金種別';
COMMENT ON COLUMN TORIHIKISAKI.KOUZA_BANGOU IS '口座番号';
COMMENT ON COLUMN TORIHIKISAKI.TESUURYOU_FUTAN_KBN IS '手数料負担区分';
COMMENT ON COLUMN TORIHIKISAKI.FURIKOMI_KBN IS '振込区分';
COMMENT ON COLUMN TORIHIKISAKI.FURIKOMI_GINKOU_CD IS '振込銀行コード';
COMMENT ON COLUMN TORIHIKISAKI.FURIKOMI_GINKOU_SHITEN_CD IS '振込銀行支店コード';
COMMENT ON COLUMN TORIHIKISAKI.SHIHARAIBI IS '支払日';
COMMENT ON COLUMN TORIHIKISAKI.SHIHARAI_KIJITSU IS '支払期日';
COMMENT ON COLUMN TORIHIKISAKI.YAKUJOU_KINGAKU IS '約定金額';
INSERT INTO torihikisaki
SELECT
  torihikisaki_cd
  ,yuubin_bangou
  ,juusho1
  ,juusho2
  ,telno
  ,faxno
  ,kouza_meiginin
  ,kouza_meiginin_furigana
  ,shiharai_shubetsu
  ,yokin_shubetsu
  ,kouza_bangou
  ,tesuuryou_futan_kbn
  ,furikomi_kbn
  ,furikomi_ginkou_cd
  ,furikomi_ginkou_shiten_cd
  ,null
  ,null
  ,yakujou_kingaku
FROM torihikisaki_tmp;
DROP TABLE torihikisaki_tmp;

-- マスター取込詳細　再インポート
DELETE FROM master_torikomi_shousai;
\copy master_torikomi_shousai FROM '.\files\csv\master_torikomi_shousai.csv' WITH CSV header ENCODING 'SHIFT-JIS';

commit;
